API MACRO name
name proc
name endp
ENDM

.code

API CAAccessCheck
API CAAccessCheckEx
API CAAddCACertificateType
API CAAddCACertificateTypeEx
API CACertTypeAccessCheck
API CACertTypeAccessCheckEx
API CACertTypeAuthzAccessCheck
API CACertTypeGetSecurity
API CACertTypeQuery
API CACertTypeRegisterQuery
API CACertTypeSetSecurity
API CACertTypeUnregisterQuery
API CACloneCertType
API CACloseCA
API CACloseCertType
API CACountCAs
API CACountCertTypes
API CACreateAutoEnrollmentObjectEx
API CACreateCertType
API CACreateLocalAutoEnrollmentObject
API CACreateNewCA
API CADCSetCertTypePropertyEx
API CADeleteCA
API CADeleteCAEx
API CADeleteCertType
API CADeleteCertTypeEx
API CADeleteLocalAutoEnrollmentObject
API CAEnumCertTypes
API CAEnumCertTypesEx
API CAEnumCertTypesEx2
API CAEnumCertTypesForCA
API CAEnumCertTypesForCAEx
API CAEnumFirstCA
API CAEnumNextCA
API CAEnumNextCertType
API CAFindByCertType
API CAFindByIssuerDN
API CAFindByName
API CAFindCertTypeByName
API CAFindCertTypeByName2
API CAFreeCAProperty
API CAFreeCertTypeExtensions
API CAFreeCertTypeProperty
API CAGetCACertificate
API CAGetCAExpiration
API CAGetCAFlags
API CAGetCAProperty
API CAGetCASecurity
API CAGetCertTypeExpiration
API CAGetCertTypeExtensions
API CAGetCertTypeExtensionsEx
API CAGetCertTypeFlags
API CAGetCertTypeFlagsEx
API CAGetCertTypeKeySpec
API CAGetCertTypeProperty
API CAGetCertTypePropertyEx
API CAGetDN
API CAInstallDefaultCertType
API CAInstallDefaultCertTypeEx
API CAIsCertTypeCurrent
API CAIsCertTypeCurrentEx
API CAOIDAdd
API CAOIDAddEx
API CAOIDCreateNew
API CAOIDCreateNewEx
API CAOIDDelete
API CAOIDDeleteEx
API CAOIDFreeLdapURL
API CAOIDFreeProperty
API CAOIDGetLdapURL
API CAOIDGetProperty
API CAOIDGetPropertyEx
API CAOIDSetProperty
API CAOIDSetPropertyEx
API CARemoveCACertificateType
API CARemoveCACertificateTypeEx
API CASetCACertificate
API CASetCAExpiration
API CASetCAFlags
API CASetCAProperty
API CASetCASecurity
API CASetCertTypeExpiration
API CASetCertTypeExtension
API CASetCertTypeFlags
API CASetCertTypeFlagsEx
API CASetCertTypeKeySpec
API CASetCertTypeProperty
API CASetCertTypePropertyEx
API CAUpdateCA
API CAUpdateCAEx
API CAUpdateCertType
API CAUpdateCertTypeEx
API ?CCFindCertificateBuildFilter@@YAJPEBGPEAPEAX@Z
API ?CCFindCertificateFreeFilter@@YAXPEAX@Z
API ?CCFindCertificateFromFilter@@YAPEBU_CERT_CONTEXT@@PEAX0PEBU1@@Z
API ?CCFreeStringArray@@YAXPEAPEAG@Z
API ?CCGetCertNameList@@YAJPEBU_CERT_CONTEXT@@KKPEAKPEAPEAPEAG@Z
API ?myVerifyEKOrAIKCertContext@@YAJHPEBU_CERT_CONTEXT@@KPEAX@Z
API ?myHResultToStringRawEx@@YAPEBGPEAG_KJ@Z
API ?myHResultToStringEx@@YAPEBGPEAG_KJ@Z
API ?myVerifyCertContext@@YAJPEBU_CERT_CONTEXT@@KKPEBQEBDPEAX2PEAPEAG@Z
API ?myVerifyEKPub@@YAJPEBG0PEAH@Z
API ?myVerifyEKCertContext@@YAJPEBU_CERT_CONTEXT@@KPEAX@Z
API ?LoadTpmTestEnumErrorMessages@@YAJW4TestKeyAttResult@@PEAPEAG@Z
API ?myFileTimeToDate@@YAJPEBU_FILETIME@@PEAN@Z
API ?myGetAlgorithmNameFromPubKey@@YAJPEBU_CERT_PUBLIC_KEY_INFO@@HPEAHPEAPEAG@Z
API ?myGetIsSigningCertificate@@YAJPEBU_CERT_CONTEXT@@K_KPEA_N@Z
API ?myCryptGetDefaultProvider@@YAJKPEBG0KPEAPEAG1@Z
API ?CSPrintErrorInit@@YAXP6AXPEBU_SYSTEMTIME@@PEBG11KJ@Z@Z
API ?CertcliGetDetailedCertcliVersionString@@YAJPEAPEBG@Z
API ?myFreeColumnDisplayNames2@@YAXXZ
API ?GetDetailedVersionString@@YAJPEBGPEAPEAG@Z
API ?myEnablePrivilege@@YAJJH@Z
API ?myGetHashAlgorithmOIDInfoFromSignatureAlgorithm@@YAJPEBU_CRYPT_ALGORITHM_IDENTIFIER@@PEAPEBU_CRYPT_OID_INFO@@@Z
API myNetLogonUser
API ?myGetTargetMachineDomainDnsName@@YAJPEBGPEAPEAG11@Z
API ?AddOrRemoveOCSPISAPIExtension@@YAJHPEAH@Z
API ?SplitConfigString@@YAJPEBGPEAPEAG1@Z
API ?RemoveVDir@@YAJPEBGPEAH@Z
API ?RemoveISAPIExtension@@YAJPEBG@Z
API ?DbgLogStringInit2@@YA?AW4LogPriority@@P6AXPEBD@ZW41@@Z
API CAIsCertTypeValid
API CAGetCertTypeAccessRights
API CAIsValid
API CAGetAccessRights
API ?CSPrintErrorLineFileData2@@YAXPEBGKJJ@Z
API ?CSPrintErrorLineFileData@@YAXPEBGKJ@Z
API ?CSPrintErrorLineFile2@@YAXKJJ@Z
API ?CSPrintErrorLineFile@@YAXKJ@Z
API ?myHGetLastError@@YAJXZ
API ?mylstrcmpiL@@YAHPEBG0@Z
API ?myGenerateGuidSerialNumber@@YAXPEAU_GUID@@@Z
API ?myGenerateGuidString@@YAJPEAPEAG@Z
API ?myRevertSanitizeName@@YAJPEBGPEAPEAG@Z
API ?mySanitizedNameToShortName@@YAJPEBGHPEAPEAG@Z
API ?mySanitizedNameToDSName@@YAJPEBGPEAPEAG@Z
API ?mySanitizeName@@YAJPEBGPEAPEAG@Z
API ?IsASPEnabledInIIS@@YAJAEA_N@Z
API ?myGetSidFromDomain@@YAKPEAGPEAPEAX@Z
API ?RemoveVDir@@YAJPEBGPEAH@Z
API ?IsISAPIExtensionEnabled@@YAJPEBGAEA_N@Z
API ?EnableASPInIIS@@YAJPEAH@Z
API ?IsASPEnabledInIIS@@YAJAEA_N@Z
API ?DbgPrintfW@@YAHKPEBGZZ
API ?myHExceptionCodePrint@@YAJPEBU_EXCEPTION_POINTERS@@PEBDKK@Z
API ?myLogExceptionInit@@YAXP6AXJPEBU_EXCEPTION_POINTERS@@PEBDKK@Z@Z
API ?myOIDHashOIDToString@@YAJPEBGPEAPEAG@Z
API caTranslateFileTimePeriodToPeriodUnits
API myRobustLdapBindEx
API ?myCAPropInfoLookup@@YAJPEBU_CAPROP@@JJPEAPEBU1@@Z
API ?myCAPropInfoUnmarshal@@YAJPEBU_CATRANSPROP@@JKPEAPEAU_CAPROP@@@Z
API ?myCAPropGetDisplayName@@YAJJPEAPEBG@Z
API ?myGetErrorMessageTextEx@@YAPEAGJKPEAPEBGK@Z
API ?myGetErrorMessageText1@@YAPEAGJKPEBG@Z
API ?WszToMultiByteInteger@@YAJKPEBGPEAKPEAPEAE@Z
API ?WszToMultiByteIntegerBuf@@YAJKPEBGPEAKPEAE@Z
API ?DbgLogStringInit@@YAXP6AXPEBD@Z@Z
API ?myAddShare@@YAJPEBG00HPEAH@Z
API ?EncodeToFileW@@YAJPEBGPEBEKK@Z
API ?DecodeFileW@@YAJPEBGPEAPEAEPEAKK@Z
API ?myModifyVirtualRootsAndFileShares@@YAJKW4ENUM_CATYPES@@KPEAK1@Z
API ?myJetHResult@@YAJJ@Z
API ?myHExceptionCode@@YAJPEBU_EXCEPTION_POINTERS@@@Z
API ?myIsDelayLoadHResult@@YAHJ@Z
API myRobustLdapBind
API ?myFreeColumnDisplayNames@@YAXXZ
API ?myDoesDSExist@@YAJH@Z
API ?myHResultToStringRaw_old@@YAPEBGPEAGJ@Z
API ?myGetErrorMessageText@@YAPEAGJK@Z
API ?myHResultToString_old@@YAPEBGPEAGJ@Z
API ?DbgIsSSActive@@YAHK@Z
API ?DbgPrintfInit@@YAXPEBD@Z
API ?DbgPrintf@@YAHKPEBDZZ
API ?CSPrintError@@YAXPEBDPEBG0KJJ@Z
API ?CSPrintAssert@@YAXPEBD0K0@Z
API ?myCryptBinaryToStringA@@YAJPEBEKKPEAPEAD@Z
API ?myCryptStringToBinaryA@@YAJPEBDKKPEAPEAEPEAK22@Z
API ?myCryptBinaryToString@@YAJPEBEKKPEAPEAG@Z
API ?myCryptStringToBinary@@YAJPEBGKKPEAPEAEPEAK22@Z

end
