.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _CAAccessCheck@8
API _CAAccessCheckEx@12
API _CAAddCACertificateType@8
API _CAAddCACertificateTypeEx@12
API _CACertTypeAccessCheck@8
API _CACertTypeAccessCheckEx@12
API _CACertTypeAuthzAccessCheck@12
API _CACertTypeGetSecurity@8
API _CACertTypeQuery@8
API _CACertTypeRegisterQuery@12
API _CACertTypeSetSecurity@8
API _CACertTypeUnregisterQuery@4
API _CACloneCertType@24
API _CACloseCA@4
API _CACloseCertType@4
API _CACountCAs@4
API _CACountCertTypes@4
API _CACreateAutoEnrollmentObjectEx@28
API _CACreateCertType@16
API _CACreateLocalAutoEnrollmentObject@16
API _CACreateNewCA@16
API _CADCSetCertTypePropertyEx@16
API _CADeleteCA@4
API _CADeleteCAEx@12
API _CADeleteCertType@4
API _CADeleteCertTypeEx@12
API _CADeleteLocalAutoEnrollmentObject@16
API _CAEnumCertTypes@8
API _CAEnumCertTypesEx@12
API _CAEnumCertTypesEx2@20
API _CAEnumCertTypesForCA@12
API _CAEnumCertTypesForCAEx@16
API _CAEnumFirstCA@12
API _CAEnumNextCA@8
API _CAEnumNextCertType@8
API _CAFindByCertType@16
API _CAFindByIssuerDN@16
API _CAFindByName@16
API _CAFindCertTypeByName@16
API _CAFindCertTypeByName2@24
API _CAFreeCAProperty@8
API _CAFreeCertTypeExtensions@8
API _CAFreeCertTypeProperty@8
API _CAGetCACertificate@8
API _CAGetCAExpiration@12
API _CAGetCAFlags@8
API _CAGetCAProperty@12
API _CAGetCASecurity@8
API _CAGetCertTypeExpiration@12
API _CAGetCertTypeExtensions@8
API _CAGetCertTypeExtensionsEx@16
API _CAGetCertTypeFlags@8
API _CAGetCertTypeFlagsEx@12
API _CAGetCertTypeKeySpec@8
API _CAGetCertTypeProperty@12
API _CAGetCertTypePropertyEx@12
API _CAGetDN@4
API _CAInstallDefaultCertType@4
API _CAInstallDefaultCertTypeEx@8
API _CAIsCertTypeCurrent@8
API _CAIsCertTypeCurrentEx@12
API _CAOIDAdd@12
API _CAOIDAddEx@16
API _CAOIDCreateNew@12
API _CAOIDCreateNewEx@16
API _CAOIDDelete@4
API _CAOIDDeleteEx@12
API _CAOIDFreeLdapURL@4
API _CAOIDFreeProperty@4
API _CAOIDGetLdapURL@12
API _CAOIDGetProperty@12
API _CAOIDGetPropertyEx@20
API _CAOIDSetProperty@12
API _CAOIDSetPropertyEx@20
API _CARemoveCACertificateType@8
API _CARemoveCACertificateTypeEx@12
API _CASetCACertificate@8
API _CASetCAExpiration@12
API _CASetCAFlags@8
API _CASetCAProperty@12
API _CASetCASecurity@8
API _CASetCertTypeExpiration@12
API _CASetCertTypeExtension@16
API _CASetCertTypeFlags@8
API _CASetCertTypeFlagsEx@12
API _CASetCertTypeKeySpec@8
API _CASetCertTypeProperty@12
API _CASetCertTypePropertyEx@12
API _CAUpdateCA@4
API _CAUpdateCAEx@12
API _CAUpdateCertType@4
API _CAUpdateCertTypeEx@12
API ?CCFindCertificateBuildFilter@@YGJPBGPAPAX@Z
API ?CCFindCertificateFreeFilter@@YGXPAX@Z
API ?CCFindCertificateFromFilter@@YGPBU_CERT_CONTEXT@@PAX0PBU1@@Z
API ?CCFreeStringArray@@YGXPAPAG@Z
API ?CCGetCertNameList@@YGJPBU_CERT_CONTEXT@@KKPAKPAPAPAG@Z
API ?myVerifyEKOrAIKCertContext@@YGJHPBU_CERT_CONTEXT@@KPAX@Z
API ?myHResultToStringRawEx@@YGPBGPAGIJ@Z
API ?myHResultToStringEx@@YGPBGPAGIJ@Z
API ?myVerifyCertContext@@YGJPBU_CERT_CONTEXT@@KKPBQBDPAX2PAPAG@Z
API ?myVerifyEKPub@@YGJPBG0PAH@Z
API ?myVerifyEKCertContext@@YGJPBU_CERT_CONTEXT@@KPAX@Z
API ?LoadTpmTestEnumErrorMessages@@YGJW4TestKeyAttResult@@PAPAG@Z
API ?myFileTimeToDate@@YGJPBU_FILETIME@@PAN@Z
API ?myGetAlgorithmNameFromPubKey@@YGJPBU_CERT_PUBLIC_KEY_INFO@@HPAHPAPAG@Z
API ?myGetIsSigningCertificate@@YGJPBU_CERT_CONTEXT@@KKPA_N@Z
API ?myCryptGetDefaultProvider@@YGJKPBG0KPAPAG1@Z
API ?CSPrintErrorInit@@YGXP6GXPBU_SYSTEMTIME@@PBG11KJ@Z@Z
API ?CertcliGetDetailedCertcliVersionString@@YGJPAPBG@Z
API ?myFreeColumnDisplayNames2@@YGXXZ
API ?GetDetailedVersionString@@YGJPBGPAPAG@Z
API ?myEnablePrivilege@@YGJJH@Z
API ?myGetHashAlgorithmOIDInfoFromSignatureAlgorithm@@YGJPBU_CRYPT_ALGORITHM_IDENTIFIER@@PAPBU_CRYPT_OID_INFO@@@Z
API _myNetLogonUser@16
API ?myGetTargetMachineDomainDnsName@@YGJPBGPAPAG11@Z
API ?AddOrRemoveOCSPISAPIExtension@@YGJHPAH@Z
API ?SplitConfigString@@YGJPBGPAPAG1@Z
API ?AddOrRemoveOCSPISAPIExtension@@YGJHPAH@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?DbgLogStringInit2@@YG?AW4LogPriority@@P6GXPBD@ZW41@@Z
API _CAIsCertTypeValid@8
API _CAGetCertTypeAccessRights@12
API _CAIsValid@8
API _CAGetAccessRights@12
API ?CSPrintErrorLineFileData2@@YGXPBGKJJ@Z
API ?CSPrintErrorLineFileData@@YGXPBGKJ@Z
API ?CSPrintErrorLineFile2@@YGXKJJ@Z
API ?CSPrintErrorLineFile@@YGXKJ@Z
API ?myHGetLastError@@YGJXZ
API ?mylstrcmpiL@@YGHPBG0@Z
API ?myGenerateGuidSerialNumber@@YGXPAU_GUID@@@Z
API ?myGenerateGuidString@@YGJPAPAG@Z
API ?myRevertSanitizeName@@YGJPBGPAPAG@Z
API ?mySanitizedNameToShortName@@YGJPBGHPAPAG@Z
API ?mySanitizedNameToDSName@@YGJPBGPAPAG@Z
API ?mySanitizeName@@YGJPBGPAPAG@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?myGetSidFromDomain@@YGKPAGPAPAX@Z
API ?AddOrRemoveOCSPISAPIExtension@@YGJHPAH@Z
API ?AddOrRemoveOCSPISAPIExtension@@YGJHPAH@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?DbgPrintfW@@YAHKPBGZZ
API ?myHExceptionCodePrint@@YGJPBU_EXCEPTION_POINTERS@@PBDKK@Z
API ?myLogExceptionInit@@YGXP6GXJPBU_EXCEPTION_POINTERS@@PBDKK@Z@Z
API ?myOIDHashOIDToString@@YGJPBGPAPAG@Z
API _caTranslateFileTimePeriodToPeriodUnits@16
API _myRobustLdapBindEx@24
API ?myCAPropInfoLookup@@YGJPBU_CAPROP@@JJPAPBU1@@Z
API ?myCAPropInfoUnmarshal@@YGJPBU_CATRANSPROP@@JKPAPAU_CAPROP@@@Z
API ?myCAPropGetDisplayName@@YGJJPAPBG@Z
API ?myGetErrorMessageTextEx@@YGPAGJKPAPBGK@Z
API ?myGetErrorMessageText1@@YGPAGJKPBG@Z
API ?WszToMultiByteInteger@@YGJKPBGPAKPAPAE@Z
API ?WszToMultiByteIntegerBuf@@YGJKPBGPAKPAE@Z
API ?DbgLogStringInit@@YGXP6GXPBD@Z@Z
API ?myModifyVirtualRootsAndFileShares@@YGJKW4ENUM_CATYPES@@KPAK1@Z
API ?EncodeToFileW@@YGJPBGPBEKK@Z
API ?DecodeFileW@@YGJPBGPAPAEPAKK@Z
API ?myModifyVirtualRootsAndFileShares@@YGJKW4ENUM_CATYPES@@KPAK1@Z
API ?myJetHResult@@YGJJ@Z
API ?myHExceptionCode@@YGJPBU_EXCEPTION_POINTERS@@@Z
API ?myIsDelayLoadHResult@@YGHJ@Z
API _myRobustLdapBind@8
API ?myFreeColumnDisplayNames@@YGXXZ
API ?myDoesDSExist@@YGJH@Z
API ?myHResultToStringRaw_old@@YGPBGPAGJ@Z
API ?myGetErrorMessageText@@YGPAGJK@Z
API ?myHResultToString_old@@YGPBGPAGJ@Z
API ?DbgIsSSActive@@YGHK@Z
API ?DbgPrintfInit@@YGXPBD@Z
API ?DbgPrintf@@YAHKPBDZZ
API ?CSPrintError@@YGXPBDPBG0KJJ@Z
API ?CSPrintAssert@@YGXPBD0K0@Z
API ?myCryptBinaryToStringA@@YGJPBEKKPAPAD@Z
API ?myCryptStringToBinaryA@@YGJPBDKKPAPAEPAK22@Z
API ?myCryptBinaryToString@@YGJPBEKKPAPAG@Z
API ?myCryptStringToBinary@@YGJPBGKKPAPAEPAK22@Z

end
