.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _FreeAddrInfoEx@4
API _FreeAddrInfoEx@4
API _freeaddrinfo@4
API _GetAddrInfoExA@40
API _GetAddrInfoExCancel@4
API _GetAddrInfoExOverlappedResult@4
API _GetAddrInfoExW@40
API _GetAddrInfoW@16
API _GetHostNameW@8
API _GetNameInfoW@28
API _InetNtopW@16
API _InetPtonW@12
API _ProcessSocketNotifications@28
API _SetAddrInfoExA@48
API _SetAddrInfoExW@48
API _WEP@0
API _WPUCompleteOverlappedRequest@20
API _WPUGetProviderPathEx@20
API _WSAAccept@20
API _WSAAddressToStringA@20
API _WSAAddressToStringW@20
API _WSAAdvertiseProvider@8
API _WSAAsyncGetHostByAddr@28
API _WSAAsyncGetHostByName@20
API _WSAAsyncGetProtoByName@20
API _WSAAsyncGetProtoByNumber@20
API _WSAAsyncGetServByName@24
API _WSAAsyncGetServByPort@24
API _WSAAsyncSelect@16
API _WSACancelAsyncRequest@4
API _WSACancelBlockingCall@0
API _WSACleanup@0
API _WSACloseEvent@4
API _WSAConnect@28
API _WSAConnectByList@32
API _WSAConnectByNameA@36
API _WSAConnectByNameW@36
API _WSACreateEvent@0
API _WSADuplicateSocketA@12
API _WSADuplicateSocketW@12
API _WSAEnumNameSpaceProvidersA@8
API _WSAEnumNameSpaceProvidersExA@8
API _WSAEnumNameSpaceProvidersExW@8
API _WSAEnumNameSpaceProvidersW@8
API _WSAEnumNetworkEvents@12
API _WSAEnumProtocolsA@12
API _WSAEnumProtocolsW@12
API _WSAEventSelect@12
API _WSAGetLastError@0
API _WSAGetOverlappedResult@20
API _WSAGetQOSByName@12
API _WSAGetServiceClassInfoA@16
API _WSAGetServiceClassInfoW@16
API _WSAGetServiceClassNameByClassIdA@12
API _WSAGetServiceClassNameByClassIdW@12
API _WSAHtonl@12
API _WSAHtons@12
API _WSAInstallServiceClassA@4
API _WSAInstallServiceClassW@4
API _WSAIoctl@36
API _WSAIsBlocking@0
API _WSAJoinLeaf@32
API _WSALookupServiceBeginA@12
API _WSALookupServiceBeginW@12
API _WSALookupServiceEnd@4
API _WSALookupServiceNextA@16
API _WSALookupServiceNextW@16
API _WSANSPIoctl@32
API _WSANtohl@12
API _WSANtohs@12
API _WSAPoll@12
API _WSAProviderCompleteAsyncCall@8
API _WSAProviderConfigChange@12
API _WSARecv@28
API _WSARecvDisconnect@8
API _WSARecvFrom@36
API _WSARemoveServiceClass@4
API _WSAResetEvent@4
API _WSASend@28
API _WSASendDisconnect@8
API _WSASendMsg@24
API _WSASendTo@36
API _WSASetBlockingHook@4
API _WSASetEvent@4
API _WSASetLastError@4
API _WSASetServiceA@12
API _WSASetServiceW@12
API _WSASocketA@24
API _WSASocketW@24
API _WSAStartup@8
API _WSAStringToAddressA@20
API _WSAStringToAddressW@20
API _WSAUnadvertiseProvider@4
API _WSAUnhookBlockingHook@0
API _WSAWaitForMultipleEvents@20
API _WSApSetPostRoutine@4
API _WSCDeinstallProvider@8
API _WSCDeinstallProviderEx@12
API _WSCEnableNSProvider@8
API _WSCEnumProtocols@16
API _WSCEnumProtocolsEx@20
API _WSCGetApplicationCategory@24
API _WSCGetApplicationCategoryEx@28
API _WSCGetProviderInfo@24
API _WPUGetProviderPath@16
API _WSCInstallNameSpace@20
API _WSCInstallNameSpaceEx@24
API _WSCInstallNameSpaceEx2@28
API _WSCInstallProvider@20
API _WSCInstallProviderAndChains@32
API _WSCInstallProviderEx@28
API _WSCSetApplicationCategory@28
API _WSCSetApplicationCategoryEx@32
API _WSCSetProviderInfo@24
API _WSCUnInstallNameSpace@4
API _WSCUnInstallNameSpaceEx2@8
API _WSCUpdateProvider@20
API _WSCUpdateProviderEx@24
API _WSCWriteNameSpaceOrder@8
API _WSCWriteProviderOrder@8
API _WSCWriteProviderOrderEx@12
API _WahCloseApcHelper@4
API _WahCloseHandleHelper@4
API _WahCloseNotificationHandleHelper@4
API _WahCloseSocketHandle@8
API _WahCloseThread@8
API _WahCompleteRequest@20
API _WahCreateHandleContextTable@4
API _WahCreateNotificationHandle@8
API _WahCreateSocketHandle@8
API _WahDestroyHandleContextTable@4
API _WahDisableNonIFSHandleSupport@0
API _WahEnableNonIFSHandleSupport@0
API _WahEnumerateHandleContexts@12
API _WahInsertHandleContext@8
API _WahNotifyAllProcesses@4
API _WahOpenApcHelper@4
API _WahOpenCurrentThread@8
API _WahOpenHandleHelper@4
API _WahOpenNotificationHandleHelper@4
API _WahQueueUserApc@16
API _WahReferenceContextByHandle@8
API _WahRemoveHandleContext@8
API _WahWaitForNotification@16
API _WahWriteLSPEvent@8
API ___WSAFDIsSet@8
API _accept@12
API _bind@12
API _closesocket@4
API _connect@12
API _freeaddrinfo@4
API _getaddrinfo@16
API _gethostbyaddr@12
API _gethostbyname@4
API _gethostname@8
API _getnameinfo@28
API _getpeername@12
API _getprotobyname@4
API _getprotobynumber@4
API _getservbyname@8
API _getservbyport@8
API _getsockname@12
API _getsockopt@20
API _ntohl@4
API _ntohs@4
API _inet_addr@4
API _inet_ntoa@4
API _inet_ntop@16
API _inet_pton@12
API _ioctlsocket@12
API _listen@8
API _ntohl@4
API _ntohs@4
API _recv@16
API _recvfrom@24
API _select@20
API _send@16
API _sendto@24
API _setsockopt@20
API _shutdown@8
API _socket@12

end
