.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _AcceptSecurityContext@36
API _AcquireCredentialsHandleA@36
API _AcquireCredentialsHandleW@36
API _AddCredentialsA@32
API _AddCredentialsW@32
API _AddSecurityPackageA@8
API _AddSecurityPackageW@8
API _ApplyControlToken@8
API _ChangeAccountPasswordA@32
API _ChangeAccountPasswordW@32
API _CompleteAuthToken@8
API _CredMarshalTargetInfo@12
API _CredUnmarshalTargetInfo@16
API _DecryptMessage@16
API _DeleteSecurityContext@4
API _DeleteSecurityPackageA@4
API _DeleteSecurityPackageA@4
API _EncryptMessage@16
API _EnumerateSecurityPackagesA@8
API _EnumerateSecurityPackagesW@8
API _ExportSecurityContext@16
API _FreeContextBuffer@4
API _FreeCredentialsHandle@4
API _GetSecurityUserInfo@12
API _GetUserNameExA@12
API _GetUserNameExW@12
API _ImpersonateSecurityContext@4
API _ImportSecurityContextA@16
API _ImportSecurityContextW@16
API _InitSecurityInterfaceA@0
API _InitSecurityInterfaceW@0
API _InitializeSecurityContextA@48
API _InitializeSecurityContextW@48
API _LogonUserExExW@44
API _LsaCallAuthenticationPackage@28
API _LsaConnectLocalUser@24
API _LsaConnectUntrusted@4
API _LsaDeregisterLogonProcess@4
API _LsaEnumerateLogonSessions@8
API _LsaFreeReturnBuffer@4
API _LsaGetLogonSessionData@8
API _LsaLogonUser@56
API _LsaLookupAuthenticationPackage@12
API _LsaRegisterLogonProcess@12
API _LsaRegisterPolicyChangeNotification@8
API ?NegMarshallSupplementalCreds@@YGJKPAEPAKPAPAX@Z
API _LsaUnregisterPolicyChangeNotification@8
API _MakeSignature@16
API _QueryContextAttributesA@12
API _QueryContextAttributesExA@16
API _QueryContextAttributesExW@16
API _QueryContextAttributesW@12
API _QueryCredentialsAttributesA@12
API _QueryCredentialsAttributesExA@16
API _QueryCredentialsAttributesExW@16
API _QueryCredentialsAttributesW@12
API _QuerySecurityContextToken@8
API _QuerySecurityPackageInfoA@8
API _QuerySecurityPackageInfoW@8
API _RevertSecurityContext@4
API _SaslAcceptSecurityContext@36
API _SaslEnumerateProfilesA@8
API _SaslEnumerateProfilesW@8
API _SaslGetContextOption@20
API _SaslGetProfilePackageA@8
API _SaslGetProfilePackageW@8
API _SaslIdentifyPackageA@8
API _SaslIdentifyPackageW@8
API _SaslInitializeSecurityContextA@48
API _SaslInitializeSecurityContextW@48
API _SaslSetContextOption@16
API _EncryptMessage@16
API _SecCacheSspiPackages@0
API ?SecDeleteUserModeContext@@YGJPAU_SecHandle@@@Z
API ?SecInitUserModeContext@@YGJPAU_SecHandle@@PAU_SecBuffer@@@Z
API _SeciAllocateAndSetCallFlags@8
API _SeciAllocateAndSetCallTarget@16
API _SeciAllocateAndSetIPAddress@12
API _SeciFreeCallContext@0
API _SeciIsProtectedUser@4
API _SetContextAttributesA@16
API _SetContextAttributesW@16
API _SetCredentialsAttributesA@16
API _SetCredentialsAttributesW@16
API _SspiCompareAuthIdentities@16
API _SspiCopyAuthIdentity@8
API _SspiDecryptAuthIdentity@4
API _SspiDecryptAuthIdentityEx@8
API _SspiEncodeAuthIdentityAsStrings@16
API _SspiEncodeStringsAsAuthIdentity@16
API _SspiEncryptAuthIdentity@4
API _SspiEncryptAuthIdentityEx@8
API _SspiExcludePackage@12
API _SspiFreeAuthIdentity@4
API _SspiGetComputerNameForSPN@8
API _SspiGetTargetHostName@8
API _SspiIsAuthIdentityEncrypted@4
API _SspiLocalFree@4
API _SspiMarshalAuthIdentity@12
API _SspiPrepareForCredRead@16
API _SspiPrepareForCredWrite@28
API _SspiUnmarshalAuthIdentity@12
API ?SspiUnmarshalAuthIdentityInternal@@YGJKPADPAPAXPAK@Z
API _SspiValidateAuthIdentity@4
API _SspiZeroAuthIdentity@4
API _DecryptMessage@16
API _VerifySignature@16

end
