.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _AssocCreate@24
API _AssocGetPerceivedType@16
API _AssocIsDangerous@4
API _AssocQueryKeyA@20
API _AssocQueryKeyW@20
API _AssocQueryStringA@24
API _AssocQueryStringByKeyA@24
API _AssocQueryStringByKeyW@24
API _AssocQueryStringW@24
API _ChrCmpIAStub@8
API _ChrCmpIWStub@8
API _ColorAdjustLuma@12
API _ColorHLSToRGB@12
API _ColorRGBToHLS@16
API _ConnectToConnectionPoint@24
API _Downlevel_DelayLoadFailureHook@8
API _DllGetClassObject@12
API _CCDllGetVersion@4
API _GUIDFromStringW@8
API _GetAcceptLanguagesAStub@8
API _GetAcceptLanguagesWStub@8
API _GetMenuPosFromID@8
API _HashDataStub@16
API _IStream_CopyStub@12
API _IStream_ReadStub@12
API _IStream_ReadPidl@8
API _IStream_ReadStrStub@8
API _IStream_ResetStub@4
API _IStream_SizeStub@8
API _IStream_WriteStub@12
API _IStream_WritePidl@8
API _IStream_WriteStrStub@8
API _IUnknown_AtomicReleaseStub@4
API _IUnknown_Exec@24
API _IUnknown_GetSiteStub@12
API _IUnknown_GetWindow@8
API _IUnknown_QueryServiceStub@16
API _IUnknown_QueryStatus@20
API _IUnknown_SetStub@8
API _IUnknown_SetSiteStub@8
API _StrIsIntlEqualAStub@16
API _StrIsIntlEqualWStub@16
API _IsCharSpaceAStub@4
API _IsCharSpaceWStub@4
API _IsInternetESCEnabledStub@0
API _IsOSStub@4
API _MLLoadLibraryA@12
API _MLLoadLibraryW@12
API _ParseURLAStub@8
API _ParseURLWStub@8
API _PathAddBackslashAStub@4
API _PathAddBackslashWStub@4
API _PathAddExtensionAStub@8
API _PathAddExtensionWStub@8
API _PathAppendAStub@8
API _PathAppendWStub@8
API _PathBuildRootAStub@8
API _PathBuildRootWStub@8
API _PathCanonicalizeAStub@8
API _PathCanonicalizeWStub@8
API _PathCombineAStub@12
API _PathCombineWStub@12
API _PathCommonPrefixAStub@12
API _PathCommonPrefixWStub@12
API _PathCompactPathA@12
API _PathCompactPathExA@16
API _PathCompactPathExW@16
API _PathCompactPathW@12
API _PathCreateFromUrlAStub@16
API _PathCreateFromUrlAllocStub@12
API _PathCreateFromUrlWStub@16
API _PathFileExistsAStub@4
API _PathFileExistsAndAttributesW@8
API _PathFileExistsWStub@4
API _PathFindExtensionAStub@4
API _PathFindExtensionWStub@4
API _PathFindFileNameAStub@4
API _PathFindFileNameWStub@4
API _PathFindNextComponentAStub@4
API _PathFindNextComponentWStub@4
API _PathFindOnPathA@8
API _PathFindOnPathW@8
API _PathFindSuffixArrayA@12
API _PathFindSuffixArrayW@12
API _PathGetArgsAStub@4
API _PathGetArgsWStub@4
API _PathGetCharTypeAStub@4
API _PathGetCharTypeWStub@4
API _PathGetDriveNumberAStub@4
API _PathGetDriveNumberWStub@4
API _PathIsContentTypeA@8
API _PathIsContentTypeW@8
API _PathIsDirectoryA@4
API _PathIsDirectoryEmptyA@4
API _PathIsDirectoryEmptyW@4
API _PathIsDirectoryW@4
API _PathIsFileSpecAStub@4
API _PathIsFileSpecWStub@4
API _PathIsLFNFileSpecAStub@4
API _PathIsLFNFileSpecWStub@4
API _PathIsNetworkPathAStub@4
API _PathIsNetworkPathWStub@4
API _PathIsPrefixAStub@8
API _PathIsPrefixWStub@8
API _PathIsRelativeAStub@4
API _PathIsRelativeWStub@4
API _PathIsRootAStub@4
API _PathIsRootWStub@4
API _PathIsSameRootAStub@8
API _PathIsSameRootWStub@8
API _PathIsSystemFolderA@8
API _PathIsSystemFolderW@8
API _PathIsUNCAStub@4
API _PathIsUNCServerAStub@4
API _PathIsUNCServerShareAStub@4
API _PathIsUNCServerShareWStub@4
API _PathIsUNCServerWStub@4
API _PathIsUNCWStub@4
API _PathIsURLAStub@4
API _PathIsURLWStub@4
API _PathMakePrettyA@4
API _PathMakePrettyW@4
API _PathMakeSystemFolderA@4
API _PathMakeSystemFolderW@4
API _PathMatchSpecAStub@8
API _PathMatchSpecExAStub@12
API _PathMatchSpecExWStub@12
API _PathMatchSpecWStub@8
API _PathParseIconLocationAStub@4
API _PathParseIconLocationWStub@4
API _PathQuoteSpacesAStub@4
API _PathQuoteSpacesWStub@4
API _PathRelativePathToAStub@20
API _PathRelativePathToWStub@20
API _PathRemoveArgsA@4
API _PathRemoveArgsW@4
API _PathRemoveBackslashAStub@4
API _PathRemoveBackslashWStub@4
API _PathRemoveBlanksAStub@4
API _PathRemoveBlanksWStub@4
API _PathRemoveExtensionAStub@4
API _PathRemoveExtensionWStub@4
API _PathRemoveFileSpecAStub@4
API _PathRemoveFileSpecWStub@4
API _PathRenameExtensionAStub@8
API _PathRenameExtensionWStub@8
API _PathSearchAndQualifyAStub@12
API _PathSearchAndQualifyWStub@12
API _PathSetDlgItemPathA@12
API _PathSetDlgItemPathW@12
API _PathSkipRootAStub@4
API _PathSkipRootWStub@4
API _PathStripPathAStub@4
API _PathStripPathWStub@4
API _PathStripToRootAStub@4
API _PathStripToRootWStub@4
API _PathUnExpandEnvStringsAStub@12
API _PathUnExpandEnvStringsWStub@12
API _PathUndecorateA@4
API _PathUndecorateW@4
API _PathUnmakeSystemFolderA@4
API _PathUnmakeSystemFolderW@4
API _PathUnquoteSpacesAStub@4
API _PathUnquoteSpacesWStub@4
API _QISearchStub@16
API _SHAllocSharedStub@12
API _SHAnsiToAnsiStub@12
API _SHAnsiToUnicodeStub@12
API _SHAutoComplete@8
API _SHCopyKeyAStub@16
API _SHCopyKeyWStub@16
API _SHCreateMemStreamStub@8
API _SHCreateShellPalette@4
API _SHCreateStreamOnFileAStub@12
API _SHCreateStreamOnFileExStub@24
API _SHCreateStreamOnFileWStub@12
API _RETIRED_SHCreateStreamWrapper@16
API _SHCreateThreadStub@16
API _SHCreateThreadRefStub@8
API _SHCreateThreadWithHandleStub@20
API _SHCreateWorkerWindowWStub@24
API _SHDeleteEmptyKeyAStub@8
API _SHDeleteEmptyKeyWStub@8
API _SHDeleteKeyAStub@8
API _SHDeleteKeyWStub@8
API _RETIRED_SHDeleteOrphanKeyA@8
API _RETIRED_SHDeleteOrphanKeyW@8
API _SHDeleteValueAStub@12
API _SHDeleteValueWStub@12
API _SHEnumKeyExAStub@16
API _SHEnumKeyExWStub@16
API _SHEnumValueAStub@28
API _SHEnumValueWStub@28
API _SHFormatDateTimeA@16
API _SHFormatDateTimeW@16
API _SHFreeSharedStub@8
API _SHGetInverseCMAP@8
API _SHGetThreadRefStub@4
API _SHGetValueAStub@24
API _SHGetValueWStub@24
API _SHGetViewStatePropertyBag@20
API _SHIsChildOrSelf@8
API ?endDocument@CStubSaxParser2@CXMLPropStoreSaxParser@@UAGJXZ
API _SHLoadIndirectStringStub@16
API _SHLockSharedStub@8
API _SHMessageBoxCheckA@24
API _SHMessageBoxCheckW@24
API _SHOpenRegStream2AStub@16
API _SHOpenRegStream2WStub@16
API _SHOpenRegStreamAStub@16
API _SHOpenRegStreamWStub@16
API _SHPackDispParamsV@16
API _SHPinDllOfCLSID@4
API _SHPropertyBag_ReadStrAlloc@12
API _SHPropertyBag_WriteBSTR@12
API _SHQueryInfoKeyAStub@20
API _SHQueryInfoKeyWStub@20
API _SHQueryValueExAStub@24
API _SHQueryValueExWStub@24
API _SHRegCloseUSKeyStub@4
API _SHRegCreateUSKeyAStub@20
API _SHRegCreateUSKeyWStub@20
API _SHRegDeleteEmptyUSKeyAStub@12
API _SHRegDeleteEmptyUSKeyWStub@12
API _SHRegDeleteUSValueAStub@12
API _SHRegDeleteUSValueWStub@12
API _SHRegDuplicateHKeyStub@4
API _SHRegEnumUSKeyAStub@20
API _SHRegEnumUSKeyWStub@20
API _SHRegEnumUSValueAStub@32
API _SHRegEnumUSValueWStub@32
API _SHRegGetBoolUSValueAStub@16
API _SHRegGetBoolUSValueWStub@16
API _SHRegGetBoolValueFromHKCUHKLM@12
API _SHRegGetIntWStub@12
API _SHRegGetPathAStub@20
API _SHRegGetPathWStub@20
API _SHRegGetUSValueAStub@32
API _SHRegGetUSValueWStub@32
API _SHRegGetValueAStub@28
API _SHRegGetValueFromHKCUHKLM@24
API _SHRegGetValueWStub@28
API _SHRegOpenUSKeyAStub@20
API _SHRegOpenUSKeyWStub@20
API _SHRegQueryInfoUSKeyAStub@24
API _SHRegQueryInfoUSKeyWStub@24
API _SHRegQueryUSValueAStub@32
API _SHRegQueryUSValueWStub@32
API _SHRegSetPathAStub@20
API _SHRegSetPathWStub@20
API _SHRegSetUSValueAStub@24
API _SHRegSetUSValueWStub@24
API _SHRegWriteUSValueAStub@24
API _SHRegWriteUSValueWStub@24
API _SHRegisterValidateTemplate@8
API _SHReleaseThreadRefStub@0
API _SHRunIndirectRegClientCommand@8
API _SHSendMessageBroadcastA@12
API _SHSendMessageBroadcastW@12
API _SHSetThreadRefStub@4
API _SHSetValueAStub@24
API _SHSetValueWStub@24
API _SHSkipJunction@8
API _SHStrDupAStub@8
API _SHStrDupWStub@8
API _SHStripMneumonicA@4
API _SHStripMneumonicW@4
API _SHUnicodeToAnsiStub@12
API _SHUnicodeToAnsiCP@16
API _SHUnicodeToUnicodeStub@12
API _SHUnlockSharedStub@4
API _ShellMessageBoxA
API _ShellMessageBoxW
API _StrCSpnAStub@8
API _StrCSpnIAStub@8
API _StrCSpnIWStub@8
API _StrCSpnWStub@8
API _StrCatBuffAStub@12
API _StrCatBuffWStub@12
API _StrCatChainWStub@16
API _Shlwapi_StrCatW@8
API _StrChrAStub@8
API _StrChrIAStub@8
API _StrChrIWStub@8
API _StrChrNIWStub@12
API _StrChrNWStub@12
API _StrChrWStub@8
API _StrCmpCAStub@8
API _StrCmpCWStub@8
API _StrCmpICAStub@8
API _StrCmpICWStub@8
API _StrCmpIWStub@8
API _StrCmpLogicalWStub@8
API _StrCmpNAStub@12
API _StrCmpNCAStub@12
API _StrCmpNCWStub@12
API _StrCmpNIAStub@12
API _StrCmpNICAStub@12
API _StrCmpNICWStub@12
API _StrCmpNIWStub@12
API _StrCmpNWStub@12
API _StrCmpWStub@8
API _StrCpyNWStub@12
API _Shlwapi_StrCpyW@8
API _StrDupAStub@4
API _StrDupWStub@4
API _StrFormatByteSize64A@16
API _StrFormatByteSizeA@12
API _StrFormatByteSizeEx@20
API _StrFormatByteSizeW@16
API _StrFormatKBSizeA@16
API _StrFormatKBSizeW@16
API _StrFromTimeIntervalA@16
API _StrFromTimeIntervalW@16
API _StrIsIntlEqualAStub@16
API _StrIsIntlEqualWStub@16
API _Shlwapi_StrNCatA@12
API _Shlwapi_StrNCatW@12
API _StrPBrkAStub@8
API _StrPBrkWStub@8
API _StrRChrAStub@12
API _StrRChrIAStub@12
API _StrRChrIWStub@12
API _StrRChrWStub@12
API _StrRStrIAStub@12
API _StrRStrIWStub@12
API _StrRetToBSTRStub@12
API _StrRetToBufA@16
API _StrRetToBufWStub@16
API _StrRetToStrA@12
API _StrRetToStrWStub@12
API _StrSpnAStub@8
API _StrSpnWStub@8
API _StrStrAStub@8
API _StrStrIAStub@8
API _StrStrIWStub@8
API _StrStrNIWStub@12
API _StrStrNWStub@12
API _StrStrWStub@8
API _StrToInt64ExAStub@12
API _StrToInt64ExWStub@12
API _StrToIntAStub@4
API _StrToIntExAStub@12
API _StrToIntExWStub@12
API _StrToIntWStub@4
API _StrTrimAStub@8
API _StrTrimWStub@8
API _UrlApplySchemeAStub@16
API _UrlApplySchemeWStub@16
API _UrlCanonicalizeAStub@16
API _UrlCanonicalizeWStub@16
API _UrlCombineAStub@20
API _UrlCombineWStub@20
API _UrlCompareAStub@12
API _UrlCompareWStub@12
API _UrlCreateFromPathAStub@16
API _UrlCreateFromPathWStub@16
API _UrlEscapeAStub@16
API _UrlEscapeWStub@16
API _UrlFixupWStub@12
API _UrlGetLocationAStub@4
API _UrlGetLocationWStub@4
API _UrlGetPartAStub@20
API _UrlGetPartWStub@20
API _UrlHashAStub@12
API _UrlHashWStub@12
API _UrlIsAStub@8
API _UrlIsNoHistoryAStub@4
API _UrlIsNoHistoryWStub@4
API _UrlIsOpaqueAStub@4
API _UrlIsOpaqueWStub@4
API _UrlIsWStub@8
API _UrlUnescapeAStub@16
API _UrlUnescapeWStub@16
API _WhichPlatform@0
API _wnsprintfA
API _wnsprintfW
API _wvnsprintfA@16
API _wvnsprintfW@16
API _SHWaitForThreadWithWakeMask@12
API _SHManagedCreateStreamOnFile@28
API _SHManagedCreateFile@28
API _IStream_WriteStrLong@8
API _IStream_ReadStrLong@8
API _PathUnExpandSystemEnvStringsW@12
API _RETIRED_SHGetSignatureInfoEx@24
API _SHGetSizeSharedStub@4
API _SHInvokeCommandsOnContextMenuEx@32
API _SHInvokeCommandOnContextMenuEx@28
API _IUnknown_TranslateAcceleratorGlobal@8
API _SHPropertyBag_WriteUnknown@12
API _SHPropertyBag_ReadUnknown@16
API _SHGetShellKeyEx@16
API _SHGlobalCounterDecrement@4
API _SHGlobalCounterIncrement@4
API _SHGlobalCounterGetValue@4
API _SHRegSetValue@28
API _SHCreateStreamOnModuleResourceW@16
API _SHCreateStreamOnDllResourceW@16
API _SHCreatePropertyBagOnCachedProfileSection@20
API _SHCreatePropertyStoreOnXML@20
API _IsAppCompatModeEnabled@4
API _SHWindowsPolicy@4
API _DupWideToAnsi@8
API _SHClearViewStatePropertyBag@12
API _SHPropertyBag_ReadPropertyKey@12
API _SHPropertyBag_WritePropertyKey@12
API _IUnknown_RemoveBackReferences@4
API _RETIRED_StrIsCanonicalEqualW@8
API _RETIRED_StrIsCanonicalEqualA@8
API _RETIRED_StrIsCanonicalEqualNW@12
API _RETIRED_StrIsCanonicalEqualNA@12
API _RETIRED_IUnknown_QueryServiceQueryStatus@24
API _RETIRED_SHSafeQueryInterface@12
API _SHAnsiToUnicodeCPAlloc@12
API _SHUnicodeToAnsiCPAlloc@12
API _RETIRED_SHGetUserToken_shlwapi@8
API _CreateSizedDIBSECTION@28
API _FactorAspectRatio@48
API _CalculateAspectRatio@12
API _ConvertDIBSECTIONToThumbnail@32
API _SHPropertyBag_WriteULONGLONG@16
API _SHPropertyBag_ReadULONGLONG@12
API _QuerySourceCreateFromKeyEx@24
API _IWebBrowser_Navigate2@24
API _RETIRED_IWebBrowser_Navigate@24
API _RETIRED_IShellFolder_ParseDisplayNameC@28
API _SHExpandEnvironmentStringsAlloc@8
API _SHInvokeCommandWithFlagsAndSite@28
API _RETIRED_SHGetPrivateProfileStruct@20
API _RETIRED_SHCoCreateExtension@24
API _RETIRED_SHCoExtensionAllowed@8
API _RETIRED_SHGetAllAccessSA@0
API _IsInternetESCEnabledStub@0
API _AssocGetUrlAction@4
API _SHWindowsPolicyGetValue@12
API _RETIRED_SHGetSignatureInfo@12
API _RETIRED_SHCoExtensionCollectStats@12
API _RETIRED_SHGetPrivateProfileStruct@20
API _RETIRED_SHGetPrivateProfileString@24
API _RETIRED_SHGetPrivateProfileSectionNames@12
API _RETIRED_SHGetPrivateProfileSection@16
API _RETIRED_SHEvaluateSystemCommandTemplate@16
API _RETIRED_IShellFolder_CompareIDs@16
API _RETIRED_GetTemplateInfoFromHandle@12
API _SHCoCreateInstanceAC@20
API _SHAreIconsEqual@8
API _RETIRED_DelayLoadFailureHook@8
API _IUnknown_DoContextMenuPopup@20
API _SHForwardContextMenuMsg@24
API _QuerySourceCreateFromKey@20
API _CreateColorSpaceW@4
API _GetUIVersion@0
API _SHInvokeCommandsOnContextMenu@24
API _SHInvokeCommandOnContextMenu@20
API _IUnknown_ShowBrowserBar@12
API _IUnknown_QueryServiceForWebBrowserApp@12
API _SHBoolSystemParametersInfo@8
API _IUnknown_QueryServicePropertyBag@16
API _SHPropertyBag_Delete@8
API _SHPropertyBag_ReadBOOL@12
API _SHGetPerScreenResName@12
API _SHPropertyBag_WriteStream@12
API _SHPropertyBag_ReadStream@12
API _SHPropertyBag_WriteLONG@12
API _SHPropertyBag_ReadLONG@12
API _SHPropertyBag_WriteSHORT@12
API _SHPropertyBag_ReadSHORT@12
API _SHPropertyBag_WritePOINTS@12
API _SHPropertyBag_ReadPOINTS@12
API _SHPropertyBag_WriteRECTL@12
API _SHPropertyBag_ReadRECTL@12
API _SHPropertyBag_WritePOINTL@12
API _SHPropertyBag_ReadPOINTL@12
API _SHPropertyBag_ReadBSTR@12
API _SKAllocValueW@24
API _SKDeleteValueW@12
API _SKSetValueW@24
API _SKGetValueW@24
API _IUnknown_ProfferService@16
API _PathFileExistsDefExtAndAttributesW@12
API _SHLockSharedExStub@12
API _IUnknown_OnFocusChangeIS@12
API _SHPropertyBag_WriteDWORD@12
API _SHPropertyBag_ReadDWORD@12
API _SHPropertyBag_WriteGUID@12
API _SHPropertyBag_ReadGUID@12
API _SHPropertyBag_WriteBOOL@12
API _RETIRED_SHPropertyBag_ReadBOOLOld@12
API _SHPropertyBag_WriteInt@12
API _SHPropertyBag_ReadInt@12
API _SHPropertyBag_WriteStr@12
API _SHPropertyBag_ReadStr@16
API _SHPropertyBag_ReadType@16
API _RETIRED_PrettifyFileDescriptionW@8
API _SHGetShellKey@12
API _GlobalFindAtomW@4
API _GlobalAddAtomW@4
API _RETIRED_SHConvertGraphicsFile@12
API _ModeToCreateFileFlags@20
API _MapWin32ErrorToSTG@4
API _IUnknown_QueryServiceExec@28
API _RETIRED_SHMessageBoxHelpW@28
API _RETIRED_SHMessageBoxHelpA@28
API _IUnknown_HasFocusIO@4
API _RETIRED_UrlCrackW@16
API _IUnknown_UIActivateIO@12
API _IUnknown_TranslateAcceleratorIO@8
API _SHCreatePropertyBagOnMemory@12
API _SHGetObjectCompatFlags@8
API _RETIRED_GetShellSecurityDescriptor@8
API _RETIRED_SHSetIniStringUTF7W@16
API _RETIRED_SHGetIniStringUTF7W@20
API _SHCreatePropertyBagOnProfileSection@20
API _SHCreatePropertyBagOnRegKey@20
API _RETIRED_IUnknown_ProfferServiceOld@20
API _RunRegCommand@12
API _RunIndirectRegCommand@16
API _PathUnExpandEnvStringsForUserW@16
API _PathUnExpandEnvStringsForUserA@16
API _SHExpandEnvironmentStringsForUserW@16
API _SHExpandEnvironmentStringsForUserA@16
API _RETIRED_SHGetAppCompatFlags@4
API _SHExpandEnvironmentStringsWStub@12
API _SHExpandEnvironmentStringsAStub@12
API _GetLongPathNameA@12
API _GetLongPathNameW@12
API _PathIsValidCharWStub@8
API _PathIsValidCharAStub@8
API _CharLowerNoDBCSW@4
API _CharLowerNoDBCSA@4
API _CharUpperNoDBCSW@4
API _CharUpperNoDBCSA@4
API _NextPathW@12
API _NextPathA@12
API _FixSlashesAndColonW@4
API _FixSlashesAndColonA@4
API _PathFileExistsAndAttributesA@8
API _GetSystemWindowsDirectoryWStub@8
API _GetSystemWindowsDirectoryAStub@8
API _GetEnvironmentVariableWStub@12
API _RETIRED_SHGetWebFolderFilePathW@12
API _RETIRED_SHGetWebFolderFilePathA@12
API _SHLoadRegUIStringW@16
API _SHLoadRegUIStringA@16
API _CLSIDFromStringWrap@8
API _CLSIDFromProgIDWrap@8
API _SendMessageTimeoutW@28
API _RETIRED_MLClearMLHInstance@4
API _RETIRED_MLSetMLHInstance@8
API _RETIRED_MLIsMLHInstance@4
API _NtUserTrackPopupMenuEx@24
API _TrackPopupMenu@28
API _NtUserDestroyMenu@4
API _NtUserDeleteMenu@12
API _RETIRED_SHGlobalCounterDecrement@4
API _RETIRED_SHGlobalCounterCreateNamedW@8
API _RETIRED_SHGlobalCounterCreateNamedA@8
API _RETIRED_SHLoadPersistedDataObject@8
API _RETIRED_SHPersistDataObject@8
API _SHFlushSFCache@0
API _RETIRED_MLFreeLibrary@4
API _RETIRED_SHWinHelpOnDemandA@20
API _RETIRED_SHWinHelpOnDemandW@20
API _RETIRED_SHHtmlHelpOnDemandA@24
API _RETIRED_SHHtmlHelpOnDemandW@24
API _SHGetMachineInfo@4
API _RETIRED_AssocMakeFileExtsToApplicationA@12
API _RETIRED_AssocMakeFileExtsToApplicationW@12
API _AssocMakeApplicationByKeyA@12
API _AssocMakeApplicationByKeyW@12
API _AssocMakeShell@16
API _AssocMakeProgid@16
API _RETIRED_MLBuildResURLW@24
API _RETIRED_MLBuildResURLA@24
API _RETIRED_IShellFolder_EnumObjects@16
API _GetOpenFileNameW@4
API _PrintDlgW@4
API _PageSetupDlgW@4
API _StrCpyNXWStub@12
API _StrCpyNXAStub@12
API _RETIRED_MLHtmlHelpW@20
API _WinHelpW@16
API _RETIRED_MLHtmlHelpA@20
API _WinHelpA@16
API _SHChangeNotifyStub@16
API _CreateDialogIndirectParamW@20
API _EndDialog@8
API _WNetGetLastErrorW@20
API _RETIRED_WNetRestoreConnectionWrapW@8
API _GetSaveFileNameW@4
API _RETIRED_SHQueryRawAcceleratorMsg@12
API _RETIRED_SHQueryRawAccelerator@20
API _RETIRED_SHLoadRawAccelerators@8
API _SHRestrictedMessageBox@4
API _ZoneConfigureW@8
API _ZoneComputePaneSize@4
API _AssocCopyVerbs@8
API _Shell_GetCachedImageIndexA@12
API _Shell_GetCachedImageIndexW@12
API _GetThreadUILanguageStub@0
API _RETIRED_SHCheckDiskForMediaW@16
API _RETIRED_SHCheckDiskForMediaA@16
API _DdeQueryStringW@20
API _DdeCreateStringHandleW@12
API _DdeInitializeW@16
API _ExtractIconW@12
API _CreateProcessWStub@40
API _GetPrivateProfileStructW@20
API _WritePrivateProfileStructW@20
API _RegEnumValueWrapW@32
API _DoesStringRoundTripW@12
API _DoesStringRoundTripA@12
API _SHInvokeCommand@16
API _RETIRED_GetUserNameWrapW@8
API _GetShortPathNameW@12
API _RemoveDirectoryW@4
API _OpenEventW@12
API _SHDefExtractIconW@24
API _SHGetNewLinkInfoW@20
API _RETIRED_SHGetAllAccessSA@0
API _IUnknown_EnableModeless@8
API _VerQueryValueWrapW@16
API _GetFileVersionInfoWrapW@16
API _GetFileVersionInfoSizeWrapW@8
API _SHGetFileDescriptionA@20
API _SHGetFileDescriptionW@20
API _RegDeleteValueWrapW@8
API _SHRegGetCLSIDKey@24
API _RETIRED_SHRegGetCLSIDKeyA@20
API _InterlockedCompareExchangeStub@12
API _FindNextFileW@8
API _MessageBoxW@16
API _GetNumberFormatWStub@24
API _SetFileAttributesW@8
API _ExtractIconExW@20
API _SHFileOperationW@4
API _ShellExecuteExW@4
API _SHGetPathFromIDListW@8
API _SHBrowseForFolderW@4
API _CallMsgFilterW@8
API _MIME_GetExtensionW@12
API _RETIRED_MIME_GetExtensionA@12
API _RETIRED_GetMIMETypeSubKeyW@12
API _RETIRED_GetMIMETypeSubKeyA@12
API _RETIRED_UnregisterExtensionForMIMETypeW@4
API _RETIRED_UnregisterExtensionForMIMETypeA@4
API _RETIRED_RegisterExtensionForMIMETypeW@8
API _RETIRED_RegisterExtensionForMIMETypeA@8
API _RETIRED_UnregisterMIMETypeForExtensionW@4
API _RETIRED_UnregisterMIMETypeForExtensionA@4
API _RETIRED_RegisterMIMETypeForExtensionW@8
API _RETIRED_RegisterMIMETypeForExtensionA@8
API _FindWindowExW@16
API _DragQueryFileW@16
API _IShellFolder_ParseDisplayName@28
API _IShellFolder_GetDisplayNameOf@20
API _GetClassInfoExW@12
API _RegisterClassExW@4
API _SHGetFileInfoWStub@20
API _GetPrivateProfileStringW@24
API _GetDateFormatWStub@24
API _GetTimeFormatWStub@24
API _LoadLibraryWStub@4
API _IsBadStringPtrW@8
API _CreateSemaphoreW@16
API _ExpandEnvironmentStringsWStub@12
API _CreateMutexW@12
API _CreateMetaFileW@4
API _InsertMenuItemW@16
API _GetMenuItemInfoW@16
API _DrawTextExW@24
API _CreateFontWStub@56
API _ExtTextOutW@32
API _WritePrivateProfileStringW@16
API _RETIRED_CreateURLFileContentsA@8
API _RETIRED_CreateURLFileContentsW@8
API _SHSetIniStringW@16
API _SHGetIniStringW@20
API _RETIRED_SHCancelUserWorkItems@8
API _SHMessageBoxCheckExW@28
API _SHMessageBoxCheckExA@28
API _RETIRED_SHMirrorIcon@8
API _PlaySoundW@12
API _IUnknown_CPContainerInvokeIndirect@12
API _IUnknown_CPContainerOnChanged@8
API _IUnknown_CPContainerInvokeParam
API _IConnectionPoint_OnChanged@8
API _IConnectionPoint_SimpleInvoke@12
API _IConnectionPoint_InvokeWithCancel@20
API _SHPackDispParams
API _SHInvokeDefaultCommand@12
API _RETIRED_SHDialogBox@20
API _RETIRED_RegisterGlobalHotkeyA@12
API _RETIRED_RegisterGlobalHotkeyW@12
API _RETIRED_SHTerminateThreadPool@0
API _RETIRED_SHSetThreadPoolLimits@4
API _SHGetRestriction@12
API _GUIDFromStringA@8
API _SHWeakReleaseInterface@8
API _SHWeakQueryInterface@16
API _SHRestrictionLookup@24
API _SHCancelTimerQueueTimer@8
API _RETIRED_SHChangeTimerQueueTimer@16
API _SHSetTimerQueueTimer@28
API _RETIRED_SHDeleteTimerQueue@4
API _RETIRED_SHCreateTimerQueue@0
API _SHQueueUserWorkItem@28
API _RETIRED_SHUnregisterWait@4
API _RETIRED_SHRegisterWaitForSingleObject@24
API _SHCreateWorkerWindowA@24
API _RETIRED_EventTraceHandler@8
API _RETIRED_StopWatchExW@24
API _RETIRED_StopWatchExA@24
API _RETIRED_StopWatch_SetMsgLastLocation@4
API _RETIRED_StopWatch_DispatchTime@36
API _RETIRED_GetPerfTime@0
API _RETIRED_StopWatch_MarkJavaStop@12
API _RETIRED_StopWatch_MarkSameFrameStart@4
API _RETIRED_StopWatch_MarkFrameStart@4
API _RETIRED_StopWatch_CheckMsg@36
API _RETIRED_StopWatch_TimerHandler@16
API _RETIRED_StopWatchW@20
API _RETIRED_StopWatchA@20
API _RETIRED_StopWatchFlush@0
API _RETIRED_StopWatchMode@0
API _SHDefWindowProc@16
API _SHUnregisterClassesW@12
API _SHUnregisterClassesA@12
API _SHRegisterClassWStub@4
API _ZoneCheckHostEx@28
API _ZoneCheckHost@12
API _ZoneCheckUrlExCacheW@36
API _ZoneCheckUrlExCacheA@36
API _ZoneCheckUrlExW@32
API _ZoneCheckUrlExA@32
API _ZoneCheckUrlW@16
API _ZoneCheckUrlA@16
API _RETIRED_ZoneCheckPathW@16
API _RETIRED_ZoneCheckPathA@16
API _RETIRED_SHGlobalCounterIncrement@4
API _RETIRED_SHGlobalCounterGetValue@4
API _RETIRED_SHGlobalCounterCreate@4
API _SHRemoveDefaultDialogFont@4
API _SHSetDefaultDialogFont@8
API _SHAnsiToUnicodeCP@16
API _FDSA_DeleteItem@8
API _FDSA_InsertItem@12
API _FDSA_Destroy@4
API _FDSA_Initialize@20
API _RETIRED_IContextMenu_Invoke@16
API _SHGetValueGoodBootW@24
API _SHGetValueGoodBootA@24
API _IsQSForward@12
API _MayExecForward@28
API _MayQSForward@24
API _SHSearchMapInt@16
API _SHFillRectClr@12
API _RETIRED_SHVerbExistsNA@16
API _SHIsExpandableFolder@8
API _SHWaitForSendMessageThread@8
API _SHGetCurColorRes@0
API _SHGetMenuFromID@8
API _IUnknown_HandleIRestrict@20
API _RETIRED_IUnknown_OnFocusOCS@8
API _RETIRED_IUnknown_TranslateAcceleratorOCS@12
API _SHLoadFromPropertyBag@8
API _SHSimulateDrop@20
API _SHRegisterClassA@4
API _SHCheckMenuItem@12
API _SHEnableMenuItem@12
API _SHRemoveAllSubMenus@4
API _SHMenuIndexFromID@8
API _SHPropagateMessage@20
API _SHLoadMenuPopup@8
API _IUnknown_GetClassID@8
API _IUnknown_SetOwner@8
API _RETIRED_SHIsSameObject@8
API _PathSkipLeadingSlashesA@4
API _SHSetParentHwnd@8
API _SHIsEmptyStream@4
API _SHSetWindowBits@16
API _SHTruncateStringStub@8
API _RETIRED_SHAboutInfoW@8
API ?SHAboutInfoA@@YGHPADK@Z
API _CompareStringWStub@24
API _wvsprintfW@12
API _WinHelpW@16
API _VkKeyScanW@4
API _UnregisterClassW@8
API _TranslateAcceleratorW@12
API _SystemParametersInfoW@16
API _StartDocW@8
API _SetWindowTextW@8
API _SetWindowsHookExW@16
API _SetWindowLongW@12
API _SetPropW@12
API _SetMenuItemInfoW@16
API _SetDlgItemTextW@12
API _SetCurrentDirectoryWStub@4
API _SendMessageW@16
API _SendDlgItemMessageW@20
API _RemovePropW@8
API _RegisterWindowMessageW@4
API _RegisterWindowMessageW@4
API _RegisterClassW@4
API _RegSetValueExWrapW@24
API _RETIRED_RegSetValueWrapW@20
API _RegQueryValueExWrapW@24
API _RegQueryValueWrapW@16
API _RegQueryInfoKeyWrapW@48
API _RegOpenKeyExWrapW@20
API _RegOpenKeyWrapW@12
API _RegEnumKeyExWrapW@32
API _RETIRED_RegEnumKeyWrapW@16
API _RegDeleteKeyWrapW@8
API _RegCreateKeyExWrapW@36
API _RETIRED_RegCreateKeyWrapW@12
API _PostThreadMessageW@16
API _PostMessageW@16
API _PeekMessageW@20
API _OutputDebugStringWStub@4
API _OemToCharW@8
API _MoveFileW@8
API _CopyFileW@12
API _GetCharacterPlacementW@24
API _GetCharWidth32W@16
API _ModifyMenuW@20
API _MessageBoxIndirectW@4
API _LoadStringW@16
API _LoadMenuW@8
API _LoadLibraryExWStub@12
API _LoadImageW@24
API _LoadIconW@8
API _LoadCursorW@8
API _LoadBitmapW@8
API _LoadAcceleratorsW@8
API _IsDialogMessageW@8
API _InsertMenuW@20
API _GetWindowsDirectoryWStub@8
API _GetWindowTextLengthW@4
API _GetWindowTextW@12
API _GetWindowLongW@8
API _GetTextMetricsWStub@8
API _GetTextFaceW@12
API _GetTextExtentPoint32WStub@16
API _GetTempPathW@8
API _GetTempFileNameW@16
API _GetStringTypeExWStub@20
API _GetPropW@8
API _GetProfileStringW@20
API _GetPrivateProfileIntW@16
API _GetObjectWStub@12
API _GetModuleHandleWStub@4
API _SearchPathWStub@24
API _GetSystemDirectoryWStub@8
API _GetModuleFileNameWStub@12
API _GetMessageW@16
API _GetMenuStringW@20
API _GetLocaleInfoWStub@16
API _GetFullPathNameW@16
API _GetFileAttributesW@4
API _GetDlgItemTextW@16
API _GetCurrentDirectoryWStub@8
API _GetClipboardFormatNameW@12
API _GetClassNameW@12
API _GetClassLongW@8
API _GetClassInfoW@12
API _FormatMessageWStub@28
API _FindWindowW@8
API _FindResourceWStub@12
API _FindFirstFileW@8
API _EnumResourceNamesW@16
API _EnumFontFamiliesExW@20
API _EnumFontFamiliesW@16
API _DrawTextW@20
API _DispatchMessageW@4
API _DialogBoxParamW@20
API _DialogBoxIndirectParamW@20
API _DeleteFileW@4
API _NtdllDefWindowProc_W@0
API _CreateWindowExW@48
API _CreateICW@16
API _CreateFontIndirectW@4
API _CreateFileW@28
API _CreateEventW@16
API _CreateDirectoryW@8
API _CreateDialogParamW@20
API _CreateDCW@16
API _NtUserCreateAcceleratorTable@8
API _NtUserCopyAcceleratorTable@12
API _CompareStringWStub@24
API _CharUpperBuffWStub@8
API _CharUpperWStub@4
API _CharToOemW@8
API _CharPrevWStub@8
API _CharNextWStub@4
API _CharLowerBuffWStub@8
API _CharLowerWStub@4
API _CallWindowProcW@20
API _AppendMenuW@16
API _GetStringType3ExW@12
API _IsCharXDigitWStub@4
API _IsCharDigitWStub@4
API _IsCharCntrlWStub@4
API _IsCharPunctWStub@4
API _IsCharBlankWStub@4
API _IsCharAlphaNumericWStub@4
API _IsCharLowerWStub@4
API _IsCharUpperWStub@4
API _IsCharAlphaWStub@4
API _SHStringFromGUIDW@12
API _SHStringFromGUIDA@12
API _SHFindDataBlock@8
API _SHRemoveDataBlock@8
API _SHAddDataBlock@8
API _SHFreeDataBlockList@4
API _SHReadDataBlockList@8
API _SHWriteDataBlockList@8
API _RETIRED_RegisterDefaultAcceptHeaders@8
API _SHMapHandleStub@20
API _PathFindOnPathExW@12
API _PathFindOnPathExA@12
API _PathFileExistsDefExtW@8
API _PathFileExistsDefExtA@8

end
