.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _CLIPFORMAT_UserFree@8
API _CLIPFORMAT_UserMarshal@12
API _CLIPFORMAT_UserSize@12
API _CLIPFORMAT_UserUnmarshal@12
API _CLSIDFromOle1Class@12
API _CLSIDFromProgID@8
API _CLSIDFromProgIDEx@8
API _CLSIDFromString@8
API _CStdAsyncStubBuffer2_Connect@8
API _CStdAsyncStubBuffer2_Disconnect@4
API _CStdAsyncStubBuffer2_Release@4
API _CStdAsyncStubBuffer_AddRef@4
API _CStdAsyncStubBuffer_Connect@8
API _CStdStubBuffer_Disconnect@4 ; -> CStdAsyncStubBuffer_Disconnect
API _CStdAsyncStubBuffer_Invoke@12
API _CStdAsyncStubBuffer_QueryInterface@12
API _CStdAsyncStubBuffer_Release@4
API _CStdStubBuffer2_Connect@8
API _CStdStubBuffer2_CountRefs@4
API _CStdAsyncStubBuffer2_Disconnect@4 ; -> CStdStubBuffer2_Disconnect
API _CStdStubBuffer2_QueryInterface@12
API _CStdAsyncStubBuffer_AddRef@4 ; -> CStdStubBuffer_AddRef
API _CStdStubBuffer_Connect@8
API _CStdStubBuffer_CountRefs@4
API _CStdStubBuffer_DebugServerQueryInterface@8
API _CStdStubBuffer_DebugServerRelease@8
API _CStdStubBuffer_Disconnect@4
API _CStdStubBuffer_Invoke@12
API _CStdStubBuffer_IsIIDSupported@8
API _CStdStubBuffer_QueryInterface@12
API _CleanupComl2StateInAllTls@0
API _CleanupOleStateInAllTls@0
API _CleanupTlsComl2State@4
API _CleanupTlsOleState@4
API _ClearCleanupFlag@4
API _CoAddRefServerProcess@0
API _CoAllowUnmarshalerCLSID@4
API _CoCancelCall@8
API _CoCopyProxy@8
API _CoCreateErrorInfo@4
API _CoCreateFreeThreadedMarshaler@8
API _CoCreateGuid@4
API _CoCreateInstance@20
API _CoCreateInstanceEx@24
API _CoCreateInstanceFromApp@24
API _CoCreateObjectInContext@16
API _CoDeactivateObject@8
API _CoDecodeProxy@16
API _CoDecrementMTAUsage@4
API _CoDisableCallCancellation@4
API _CoDisconnectContext@4
API _CoDisconnectObject@8
API _CoEnableCallCancellation@4
API _CoFileTimeNow@4
API _CoFreeUnusedLibraries@0
API _CoFreeUnusedLibrariesEx@8
API _CoGetActivationState@24
API _CoGetApartmentID@8
API _CoGetApartmentType@8
API _CoGetCallContext@8
API _CoGetCallState@8
API _CoGetCallerTID@4
API _CoGetCancelObject@12
API _CoGetClassObject@20
API _CoGetClassVersion@12
API _CoGetContextToken@4
API _CoGetCurrentLogicalThreadId@4
API _CoGetCurrentProcess@0
API _CoGetDefaultContext@12
API _CoGetErrorInfo@8
API _CoGetInstanceFromFile@32
API _CoGetInstanceFromIStorage@28
API _CoGetInterfaceAndReleaseStream@12
API _CoGetMalloc@8
API _CoGetMarshalSizeMax@24
API _CoGetModuleArchitecture@8
API _CoGetModuleType@8
API _CoGetObjectContext@8
API _CoGetPSClsid@8
API _CoGetProcessIdentifier@4
API _CoGetStandardMarshal@24
API _CoGetStdMarshalEx@12
API _CoGetSystemSecurityPermissions@8
API _CoGetTreatAsClass@8
API _CoImpersonateClient@0
API _CoIncrementMTAUsage@4
API _CoInitializeEx@8
API _CoInitializeSecurity@36
API _CoInitializeWOW@8
API _CoInvalidateRemoteMachineBindings@4
API _CoIsHandlerConnected@4
API _CoIsOle1Class@4
API _CoLockObjectExternal@12
API _CoMarshalHresult@8
API _CoMarshalInterThreadInterfaceInStream@12
API _CoMarshalInterface@24
API _CoPopServiceDomain@4
API _CoPushServiceDomain@4
API _CoQueryAuthenticationServices@8
API _CoQueryClientBlanket@28
API _CoQueryProxyBlanket@32
API _CoReactivateObject@8
API _CoRegisterActivationFilter@4
API _CoRegisterClassObject@20
API _CoRegisterConsoleHandles@16
API _CoRegisterDeviceCatalog@8
API _CoRegisterInitializeSpy@8
API _CoRegisterMallocSpy@4
API _CoRegisterMessageFilter@8
API _CoRegisterPSClsid@8
API _CoRegisterRacActivationToken@8
API _CoRegisterSurrogate@4
API _CoRegisterSurrogateEx@8
API _CoReleaseMarshalData@4
API _CoReleaseServerProcess@0
API _CoResumeClassObjects@0
API _CoRetireServer@4
API _CoRevertToSelf@0
API _CoRevokeClassObject@4
API _CoRevokeConsoleHandles@8
API _CoRevokeDeviceCatalog@4
API _CoRevokeInitializeSpy@8
API _CoRevokeMallocSpy@0
API _CoRevokeRacActivationToken@8
API _CoSetCancelObject@4
API _CoSetErrorInfo@8
API _CoSetProxyBlanket@32
API _CoSuspendClassObjects@0
API _CoSwitchCallContext@8
API _CoTaskMemAlloc@4
API _CoTaskMemFree@4
API _CoTaskMemRealloc@8
API _CoTestCancel@0
API _CoTreatAsClass@8
API _CoUninitialize@0
API _CoUnloadingWOW@4
API _CoUnmarshalHresult@8
API _CoUnmarshalInterface@12
API _CoVrfCheckThreadState@4
API _CoVrfGetThreadState@4
API _CoVrfReleaseThreadState@4
API _CoWaitForMultipleHandles@20
API _CoWaitForMultipleObjects@20
API _CoCreateErrorInfo@4 ; -> CreateErrorInfo
API _CreateStreamOnHGlobal@12
API _DcomChannelSetHResult@12
API _DllDebugObjectRPCHook@8
API _DllGetActivationFactory@8
API _DllGetClassObject@12
API _EnableHookObject@8
API _FreePropVariantArray@8
API _FreePropVariantArrayWorker@12
API _GetCatalogHelper@8
API _CoGetErrorInfo@8 ; -> GetErrorInfo
API _GetFuncDescs@8
API _GetHGlobalFromStream@8
API _GetHookInterface@4
API _GetRestrictedErrorInfo@4
API _CStdStubBuffer_DebugServerRelease@8 ; -> HACCEL_UserFree
API _HACCEL_UserMarshal@12
API _HDC_UserSize@12 ; -> HACCEL_UserSize
API _HDC_UserUnmarshal@12 ; -> HACCEL_UserUnmarshal
API _HBITMAP_UserFree@8
API _HBITMAP_UserMarshal@12
API _HBITMAP_UserSize@12
API _HBITMAP_UserUnmarshal@12
API _CStdStubBuffer_DebugServerRelease@8 ; -> HBRUSH_UserFree
API _HACCEL_UserMarshal@12 ; -> HBRUSH_UserMarshal
API _HDC_UserSize@12 ; -> HBRUSH_UserSize
API _HDC_UserUnmarshal@12 ; -> HBRUSH_UserUnmarshal
API ?HRGN_UserFree@@YGXPAKPAPAUHRGN__@@@Z ; -> HDC_UserFree
API _HACCEL_UserMarshal@12 ; -> HDC_UserMarshal
API _HDC_UserSize@12
API _HDC_UserUnmarshal@12
API _HGLOBAL_UserFree@8
API _HGLOBAL_UserMarshal@12
API _HGLOBAL_UserSize@12
API _HGLOBAL_UserUnmarshal@12
API _CStdStubBuffer_DebugServerRelease@8 ; -> HICON_UserFree
API _HACCEL_UserMarshal@12 ; -> HICON_UserMarshal
API _HDC_UserSize@12 ; -> HICON_UserSize
API _HDC_UserUnmarshal@12 ; -> HICON_UserUnmarshal
API _CStdStubBuffer_DebugServerRelease@8 ; -> HMENU_UserFree
API _HACCEL_UserMarshal@12 ; -> HMENU_UserMarshal
API _HDC_UserSize@12 ; -> HMENU_UserSize
API _HDC_UserUnmarshal@12 ; -> HMENU_UserUnmarshal
API _CStdStubBuffer_DebugServerRelease@8 ; -> HMONITOR_UserFree
API _HMONITOR_UserMarshal@12
API _HMONITOR_UserSize@12
API _HWND_UserUnmarshal@12 ; -> HMONITOR_UserUnmarshal
API _HPALETTE_UserFree@8
API _HPALETTE_UserMarshal@12
API _HPALETTE_UserSize@12
API _HPALETTE_UserUnmarshal@12
API ?HRGN_UserFree@@YGXPAKPAPAUHRGN__@@@Z
API _HACCEL_UserMarshal@12 ; -> HRGN_UserMarshal
API _HDC_UserSize@12 ; -> HRGN_UserSize
API _HDC_UserUnmarshal@12 ; -> HRGN_UserUnmarshal
API _HSTRING_UserFree@8
API _HSTRING_UserMarshal@12
API _HSTRING_UserSize@12
API _HSTRING_UserUnmarshal@12
API _CStdStubBuffer_DebugServerRelease@8 ; -> HWND_UserFree
API _HMONITOR_UserMarshal@12 ; -> HWND_UserMarshal
API _HMONITOR_UserSize@12 ; -> HWND_UserSize
API _HWND_UserUnmarshal@12
API _HkOleRegisterObject@16
API _IIDFromString@8
API _InternalAppInvokeExceptionFilter@16
API ?NdrExtFreeInterfacePointer@@YGXPAE@Z ; -> InternalCAggIdRelease
API _InternalCAggIdSetHandler@8
API _InternalCCFreeUnused@4
API _InternalCCGetClassInformationForDde@8
API _InternalCCGetClassInformationFromKey@4
API _InternalCCSetDdeServerWindow@8
API _InternalCMLSendReceive@16
API _InternalCMLSendReceive2@12
API _InternalCStdIdentityGetIProxyManager@4
API _InternalCStdIdentityGetInternalUnk@4
API _InternalCStdIdentityUpdateFlags@8
API _InternalServerExceptionFilter@4 ; -> InternalCallAsProxyExceptionFilter
API _InternalCallFrameExceptionFilter@8
API _InternalCallerIsAppContainer@4
API _InternalReleaseMarshalObjRef@4 ; -> InternalCanMakeOutCall
API _InternalCanMakeOutCall2@4
API _InternalCoIsSurrogateProcess@0
API _InternalCoRegisterDisconnectCallback@20
API _InternalCoRegisterSurrogatedObject@4
API _InternalCoStdMarshalObject@28
API _InternalCoUnregisterDisconnectCallback@4
API _InternalCMLSendReceive@16 ; -> InternalCompleteObjRef
API _InternalCreateCAggId@8
API _InternalCreateIdentityHandler@12
API _InternalDoATClassCreate@16
API _InternalFillLocalOXIDInfo@8
API ?CleanupIdentity@@YGXPAUSHashChain@@@Z ; -> InternalFreeObjRef
API _InternalRegisterWindowPropInterface@20 ; -> InternalGetWindowPropInterface
API _InternalGetWindowPropInterface2@24
API _InternalIrotEnumRunning@4
API _InternalIrotEnumRunning2@8
API _InternalIrotGetObject@20
API ?CopyTo@?$GenericStreamBase@UIMarshalingStream@@VAllocationWrapper@@@@UAGJPAUIStream@@T_ULARGE_INTEGER@@PAT3@2@Z ; -> InternalIrotGetObject2
API _InternalIrotGetObject3@28
API ?ReleaseMarshalData@?$HandleWrapperImpl@URegistryKeyHandleWrapperTraits@@@@UAGJPAUIStream@@@Z ; -> InternalIrotGetTimeOfLastChange
API _InternalIrotGetTimeOfLastChange2@12
API _InternalIrotEnumRunning@4 ; -> InternalIrotIsRunning
API _InternalIrotIsRunning2@8
API _InternalIrotNoteChangeTime@8
API _InternalIrotRegister@28
API _InternalIrotRevoke@16
API _InternalIsApartmentInitialized@0
API _InternalIsProcessInitialized@0
API _InternalStubInvoke@24 ; -> InternalMarshalObjRef
API _InternalNotifyDDStartOrStop@4
API _InternalOle1ClassFromCLSID2@12
API _InternalOleModalLoopBlockFn@0
API _InternalRegOpenClassKey@12
API _InternalRegisterWindowPropInterface@20
API _InternalRegisterWindowPropInterface2@20
API _InternalReleaseMarshalObjRef@4
API _InternalRevokeWindowPropInterface@20
API _InternalSTAInvoke@28
API _InternalServerExceptionFilter@4
API _InternalSetAptCallCtrlOnTlsIfRequired@0
API _InternalSetOleThunkWowPtr@4
API _InternalStubInvoke@24
API _InternalTlsAllocData@4
API _InternalUnmarshalObjRef@12
API _IsErrorPropagationEnabled@0
API _NdrCStdStubBuffer2_Release@8
API _NdrCStdStubBuffer_Release@8
API _NdrExtStubInitialize@16
API _NdrOleDllGetClassObject@24
API ?NdrOleInitializeExtension@@YGJPAPBU_NDROLE_EXTENSION_ROUTINES_TABLE@@PAPBU_NDR_FWD_ROUTINES@@@Z
API _NdrProxyForwardingFunction10@0
API _NdrProxyForwardingFunction11@0
API _NdrProxyForwardingFunction12@0
API _NdrProxyForwardingFunction13@0
API _NdrProxyForwardingFunction14@0
API _NdrProxyForwardingFunction15@0
API _NdrProxyForwardingFunction16@0
API _NdrProxyForwardingFunction17@0
API _NdrProxyForwardingFunction18@0
API _NdrProxyForwardingFunction19@0
API _NdrProxyForwardingFunction20@0
API _NdrProxyForwardingFunction21@0
API _NdrProxyForwardingFunction22@0
API _NdrProxyForwardingFunction23@0
API _NdrProxyForwardingFunction24@0
API _NdrProxyForwardingFunction25@0
API _NdrProxyForwardingFunction26@0
API _NdrProxyForwardingFunction27@0
API _NdrProxyForwardingFunction28@0
API _NdrProxyForwardingFunction29@0
API _NdrProxyForwardingFunction3@0
API _NdrProxyForwardingFunction30@0
API _NdrProxyForwardingFunction31@0
API _NdrProxyForwardingFunction32@0
API _NdrProxyForwardingFunction4@0
API _NdrProxyForwardingFunction5@0
API _NdrProxyForwardingFunction6@0
API _NdrProxyForwardingFunction7@0
API _NdrProxyForwardingFunction8@0
API _NdrProxyForwardingFunction9@0
API _NdrpFindInterface@16
API _ObjectStublessClient10@0
API _ObjectStublessClient11@0
API _ObjectStublessClient12@0
API _ObjectStublessClient13@0
API _ObjectStublessClient14@0
API _ObjectStublessClient15@0
API _ObjectStublessClient16@0
API _ObjectStublessClient17@0
API _ObjectStublessClient18@0
API _ObjectStublessClient19@0
API _ObjectStublessClient20@0
API _ObjectStublessClient21@0
API _ObjectStublessClient22@0
API _ObjectStublessClient23@0
API _ObjectStublessClient24@0
API _ObjectStublessClient25@0
API _ObjectStublessClient26@0
API _ObjectStublessClient27@0
API _ObjectStublessClient28@0
API _ObjectStublessClient29@0
API _ObjectStublessClient3@0
API _ObjectStublessClient30@0
API _ObjectStublessClient31@0
API _ObjectStublessClient32@0
API _ObjectStublessClient4@0
API _ObjectStublessClient5@0
API _ObjectStublessClient6@0
API _ObjectStublessClient7@0
API _ObjectStublessClient8@0
API _ObjectStublessClient9@0
API _ProgIDFromCLSID@8
API _PropVariantClear@4
API _PropVariantCopy@8
API _ReleaseFuncDescs@8
API _RoActivateInstance@8
API _RoCaptureErrorContext@4
API _RoClearError@0
API _RoFailFastWithErrorContext@4
API ?RoFailFastWithErrorContextInternal@@YGXJKQAPAU_STOWED_EXCEPTION_INFORMATION_V1@@@Z
API ?RoFailFastWithErrorContextInternal2@@YGXJKQAPAU_STOWED_EXCEPTION_INFORMATION_V2@@@Z
API _RoFreeParameterizedTypeExtra@4
API _RoGetActivatableClassRegistration@8
API _RoGetActivationFactory@12
API _RoGetAgileReference@16
API _RoGetApartmentIdentifier@4
API _RoGetErrorReportingFlags@4
API _RoGetMatchingRestrictedErrorInfo@8
API _RoGetParameterizedTypeInstanceIID@20
API _RoGetServerActivatableClasses@12
API _RoInitialize@4
API _RoInspectCapturedStackBackTrace@24
API _RoInspectThreadErrorInfo@20
API _RoOriginateError@8
API _RoOriginateErrorW@12
API _RoOriginateLanguageException@12
API _RoParameterizedTypeExtraGetTypeSignature@4
API _RoRegisterActivationFactories@16
API _RoRegisterForApartmentShutdown@12
API _RoReportCapabilityCheckFailure@16
API _RoReportFailedDelegate@8
API _RoReportUnhandledError@4
API _RoResolveRestrictedErrorInfoReference@8
API _RoRevokeActivationFactories@4
API _RoSetErrorReportingFlags@4
API _RoTransformError@12
API _RoTransformErrorW@16
API _RoUninitialize@0
API _RoUnregisterForApartmentShutdown@4
API _SetCleanupFlag@4
API _CoSetErrorInfo@8 ; -> SetErrorInfo
API _SetRestrictedErrorInfo@4
API _StringFromCLSID@8
API _StringFromGUID2@12
API _StringFromIID@8
API _UpdateDCOMSettings@0
API ?UpdateProcessTracing@@YGJKH@Z
API _WdtpInterfacePointer_UserFree@4
API _WdtpInterfacePointer_UserMarshal@20
API _WdtpInterfacePointer_UserSize@20
API _WdtpInterfacePointer_UserUnmarshal@16
API _WindowsCompareStringOrdinal@12
API _WindowsConcatString@12
API _WindowsCreateString@12
API _WindowsCreateStringReference@16
API _WindowsDeleteString@4
API _WindowsDeleteStringBuffer@4
API _WindowsDuplicateString@8
API _WindowsGetStringLen@4
API _WindowsGetStringRawBuffer@8
API _WindowsInspectString@24
API _WindowsInspectString2@28
API _WindowsIsStringEmpty@4
API _WindowsPreallocateStringBuffer@12
API _WindowsPromoteStringBuffer@8
API _WindowsReplaceString@16
API _WindowsStringHasEmbeddedNull@8
API _WindowsSubstring@12
API _WindowsSubstringWithSpecifiedLength@16
API _WindowsTrimStringEnd@12
API _WindowsTrimStringStart@12
API _CoTestDisableCatalogPackageRegistrationChecks@0
API _CoTestSetExtensionsDestCtxOverrideForActivation@4
API _CoGetClassObjectOfPackagedImplementationClass@24
API _CoGetTreatAsClassInternal@12
API _SetMockRunningIn16Bit@4
API _STGMEDIUM_UserFree@8
API _STGMEDIUM_UserUnmarshal@12
API _STGMEDIUM_UserMarshal@12
API _STGMEDIUM_UserSize@12
API _SNB_UserFree@8
API _SNB_UserUnmarshal@12
API _SNB_UserMarshal@12
API _SNB_UserSize@12
API _HMETAFILE_UserFree@8
API _HMETAFILE_UserUnmarshal@12
API _HMETAFILE_UserMarshal@12
API _HMETAFILE_UserSize@12
API _HMETAFILEPICT_UserFree@8
API _HMETAFILEPICT_UserUnmarshal@12
API _HMETAFILEPICT_UserMarshal@12
API _HMETAFILEPICT_UserSize@12
API _HENHMETAFILE_UserFree@8
API _HENHMETAFILE_UserUnmarshal@12
API _HENHMETAFILE_UserMarshal@12
API _HENHMETAFILE_UserSize@12
API _CoGetCallLocality@8
API ?CoTestDcomContainerProtocolVersionNumber@@3IB
API _CoTestSetUseContainerErrorInformationLocalPropagation@0
API _CoDoesOtherSideSupportUDTMarshaling@4
API _CoDoesOtherSideVariantMarshalingNeedTrailingPadding@4
API _RoInitializeStrict@4
API _ClearChainRestrictedErrors@0
API _SetChainRestrictedErrors@0
API _OriginateOrTransformError@4
API _CoTestGetResponseContainerPassthroughData@8
API _CoTestSetResponseContainerPassthroughData@8
API _CoTestGetRequestContainerPassthroughData@8
API _CoTestSetRequestContainerPassthroughData@8
API _SetRuntimeBrokerActivationTestHook@4
API _RoDisableDebuggingForPackageEx@12
API _RoEnableDebuggingForPackageEx@20
API _CoImpersonateClientOfObject@8
API _CoGetCallContextOfObject@12
API _RpcUnmarshalRestrictedErrorToTls@8
API _RpcMarshalRestrictedErrorFromTls@8
API _RpcMarshalRestrictedErrorFromTlsToExtent@8
API _CoEnableAutomaticClientDependencyCreation@0
API _RoInitializeBridgeSTA@0
API _CoTestWaitForCallTracingEnabled@0
API _RoGetExtensionRegistrationForCurrentApplicationLaunchContract@4
API _RoGetExtensionRegistrationForLaunchContracts@20
API _CoTestIssueRundown@4
API _RoGetDesignModeV2@4
API _CoTestSetPointOfRandomDelay@8
API _CoIsExceptionReportingSuppressed@0
API _CoCreateInstanceAsUser@28
API _RoGetRegistrationStoreContext@20
API _CoTestSimulatedRpcSendFailure@12
API _CoReleaseCachedRuntimeBrokerReferences@0
API _CoSuppressExceptionReporting@0
API _CoTestInjectedDelayForIncomingOutofprocCall@12
API _RoGetActivationFactoryAsUser@20
API _RoActivateInstanceAsUser@16
API _CoVrfSetMockApplicationVerifierStop@4
API _CoVrfComVerifierIsEnabled@0
API ?CoGetSystemSecurityPermissionsTestHook@@YGJQAKPAKPAPAE@Z
API ?CleanupIdentity@@YGXPAUSHashChain@@@Z
API _CoSetAsyncCallCancelListenerTestHook@4
API _CoAllowSetForegroundWindow@8
API _RoGetMachineGlobalObjectTable@4
API _CoGetRundownInstrumentationData@4
API _CoDisableASTACallReentrancyGuardForSTAByDefault@0
API _RoGetAgileMarshaler@4
API _RoActivateInstanceInPackage@12
API _RoInitializeASTA@0
API _RoIsASTAWorkScheduledAtPriorityOrHigher@4
API _CoSetBulkUpdateRate@4
API _CoSetFastRundownTimeout@4
API _CoSetNonFastRundownTimeout@4
API _CoSetForcedBulkUpdateForAllOutofprocProxiesTestMode@4
API _CoSetInprocDirectMarshalingMitigationTestMode@4
API _CoSetOutofprocOutParameterMitigationTestMode@4
API _CoSetInprocOutParameterMitigationTestMode@4
API _CoSetInParameterMitigationTestMode@4
API _CoGetApartmentIdentifier@4
API _CoUnregisterForApartmentShutdown@4
API _CoRegisterForApartmentShutdown@12
API _CoRegisterChannelHook@8
API _CoHandlePriorityEventsFromMessagePump@0
API _CoSetMessageDispatcher@4
API ?CoVrfNotifyExtraOleUninit@@YGXXZ
API ?CoVrfShouldCallOleInit@@YGXPBD@Z
API ?CoVrfNotifyOleUninit@@YGXXZ
API ?CoVrfNotifyOleInit@@YGXXZ
API _CoSetASTATestMode@4
API _CoEnableASTACallReentrancyGuardForSTAByDefault@0
API _CoSetRetryForReentrancyGuardTimeout@4
API _CoIsHandlingIncomingTouchedASTACall@0
API _CoEnableASTACallReentrancyGuardForSTA@0
API _CoSignalPendingGitRegistrationWaits@0
API _NdrOleGetComMarshalingContextAttribute@12
API _CoSetASTAQueuedCallTimeout@4
API _RoGetDesignMode@4
API _CoEndProcessEvents@4
API _CoMsgWaitInProcessEvents@24
API _CoBeginProcessEvents@4
API _RoDisableDebuggingForPackage@4
API _RoEnableDebuggingForPackage@12
API _RoGetExtensionRegistrationByExtensionId@12
API _CoWaitMTACompletion@0
API _CoGetMTAUsageInfo@0
API _CoRegisterServerShutdownDelay@8
API _CoReleaseSharedService@4
API _CoAddRefSharedService@4
API _CoGetSharedServiceId@4
API _RoGetExtensionRegistration@16
API _GetStringCount@4
API _GetStringRefCount@8
API _WinRTNotifyChangedStore@0

end
