.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _AccessCheck@32
API _AccessCheckAndAuditAlarmW@44
API _AccessCheckByType@44
API _AccessCheckByTypeAndAuditAlarmW@64
API _AccessCheckByTypeResultList@44
API _AccessCheckByTypeResultListAndAuditAlarmByHandleW@68
API _AccessCheckByTypeResultListAndAuditAlarmW@64
API _RtlAcquireSRWLockExclusive@4
API _RtlAcquireSRWLockShared@4
API _AcquireStateLock@12
API _ActivateActCtx@8
API _AddAccessAllowedAce@16
API _AddAccessAllowedAceEx@20
API _AddAccessAllowedObjectAce@28
API _AddAccessDeniedAce@16
API _AddAccessDeniedAceEx@20
API _AddAccessDeniedObjectAce@28
API _AddAce@20
API _AddAuditAccessAce@24
API _AddAuditAccessAceEx@28
API _AddAuditAccessObjectAce@36
API _AddConsoleAliasA@12
API _AddConsoleAliasW@12
API _AddDependencyToProcessPackageGraph@16
API _AddDllDirectory@4
API _AddExtensionProgId@16
API _AddMandatoryAce@20
API _AddPackageDependency@20
API _AddPackageDependency2@20
API _AddPackageNameAliasesByPackageDependency@12
API _AddPackageNameAliasesByPackageFullName@12
API _AddRefActCtx@4
API _AddResourceAttributeAce@28
API _AddSIDToBoundaryDescriptor@8
API _AddScopedPolicyIDAce@20
API _RtlAddVectoredContinueHandler@8
API _RtlAddVectoredExceptionHandler@8
API _AdjustTokenGroups@24
API _AdjustTokenPrivileges@24
API _AllocConsole@0
API _AllocConsoleWithOptions@8
API _AllocateAndInitializeSid@44
API _AllocateLocallyUniqueId@4
API _AllocateUserPhysicalPages@12
API _AllocateUserPhysicalPages2@20
API _AllocateUserPhysicalPagesNuma@16
API _AppContainerDeriveSidFromMoniker@8
API _AppContainerFreeMemory@4
API _AppContainerLookupDisplayNameMrtReference@8
API _AppContainerLookupMoniker@8
API _AppContainerRegisterSid@12
API _AppContainerUnregisterSid@4
API _AppPolicyGetClrCompat@8
API _AppPolicyGetCreateFileAccess@8
API _AppPolicyGetLifecycleManagement@8
API _AppPolicyGetMediaFoundationCodecLoading@8
API _AppPolicyGetProcessTerminationMethod@8
API _AppPolicyGetShowDeveloperDiagnostic@8
API _AppPolicyGetThreadInitializationType@8
API _AppPolicyGetWindowingModel@8
API _AppXCheckPplSupport@8
API _AppContainerFreeMemory@4
API _AppXGetApplicationData@32
API _AppXGetDevelopmentMode@8
API _AppXGetOSMaxVersionTested@8
API _MFCreatePathFromURL@8
API _AppXGetPackageCapabilities@16
API _AppXGetPackageSid@8
API _AppXLookupDisplayName@8
API _AppXLookupMoniker@8
API _AppXPostSuccessExtension@8
API _AppXPreCreationExtension@28
API _AppXReleaseAppXContext@4
API _RtwqScheduleWorkItem@16
API _PackageRelativeApplicationIdFromProductId@12
API _AreAllAccessesGranted@8
API _AreAnyAccessesGranted@8
API _AreFileApisANSI@0
API _AreShortNamesEnabled@8
API _AreThereVisibleLogoffScriptsInternal@4
API _AreThereVisibleShutdownScriptsInternal@4
API _ArmFeatureUsageSubscriberFlushNotification@0
API _AttachConsole@4
API _BaseCheckAppcompatCache@16
API _BaseCheckAppcompatCacheEx@36
API _BaseCleanupAppcompatCacheSupport@4
API _BaseDllFreeResourceId@4
API _BaseDllMapResourceIdW@4
API _BaseDumpAppcompatCache@0
API _BaseFlushAppcompatCache@0
API _BaseFormatObjectAttributes@16
API _BaseFreeAppCompatDataForProcess@4
API _BaseGetConsoleReference@0
API _BaseGetNamedObjectDirectory@4
API _BaseInitAppcompatCacheSupport@0
API _BaseIsAppcompatInfrastructureDisabled@0
API _BaseMarkFileForDelete@8
API _BaseReadAppCompatDataForProcess@12
API _BaseUpdateAppcompatCache@12
API _BasepAdjustObjectAttributesForPrivateNamespace@4
API _BasepCopyFileCallback@8
API _BasepCopyFileExW@64
API _BasepNotifyTrackingService@16
API _Beep@8
API _BuildIoRingCancelRequest@20
API _BuildIoRingFlushFile@24
API _BuildIoRingReadFile@44
API _BuildIoRingReadFileScatter@40
API _BuildIoRingRegisterBuffers@16
API _BuildIoRingRegisterFileHandles@16
API _BuildIoRingWriteFile@48
API _BuildIoRingWriteFileGather@44
API _CLOSE_LOCAL_HANDLE_INTERNAL@8
API _CallEnclave@16
API _CallNamedPipeW@28
API _CallbackMayRunLong@4
API _CancelIo@4
API _CancelIoEx@8
API _CancelSynchronousIo@4
API _TpCancelAsyncIoOperation@4
API _CancelWaitableTimer@4
API _CeipIsOptedIn@0
API _ChangeTimerQueueTimer@16
API _CharLowerA@4
API _CharLowerBuffA@8
API _CharLowerBuffW@8
API _CharLowerW@4
API _CharNextA@4
API _CharNextExA@12
API _CharNextW@4
API _CharPrevA@8
API _CharPrevExA@16
API _CharPrevW@8
API _CharUpperA@4
API _CharUpperBuffA@8
API _CharUpperBuffW@8
API _CharUpperW@4
API _CheckAllowDecryptedRemoteDestinationPolicy@0
API _CheckGroupPolicyEnabled@8
API _CheckIfStateChangeNotificationExists@8
API _CheckIsMSIXPackage@8
API _CheckRemoteDebuggerPresent@8
API _CheckTokenCapability@12
API _CheckTokenMembership@12
API _CheckTokenMembershipEx@16
API _ChrCmpIA@8
API _ChrCmpIW@8
API _ClearCommBreak@4
API _ClearCommError@12
API _CloseHandle@4
API _CloseIoRing@4
API _ClosePackageInfo@4
API _ClosePrivateNamespace@8
API _ClosePseudoConsole@4
API _CloseState@4
API _CloseStateAtom@4
API _CloseStateChangeNotification@4
API _CloseStateContainer@4
API _CloseStateLock@4
API _TpReleasePool@4
API _TpReleaseCleanupGroup@4
API _TpReleaseCleanupGroupMembers@12
API _TpReleaseIoCompletion@4
API _TpReleaseTimer@4
API _TpReleaseWait@4
API _TpReleaseWork@4
API _CommandLineToArgvW@8
API _CommitStateAtom@12
API _CompareFileTime@8
API _CompareObjectHandles@8
API _CompareStringA@24
API _SortCompareString@36
API _CompareStringOrdinal@20
API _CompareStringW@24
API _ConnectNamedPipe@8
API _ContinueDebugEvent@12
API _ConvertAuxiliaryCounterToPerformanceCounter@16
API _ConvertDefaultLocale@4
API _ConvertFiberToThread@0
API _ConvertPerformanceCounterToAuxiliaryCounter@16
API _ConvertThreadToFiber@4
API _ConvertThreadToFiberEx@8
API _ConvertToAutoInheritPrivateObjectSecurity@24
API _CopyContext@12
API _CopyFile2@12
API _CopyFileExW@24
API _CopyFileFromAppW@12
API _CopyFileW@12
API _CopySid@12
API _CouldMultiUserAppsBehaviorBePossibleForPackage@8
API _CreateActCtxW@4
API _CreateAppContainerToken@12
API _CreateAppSiloToken@12
API _CreateBoundaryDescriptorW@8
API _CreateConsoleScreenBuffer@20
API _CreateDirectoryA@8
API _CreateDirectoryExW@12
API _CreateDirectoryFromAppW@8
API _CreateDirectoryW@8
API _CreateEnclave@32
API _CreateEventA@16
API _CreateEventExA@16
API _CreateEventExW@16
API _CreateEventW@16
API _CreateFiber@12
API _CreateFiberEx@20
API _CreateFile2@20
API _CreateFile2FromAppW@20
API _CreateFileA@28
API _CreateFileFromAppW@28
API _CreateFileMapping2@40
API _CreateFileMappingFromApp@24
API _CreateFileMappingNumaW@28
API _CreateFileMappingW@24
API _CreateFileW@28
API _CreateHardLinkA@12
API _CreateHardLinkW@12
API _CreateIoCompletionPort@16
API _CreateIoRing@24
API _CreateMemoryResourceNotification@4
API _CreateMutexA@12
API _CreateMutexExA@16
API _CreateMutexExW@16
API _CreateMutexW@12
API _CreateNamedPipeW@32
API _CreatePipe@16
API _CreatePrivateNamespaceW@12
API _CreatePrivateObjectSecurity@24
API _CreatePrivateObjectSecurityEx@32
API _CreatePrivateObjectSecurityWithMultipleInheritance@36
API _CreateProcessA@40
API _CreateProcessAsUserA@44
API _CreateProcessAsUserW@44
API _CreateProcessInternalA@48
API _CreateProcessInternalW@48
API _CreateProcessW@40
API _CreatePseudoConsole@20
API _CreatePseudoConsoleAsUser@24
API _CreateRemoteThread@28
API _CreateRemoteThreadEx@32
API _CreateRestrictedToken@36
API _CreateSemaphoreExW@24
API _CreateSemaphoreW@16
API _CreateStateAtom@0
API _CreateStateChangeNotification@4
API _CreateStateContainer@16
API _CreateStateLock@4
API _CreateStateSubcontainer@12
API _CreateSymbolicLinkW@12
API _CreateThread@24
API _CreateThreadpool@4
API _CreateThreadpoolCleanupGroup@0
API _CreateThreadpoolIo@16
API _CreateThreadpoolTimer@12
API _CreateThreadpoolWait@12
API _CreateThreadpoolWork@12
API _CreateTimerQueue@0
API _CreateTimerQueueTimer@28
API _CreateWaitableTimerExW@16
API _CreateWaitableTimerW@12
API _CreateWellKnownSid@16
API _CtrlRoutine@4
API _CveEventWrite@8
API _DeactivateActCtx@8
API _DebugActiveProcess@4
API _DebugActiveProcessStop@4
API ?DebugBreak@details@wil@@YGXXZ
API _RtlDecodePointer@4
API _RtlDecodeRemotePointer@12
API _RtlDecodeSystemPointer@4
API _DefineDosDeviceW@12
API _DelayLoadFailureHook@8
API _DelayLoadFailureHookLookup@12
API _DeleteAce@8
API _DeleteBoundaryDescriptor@4
API _RtlDeleteCriticalSection@4
API _DeleteEnclave@4
API _DeleteFiber@4
API _DeleteFileA@4
API _DeleteFileFromAppW@4
API _DeleteFileW@4
API _DeletePackageDependency@4
API _DeletePersistedRegistryValue@12
API _sqlite3_mutex_enter@4
API _DeleteStateAtomValue@8
API _DeleteStateContainer@8
API _DeleteStateContainerValue@8
API _DeleteSynchronizationBarrier@4
API _DeleteTimerQueue@4
API _DeleteTimerQueueEx@8
API _DeleteTimerQueueTimer@12
API _DeleteVolumeMountPointW@4
API _DeriveCapabilitySidsFromName@20
API _DestroyPrivateObjectSecurity@4
API _DeviceIoControl@32
API _DisablePredefinedHandleTableInternal@4
API _DisableThreadLibraryCalls@4
API _TpDisassociateCallback@4
API _DiscardVirtualMemory@8
API _DisconnectNamedPipe@4
API _DnsHostnameToComputerNameExW@12
API _DsBindWithSpnExW@24
API _DsCrackNamesW@28
API _DsFreeDomainControllerInfoW@12
API _DsFreeNameResultW@4
API _DsFreeNgcKey@4
API _DsFreePasswordCredentials@4
API _DsGetDomainControllerInfoW@20
API _DsMakePasswordCredentialsW@16
API _DsReadNgcKeyW@16
API _DsUnBindW@4
API _DsWriteNgcKeyW@16
API _DuplicateHandle@28
API _DuplicateStateContainerHandle@4
API _DuplicateToken@12
API _DuplicateTokenEx@24
API _K32EmptyWorkingSet@4
API _EnableProcessOptionalXStateFeatures@8
API _RtlEncodePointer@4
API _RtlEncodeRemotePointer@12
API _RtlEncodeSystemPointer@4
API _EnterCriticalPolicySectionInternal@4
API _RtlEnterCriticalSection@4
API _EnterSynchronizationBarrier@8
API _EnumCalendarInfoExEx@24
API _EnumCalendarInfoExW@16
API _EnumCalendarInfoW@16
API _EnumDateFormatsExEx@16
API _EnumDateFormatsExW@12
API _EnumDateFormatsW@12
API _K32EnumDeviceDrivers@12
API _EnumDynamicTimeZoneInformation@8
API _EnumLanguageGroupLocalesW@16
API _K32EnumPageFilesA@8
API _K32EnumPageFilesW@8
API _K32EnumProcessModules@16
API _K32EnumProcessModulesEx@20
API _K32EnumProcesses@12
API _EnumResourceLanguagesExA@28
API _EnumResourceLanguagesExW@28
API _EnumResourceNamesA@16
API _EnumResourceNamesExA@24
API _EnumResourceNamesExW@24
API _EnumResourceNamesW@16
API _EnumResourceTypesExA@20
API _EnumResourceTypesExW@20
API _EnumSystemCodePagesW@8
API _EnumSystemFirmwareTables@12
API _EnumSystemGeoID@12
API _EnumSystemGeoNames@12
API _EnumSystemLanguageGroupsW@12
API _EnumSystemLocalesA@8
API _EnumSystemLocalesEx@16
API _EnumSystemLocalesW@8
API _EnumTimeFormatsEx@16
API _EnumTimeFormatsW@12
API _EnumUILanguagesW@12
API _EnumerateExtensionNames@24
API _EnumerateStateAtomValues@12
API _EnumerateStateContainerItems@16
API _EqualDomainSid@12
API _EqualPrefixSid@8
API _EqualSid@8
API _EscapeCommFunction@8
API _EtwEventActivityIdControl@8
API _EtwEventEnabled@12
API _EtwEventProviderEnabled@20
API _EtwEventRegister@16
API _EtwEventSetInformation@20
API _EtwEventUnregister@8
API _EtwEventWrite@20
API _EtwEventWriteEx@40
API _EtwEventWriteString@24
API _EtwEventWriteTransfer@28
API _RtlExitUserProcess@4
API _RtlExitUserThread@4
API _ExpandEnvironmentStringsA@12
API _ExpandEnvironmentStringsW@12
API _ExpungeConsoleCommandHistoryA@4
API _ExpungeConsoleCommandHistoryW@4
API ___FC_Query_Config@12
API _FatalAppExitA@8
API _FatalAppExitW@8
API _FileTimeToLocalFileTime@8
API _FileTimeToSystemTime@8
API _FillConsoleOutputAttribute@20
API _FillConsoleOutputCharacterA@20
API _FillConsoleOutputCharacterW@20
API _FindActCtxSectionGuid@20
API _FindActCtxSectionStringW@20
API _FindClose@4
API _FindCloseChangeNotification@4
API _FindFirstChangeNotificationA@12
API _FindFirstChangeNotificationW@12
API _FindFirstFileA@8
API _FindFirstFileExA@24
API _FindFirstFileExFromAppW@24
API _FindFirstFileExW@24
API _FindFirstFileNameW@16
API _FindFirstFileW@8
API _FindFirstFreeAce@8
API _FindFirstStreamW@16
API _FindFirstVolumeW@8
API _FindNLSString@28
API _SortFindString@40
API _FindNextChangeNotification@4
API _FindNextFileA@8
API _FindNextFileNameW@12
API _FindNextFileW@8
API _FindNextStreamW@8
API _FindNextVolumeW@12
API _FindPackageDependency@12
API _FindPackagesByPackageFamily@28
API _FindResourceExW@16
API _FindResourceW@12
API _FindStringOrdinal@24
API _FindVolumeClose@4
API _FlsAlloc@4
API _FlsFree@4
API _FlsGetValue@4
API _RtlFlsGetValue2@4
API _FlsSetValue@8
API _FlushConsoleInputBuffer@4
API _FlushFileBuffers@4
API _FlushInstructionCache@12
API _ZwFlushProcessWriteBuffers@0
API _FlushViewOfFile@8
API _FoldStringW@20
API _ForceSyncFgPolicyInternal@4
API _FormatApplicationUserModelId@16
API _FormatApplicationUserModelIdA@16
API _FormatMessageA@28
API _FormatMessageW@28
API _FreeConsole@0
API _FreeEnvironmentStringsA@4
API _FreeEnvironmentStringsA@4
API _FreeGPOListInternalA@4
API _FreeGPOListInternalW@4
API _FreeLibrary@4
API _FreeLibraryAndExitThread@8
API _TpCallbackUnloadDllOnCompletion@8
API _sqlite3_value_bytes@4
API _FreeSid@4
API _FreeUserPhysicalPages@12
API _GenerateConsoleCtrlEvent@8
API _GenerateGPNotificationInternal@12
API _GetACP@0
API _GetAcceptLanguagesA@8
API _GetAcceptLanguagesW@8
API _GetAce@12
API _GetAclInformation@16
API _GetAdjustObjectAttributesForPrivateNamespaceRoutine@0
API _GetAlternatePackageRoots@8
API _GetAppContainerAce@16
API _GetAppContainerNamedObjectPath@20
API _GetAppDataFolder@12
API _GetAppModelVersion@4
API _GetApplicationRecoveryCallback@20
API _GetApplicationRestartSettings@16
API _GetApplicationUserModelId@12
API _GetApplicationUserModelIdFromToken@12
API _GetAppliedGPOListInternalA@20
API _GetAppliedGPOListInternalW@20
API _GetCPFileNameFromRegistry@12
API @GetCPHashNode@8
API _GetCPInfo@8
API _GetCPInfoExW@12
API _GetCachedSigningLevel@24
API _GetCalendar@8
API _GetCalendarInfoEx@28
API _GetCalendarInfoW@24
API _GetCommConfig@12
API _GetCommMask@8
API _GetCommModemStatus@8
API _GetCommPorts@12
API _GetCommProperties@8
API _GetCommState@8
API _GetCommTimeouts@8
API _GetCommandLineA@0
API _GetCommandLineW@0
API _GetCompressedFileSizeA@8
API _GetCompressedFileSizeW@8
API _GetComputerNameExA@12
API _GetComputerNameExW@12
API _GetConsoleAliasA@16
API _GetConsoleAliasExesA@8
API _GetConsoleAliasExesLengthA@0
API _GetConsoleAliasExesLengthW@0
API _GetConsoleAliasExesW@8
API _GetConsoleAliasW@16
API _GetConsoleAliasesA@12
API _GetConsoleAliasesLengthA@4
API _GetConsoleAliasesLengthW@4
API _GetConsoleAliasesW@12
API _GetConsoleCP@0
API _GetConsoleCommandHistoryA@12
API _GetConsoleCommandHistoryLengthA@4
API _GetConsoleCommandHistoryLengthW@4
API _GetConsoleCommandHistoryW@12
API _GetConsoleCursorInfo@8
API _GetConsoleDisplayMode@4
API _GetConsoleFontSize@8
API _GetConsoleHistoryInfo@4
API _GetConsoleInputExeNameA@8
API _GetConsoleInputExeNameW@8
API _GetConsoleMode@8
API _GetConsoleOriginalTitleA@8
API _GetConsoleOriginalTitleW@8
API _GetConsoleOutputCP@0
API _GetConsoleProcessList@8
API _GetConsoleScreenBufferInfo@8
API _GetConsoleScreenBufferInfoEx@8
API _GetConsoleSelectionInfo@4
API _GetConsoleTitleA@8
API _GetConsoleTitleW@8
API _GetConsoleWindow@0
API _GetCurrencyFormatEx@24
API _GetCurrencyFormatW@24
API _GetCurrentActCtx@4
API _GetCurrentApplicationUserModelId@8
API _GetCurrentConsoleFont@12
API _GetCurrentConsoleFontEx@12
API _GetCurrentDirectoryA@8
API _GetCurrentDirectoryW@8
API _GetCurrentPackageApplicationContext@12
API _GetCurrentPackageApplicationResourcesContext@12
API _GetCurrentPackageContext@12
API _GetCurrentPackageFamilyName@8
API _GetCurrentPackageFullName@8
API _GetCurrentPackageGlobalizationContext@12
API _GetCurrentPackageId@8
API _GetCurrentPackageInfo@16
API _GetCurrentPackageInfo2@20
API _GetCurrentPackageInfo3@20
API _GetCurrentPackageInfo_PackageNameAliases@16
API _GetCurrentPackagePath@8
API _GetCurrentPackagePath2@12
API _GetCurrentPackageResourcesContext@12
API _GetCurrentPackageSecurityContext@8
API _ubrk_current
API _GetCurrentProcessId@0
API _RtlGetCurrentProcessorNumber@0
API _RtlGetCurrentProcessorNumberEx@4
API _GetCurrentTargetPlatformContext@8
API _GetCurrentThread@0
API _GetCurrentThreadId@0
API _GetCurrentThreadStackLimits@8
API _GetDateFormatA@24
API _GetDateFormatEx@28
API _GetDateFormatW@24
API _GetDeveloperDriveEnablementState@0
API _K32GetDeviceDriverBaseNameA@12
API _K32GetDeviceDriverBaseNameW@12
API _K32GetDeviceDriverFileNameA@12
API _K32GetDeviceDriverFileNameW@12
API _GetDiskFreeSpaceA@20
API _GetDiskFreeSpaceExA@16
API _GetDiskFreeSpaceExW@16
API _GetDiskFreeSpaceW@20
API _GetDiskSpaceInformationA@8
API _GetDiskSpaceInformationW@8
API _GetDiskSpaceInformationWCOS@16
API _GetDriveTypeA@4
API _GetDriveTypeW@4
API _GetDurationFormatEx@32
API _GetDynamicTimeZoneInformation@4
API _GetDynamicTimeZoneInformationEffectiveYears@12
API _GetEffectivePackageStatusForUser@12
API _GetEffectivePackageStatusForUserSid@12
API _GetEightBitStringToUnicodeSizeRoutine@0
API _GetEightBitStringToUnicodeStringRoutine@0
API _GetEnabledXStateFeatures@0
API _GetEnvironmentStrings@0
API _GetEnvironmentStrings@0
API _GetEnvironmentStringsW@0
API _GetEnvironmentVariableA@12
API _GetEnvironmentVariableW@12
API _GetEraNameCountedString@16
API _GetErrorMode@0
API _GetExitCodeProcess@8
API _GetExitCodeThread@8
API _GetExtensionApplicationUserModelId@20
API _SetEnrollState@20
API _GetExtensionProperty@28
API _GetExtensionProperty2@32
API _GetFallbackDisplayName@4
API _RtlGetFeatureToggleConfiguration@12
API _RtlGetFeatureTogglesChangeToken@0
API _GetFileAttributesA@4
API _GetFileAttributesExA@12
API _GetFileAttributesExFromAppW@12
API _GetFileAttributesExW@12
API _GetFileAttributesW@4
API _GetFileInformationByHandle@8
API _GetFileInformationByHandleEx@16
API _GetFileInformationByName@16
API _GetFileMUIInfo@16
API _GetFileMUIPath@28
API _GetFileSecurityW@20
API _GetFileSize@8
API _GetFileSizeEx@8
API _GetFileTime@16
API _GetFileType@4
API _GetFileVersionInfoA@16
API _GetFileVersionInfoByHandle@16
API _GetFileVersionInfoExA@20
API _GetFileVersionInfoExW@20
API _GetFileVersionInfoSizeA@8
API _GetFileVersionInfoSizeExA@12
API _GetFileVersionInfoSizeExW@12
API _GetFileVersionInfoSizeW@8
API _GetFileVersionInfoW@16
API _GetFinalPathNameByHandleA@16
API _GetFinalPathNameByHandleW@16
API _GetFullPathNameA@16
API _GetFullPathNameW@16
API _GetGPOListInternalA@24
API _GetGPOListInternalW@24
API _GetGamingDeviceModelInformation@4
API _GetGeoInfoEx@16
API _GetGeoInfoW@20
API _GetHandleInformation@8
API _GetHivePath@16
API _GetIdForPackageDependencyContext@8
API _GetIntegratedDisplaySize@4
API _GetIoRingInfo@8
API _GetIsEdpEnabled@0
API _GetIsWdagEnabled@0
API _GetKernelObjectSecurity@20
API _GetLargePageMinimum@0
API _GetLargestConsoleWindowSize@4
API _GetLastError@0
API _GetLengthSid@4
API _GetLocalTime@4
API _GetLocaleInfoA@16
API _GetLocaleInfoEx@16
API _GetLocaleInfoHelper@16
API _GetLocaleInfoW@16
API _GetLogicalDriveStringsW@8
API _GetLogicalDrives@0
API _GetLogicalProcessorInformation@8
API _GetLogicalProcessorInformationEx@12
API _GetLongPathNameA@12
API _GetLongPathNameW@12
API _GetMachineTypeAttributes@8
API _K32GetMappedFileNameA@16
API _K32GetMappedFileNameW@16
API _GetMemoryErrorHandlingCapabilities@4
API _GetMemoryNumaClosestInitiatorNode@8
API _GetMemoryNumaPerformanceInformation@12
API _K32GetModuleBaseNameA@16
API _K32GetModuleBaseNameW@16
API _GetModuleFileNameA@12
API _K32GetModuleFileNameExA@16
API _K32GetModuleFileNameExW@16
API _GetModuleFileNameW@12
API _GetModuleHandleA@4
API _GetModuleHandleExA@12
API _GetModuleHandleExW@12
API _GetModuleHandleW@4
API _K32GetModuleInformation@16
API _GetNLSVersion@12
API _GetNLSVersionEx@12
API @GetNamedLocaleHashNode@8
API _GetNamedPipeAttribute@20
API _GetNamedPipeClientComputerNameW@12
API _GetNamedPipeHandleStateW@28
API _GetNamedPipeInfo@20
API _GetNativeSystemInfo@4
API _GetNextFgPolicyRefreshInfoInternal@8
API _GetNumaHighestNodeNumber@4
API _GetNumaNodeProcessorMask2@16
API _GetNumaNodeProcessorMaskEx@8
API _GetNumaProximityNodeEx@8
API _GetNumberFormatEx@24
API _GetNumberFormatW@24
API _GetNumberOfConsoleInputEvents@8
API _GetNumberOfConsoleMouseButtons@4
API _GetOEMCP@0
API _GetOsManufacturingMode@4
API _GetOsSafeBootMode@4
API _GetOverlappedResult@16
API _GetOverlappedResultEx@20
API _GetPackageApplicationContext@16
API _GetPackageApplicationIds@16
API _GetPackageApplicationProperty@16
API _GetPackageApplicationPropertyString@16
API _GetPackageApplicationResourcesContext@16
API _GetPackageContext@16
API _GetPackageDependencyInformation@36
API _GetPackageFamilyName@12
API _GetPackageFamilyNameFromFilePath@12
API ___FC_Query_Config@12
API _GetPackageFamilyNameFromToken@12
API _GetPackageFullName@12
API _GetPackageFullNameFromToken@12
API _GetPackageGlobalizationContext@16
API _GetPackageGlobalizationProperty@16
API _GetPackageGraphRevisionId@0
API _GetPackageId@12
API _GetPackageInfo@20
API _GetPackageInfo2@24
API _GetPackageInfo3@24
API _GetPackageNameAliasesByPackageFullName@12
API _GetPackageOSMaxVersionTested@8
API _GetPackagePath@16
API _GetPackagePathByFullName@12
API _GetPackagePathByFullName2@16
API _GetPackagePathOnVolume@16
API _GetPackageProperty@16
API _GetPackagePropertyString@16
API _GetPackageResourcesContext@16
API _GetPackageResourcesProperty@20
API _GetPackageSecurityContext@12
API _GetPackageSecurityProperty@16
API _GetPackageStatus@8
API _GetPackageStatusForUser@12
API _GetPackageStatusForUserSid@12
API _GetPackageTargetPlatformProperty@16
API _GetPackageVolumeSisPath@12
API _GetPackagedDataForFile@16
API _GetPackagesByPackageFamily@20
API _K32GetPerformanceInfo@8
API _GetPersistedFileLocationW@20
API _GetPersistedRegistryLocationW@20
API _GetPersistedRegistryValueW@32
API _GetPhysicallyInstalledSystemMemory@4
API _GetPreviousFgPolicyRefreshInfoInternal@8
API _GetPriorityClass@4
API _GetPrivateObjectSecurity@20
API _GetProcAddress@8
API _GetProcAddressForCaller@12
API _GetProcessDefaultCpuSetMasks@16
API _GetProcessDefaultCpuSets@16
API _GetProcessGroupAffinity@12
API _GetProcessHandleCount@8
API _GetProcessHeap@0
API _GetProcessHeaps@8
API _GetProcessId@4
API _GetProcessIdOfThread@4
API _K32GetProcessImageFileNameA@12
API _K32GetProcessImageFileNameW@12
API _GetProcessInformation@16
API _K32GetProcessMemoryInfo@12
API _GetProcessMitigationPolicy@16
API _GetProcessPreferredUILanguages@16
API _GetProcessPriorityBoost@8
API _GetProcessShutdownParameters@8
API _GetProcessTimes@20
API _GetProcessVersion@4
API _GetProcessWorkingSetSize@12
API _GetProcessWorkingSetSizeEx@16
API _GetProcessesUsingPackageDependency@20
API _GetProcessorSystemCycleTime@12
API _GetProductInfo@20
API _GetProtocolAumid@16
API _GetProtocolProperty@24
API _GetPtrCalData@16
API _GetPtrCalDataArray@12
API _GetPublisherCacheFolder@16
API _GetPublisherRootFolder@12
API _GetQueuedCompletionStatus@20
API _GetQueuedCompletionStatusEx@24
API _GetRegistryExtensionFlags@4
API _GetRegistryValueWithFallbackW@40
API _GetResolvedPackageFullNameForPackageDependency@8
API _GetResolvedPackageFullNameForPackageDependency2@8
API _GetRoamingLastObservedChangeTime@8
API _GetSecureSystemAppDataFolder@12
API _GetSecurityDescriptorControl@12
API _GetSecurityDescriptorDacl@16
API _GetSecurityDescriptorGroup@12
API _GetSecurityDescriptorLength@4
API _GetSecurityDescriptorOwner@12
API _GetSecurityDescriptorRMControl@8
API _GetSecurityDescriptorSacl@16
API _GetSerializedAtomBytes@12
API _GetSharedLocalFolder@12
API _GetShortPathNameW@12
API _GetSidIdentifierAuthority@4
API _GetSidLengthRequired@4
API _GetSidSubAuthority@8
API _GetSidSubAuthorityCount@4
API _GetStagedPackageOrigin@8
API _GetStagedPackagePathByFullName@12
API _GetStagedPackagePathByFullName2@16
API _GetStartupInfoW@4
API _GetStateContainerDepth@8
API _GetStateFolder@16
API _GetStateRootFolder@12
API _GetStateRootFolderBase@12
API _GetStateSettingsFolder@12
API _GetStateVersion@12
API _GetStdHandle@4
API _GetStringScripts@20
API _GetStringTableEntry@16
API _GetStringTypeA@20
API _GetStringTypeExW@20
API _GetStringTypeW@16
API _GetSystemAppDataFolder@12
API _GetSystemAppDataKey@16
API _GetSystemCpuSetInformation@20
API _GetSystemDefaultLCID@0
API _GetSystemDefaultLangID@0
API _GetSystemDefaultLocaleName@8
API _GetSystemDefaultUILanguage@0
API _GetSystemDirectoryA@8
API _GetSystemDirectoryW@8
API _GetSystemFileCacheSize@12
API _GetSystemFirmwareTable@16
API _GetSystemInfo@4
API _GetSystemLeapSecondInformation@8
API _GetSystemMetadataPath@8
API _GetSystemMetadataPathForPackage@12
API _GetSystemMetadataPathForPackageFamily@12
API _GetSystemPreferredUILanguages@16
API _GetSystemStateRootFolder@12
API _GetSystemTime@4
API _GetSystemTimeAdjustment@12
API _GetSystemTimeAdjustmentPrecise@12
API _GetSystemTimeAsFileTime@4
API _GetSystemTimePreciseAsFileTime@4
API _GetSystemTimes@12
API _GetSystemWindowsDirectoryA@8
API _GetSystemWindowsDirectoryW@8
API _GetSystemWow64Directory2A@12
API _GetSystemWow64Directory2W@12
API _GetSystemWow64DirectoryA@8
API _GetSystemWow64DirectoryW@8
API _GetTargetPlatformContext@12
API _GetTempFileNameA@16
API _GetTempFileNameW@16
API _GetTempPath2A@8
API _GetTempPath2W@8
API _GetTempPathA@8
API _GetTempPathW@8
API _GetThreadContext@8
API _GetThreadDescription@8
API _GetThreadEnabledXStateFeatures@0
API _GetThreadErrorMode@0
API _GetThreadGroupAffinity@8
API _GetThreadIOPendingFlag@8
API _GetThreadId@4
API _GetThreadIdealProcessorEx@8
API _GetThreadInformation@16
API _GetThreadLocale@0
API _GetThreadPreferredUILanguages@16
API _GetThreadPriority@4
API _GetThreadPriorityBoost@8
API _GetThreadSelectedCpuSetMasks@16
API _GetThreadSelectedCpuSets@16
API _GetThreadTimes@20
API _GetThreadUILanguage@0
API _GetTickCount@0
API _GetTickCount64@0
API _GetTimeFormatA@24
API _GetTimeFormatEx@24
API _GetTimeFormatW@24
API _GetTimeZoneInformation@4
API _GetTimeZoneInformationForYear@12
API _GetTokenInformation@20
API _EtwGetTraceEnableFlags@8
API _EtwGetTraceEnableLevel@8
API _EtwGetTraceLoggerHandle@4
API _GetUILanguageInfo@20
API _GetUnicodeStringToEightBitSizeRoutine@0
API _GetUnicodeStringToEightBitStringRoutine@0
API _GetUserDefaultGeoName@8
API _GetUserDefaultLCID@0
API _GetUserDefaultLangID@0
API _GetUserDefaultLocaleName@8
API _GetUserDefaultUILanguage@0
API _GetUserGeoID@4
API _GetUserInfo@20
API _GetUserInfoWord@12
API _GetUserOverrideString@24
API _GetUserOverrideWord@16
API _GetUserPreferredUILanguages@16
API _GetVersion@0
API _GetVersionExA@4
API _GetVersionExW@4
API _GetVolumeInformationA@32
API _GetVolumeInformationByHandleW@32
API _GetVolumeInformationW@32
API _GetVolumeNameForVolumeMountPointW@12
API _GetVolumePathNameW@12
API _GetVolumePathNamesForVolumeNameW@16
API _GetWindowsAccountDomainSid@12
API _GetWindowsDirectoryA@8
API _GetWindowsDirectoryW@8
API _GetWriteWatch@24
API _K32GetWsChanges@12
API _K32GetWsChangesEx@12
API _GetXStateFeaturesMask@8
API _GlobalAlloc@8
API _GlobalFlags@4
API _GlobalFree@4
API _GlobalHandle@4
API _GlobalLock@4
API _GlobalMemoryStatusEx@4
API _GlobalReAlloc@12
API _GlobalSize@4
API _GlobalUnlock@4
API _GuardCheckLongJumpTarget@8
API _HasPolicyForegroundProcessingCompletedInternal@20
API _HashData@16
API _RtlAllocateHeap@12
API _HeapCompact@8
API _HeapCreate@12
API _HeapDestroy@4
API _RtlFreeHeap@12
API _HeapLock@4
API _HeapQueryInformation@20
API _RtlReAllocateHeap@16
API _HeapSetInformation@16
API _RtlSizeHeap@12
API _HeapSummary@12
API _HeapUnlock@4
API _HeapValidate@12
API _HeapWalk@8
API _IdnToAscii@20
API _IdnToNameprepUnicode@20
API _IdnToUnicode@20
API _ImpersonateAnonymousToken@4
API _ImpersonateLoggedOnUser@4
API _ImpersonateNamedPipeClient@4
API _ImpersonateSelf@4
API _IncrementPackageStatusVersion@0
API _InitOnceBeginInitialize@16
API _InitOnceComplete@12
API _InitOnceExecuteOnce@16
API _RtlRunOnceInitialize@4
API _InitializeAcl@12
API _RtlRunOnceInitialize@4
API _InitializeContext@16
API _InitializeContext2@24
API _RtlInitializeCriticalSection@4
API _InitializeCriticalSectionAndSpinCount@8
API _InitializeCriticalSectionEx@12
API _InitializeEnclave@20
API _InitializeProcThreadAttributeList@16
API _K32InitializeProcessForWsWatch@4
API _RtlInitializeSListHead@4
API _RtlRunOnceInitialize@4
API _InitializeSecurityDescriptor@8
API _InitializeSid@12
API _InitializeSynchronizationBarrier@12
API _InstallELAMCertificateInfo@4
API _InterlockedCompareExchange@12
API _InterlockedCompareExchange64@20
API _InterlockedDecrement@4
API _InterlockedExchange@8
API _InterlockedExchangeAdd@8
API _RtlInterlockedFlushSList@4
API _InterlockedIncrement@4
API _RtlInterlockedPopEntrySList@4
API _RtlInterlockedPushEntrySList@8
API @InterlockedPushListSList@16
API _RtlInterlockedPushListSListEx@16
API @InternalLcidToName@8
API _Internal_EnumCalendarInfo@32
API _Internal_EnumDateFormats@28
API _Internal_EnumLanguageGroupLocales@20
API _Internal_EnumSystemCodePages@12
API _Internal_EnumSystemLanguageGroups@16
API _Internal_EnumSystemLocales@24
API _Internal_EnumTimeFormats@24
API _Internal_EnumUILanguages@16
API _InternetTimeFromSystemTimeA@16
API _InternetTimeFromSystemTimeW@16
API _InternetTimeToSystemTimeA@12
API _InternetTimeToSystemTimeW@12
API _InvalidateAppModelVersionCache@0
API _IsApiSetImplemented@4
API _IsCharAlphaA@4
API _IsCharAlphaNumericA@4
API _IsCharAlphaNumericW@4
API _IsCharAlphaW@4
API _IsCharBlankW@4
API _IsCharCntrlW@4
API _IsCharDigitW@4
API _IsCharLowerA@4
API _IsCharLowerW@4
API _IsCharPunctW@4
API _IsCharSpaceA@4
API _IsCharSpaceW@4
API _IsCharUpperA@4
API _IsCharUpperW@4
API _IsCharXDigitW@4
API _IsDBCSLeadByte@4
API _IsDBCSLeadByteEx@8
API _IsDebuggerPresent@0
API _IsDeveloperModeEnabled@4
API _IsDeveloperModePolicyApplied@4
API _IsEnclaveTypeSupported@4
API _IsInternetESCEnabled@0
API _IsIoRingOpSupported@8
API _IsMrtResourceRedirectionEnabled@8
API _SortIsDefinedString@20
API _IsNormalizedString@12
API _IsOnDemandRegistrationSupportedForExtensionCategory@8
API _IsProcessCritical@8
API _IsProcessInJob@12
API _IsProcessorFeaturePresent@4
API _IsSideloadingEnabled@4
API _IsSideloadingPolicyApplied@4
API _IsSyncForegroundPolicyRefresh@12
API _IsThreadAFiber@0
API _TpIsTimerSet@4
API _IsTimeZoneRedirectionEnabled@0
API _IsTokenRestricted@4
API _sqlite3_value_bytes@4
API _IsValidAcl@4
API _IsValidCodePage@4
API _IsValidLanguageGroup@8
API _IsValidLocale@8
API _IsValidLocaleName@4
API _IsValidNLSVersion@12
API _IsValidRelativeSecurityDescriptor@12
API _IsValidSecurityDescriptor@4
API _IsValidSid@4
API _IsWellKnownSid@8
API _IsWow64GuestMachineSupported@8
API _IsWow64Process@8
API _IsWow64Process2@12
API _K32EmptyWorkingSet@4
API _K32EnumDeviceDrivers@12
API _K32EnumPageFilesA@8
API _K32EnumPageFilesW@8
API _K32EnumProcessModules@16
API _K32EnumProcessModulesEx@20
API _K32EnumProcesses@12
API _K32GetDeviceDriverBaseNameA@12
API _K32GetDeviceDriverBaseNameW@12
API _K32GetDeviceDriverFileNameA@12
API _K32GetDeviceDriverFileNameW@12
API _K32GetMappedFileNameA@16
API _K32GetMappedFileNameW@16
API _K32GetModuleBaseNameA@16
API _K32GetModuleBaseNameW@16
API _K32GetModuleFileNameExA@16
API _K32GetModuleFileNameExW@16
API _K32GetModuleInformation@16
API _K32GetPerformanceInfo@8
API _K32GetProcessImageFileNameA@12
API _K32GetProcessImageFileNameW@12
API _K32GetProcessMemoryInfo@12
API _K32GetWsChanges@12
API _K32GetWsChangesEx@12
API _K32InitializeProcessForWsWatch@4
API _K32QueryWorkingSet@12
API _K32QueryWorkingSetEx@12
API _KernelBaseGetGlobalData@0
API @KernelbasePostInit@0
API _LCIDToLocaleName@16
API _LCMapStringA@24
API _LCMapStringEx@36
API _LCMapStringW@24
API _LeaveCriticalPolicySectionInternal@4
API _RtlLeaveCriticalSection@4
API _TpCallbackLeaveCriticalSectionOnCompletion@8
API ?ObjectStublessClient20@@YGXXZ
API _LoadEnclaveData@36
API _LoadEnclaveImageA@8
API _LoadEnclaveImageW@8
API _LoadLibraryA@4
API _LoadLibraryExA@12
API _LoadLibraryExW@12
API _LoadLibraryW@4
API _LoadPackagedLibrary@8
API _LoadResource@8
API _LoadStringA@16
API _LoadStringBaseExW@20
API _LoadStringByReference@28
API _LoadStringW@16
API _LocalAlloc@8
API _LocalFileTimeToFileTime@8
API _LocalFileTimeToLocalSystemTime@12
API _LocalFlags@4
API _LocalFree@4
API _LocalLock@4
API _LocalReAlloc@12
API _LocalSize@4
API _LocalSystemTimeToLocalFileTime@12
API _LocalUnlock@4
API _LocaleNameToLCID@8
API _LocateXStateFeature@12
API _LockFile@20
API _LockFileEx@24
API _LockResource@4
API _LogStagedFeatureUsage@12
API _MakeAbsoluteSD@44
API _MakeAbsoluteSD2@8
API _MakeSelfRelativeSD@12
API _MapGenericMask@8
API _MapPredefinedHandleInternal@16
API _MapUserPhysicalPages@12
API _MapViewOfFile@20
API _MapViewOfFile3@40
API _MapViewOfFile3FromApp@40
API _MapViewOfFileEx@24
API _MapViewOfFileExNuma@28
API _MapViewOfFileFromApp@20
API _MapViewOfFileNuma2@36
API _MoveFileExW@12
API _MoveFileFromAppW@8
API _MoveFileWithProgressTransactedW@24
API _MoveFileWithProgressW@20
API ___FC_Query_Config@12
API ?MsixIsSystemPackageByPackageFullName@Internal@ARI@@YGJPBGPAH@Z
API _MulDiv@12
API _MultiByteToWideChar@24
API _NamedPipeEventEnum@12
API _NamedPipeEventSelect@12
API _NeedCurrentDirectoryForExePathA@4
API _NeedCurrentDirectoryForExePathW@4
API _NlsCheckPolicy@8
API _NlsDispatchAnsiEnumProc@36
API _NlsGetACPFromLocale@8
API _NlsGetCacheUpdateCount@0
API _NlsIsUserDefaultLocale@4
API _NlsUpdateLocale@8
API _NlsUpdateSystemLocale@8
API _NlsValidateLocale@8
API _NormalizeString@20
API _RtlNotifyFeatureToggleUsage@12
API _NotifyMountMgr@12
API _NotifyRedirectedStringChange@4
API _ObjectCloseAuditAlarmW@12
API _ObjectDeleteAuditAlarmW@12
API _ObjectOpenAuditAlarmW@48
API _ObjectPrivilegeAuditAlarmW@24
API _OfferVirtualMemory@12
API _OpenCommPort@12
API _OpenDedicatedMemoryPartition@20
API _OpenEventA@12
API _OpenEventW@12
API _OpenFileById@24
API _OpenFileMappingFromApp@12
API _OpenFileMappingW@12
API _OpenGlobalizationUserSettingsKey@12
API _OpenMutexW@12
API _OpenPackageInfoByFullName@12
API _OpenPackageInfoByFullNameForMachine@12
API _OpenPackageInfoByFullNameForUser@16
API _OpenPrivateNamespaceW@8
API _OpenProcess@12
API _OpenProcessToken@12
API _OpenRegKey@20
API _OpenSemaphoreW@12
API _OpenState@0
API _OpenStateAtom@8
API _OpenStateExplicit@8
API _OpenStateExplicitForUserSid@8
API _OpenStateExplicitForUserSidString@8
API _OpenThread@12
API _OpenThreadToken@16
API _OpenWaitableTimerW@12
API _OutputDebugStringA@4
API _OutputDebugStringW@4
API _OverrideRoamingDataModificationTimesInRange@16
API _PackageFamilyNameFromFullName@12
API _PackageFamilyNameFromFullNameA@12
API _PackageFamilyNameFromId@12
API _PackageFamilyNameFromIdA@12
API _PackageFamilyNameFromProductId@12
API _PackageFullNameFromId@12
API _PackageFullNameFromIdA@12
API _PackageFullNameFromProductId@20
API _PackageIdFromFullName@16
API _PackageIdFromFullNameA@16
API _PackageIdFromProductId@24
API _PackageIsEffectiveSupportedUsersMultiple@8
API _PackageNameAndPublisherIdFromFamilyName@20
API _PackageNameAndPublisherIdFromFamilyNameA@20
API _PackagePublisherAddUserIfNecessary@12
API _PackagePublisherIdFromPublisher@12
API _PackageRelativeApplicationIdFromProductId@12
API _PackageSidFromFamilyName@8
API ?PackageSidFromProductId@Internal@ARI@@YGJPBU_GUID@@PAPAX@Z
API _ParseApplicationUserModelId@20
API _ParseApplicationUserModelIdA@20
API _ParseURLA@8
API _ParseURLW@8
API _PathAddBackslashA@4
API _PathAddBackslashW@4
API _PathAddExtensionA@8
API _PathAddExtensionW@8
API _PathAllocCanonicalize@12
API _PathAllocCombine@16
API _PathAppendA@8
API _PathAppendW@8
API _PathCanonicalizeA@8
API _PathCanonicalizeW@8
API _PathCchAddBackslash@8
API _PathCchAddBackslashEx@16
API _PathCchAddExtension@12
API _PathCchAppend@12
API _PathCchAppendEx@16
API _PathCchCanonicalize@12
API _PathCchCanonicalizeEx@16
API _PathCchCombine@16
API _PathCchCombineEx@20
API _PathCchFindExtension@12
API _PathCchIsRoot@4
API _PathCchRemoveBackslash@8
API _PathCchRemoveBackslashEx@16
API _PathCchRemoveExtension@8
API _PathCchRemoveFileSpec@8
API _PathCchRenameExtension@12
API _PathCchSkipRoot@8
API _PathCchStripPrefix@8
API _PathCchStripToRoot@8
API _PathCombineA@12
API _PathCombineW@12
API _PathCommonPrefixA@12
API _PathCommonPrefixW@12
API _PathCreateFromUrlA@16
API _PathCreateFromUrlAlloc@12
API _PathCreateFromUrlW@16
API _PathFileExistsA@4
API _PathFileExistsW@4
API _PathFindExtensionA@4
API _PathFindExtensionW@4
API _PathFindFileNameA@4
API _PathFindFileNameW@4
API _PathFindNextComponentA@4
API _PathFindNextComponentW@4
API _PathGetArgsA@4
API _PathGetArgsW@4
API _PathGetCharTypeA@4
API _PathGetCharTypeW@4
API _PathGetDriveNumberA@4
API _PathGetDriveNumberW@4
API _PathIsFileSpecA@4
API _PathIsFileSpecW@4
API _PathIsLFNFileSpecA@4
API _PathIsLFNFileSpecW@4
API _PathIsPrefixA@8
API _PathIsPrefixW@8
API _PathIsRelativeA@4
API _PathIsRelativeW@4
API _PathIsRootA@4
API _PathIsRootW@4
API _PathIsSameRootA@8
API _PathIsSameRootW@8
API _PathIsUNCA@4
API _PathIsUNCEx@8
API _PathIsUNCServerA@4
API _PathIsUNCServerShareA@4
API _PathIsUNCServerShareW@4
API _PathIsUNCServerW@4
API _PathIsUNCW@4
API _PathIsURLA@4
API _PathIsURLW@4
API _PathIsValidCharA@8
API _PathIsValidCharW@8
API _PathMatchSpecA@8
API _PathMatchSpecExA@12
API _PathMatchSpecExW@12
API _PathMatchSpecW@8
API _PathParseIconLocationA@4
API _PathParseIconLocationW@4
API _PathQuoteSpacesA@4
API _PathQuoteSpacesW@4
API _PathRelativePathToA@20
API _PathRelativePathToW@20
API _PathRemoveBackslashA@4
API _PathRemoveBackslashW@4
API _PathRemoveBlanksA@4
API _PathRemoveBlanksW@4
API _PathRemoveExtensionA@4
API _PathRemoveExtensionW@4
API _PathRemoveFileSpecA@4
API _PathRemoveFileSpecW@4
API _PathRenameExtensionA@8
API _PathRenameExtensionW@8
API _PathSearchAndQualifyA@12
API _PathSearchAndQualifyW@12
API _PathSkipRootA@4
API _PathSkipRootW@4
API _PathStripPathA@4
API _PathStripPathW@4
API _PathStripToRootA@4
API _PathStripToRootW@4
API _PathUnExpandEnvStringsA@12
API _PathUnExpandEnvStringsW@12
API _PathUnquoteSpacesA@4
API _PathUnquoteSpacesW@4
API _PcwAddQueryItem@36
API _PcwClearCounterSetSecurity@4
API _PcwCollectData@16
API _PcwCompleteNotification@20
API _PcwCreateNotifier@8
API _PcwCreateQuery@8
API _PcwDisconnectCounterSet@8
API _PcwEnumerateInstances@24
API _PcwIsNotifierAlive@12
API _PcwQueryCounterSetSecurity@20
API _PcwReadNotificationData@16
API _PcwRegisterCounterSet@12
API _PcwRemoveQueryItem@8
API _PcwSendNotification@32
API _PcwSendStatelessNotification@32
API _PcwSetCounterSetSecurity@12
API _PcwSetQueryItemUserData@12
API _PeekConsoleInputA@16
API _PeekConsoleInputW@16
API _PeekNamedPipe@24
API _PerfCreateInstance@16
API _PerfDecrementULongCounterValue@16
API _PerfDecrementULongLongCounterValue@20
API _PerfDeleteInstance@8
API _PerfIncrementULongCounterValue@16
API _PerfIncrementULongLongCounterValue@20
API _PerfQueryInstance@16
API _PerfSetCounterRefValue@16
API _PerfSetCounterSetInfo@12
API _PerfSetULongCounterValue@16
API _PerfSetULongLongCounterValue@20
API _PerfStartProvider@12
API _PerfStartProviderEx@12
API _PerfStopProvider@4
API _PoolPerAppKeyStateInternal@0
API _PopIoRingCompletion@8
API _PostQueuedCompletionStatus@16
API _PrefetchVirtualMemory@16
API _PrivCopyFileExW@24
API _PrivilegeCheck@12
API _PrivilegedServiceAuditAlarmW@20
API _ProcessIdToSessionId@8
API _ProductIdFromPackageFamilyName@8
API _PsmCreateKey@16
API _PsmCreateKeyWithDynamicId@20
API _PsmEqualApplication@8
API _PsmEqualPackage@8
API _PsmGetApplicationNameFromKey@12
API _PsmGetAumidFromKey@12
API _PsmGetDynamicIdFromKey@8
API _PsmGetKeyFromProcess@16
API _PsmGetKeyFromToken@16
API _PsmGetPackageFullNameFromKey@12
API _PsmIsChildKey@8
API _PsmIsDynamicKey@4
API _PsmIsValidKey@4
API _PssCaptureSnapshot@16
API _PssDuplicateSnapshot@20
API _PssFreeSnapshot@8
API _PssQuerySnapshot@16
API _PssWalkMarkerCreate@8
API _PssWalkMarkerFree@4
API _PssWalkMarkerTell@8
API _PssWalkMarkerRewind@4
API _PssWalkMarkerSeek@8
API _PssWalkSnapshot@20
API _PublishStateChangeNotification@4
API _PublisherFromPackageFullName@12
API _PulseEvent@4
API _PurgeComm@8
API _QISearch@16
API _QueryActCtxSettingsW@28
API _QueryActCtxW@28
API _QueryAuxiliaryCounterFrequency@4
API _RtlQueryDepthSList@4
API _QueryDosDeviceW@12
API _QueryFullProcessImageNameA@16
API _QueryFullProcessImageNameW@16
API _QueryGlobalizationUserSettingsStatus@8
API _QueryIdleProcessorCycleTime@8
API _QueryIdleProcessorCycleTimeEx@12
API _QueryInterruptTime@4
API _QueryInterruptTimePrecise@4
API _QueryIoRingCapabilities@4
API _QueryMemoryResourceNotification@8
API _QueryOptionalDelayLoadedAPI@16
API _QueryPartitionInformation@16
API _RtlQueryPerformanceCounter@4
API _RtlQueryPerformanceFrequency@4
API _QueryProcessAffinityUpdateMode@8
API _QueryProcessCycleTime@8
API _QueryProtectedPolicy@8
API _QuerySecurityAccessMask@8
API _QueryStateAtomValueInfo@12
API _QueryStateContainerCreatedNew@8
API _QueryStateContainerItemInfo@12
API _QueryThreadCycleTime@8
API _QueryThreadpoolStackInformation@8
API _RtlQueryUnbiasedInterruptTime@4
API _QueryUnbiasedInterruptTimePrecise@4
API _QueryVirtualMemoryInformation@24
API _K32QueryWorkingSet@12
API _K32QueryWorkingSetEx@12
API _QueueUserAPC@12
API _QueueUserAPC2@16
API _QueueUserWorkItem@12
API _QuirkGetData@8
API _QuirkGetData2@8
API _QuirkIsEnabled@4
API _QuirkIsEnabled2@12
API _QuirkIsEnabled3@8
API _QuirkIsEnabledForPackage@16
API _QuirkIsEnabledForPackage2@24
API _QuirkIsEnabledForPackage3@20
API _QuirkIsEnabledForPackage4@20
API _QuirkIsEnabledForProcess@12
API _RaiseCustomSystemEventTrigger@4
API _RaiseException@16
API _RaiseFailFastException@12
API _ReOpenFile@16
API _ReadConsoleA@20
API _ReadConsoleInputA@16
API _ReadConsoleInputExA@20
API _ReadConsoleInputExW@20
API _ReadConsoleInputW@16
API _ReadConsoleOutputA@20
API _ReadConsoleOutputAttribute@20
API _ReadConsoleOutputCharacterA@20
API _ReadConsoleOutputCharacterW@20
API _ReadConsoleOutputW@20
API _ReadConsoleW@20
API _ReadDirectoryChangesExW@36
API _ReadDirectoryChangesW@32
API _ReadFile@20
API _ReadFileEx@20
API _ReadFileScatter@20
API _ReadProcessMemory@20
API _ReadStateAtomValue@20
API _ReadStateContainerValue@20
API _ReclaimVirtualMemory@8
API _RecordFeatureUsage2@12
API _RefreshPackageInfo@4
API _RefreshPolicyExInternal@8
API _RefreshPolicyInternal@4
API _RegCloseKey@4
API _RegCopyTreeW@12
API _RegCreateKeyExA@36
API _RegCreateKeyExInternalA@40
API _RegCreateKeyExInternalW@40
API _RegCreateKeyExW@36
API _RegDeleteKeyExA@16
API _RegDeleteKeyExInternalA@20
API _RegDeleteKeyExInternalW@20
API _RegDeleteKeyExW@16
API _RegDeleteKeyValueA@12
API _RegDeleteKeyValueW@12
API _RegDeleteTreeA@8
API _RegDeleteTreeW@8
API _RegDeleteValueA@8
API _RegDeleteValueW@8
API _RegDisablePredefinedCacheEx@0
API _RegEnumKeyExA@32
API _RegEnumKeyExW@32
API _RegEnumValueA@32
API _RegEnumValueW@32
API _RegFlushKey@4
API _RegGetKeySecurity@16
API _RegGetValueA@28
API _RegGetValueW@28
API _RegKrnGetAppKeyEventAddressInternal@0
API _RegKrnGetAppKeyLoaded@0
API _RegKrnGetClassesEnumTableAddressInternal@0
API _RegKrnGetHKEY_ClassesRootAddress@0
API _RegKrnGetTermsrvRegistryExtensionFlags@0
API _RegKrnResetAppKeyLoaded@0
API _RegKrnSetDllHasThreadStateGlobal@4
API _RegKrnSetTermsrvRegistryExtensionFlags@4
API _RegLoadAppKeyA@20
API _RegLoadAppKeyW@20
API _RegLoadKeyA@12
API _RegLoadKeyW@12
API _RegLoadMUIStringA@28
API _RegLoadMUIStringW@28
API _RegNotifyChangeKeyValue@20
API _RegOpenCurrentUser@8
API _RegOpenKeyExA@20
API _RegOpenKeyExInternalA@24
API _RegOpenKeyExInternalW@24
API _RegOpenKeyExW@20
API _RegOpenUserClassesRoot@16
API _RegQueryInfoKeyA@48
API _RegQueryInfoKeyW@48
API _RegQueryMultipleValuesA@20
API _RegQueryMultipleValuesW@20
API _RegQueryValueExA@24
API _RegQueryValueExW@24
API _RegRestoreKeyA@12
API _RegRestoreKeyW@12
API _RegSaveKeyExA@16
API _RegSaveKeyExW@16
API _RegSetKeySecurity@12
API _RegSetKeyValueA@24
API _RegSetKeyValueW@24
API _RegSetValueExA@24
API _RegSetValueExW@24
API _RegUnLoadKeyA@8
API _RegUnLoadKeyW@8
API _RegisterApplicationRestart@8
API _RegisterBadMemoryNotification@4
API _RegisterGPNotificationInternal@8
API _RegisterStateChangeNotification@8
API _RegisterStateLock@4
API _EtwRegisterTraceGuidsW@32
API _RegisterWaitForSingleObjectEx@20
API _ReleaseActCtx@4
API _ReleaseMutex@4
API _TpCallbackReleaseMutexOnCompletion@8
API _ReleasePackagedDataForFile@4
API _ReleasePseudoConsole@4
API _RtlReleaseSRWLockExclusive@4
API _RtlReleaseSRWLockShared@4
API _ReleaseSemaphore@12
API _TpCallbackReleaseSemaphoreOnCompletion@12
API _ReleaseStateLock@4
API _RemapPredefinedHandleInternal@8
API _RemoveDirectoryA@4
API _RemoveDirectoryFromAppW@4
API _RemoveDirectoryW@4
API _RemoveDllDirectory@4
API _RemoveExtensionProgIds@4
API _RemovePackageDependency@4
API _RemovePackageStatus@4
API _RemovePackageStatusForUser@8
API _RtlRemoveVectoredContinueHandler@4
API _RtlRemoveVectoredExceptionHandler@4
API _ReplaceFileExInternal@32
API _ReplaceFileFromAppW@24
API _ReplaceFileW@24
API _ResetEvent@4
API _ResetState@4
API _ResetWriteWatch@8
API _ResizePseudoConsole@8
API _ResolveDelayLoadedAPI@24
API _ResolveDelayLoadsFromDll@12
API _ResolveLocaleName@12
API _RtlSetLastWin32Error@4
API _RestoreThreadPreferredUILanguages@4
API _ResumeThread@4
API _RevertToSelf@0
API _RsopLoggingEnabledInternal@0
API _SHCoCreateInstance@20
API _SHExpandEnvironmentStringsA@12
API _SHExpandEnvironmentStringsW@12
API _SHLoadIndirectString@16
API _SHLoadIndirectStringInternal@16
API _SHRegCloseUSKey@4
API _SHRegCreateUSKeyA@20
API _SHRegCreateUSKeyW@20
API _SHRegDeleteEmptyUSKeyA@12
API _SHRegDeleteEmptyUSKeyW@12
API _SHRegDeleteUSValueA@12
API _SHRegDeleteUSValueW@12
API _SHRegEnumUSKeyA@20
API _SHRegEnumUSKeyW@20
API _SHRegEnumUSValueA@32
API _SHRegEnumUSValueW@32
API _SHRegGetBoolUSValueA@16
API _SHRegGetBoolUSValueW@16
API _SHRegGetUSValueA@32
API _SHRegGetUSValueW@32
API _SHRegOpenUSKeyA@20
API _SHRegOpenUSKeyW@20
API _SHRegQueryInfoUSKeyA@24
API _SHRegQueryInfoUSKeyW@24
API _SHRegQueryUSValueA@32
API _SHRegQueryUSValueW@32
API _SHRegSetUSValueA@24
API _SHRegSetUSValueW@24
API _SHRegWriteUSValueA@24
API _SHRegWriteUSValueW@24
API _SHTruncateString@8
API _SaveAlternatePackageRootPath@4
API _GetAlternatePackageRoots@8
API _ScrollConsoleScreenBufferA@20
API _ScrollConsoleScreenBufferW@20
API _SearchPathA@24
API _SearchPathW@24
API _SetAclInformation@16
API _SetCachedSigningLevel@16
API _SetCalendarInfoW@16
API _SetClientDynamicTimeZoneInformation@4
API _SetClientTimeZoneInformation@4
API _SetCommBreak@4
API _SetCommConfig@12
API _SetCommMask@8
API _SetCommState@8
API _SetCommTimeouts@8
API _SetComputerNameA@4
API _SetComputerNameEx2W@12
API _SetComputerNameExA@8
API _SetComputerNameExW@8
API _SetComputerNameW@4
API _SetConsoleActiveScreenBuffer@4
API _SetConsoleCP@4
API _SetConsoleCtrlHandler@8
API _SetConsoleCursorInfo@8
API _SetConsoleCursorPosition@8
API _SetConsoleDisplayMode@12
API _SetConsoleHistoryInfo@4
API _SetConsoleInputExeNameA@4
API _SetConsoleInputExeNameW@4
API _SetConsoleMode@8
API _SetConsoleNumberOfCommandsA@8
API _SetConsoleNumberOfCommandsW@8
API _SetConsoleOutputCP@4
API _SetConsoleScreenBufferInfoEx@8
API _SetConsoleScreenBufferSize@8
API _SetConsoleTextAttribute@8
API _SetConsoleTitleA@4
API _SetConsoleTitleW@4
API _SetConsoleWindowInfo@12
API _RtlSetCriticalSectionSpinCount@8
API _SetCurrentConsoleFontEx@12
API _SetCurrentDirectoryA@4
API _SetCurrentDirectoryW@4
API _SetDefaultDllDirectories@4
API _SetDynamicTimeZoneInformation@4
API _SetEndOfFile@4
API _SetEnvironmentStringsW@4
API _SetEnvironmentVariableA@8
API _SetEnvironmentVariableW@8
API _SetErrorMode@4
API _SetEvent@4
API _TpCallbackSetEventOnCompletion@8
API _SetExtensionProperty@24
API _SetFileApisToANSI@0
API _SetFileApisToOEM@0
API _SetFileAttributesA@8
API _SetFileAttributesFromAppW@8
API _SetFileAttributesW@8
API _SetFileInformationByHandle@16
API _SetFileIoOverlappedRange@12
API _SetFilePointer@16
API _SetFilePointerEx@20
API _SetFileSecurityW@12
API _SetFileTime@16
API _SetFileValidData@12
API _LockResource@4
API _SetHandleInformation@12
API _SetIoRingCompletionEvent@8
API _SetIsDeveloperModeEnabled@4
API _SetIsSideloadingEnabled@4
API _SetKernelObjectSecurity@12
API _SetLastConsoleEventActive@0
API _RtlSetLastWin32Error@4
API _SetLocalTime@4
API _SetLocaleInfoW@12
API _SetNamedPipeHandleState@16
API _SetPersistedRegistryDWORD@16
API _SetPersistedRegistryDWORD@16
API _SetPersistedRegistryString@16
API _SetPersistedRegistryValue@24
API _SetPriorityClass@8
API _SetPrivateObjectSecurity@20
API _SetPrivateObjectSecurityEx@24
API _SetProcessAffinityUpdateMode@8
API _SetProcessDefaultCpuSetMasks@12
API _SetProcessDefaultCpuSets@12
API _SetProcessDynamicEHContinuationTargets@12
API _SetProcessDynamicEnforcedCetCompatibleRanges@12
API _SetProcessGroupAffinity@12
API _SetProcessInformation@16
API _SetProcessMitigationPolicy@12
API _SetProcessPreferredUILanguages@12
API _SetProcessPriorityBoost@8
API _SetProcessShutdownParameters@8
API _SetProcessValidCallTargets@20
API _SetProcessValidCallTargetsForMappedView@32
API _SetProcessWorkingSetSize@12
API _SetProcessWorkingSetSizeEx@16
API _SetProtectedPolicy@12
API _SetProtocolProperty@20
API _SetRoamingLastObservedChangeTime@8
API _SetSecurityAccessMask@8
API _SetSecurityDescriptorControl@12
API _SetSecurityDescriptorDacl@16
API _SetSecurityDescriptorGroup@12
API _SetSecurityDescriptorOwner@12
API _SetSecurityDescriptorRMControl@8
API _SetSecurityDescriptorSacl@16
API _SetStateVersion@8
API _SetStdHandle@8
API _SetStdHandleEx@12
API _SetSystemFileCacheSize@12
API _SetSystemTime@4
API _SetSystemTimeAdjustment@8
API _SetSystemTimeAdjustmentPrecise@12
API _SetThreadContext@8
API _SetThreadDescription@8
API _SetThreadErrorMode@8
API _SetThreadGroupAffinity@12
API _SetThreadIdealProcessor@8
API _SetThreadIdealProcessorEx@12
API _SetThreadInformation@16
API _SetThreadLocale@4
API _SetThreadPreferredUILanguages@12
API _SetThreadPreferredUILanguages2@16
API _SetThreadPriority@8
API _SetThreadPriorityBoost@8
API _SetThreadSelectedCpuSetMasks@12
API _SetThreadSelectedCpuSets@12
API _SetThreadStackGuarantee@4
API _SetThreadToken@8
API _SetThreadUILanguage@4
API _SetThreadpoolStackInformation@8
API _TpSetPoolMaxThreads@8
API _SetThreadpoolThreadMinimum@8
API _TpSetTimer@16
API _TpSetTimerEx@16
API _TpSetWait@12
API _TpSetWaitEx@16
API _SetTimeZoneInformation@4
API _SetTokenInformation@16
API _SetUnhandledExceptionFilter@4
API _SetUserGeoID@4
API _SetUserGeoName@4
API _SetWaitableTimer@24
API _SetWaitableTimerEx@28
API _SetXStateFeaturesMask@12
API _SetupComm@12
API _SharedLocalIsEnabled@4
API _SignalObjectAndWait@16
API _SizeofResource@8
API _Sleep@4
API _SleepConditionVariableCS@12
API _SleepConditionVariableSRW@16
API _SleepEx@8
API _ImageList_MirroredDraw@24
API _TpStartAsyncIoOperation@4
API _StrCSpnA@8
API _StrCSpnIA@8
API _StrCSpnIW@8
API _StrCSpnW@8
API _StrCatBuffA@12
API _StrCatBuffW@12
API _StrCatChainW@16
API _StrChrA@8
API _StrChrA_MB@12
API _StrChrIA@8
API _StrChrIW@8
API _StrChrNIW@12
API _StrChrNW@12
API _StrChrW@8
API _StrCmpCA@8
API _StrCmpCW@8
API _StrCmpICA@8
API _StrCmpICW@8
API _StrCmpIW@8
API _StrCmpLogicalW@8
API _StrCmpNA@12
API _StrCmpNCA@12
API _StrCmpNCW@12
API _StrCmpNIA@12
API _StrCmpNICA@12
API _StrCmpNICW@12
API _StrCmpNIW@12
API _StrCmpNW@12
API _StrCmpW@8
API _StrCpyNW@12
API _StrCpyNXA@12
API _StrCpyNXW@12
API _StrDupA@4
API _StrDupW@4
API _StrIsIntlEqualA@16
API _StrIsIntlEqualW@16
API _StrPBrkA@8
API _StrPBrkW@8
API _StrRChrA@12
API _StrRChrIA@12
API _StrRChrIW@12
API _StrRChrW@12
API _StrRStrIA@12
API _StrRStrIW@12
API _StrSpnA@8
API _StrSpnW@8
API _StrStrA@8
API _StrStrIA@8
API _StrStrIW@8
API _StrStrNIW@12
API _StrStrNW@12
API _StrStrW@8
API _StrToInt64ExA@12
API _StrToInt64ExW@12
API _StrToIntA@4
API _StrToIntExA@12
API _StrToIntExW@12
API _StrToIntW@4
API _StrTrimA@8
API _StrTrimW@8
API _SubmitIoRing@16
API _TpPostWork@4
API _SubscribeEdpEnabledStateChange@12
API _SubscribeFeatureUsageFlush@8
API _SubscribeStateChangeNotification@12
API _SubscribeWdagEnabledStateChange@12
API _SuspendThread@4
API _SwitchToFiber@4
API _SwitchToThread@0
API _SystemTimeToFileTime@8
API _SystemTimeToTzSpecificLocalTime@12
API _SystemTimeToTzSpecificLocalTimeEx@12
API _TerminateEnclave@8
API _TerminateProcess@8
API _TerminateProcessOnMemoryExhaustion@4
API _TerminateThread@8
API _TestClose@4
API _TestControlReporting@4
API _TestCreate@24
API _TestOpen@20
API _TestQueryData@16
API _TestRecoverResults@4
API _TestReport@4
API _TestUnlockData@16
API _TlsAlloc@0
API _TlsFree@4
API _TlsGetValue@4
API _TlsGetValue2@4
API _TlsSetValue@8
API _EtwLogTraceEvent@12
API _EtwTraceMessage
API _EtwTraceMessageVa@24
API _TransactNamedPipe@28
API _TransmitCommChar@8
API _RtlTryAcquireSRWLockExclusive@4
API _RtlTryAcquireSRWLockShared@4
API _TryCreatePackageDependency@36
API _TryCreatePackageDependency2@40
API _RtlTryEnterCriticalSection@4
API _TrySubmitThreadpoolCallback@12
API _TzSpecificLocalTimeToSystemTime@12
API _TzSpecificLocalTimeToSystemTimeEx@12
API _UnhandledExceptionFilter@4
API _UnlockFile@20
API _UnlockFileEx@20
API _UnmapViewOfFile@4
API _UnmapViewOfFile2@12
API _UnmapViewOfFileEx@8
API _UnregisterApplicationRestart@0
API _UnregisterBadMemoryNotification@4
API _UnregisterGPNotificationInternal@4
API _UnregisterStateChangeNotification@4
API _UnregisterStateLock@8
API _EtwUnregisterTraceGuids@8
API _UnregisterWaitEx@8
API _UnsubscribeWdagEnabledStateChange@4
API _UnsubscribeFeatureUsageFlush@4
API _UnsubscribeStateChangeNotification@4
API _UnsubscribeWdagEnabledStateChange@4
API _UpdatePackageStatus@12
API _UpdatePackageStatusForUser@16
API _UpdatePackageStatusForUserSid@16
API _UpdateProcThreadAttribute@28
API _UrlApplySchemeA@16
API _UrlApplySchemeW@16
API _UrlCanonicalizeA@16
API _UrlCanonicalizeW@16
API _UrlCombineA@20
API _UrlCombineW@20
API _UrlCompareA@12
API _UrlCompareW@12
API _UrlCreateFromPathA@16
API _UrlCreateFromPathW@16
API _UrlEscapeA@16
API _UrlEscapeW@16
API _UrlFixupW@12
API _UrlGetLocationA@4
API _UrlGetLocationW@4
API _UrlGetPartA@20
API _UrlGetPartW@20
API _UrlHashA@12
API _UrlHashW@12
API _UrlIsA@8
API _UrlIsNoHistoryA@4
API _UrlIsNoHistoryW@4
API _UrlIsOpaqueA@4
API _UrlIsOpaqueW@4
API _UrlIsW@8
API _UrlUnescapeA@16
API _UrlUnescapeW@16
API _VerFindFileA@32
API _VerFindFileW@32
API _VerLanguageNameA@12
API _VerLanguageNameW@12
API _VerQueryValueA@16
API _VerQueryValueW@16
API _VerSetConditionMask@16
API _VerifyApplicationUserModelId@4
API _VerifyApplicationUserModelIdA@4
API _VerifyPackageFamilyName@4
API _VerifyPackageFamilyNameA@4
API _VerifyPackageFullName@4
API _VerifyPackageFullNameA@4
API _VerifyPackageId@4
API _VerifyPackageIdA@4
API _VerifyPackageName@4
API _VerifyPackageNameA@4
API _VerifyPackagePublisher@8
API _VerifyPackagePublisherA@8
API _VerifyPackageRelativeApplicationId@4
API _VerifyPackageRelativeApplicationIdA@4
API _VerifyScripts@20
API _VirtualAlloc@16
API _VirtualAlloc2@28
API _VirtualAlloc2FromApp@28
API _VirtualAllocEx@20
API _VirtualAllocExNuma@24
API _VirtualAllocFromApp@16
API _VirtualFree@12
API _VirtualFreeEx@16
API _VirtualLock@8
API _VirtualProtect@16
API _VirtualProtectEx@20
API _VirtualProtectFromApp@16
API _VirtualQuery@12
API _VirtualQueryEx@16
API _VirtualUnlock@8
API _VirtualUnlockEx@12
API _WTSGetServiceSessionId@0
API _WTSIsServerContainer@0
API _WaitCommEvent@12
API _WaitForDebugEvent@8
API _WaitForDebugEventEx@8
API _WaitForMachinePolicyForegroundProcessingInternal@0
API _WaitForMultipleObjects@16
API _WaitForMultipleObjectsEx@20
API _WaitForSingleObject@8
API _WaitForSingleObjectEx@12
API _TpWaitForIoCompletion@8
API _TpWaitForTimer@8
API _TpWaitForWait@8
API _TpWaitForWork@8
API _WaitForUserPolicyForegroundProcessingInternal@0
API _WaitNamedPipeW@8
API _WaitOnAddress@16
API _RtlWakeAllConditionVariable@4
API _RtlWakeAddressAll@4
API _RtlWakeAddressSingle@4
API _RtlWakeConditionVariable@4
API _WerGetFlags@8
API _WerRegisterAdditionalProcess@8
API _WerRegisterAppLocalDump@4
API _WerRegisterCustomMetadata@8
API _WerRegisterExcludedMemoryBlock@8
API _WerRegisterFile@12
API _WerRegisterMemoryBlock@8
API _WerRegisterRuntimeExceptionModule@8
API _WerSetFlags@4
API _WerSetMaxProcessHoldMilliseconds@4
API _WerUnregisterAdditionalProcess@4
API _WerUnregisterAppLocalDump@0
API _WerUnregisterCustomMetadata@4
API _WerUnregisterExcludedMemoryBlock@4
API _WerUnregisterFile@4
API _WerUnregisterMemoryBlock@4
API _WerUnregisterRuntimeExceptionModule@8
API _RtwqScheduleWorkItem@16
API _FhServiceUnblockBackup@4
API _WideCharToMultiByte@32
API _WilFailureNotifyWatchers@12
API _WilFailureWatcherResume@4
API _WilFailureWatcherSubscribe@16
API _WilFailureWatcherSuspend@4
API _WilFailureWatcherUnsubscribe@4
API _Wow64DisableWow64FsRedirection@4
API _Wow64EnableWow64FsRedirection@4
API _GetThreadContext@8
API _Wow64RevertWow64FsRedirection@4
API _SetThreadContext@8
API _Wow64SetThreadDefaultGuestMachine@4
API _SuspendThread@4
API Wow64Transition
API _WriteConsoleA@20
API _WriteConsoleInputA@16
API _WriteConsoleInputW@16
API _WriteConsoleOutputA@20
API _WriteConsoleOutputAttribute@20
API _WriteConsoleOutputCharacterA@20
API _WriteConsoleOutputCharacterW@20
API _WriteConsoleOutputW@20
API _WriteConsoleW@20
API _WriteFile@20
API _WriteFileEx@20
API _WriteFileGather@20
API _WriteProcessMemory@20
API _WriteStateAtomValue@20
API _WriteStateContainerValue@24
API _ZombifyActCtx@4
API __AddMUIStringToCache@16
API __GetMUIStringFromCache@24
API __OpenMuiStringCache@24
API ___FC_Query_Config@12
API ?MFGetPlatformFlags@@YGKXZ
API _WerpTraceDuration@24
API _sqlite3_create_module@16
API _sqlite3_mutex_enter@4
API ___dllonexit3
API ___wgetmainargs
API ?ObjectStublessClient20@@YGXXZ
API __c_exit
API __cexit
API __exit
API __initterm
API __initterm_e
API __invalid_parameter
API __onexit
API __purecall
API __time64
API _atexit
API _exit
API _hgets
API _hwprintf
API _lstrcmpA@8
API _lstrcmpA@8
API _lstrcmpW@8
API _lstrcmpiA@8
API _lstrcmpiA@8
API _lstrcmpiW@8
API _lstrcpynA@12
API _lstrcpynA@12
API _lstrcpynW@12
API _lstrlenA@4
API _lstrlenA@4
API _lstrlenW@4
API _time
API _wprintf

end
