.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _CommandLineToArgvWStub@8 ; -> CommandLineToArgvW
API _CreateRandomAccessStreamOnFile@16
API _CreateRandomAccessStreamOverStream@16
API _CreateStreamOverRandomAccessStream@12
API _DllCanUnloadNow@0
API _DllGetActivationFactory@8
API _DllGetClassObject@12
API _GetCurrentProcessExplicitAppUserModelID@4
API _GetDpiForMonitor@16
API _GetDpiForShellUIComponent@4
API _GetFeatureEnabledState@8
API _GetFeatureVariant@16
API _GetProcessDpiAwareness@8
API _GetProcessReference@4
API _GetScaleFactorForDevice@4
API _GetScaleFactorForMonitor@8
API _IStream_Copy@12
API _IStream_Read@12
API _IStream_ReadStr@8
API _IStream_Reset@4
API _IStream_Size@8
API _IStream_Write@12
API _IStream_WriteStr@8
API _IUnknown_AtomicRelease@4
API _IUnknown_GetSite@12
API _IUnknown_QueryService@16
API _IUnknown_Set@8
API _IUnknown_SetSite@8
API _IsOS@4
API _IsProcessInIsolatedContainer@4
API _IsProcessInWDAGContainer@8
API ?WilApiImpl_RecordFeatureError@details@wil@@YGXIPBUFEATURE_ERROR@@@Z ; -> RecordFeatureError
API _RecordFeatureUsage@16
API _RegisterScaleChangeEvent@8
API _RegisterScaleChangeNotifications@16
API _RevokeScaleChangeNotifications@8
API _SHAnsiToAnsi@12
API _SHAnsiToUnicode@12
API _SHCopyKeyA@16
API _SHCopyKeyW@16
API _SHCreateMemStream@8
API _SHCreateStreamOnFileA@12
API _SHCreateStreamOnFileEx@24
API _SHCreateStreamOnFileW@12
API _SHCreateThread@16
API _SHCreateThreadRef@8
API _SHCreateThreadWithHandle@20
API _SHDeleteEmptyKeyA@8
API _SHDeleteEmptyKeyW@8
API _SHDeleteKeyA@8
API _SHDeleteKeyW@8
API _SHDeleteValueA@12
API _SHDeleteValueW@12
API _SHEnumKeyExA@16
API _SHEnumKeyExW@16
API _SHEnumValueA@28
API _SHEnumValueW@28
API _SHGetThreadRef@4
API _SHGetValueA@24
API _SHGetValueW@24
API _SHOpenRegStream2A@16
API _SHOpenRegStream2W@16
API _SHOpenRegStreamA@16
API _SHOpenRegStreamW@16
API _SHQueryInfoKeyA@20
API _SHQueryInfoKeyW@20
API _SHQueryValueExA@24
API _SHQueryValueExW@24
API _SHRegDuplicateHKey@4
API _SHRegGetIntW@12
API _SHRegGetPathA@20
API _SHRegGetPathW@20
API _SHRegGetValueA@28
API _SHRegGetValueFromHKCUHKLM@24
API _SHRegGetValueW@28
API _SHRegSetPathA@20
API _SHRegSetPathW@20
API _SHReleaseThreadRef@0
API _SHSetThreadRef@4
API _SHSetValueA@24
API _SHSetValueW@24
API _SHStrDupA@8
API _SHStrDupW@8
API _SHTaskPoolAllowThreadReuse@0
API _SHTaskPoolDoNotWaitForMoreTasks@0
API _SHTaskPoolGetCurrentThreadLifetime@4
API _SHTaskPoolGetUniqueContext@0
API _SHTaskPoolQueueTask@24
API _SHTaskPoolSetThreadReuseAllowed@4
API _SHUnicodeToAnsi@12
API _SHUnicodeToUnicode@12
API _SetCurrentProcessExplicitAppUserModelID@4
API _SetProcessDpiAwareness@4
API _SetProcessReference@4
API _SubscribeFeatureStateChangeNotification@12
API _UnregisterScaleChangeEvent@4
API _UnsubscribeFeatureStateChangeNotification@4
API _SHCreateDirectory@8
API _SHCreateDirectoryExA@12
API _SHCreateDirectoryExW@12
API _IsNotifySuspended@0
API _ResumeSHNotify@0
API _SuspendSHNotify@0
API _Win32CreateDirectory@8
API __CreateDirectoryHelper@16
API _SHCreateMemoryStreamOnSharedBuffer@12
API _GetScaleFactorForCoreWindow@8
API _GetScaleFactorForMonitor_Uncached@8
API _GetLegacyModernScaleFactor@4
API _GetMonitorSizeOverride@4
API _RelativeRectFromPhysicalRectWithScales@16
API _PhysicalRectFromRelativeRectWithScales@16
API _GetCurrentWindow@4
API _AddCurrentWindowCandidate@4
API _UnregisterWindowMonitorChangeListener@8
API _UnregisterCurrentWindowChangeListener@4
API _RegisterWindowMonitorChangeListener@12
API _RegisterCurrentWindowChangeListener@8
API _UpdateScalingInfoCache@0
API _GetSystemScaleFactorForWindow@8
API _GetOverrideScaleFactorForWindow@8
API _RevokeScaleChangeNotificationsForWindow@8
API _RegisterScaleChangeNotificationsForWindow@16
API _GetScaleFactorForWindow@8
API _RelativeRectFromPhysicalRectWithScale@12
API _ScaleAndMapRelativeRect@12
API _RegisterScaleChangeSinkForWindow@12
API _SHRegisterClassW@4
API _SHDefSubclassProc@16
API _SHRemoveWindowSubclass@12
API _SHGetWindowSubclassData@16
API _SHSetWindowSubclass@16
API _GetProposedScaleFactorForWindow@12
API _SetDesignModeScaleFactor@8
API _ScaleAndMapRelativeRectForDevice@16
API _PhysicalRectFromScaledRect@12
API _ScaleRelativePixelsForDevice@8
API _GetPhysicalDpiForDevice@4
API _GUIDFromStringW@8
API _SHGetObjectCompatFlags@8
API _IsAppCompatModeEnabled@4
API _SHWindowsPolicyGetValue@12
API _SHWindowsPolicy@4
API _SHCreateOplockProvider@8
API _SHCreateWorkerWindowW@24
API _SHFreeShared@8
API _SHUnlockShared@4
API _SHGetSizeShared@4
API _SHLockShared@8
API _SHLockSharedEx@12
API _SHAllocShared@12
API _SHMapHandle@20
API _IsNetDrive@4
API _DriveType@4
API _PathBuildRootA@8
API _PathBuildRootW@8
API _PathIsNetworkPathA@4
API _PathIsNetworkPathW@4
API _SHQueueUserWorkItem@28
API _SHWaitForThreadWithWakeMask@12
API _SHWaitForSendMessageThread@8
API _SHAnsiToUnicodeCPAlloc@12
API _SHUnicodeToAnsiCPAlloc@12
API _SHUnicodeToAnsiCP@16
API _SHAnsiToUnicodeCP@16
API _StrRetToBufW@16
API _StrRetToBSTR@12
API _StrRetToStrW@12
API _IUnknown_GetClassID@8
API _IUnknown_RemoveBackReferences@4
API _IUnknown_ProfferService@16
API _SHGlobalCounterSetValue@8
API _SHGlobalCounterDecrement@4
API _SHGlobalCounterIncrement@4
API _SHGlobalCounterGetValue@4
API _QuerySourceCreateFromKeyEx@24
API _SHLoadRegUIStringW@16
API _SHGetValueGoodBootW@24
API _SHGetValueGoodBootA@24
API _SHRegGetBoolValueFromHKCUHKLM@12
API _SHRegSetValue@28
API _SHRegGetCLSIDKey@24
API _CreateRandomAccessStreamOnPlaceholderFile@36
API _RandomAccessStreamCopyAsync@28
API _CreateRandomAccessStreamOnFileWithOptions@16
API _CreateWritableSharedMemoryStream@12
API _SHCreateStreamOnDllResourceW@16
API _SHCreateStreamOnModuleResourceW@16
API _IStream_WriteStrLong@8
API _IStream_ReadStrLong@8
API _StreamCopyTo@24
API _CreateTempStreamName@16
API _ModeToCreateFileFlags@20
API _MapWin32ErrorToSTG@4
API _SHIsEmptyStream@4
API _SHManagedCreateFile@28
API _SHManagedCreateStreamOnFile@28
API _SHCreateReadOnlySharedMemoryStream@16

end
