API MACRO name
name proc
name endp
ENDM

.code

API ??0__non_rtti_object@@QEAA@AEBV0@@Z
API ??0__non_rtti_object@@QEAA@PEBD@Z
API ??0bad_cast@@AAE@PBQBD@Z
API ??0bad_cast@@AEAA@PEBQEBD@Z
API ??0bad_cast@@QAE@ABQBD@Z
API ??0bad_cast@@QEAA@AEBQEBD@Z
API ??0bad_cast@@QEAA@AEBV0@@Z
API ??0bad_cast@@QEAA@PEBD@Z
API ??0bad_typeid@@QEAA@AEBV0@@Z
API ??0bad_typeid@@QEAA@PEBD@Z
API ??0exception@@QEAA@AEBQEBD@Z
API ??0exception@@QEAA@AEBQEBDH@Z
API ??0exception@@QEAA@AEBV0@@Z
API ??0exception@@QEAA@XZ
API ??1__non_rtti_object@@UEAA@XZ
API ??1bad_cast@@UEAA@XZ
API ??1bad_typeid@@UEAA@XZ
API ??1exception@@UEAA@XZ
API ??1type_info@@UEAA@XZ
API ??2@YAPEAX_K@Z
API ??2@YAPEAX_KHPEBDH@Z
API ??3@YAXPEAX@Z
API ??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z
API ??4bad_cast@@QEAAAEAV0@AEBV0@@Z
API ??4bad_typeid@@QEAAAEAV0@AEBV0@@Z
API ??4exception@@QEAAAEAV0@AEBV0@@Z
API ??8type_info@@QEBAHAEBV0@@Z
API ??9type_info@@QEBAHAEBV0@@Z
API ??_7__non_rtti_object@@6B@
API ??_7bad_cast@@6B@
API ??_7bad_typeid@@6B@
API ??_7exception@@6B@
API ??_Fbad_cast@@QEAAXXZ
API ??_Fbad_typeid@@QEAAXXZ
API ??_U@YAPEAX_K@Z
API ??_U@YAPEAX_KHPEBDH@Z
API ??_V@YAXPEAX@Z
API ?_Doraise@bad_cast@@MEBAXXZ
API ?_Doraise@bad_typeid@@MEBAXXZ
API ?_inconsistency@@YAXXZ
API ?_is_exception_typeof@@YAHAEBVtype_info@@PEAU_EXCEPTION_POINTERS@@@Z
API ?_query_new_handler@@YAP6AH_K@ZXZ
API ?_query_new_mode@@YAHXZ
API ?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z
API ?_set_new_mode@@YAHH@Z
API ?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z
API ?before@type_info@@QEBAHAEBV1@@Z
API ?name@type_info@@QEBAPEBDPEAU__type_info_node@@@Z
API ?name@type_info@@QEBAPEBDXZ
API ?raw_name@type_info@@QEBAPEBDXZ
API ?set_new_handler@@YAP6AXXZP6AXXZ@Z
API ?set_terminate@@YAP6AXXZP6AXXZ@Z
API ?set_unexpected@@YAP6AXXZP6AXXZ@Z
API ?terminate@@YAXXZ
API ?unexpected@@YAXXZ
API ?what@exception@@UEBAPEBDXZ
API _CrtCheckMemory
API _fpclear
API _CrtDbgReport
API _CrtDbgReportV
API _CrtDbgReportW
API _CrtDbgReportWV
API _CrtDoForAllClientObjects
API _CrtDumpMemoryLeaks
API _CrtIsMemoryBlock
API _CrtIsValidHeapPointer
API _CrtIsValidPointer
API _CrtMemCheckpoint
API _CrtMemDifference
API _CrtMemDumpStatistics
API _CrtMemDumpStatistics
API _CrtReportBlockType
API _CrtSetAllocHook
API _CrtSetBreakAlloc
API _CrtSetDbgBlockType
API _CrtSetDbgFlag
API _CrtSetDumpClient
API _CrtSetReportFile
API _CrtSetReportHook
API _CrtSetReportHook2
API _CrtSetReportMode
API _CxxThrowException
API _Getdays
API _Getmonths
API _Gettnames
API _HUGE
API _Strftime
API _W_Getdays
API _W_Getmonths
API _W_Gettnames
API _Wcsftime
API _XcptFilter
API __AdjustPointer
API __BuildCatchObject
API __BuildCatchObjectHelper
API __C_specific_handler
API __CppXcptFilter_Export
API __CxxFrameHandler
API __CxxFrameHandler
API __CxxFrameHandler3
API __CxxFrameHandler4
API __DestructExceptionObject
API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z
API ?__ExceptionPtrCompare@@YA_NPEBX0@Z
API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z
API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z
API ?__ExceptionPtrCreate@@YAXPEAX@Z
API ?__ExceptionPtrCurrentException@@YAXPEAX@Z
API ?__ExceptionPtrDestroy@@YAXPEAX@Z
API ?__ExceptionPtrRethrow@@YAXPEBX@Z
API ?__ExceptionPtrSwap@@YAXPEAX0@Z
API ?__ExceptionPtrToBool@@YA_NPEBX@Z
API __RTCastToVoid
API __RTDynamicCast
API __RTtypeid
API __STRINGTOLD
API __TypeMatch
API ___lc_codepage_func
API ___lc_collate_cp_func
API ___lc_handle_func
API ___mb_cur_max_func
API ___setlc_active_func
API ___unguarded_readlc_active_add_func
API __argc
API __argv
API __badioinfo
API __crtCompareStringA
API __crtCompareStringW
API __crtGetLocaleInfoW
API __crtGetStringTypeW
API __crtLCMapStringA
API __crtLCMapStringW
API __daylight
API __dllonexit
API __doserrno
API __dstbias
API __fpecode
API __getmainargs
API __initenv
API __iob_func
API __isascii
API __iscsym
API __iscsymf
API __lc_codepage
API __lc_collate_cp
API __lc_handle
API __lconv_init
API __mb_cur_max
API __pctype_func
API __pioinfo
API __pwctype_func
API __pxcptinfoptrs
API __set_app_type
API __setlc_active
API __setusermatherr
API __strncnt
API __threadhandle
API __threadid
API __toascii
API __unDName
API __unDNameEx
API ?__uncaught_exception@@YA_NXZ
API __unguarded_readlc_active
API __wargv
API __wcserror
API __wcserror_s
API __wcsncnt
API __wgetmainargs
API __winitenv
API _abs64
API _access
API _access_s
API _acmdln
API _aexit_rtn
API _aligned_free
API _aligned_free_dbg
API _aligned_malloc
API _aligned_malloc_dbg
API _aligned_offset_malloc
API _aligned_offset_malloc_dbg
API _aligned_offset_realloc
API _aligned_offset_realloc_dbg
API _aligned_realloc
API _aligned_realloc_dbg
API _amsg_exit
API _assert
API _atodbl
API _atodbl_l
API _atof_l
API _atoflt_l
API _atoi64
API _atoi64_l
API _atoi_l
API _atol_l
API _atoldbl
API _atoldbl_l
API _beep
API _beginthread
API _beginthreadex
API _c_exit
API _cabs
API _callnewh
API _calloc_dbg
API _cexit
API _cgets
API _cgets_s
API _cgetws
API _cgetws_s
API _chdir
API _chdrive
API _chgsign
API _chgsignf
API _chmod
API _chsize
API _chsize_s
API _chvalidator
API _chvalidator_l
API _clearfp
API _close
API _commit
API _commode
API _control87
API _controlfp
API _controlfp_s
API _copysign
API _copysignf
API _cprintf
API _cprintf_l
API _cprintf_p
API _cprintf_p_l
API _cprintf_s
API _cprintf_s_l
API _cputs
API _cputws
API _creat
API _create_locale
API _crtAssertBusy
API _crtAssertBusy
API _crtDbgFlag
API _cscanf
API _cscanf_l
API _cscanf_s
API _cscanf_s_l
API _ctime32
API _ctime32_s
API _ctime64
API _ctime64_s
API _ctype
API _cwait
API _cwprintf
API _cwprintf_l
API _cwprintf_p
API _cwprintf_p_l
API _cwprintf_s
API _cwprintf_s_l
API _cwscanf
API _cwscanf_l
API _cwscanf_s
API _cwscanf_s_l
API _daylight
API _difftime32
API _difftime64
API _dstbias
API _dup
API _dup2
API _ecvt
API _ecvt_s
API _endthread
API _endthreadex
API _environ
API _eof
API _errno
API _execl
API _execle
API _execlp
API _execlpe
API _execv
API _execve
API _execvp
API _execvpe
API _exit
API _expand
API _expand_dbg
API _fcloseall
API _fcvt
API _fcvt_s
API _fdopen
API _fgetchar
API getwchar
API _filbuf
API _fileinfo
API _filelength
API _filelengthi64
API _fileno
API _findclose
API _findfirst
API _findfirst64
API _findfirsti64
API _findnext
API _findnext64
API _findnexti64
API _finite
API _finitef
API _flsbuf
API _flushall
API _fmode
API _fpclass
API _fpclassf
API _fpreset
API _fprintf_l
API _fprintf_p
API _fprintf_p_l
API _fprintf_s_l
API putchar
API putwchar
API _free_dbg
API _free_locale
API _freea
API _freea
API _freefls
API _fscanf_l
API _fscanf_s_l
API _fseeki64
API _fsopen
API _fstat
API _fstat64
API _fstati64
API _ftime
API _ftime32
API _ftime32_s
API _ftime64
API _ftime64_s
API _fullpath
API _fullpath_dbg
API _futime
API _futime32
API _futime64
API _fwprintf_l
API _fwprintf_p
API _fwprintf_p_l
API _fwprintf_s_l
API _fwscanf_l
API _fwscanf_s_l
API _gcvt
API _gcvt_s
API _get_current_locale
API _get_doserrno
API _get_environ
API _get_errno
API _get_fileinfo
API _get_fmode
API _get_heap_handle
API _get_osfhandle
API _get_osplatform
API _get_osver
API _get_output_format
API _get_pgmptr
API _get_sbh_threshold
API _get_terminate
API _get_unexpected
API _get_wenviron
API _get_winmajor
API _get_winminor
API _get_winver
API _get_wpgmptr
API _getch
API _getche
API _getcwd
API _getdcwd
API _getdiskfree
API _getdrive
API _getdrives
API _getmaxstdio
API _getmbcp
API _getpid
API _getsystime
API _getw
API _getwch
API _getwche
API _getws
API _gmtime32
API _gmtime32_s
API _gmtime64
API _gmtime64_s
API _heapchk
API _heapmin
API _heapset
API _heapwalk
API _hypot
API _hypotf
API _i64toa
API _i64toa_s
API _i64tow
API _i64tow_s
API _initterm
API _initterm_e
API _invalid_parameter
API _iob
API _isalnum_l
API _isalpha_l
API _isatty
API _iscntrl_l
API _isctype
API _isctype_l
API _isdigit_l
API _isgraph_l
API _isleadbyte_l
API _islower_l
API _ismbbalnum
API _ismbbalnum_l
API _ismbbalpha
API _ismbbalpha_l
API _ismbbgraph
API _ismbbgraph_l
API _ismbbkalnum
API _ismbbkalnum_l
API _ismbbkana
API _ismbbkana_l
API _ismbbkprint
API _ismbbkprint_l
API _ismbbkpunct
API _ismbbkpunct_l
API _ismbblead
API _ismbblead_l
API _ismbbprint
API _ismbbprint_l
API _ismbbpunct
API _ismbbpunct_l
API _ismbbtrail
API _ismbbtrail_l
API _ismbcalnum
API _ismbcalnum_l
API _ismbcalpha
API _ismbcalpha_l
API _ismbcdigit
API _ismbcdigit_l
API _ismbcgraph
API _ismbcgraph_l
API _ismbchira
API _ismbchira_l
API _ismbckata
API _ismbckata_l
API _ismbcl0
API _ismbcl0_l
API _ismbcl1
API _ismbcl1_l
API _ismbcl2
API _ismbcl2_l
API _ismbclegal
API _ismbclegal_l
API _ismbclower
API _ismbclower_l
API _ismbcprint
API _ismbcprint_l
API _ismbcpunct
API _ismbcpunct_l
API _ismbcspace
API _ismbcspace_l
API _ismbcsymbol
API _ismbcsymbol_l
API _ismbcupper
API _ismbcupper_l
API _ismbslead
API _ismbslead_l
API _ismbstrail
API _ismbstrail_l
API _isnan
API _isnanf
API _isprint_l
API _isspace_l
API _isupper_l
API _iswalnum_l
API _iswalpha_l
API _iswcntrl_l
API _iswctype_l
API _iswdigit_l
API _iswgraph_l
API _iswlower_l
API _iswprint_l
API _iswpunct_l
API _iswspace_l
API _iswupper_l
API _iswxdigit_l
API _isxdigit_l
API _itoa
API _itoa_s
API _itow
API _itow_s
API _j0
API _j1
API _jn
API _kbhit
API _lfind
API _lfind_s
API _local_unwind
API _localtime32
API _localtime32_s
API _localtime64
API _localtime64_s
API _lock
API _locking
API _logb
API _logbf
API _lrotl
API _lrotr
API _lsearch
API _lsearch_s
API _lseek
API _lseeki64
API _ltoa
API _ltoa_s
API _ltow
API _ltow_s
API _makepath
API _makepath_s
API _malloc_dbg
API _mbbtombc
API _mbbtombc_l
API _mbbtype
API _mbcasemap
API _mbccpy
API _mbccpy_l
API _mbccpy_s
API _mbccpy_s_l
API _mbcjistojms
API _mbcjistojms_l
API _mbcjmstojis
API _mbcjmstojis_l
API _mbclen
API _mbclen_l
API _mbctohira
API _mbctohira_l
API _mbctokata
API _mbctokata_l
API _mbctolower
API _mbctolower_l
API _mbctombb
API _mbctombb_l
API _mbctoupper
API _mbctoupper_l
API _mbctype
API _mblen_l
API _mbsbtype
API _mbsbtype_l
API strcat
API _mbscat_s
API _mbscat_s_l
API _mbschr
API _mbschr_l
API _mbscmp
API _mbscmp_l
API _mbscoll
API _mbscoll_l
API strcpy
API _mbscpy_s
API _mbscpy_s_l
API _mbscspn
API _mbscspn_l
API _mbsdec
API _mbsdec_l
API _strdup
API _mbsicmp
API _mbsicmp_l
API _mbsicoll
API _mbsicoll_l
API _mbsinc
API _mbsinc_l
API _mbslen
API _mbslen_l
API _mbslwr
API _mbslwr_l
API _mbslwr_s
API _mbslwr_s_l
API _mbsnbcat
API _mbsnbcat_l
API _mbsnbcat_s
API _mbsnbcat_s_l
API _mbsnbcmp
API _mbsnbcmp_l
API _mbsnbcnt
API _mbsnbcnt_l
API _mbsnbcoll
API _mbsnbcoll_l
API _mbsnbcpy
API _mbsnbcpy_l
API _mbsnbcpy_s
API _mbsnbcpy_s_l
API _mbsnbicmp
API _mbsnbicmp_l
API _mbsnbicoll
API _mbsnbicoll_l
API _mbsnbset
API _mbsnbset_l
API _mbsnbset_s
API _mbsnbset_s_l
API _mbsncat
API _mbsncat_l
API _mbsncat_s
API _mbsncat_s_l
API _mbsnccnt
API _mbsnccnt_l
API _mbsncmp
API _mbsncmp_l
API _mbsncoll
API _mbsncoll_l
API _mbsncpy
API _mbsncpy_l
API _mbsncpy_s
API _mbsncpy_s_l
API _mbsnextc
API _mbsnextc_l
API _mbsnicmp
API _mbsnicmp_l
API _mbsnicoll
API _mbsnicoll_l
API _mbsninc
API _mbsninc_l
API _mbsnlen
API _mbsnlen_l
API _mbsnset
API _mbsnset_l
API _mbsnset_s
API _mbsnset_s_l
API _mbspbrk
API _mbspbrk_l
API _mbsrchr
API _mbsrchr_l
API _mbsrev
API _mbsrev_l
API _mbsset
API _mbsset_l
API _mbsset_s
API _mbsset_s_l
API _mbsspn
API _mbsspn_l
API _mbsspnp
API _mbsspnp_l
API _mbsstr
API _mbsstr_l
API _mbstok
API _mbstok_l
API _mbstok_s
API _mbstok_s_l
API _mbstowcs_l
API _mbstowcs_s_l
API _mbstrlen
API _mbstrlen_l
API _mbstrnlen
API _mbstrnlen_l
API _mbsupr
API _mbsupr_l
API _mbsupr_s
API _mbsupr_s_l
API _mbtowc_l
API _memccpy
API _memicmp
API _memicmp_l
API _mkdir
API _mkgmtime
API _mkgmtime32
API _mkgmtime64
API _mktemp
API _mktemp_s
API _mktime32
API _mktime64
API _msize
API _msize_dbg
API _nextafter
API _nextafterf
API _onexit
API _open
API _open_osfhandle
API _osplatform
API _osver
API _pclose
API _pctype
API _pgmptr
API _pipe
API _popen
API _printf_l
API _printf_p
API _printf_p_l
API _printf_s_l
API _purecall
API _putch
API _putenv
API _putenv_s
API _putw
API _putwch
API _putws
API _pwctype
API _read
API _realloc_dbg
API _resetstkoflw
API _rmdir
API _rmtmp
API _rotl
API _rotl64
API _rotr
API _rotr64
API _scalb
API _scalbf
API _scanf_l
API _scanf_s_l
API _scprintf
API _scprintf_l
API _scprintf_p_l
API _scwprintf
API _scwprintf_l
API _scwprintf_p_l
API _searchenv
API _searchenv_s
API _set_controlfp
API _set_doserrno
API _set_errno
API _set_error_mode
API _set_fileinfo
API _set_fmode
API _set_output_format
API _set_sbh_threshold
API _seterrormode
API _setjmp
API _setjmpex
API _setmaxstdio
API _setmbcp
API _setmode
API _setsystime
API _sleep
API _snprintf
API _snprintf_c
API _snprintf_c_l
API _snprintf_l
API _snprintf_s
API _snprintf_s_l
API _snscanf
API _snscanf_l
API _snscanf_s
API _snscanf_s_l
API _snwprintf
API _snwprintf_l
API _snwprintf_s
API _snwprintf_s_l
API _snwscanf
API _snwscanf_l
API _snwscanf_s
API _snwscanf_s_l
API _sopen
API _sopen_s
API _spawnl
API _spawnle
API _spawnlp
API _spawnlpe
API _spawnv
API _spawnve
API _spawnvp
API _spawnvpe
API _splitpath
API _splitpath_s
API _sprintf_l
API _sprintf_p_l
API _sprintf_s_l
API _sscanf_l
API _sscanf_s_l
API _stat
API _stat64
API _stati64
API _statusfp
API _stricmp
API _strcoll_l
API _strdate
API _strdate_s
API _strdup
API _strdup_dbg
API _strerror
API _strerror_s
API _stricmp
API _stricmp_l
API _stricoll
API _stricoll_l
API _strlwr
API _strlwr_l
API _strlwr_s
API _strlwr_s_l
API _strncoll
API _strncoll_l
API _strnicmp
API _strnicmp_l
API _strnicoll
API _strnicoll_l
API _strnset
API _strnset_s
API _strrev
API _strset
API _strset_s
API _strtime
API _strtime_s
API _strtod_l
API _strtoi64
API _strtoi64_l
API _strtol_l
API _strtoui64
API _strtoui64_l
API _strtoul_l
API _strupr
API _strupr_l
API _strupr_s
API _strupr_s_l
API _strxfrm_l
API _swab
API _swprintf
API _swprintf_c
API _swprintf_c_l
API _swprintf_p_l
API _swprintf_s_l
API _swscanf_l
API _swscanf_s_l
API _sys_errlist
API _sys_nerr
API _tell
API _telli64
API _tempnam
API _tempnam_dbg
API _time32
API _time64
API _timezone
API _tolower
API _tolower_l
API _toupper
API _toupper_l
API _towlower_l
API _towupper_l
API _tzname
API _tzset
API _ui64toa
API _ui64toa_s
API _ui64tow
API _ui64tow_s
API _ultoa
API _ultoa_s
API _ultow
API _ultow_s
API _umask
API _umask_s
API _ungetc_nolock
API _ungetch
API _ungetwch
API _unlink
API _unlock
API _utime
API _utime32
API _utime64
API _vcprintf
API _vcprintf_l
API _vcprintf_p
API _vcprintf_p_l
API _vcprintf_s
API _vcprintf_s_l
API _vcwprintf
API _vcwprintf_l
API _vcwprintf_p
API _vcwprintf_p_l
API _vcwprintf_s
API _vcwprintf_s_l
API _vfprintf_l
API _vfprintf_p
API _vfprintf_p_l
API _vfprintf_s_l
API _vfwprintf_l
API _vfwprintf_p
API _vfwprintf_p_l
API _vfwprintf_s_l
API _vprintf_l
API _vprintf_p
API _vprintf_p_l
API _vprintf_s_l
API _vscprintf
API _vscprintf_l
API _vscprintf_p_l
API _vscwprintf
API _vscwprintf_l
API _vscwprintf_p_l
API _vsnprintf
API _vsnprintf_c
API _vsnprintf_c_l
API _vsnprintf_l
API _vsnprintf_s
API _vsnprintf_s_l
API _vsnwprintf
API _vsnwprintf_l
API _vsnwprintf_s
API _vsnwprintf_s_l
API _vsprintf_l
API _vsprintf_p
API _vsprintf_p_l
API _vsprintf_s_l
API _vswprintf
API _vswprintf_c
API _vswprintf_c_l
API _vswprintf_l
API _vswprintf_p_l
API _vswprintf_s_l
API _vwprintf_l
API _vwprintf_p
API _vwprintf_p_l
API _vwprintf_s_l
API _waccess
API _waccess_s
API _wasctime
API _wasctime_s
API _wassert
API _wchdir
API _wchmod
API _wcmdln
API _wcreat
API _wcscoll_l
API _wcsdup
API _wcsdup_dbg
API _wcserror
API _wcserror_s
API _wcsftime_l
API _wcsicmp
API _wcsicmp_l
API _wcsicoll
API _wcsicoll_l
API _wcslwr
API _wcslwr_l
API _wcslwr_s
API _wcslwr_s_l
API _wcsncoll
API _wcsncoll_l
API _wcsnicmp
API _wcsnicmp_l
API _wcsnicoll
API _wcsnicoll_l
API _wcsnset
API _wcsnset_s
API _wcsrev
API _wcsset
API _wcsset_s
API _wcstod_l
API _wcstoi64
API _wcstoi64_l
API _wcstol_l
API _wcstombs_l
API _wcstombs_s_l
API _wcstoui64
API _wcstoui64_l
API _wcstoul_l
API _wcsupr
API _wcsupr_l
API _wcsupr_s
API _wcsupr_s_l
API _wcsxfrm_l
API _wctime
API _wctime32
API _wctime32_s
API _wctime64
API _wctime64_s
API _wctomb_l
API _wctomb_s_l
API _wctype
API _wenviron
API _wexecl
API _wexecle
API _wexeclp
API _wexeclpe
API _wexecv
API _wexecve
API _wexecvp
API _wexecvpe
API _wfdopen
API _wfindfirst
API _wfindfirst64
API _wfindfirsti64
API _wfindnext
API _wfindnext64
API _wfindnexti64
API _wfopen
API _wfopen_s
API _wfreopen
API _wfreopen_s
API _wfsopen
API _wfullpath
API _wfullpath_dbg
API _wgetcwd
API _wgetdcwd
API _wgetenv
API _wgetenv_s
API _winmajor
API _winminor
API _winput_s
API _winver
API _wmakepath
API _wmakepath_s
API _wmkdir
API _wmktemp
API _wmktemp_s
API _wopen
API _woutput_s
API _wperror
API _wpgmptr
API _wpopen
API _wprintf_l
API _wprintf_p
API _wprintf_p_l
API _wprintf_s_l
API _wputenv
API _wputenv_s
API _wremove
API _wrename
API _write
API _wrmdir
API _wscanf_l
API _wscanf_s_l
API _wsearchenv
API _wsearchenv_s
API _wsetlocale
API _wsopen
API _wsopen_s
API _wspawnl
API _wspawnle
API _wspawnlp
API _wspawnlpe
API _wspawnv
API _wspawnve
API _wspawnvp
API _wspawnvpe
API _wsplitpath
API _wsplitpath_s
API _wstat
API _wstat64
API _wstati64
API _wstrdate
API _wstrdate_s
API _wstrtime
API _wstrtime_s
API _wsystem
API _wtempnam
API _wtempnam_dbg
API _wtmpnam
API _wtmpnam_s
API _wtof
API _wtof_l
API _wtoi
API _wtoi64
API _wtoi64_l
API _wtoi_l
API _wtol
API _wtol_l
API _wunlink
API _wutime
API _wutime32
API _wutime64
API _y0
API _y1
API _yn
API abort
API abs
API acos
API acosf
API asctime
API asctime_s
API asin
API asinf
API atan
API atan2
API atan2f
API atanf
API atexit
API atof
API atoi
API atol
API bsearch
API bsearch_s
API btowc
API calloc
API ceil
API ceilf
API clearerr
API clearerr_s
API clock
API cos
API cosf
API cosh
API coshf
API ctime
API difftime
API $div
API exit
API exp
API expf
API $fabs
API fclose
API feof
API ferror
API fflush
API getc
API fgetpos
API fgets
API fgetwc
API fgetws
API floor
API floorf
API fmod
API fmodf
API fopen
API fopen_s
API fprintf
API fprintf_s
API fputc
API fputs
API fputwc
API fputws
API fread
API free
API freopen
API freopen_s
API frexp
API fscanf
API fscanf_s
API fseek
API fsetpos
API ftell
API fwprintf
API fwprintf_s
API fwrite
API fwscanf
API fwscanf_s
API getc
API _fgetchar
API getenv
API getenv_s
API gets
API getwc
API getwchar
API gmtime
API is_wctype
API isalnum
API isalpha
API iscntrl
API isdigit
API isgraph
API isleadbyte
API islower
API isprint
API ispunct
API isspace
API isupper
API iswalnum
API iswalpha
API iswascii
API iswcntrl
API iswctype
API iswdigit
API iswgraph
API iswlower
API iswprint
API iswpunct
API iswspace
API iswupper
API iswxdigit
API isxdigit
API labs
API ldexp
API ldiv
API localeconv
API localtime
API log
API log10
API log10f
API logf
API longjmp
API malloc
API mblen
API mbrlen
API mbrtowc
API _strdup_dbg
API mbsrtowcs
API mbsrtowcs_s
API mbstowcs
API mbstowcs_s
API mbtowc
API memchr
API memcmp
API memmove
API memcpy_s
API memmove
API memmove_s
API memset$thunk$772440563353939046
API mktime
API modf
API modff
API perror
API pow
API powf
API printf
API printf_s
API fputc
API putchar
API puts
API putwc
API putwchar
API qsort
API qsort_s
API raise
API rand
API rand_s
API realloc
API remove
API rename
API rewind
API scanf
API scanf_s
API setbuf
API setjmp
API setlocale
API setvbuf
API signal
API sin
API sinf
API sinh
API sinhf
API sprintf
API sprintf_s
API sqrt
API sqrtf
API srand
API sscanf
API sscanf_s
API strcat
API strcat_s
API strchr
API strcmp
API strcoll
API strcpy
API strcpy_s
API strcspn
API strerror
API strerror_s
API strftime
API strlen
API strncat
API strncat_s
API strncmp
API strncpy
API strncpy_s
API strnlen
API strpbrk
API strrchr
API strspn
API strstr
API strtod
API strtok
API strtok_s
API strtol
API strtoul
API strxfrm
API _swprintf
API swprintf_s
API swscanf
API swscanf_s
API system
API tan
API tanf
API tanh
API tanhf
API time
API tmpfile
API tmpfile_s
API tmpnam
API tmpnam_s
API tolower
API toupper
API towlower
API towupper
API ungetc
API ungetwc
API utime
API vfprintf
API vfprintf_s
API vfwprintf
API vfwprintf_s
API vprintf
API vprintf_s
API _vsnprintf
API vsprintf
API vsprintf_s
API _vswprintf
API vswprintf_s
API vwprintf
API vwprintf_s
API wcrtomb
API wcrtomb_s
API wcscat
API wcscat_s
API wcschr
API wcscmp
API wcscoll
API wcscpy
API wcscpy_s
API wcscspn
API wcsftime
API wcslen
API wcsncat
API wcsncat_s
API wcsncmp
API wcsncpy
API wcsncpy_s
API wcsnlen
API wcspbrk
API wcsrchr
API wcsrtombs
API wcsrtombs_s
API wcsspn
API wcsstr
API wcstod
API wcstok
API wcstok_s
API wcstol
API wcstombs
API wcstombs_s
API wcstoul
API wcsxfrm
API wctob
API wctomb
API wctomb_s
API wprintf
API wprintf_s
API wscanf
API wscanf_s

end
