.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _$I10_OUTPUT
API ??0__non_rtti_object@@QAE@ABV0@@Z
API ??0__non_rtti_object@@QAE@PBD@Z
API ??0bad_cast@@AAE@PBQBD@Z
API ??0bad_cast@@QAE@ABQBD@Z
API ??0bad_cast@@QAE@ABV0@@Z
API ??0bad_cast@@QAE@PBD@Z
API ??0bad_typeid@@QAE@ABV0@@Z
API ??0bad_typeid@@QAE@PBD@Z
API ??0exception@@QAE@ABQBD@Z
API ??0exception@@QAE@ABQBDH@Z
API ??0exception@@QAE@ABV0@@Z
API ??0exception@@QAE@XZ
API ??1__non_rtti_object@@UAE@XZ
API ??1bad_cast@@UAE@XZ
API ??1bad_typeid@@UAE@XZ
API ??1exception@@UAE@XZ
API ??1type_info@@UAE@XZ
API ??2@YAPAXI@Z
API ??2@YAPAXIHPBDH@Z
API ??3@YAXPAX@Z
API ??4__non_rtti_object@@QAEAAV0@ABV0@@Z
API ??4bad_cast@@QAEAAV0@ABV0@@Z
API ??4bad_typeid@@QAEAAV0@ABV0@@Z
API ??4exception@@QAEAAV0@ABV0@@Z
API ??8type_info@@QBEHABV0@@Z
API ??9type_info@@QBEHABV0@@Z
API ??_7__non_rtti_object@@6B@
API ??_7bad_cast@@6B@
API ??_7bad_typeid@@6B@
API ??_7exception@@6B@
API ??_E__non_rtti_object@@UAEPAXI@Z
API ??_Ebad_cast@@UAEPAXI@Z
API ??_Ebad_typeid@@UAEPAXI@Z
API ??_Eexception@@UAEPAXI@Z
API ??_Fbad_cast@@QAEXXZ
API ??_Fbad_typeid@@QAEXXZ
API ??_G__non_rtti_object@@UAEPAXI@Z
API ??_Gbad_cast@@UAEPAXI@Z
API ??_Gbad_typeid@@UAEPAXI@Z
API ??_Gexception@@UAEPAXI@Z
API ??_U@YAPAXI@Z
API ??_U@YAPAXIHPBDH@Z
API ??_V@YAXPAX@Z
API ?_Doraise@bad_cast@@MBEXXZ
API ?_Doraise@bad_typeid@@MBEXXZ
API ?_inconsistency@@YAXXZ
API ?_is_exception_typeof@@YAHABVtype_info@@PAU_EXCEPTION_POINTERS@@@Z
API ?_query_new_handler@@YAP6AHI@ZXZ
API ?_query_new_mode@@YAHXZ
API ?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z
API ?_set_new_mode@@YAHH@Z
API ?_set_se_translator@@YAP6AXIPAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z
API ?before@type_info@@QBEHABV1@@Z
API ?name@type_info@@QBEPBDPAU__type_info_node@@@Z
API ?name@type_info@@QBEPBDXZ
API ?raw_name@type_info@@QBEPBDXZ
API ?set_new_handler@@YAP6AXXZP6AXXZ@Z
API ?set_terminate@@YAP6AXXZP6AXXZ@Z
API ?set_unexpected@@YAP6AXXZP6AXXZ@Z
API ?terminate@@YAXXZ
API ?unexpected@@YAXXZ
API ?what@exception@@UBEPBDXZ
API __CIacos
API __CIasin
API __CIatan
API __CIatan2
API __CIcos
API __CIcosh
API __CIexp
API __CIfmod
API __CIlog
API __CIlog10
API __CIpow
API __CIsin
API __CIsinh
API __CIsqrt
API __CItan
API __CItanh
API ?_CallMemberFunction0@@YGXQAX0@Z
API ?_CallMemberFunction1@@YGXQAX00@Z
API ?_CallMemberFunction2@@YGXQAX00H@Z
API ?length@charNode@@UBEHXZ
API __CrtDoForAllClientObjects
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __CrtDoForAllClientObjects
API __crtBreakAlloc
API __crtBreakAlloc
API ?length@charNode@@UBEHXZ
API ?_ValidateRead@@YAHPBXI@Z
API __CrtDoForAllClientObjects
API __crtBreakAlloc
API __CrtDoForAllClientObjects
API __CrtDoForAllClientObjects
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __CrtDoForAllClientObjects
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __CxxThrowException@8
API __EH_prolog
API __Getdays
API __Getmonths
API __Gettnames
API __HUGE
API __Strftime
API __W_Getdays
API __W_Getmonths
API __W_Gettnames
API __Wcsftime
API __XcptFilter
API ___AdjustPointer
API ___BuildCatchObject
API ___BuildCatchObjectHelper
API ___CppXcptFilter_Export
API ___CxxCallUnwindDelDtor
API ___CxxCallUnwindDtor
API ___CxxCallUnwindVecDtor
API ___CxxDetectRethrow
API ___CxxExceptionFilter
API ___CxxFrameHandler3
API ___CxxFrameHandler3
API ___CxxFrameHandler3
API ___CxxLongjmpUnwind@4
API ___CxxQueryExceptionSize
API ___CxxRegisterExceptionObject
API ___CxxUnregisterExceptionObject
API ___DestructExceptionObject
API ?__ExceptionPtrAssign@@YAXPAXPBX@Z
API ?__ExceptionPtrCompare@@YA_NPBX0@Z
API ?__ExceptionPtrCopy@@YAXPAXPBX@Z
API ?__ExceptionPtrCopyException@@YAXPAXPBX1@Z
API ?__ExceptionPtrCreate@@YAXPAX@Z
API ?__ExceptionPtrCurrentException@@YAXPAX@Z
API ?__ExceptionPtrDestroy@@YAXPAX@Z
API ?__ExceptionPtrRethrow@@YAXPBX@Z
API ?__ExceptionPtrSwap@@YAXPAX0@Z
API ?__ExceptionPtrToBool@@YA_NPBX@Z
API ___RTCastToVoid
API ___RTDynamicCast
API ___RTtypeid
API ___STRINGTOLD
API ___TypeMatch
API ____lc_codepage_func
API ____lc_collate_cp_func
API ____lc_handle_func
API ____mb_cur_max_func
API ____setlc_active_func
API ____unguarded_readlc_active_add_func
API __argc
API __argv
API ___badioinfo
API ___crtCompareStringA
API ___crtCompareStringW
API ___crtGetLocaleInfoW
API ___crtGetStringTypeW
API ___crtLCMapStringA
API ___crtLCMapStringW
API ___p__daylight
API ___dllonexit
API ___doserrno
API ___dstbias
API ___fpecode
API __freefls@4
API ___getmainargs
API __initenv
API ___p__iob
API ___isascii
API ___iscsym
API ___iscsymf
API ___lc_codepage
API ___lc_collate_cp
API ___lc_handle
API ___lconv_init
API ___libm_sse2_acos
API ___libm_sse2_acosf
API ___libm_sse2_asin
API ___libm_sse2_asinf
API ___libm_sse2_atan
API ___libm_sse2_atan2
API ___libm_sse2_atanf
API ___libm_sse2_cos
API ___libm_sse2_cosf
API ___libm_sse2_exp
API ___libm_sse2_expf
API ___libm_sse2_log
API ___libm_sse2_log10
API ___libm_sse2_log10f
API ___libm_sse2_logf
API ___libm_sse2_pow
API ___libm_sse2_powf
API ___libm_sse2_sin
API ___libm_sse2_sinf
API ___libm_sse2_tan
API ___libm_sse2_tanf
API ___mb_cur_max
API ___p___argc
API ___p___argv
API ___p___initenv
API ___p___mb_cur_max
API ___p___wargv
API ___p___winitenv
API ___p__acmdln
API ___p__amblksiz
API ___p__commode
API ___p__daylight
API ___dstbias
API ___p__environ
API ___p__fileinfo
API ___p__fmode
API ___p__iob
API ___p__mbcasemap
API ___p__mbctype
API ___p__osver
API ___p__pctype
API ___p__pgmptr
API ___p__pwctype
API ___p__timezone
API ___p__tzname
API ___p__wcmdln
API ___p__wenviron
API ___p__winmajor
API ___p__winminor
API ___p__winver
API ___p__wpgmptr
API ___pctype_func
API __pioinfo
API ___pwctype_func
API ___pxcptinfoptrs
API ___set_app_type
API __setlc_active
API ___setusermatherr
API ___strncnt
API ___threadhandle
API ___threadid
API ___toascii
API ___unDName
API ___unDNameEx
API ?__uncaught_exception@@YA_NXZ
API __unguarded_readlc_active
API __wargv
API ___wcserror
API ___wcserror_s
API ___wcsncnt
API ___wgetmainargs
API __winitenv
API __abnormal_termination
API __abs64
API __access
API __access_s
API __acmdln
API __adj_fdiv_m16i
API __adj_fdiv_m32
API __adj_fdiv_m32i
API __adj_fdiv_m64
API __adj_fdiv_r
API __adj_fdivr_m16i
API __adj_fdivr_m32
API __adj_fdivr_m32i
API __adj_fdivr_m64
API __adj_fpatan
API __adj_fprem
API __adj_fprem1
API __adj_fptan
API _adjust_fdiv
API __aexit_rtn
API __aligned_free
API __aligned_free_dbg
API __aligned_malloc_dbg
API __aligned_malloc_dbg
API __aligned_offset_malloc
API __aligned_offset_malloc_dbg
API __aligned_offset_realloc
API __aligned_offset_realloc_dbg
API __aligned_realloc
API __aligned_realloc
API __amsg_exit
API __assert
API __atodbl
API __atodbl_l
API __atof_l
API __atoflt_l
API __atoi64
API __atoi64_l
API __atoi_l
API __atol_l
API __atoldbl
API __atoldbl_l
API __beep
API __beginthread
API __beginthreadex
API __c_exit
API __cabs
API __callnewh
API __calloc_dbg
API __cexit
API __cgets
API __cgets_s
API __cgetws
API __cgetws_s
API __chdir
API __chdrive
API __chgsign
API __chkesp
API __chmod
API __chsize
API __chsize_s
API __chvalidator
API __chvalidator_l
API __clearfp
API __close
API __commit
API _commode
API __control87
API __controlfp
API __controlfp_s
API __copysign
API __cprintf
API __cprintf_l
API __cprintf_p
API __cprintf_p_l
API __cprintf_s
API __cprintf_s_l
API __cputs
API __cputws
API __creat
API __create_locale
API __crtBreakAlloc
API __crtBreakAlloc
API __crtBreakAlloc
API __cscanf
API __cscanf_l
API __cscanf_s
API __cscanf_s_l
API __ctime32
API __ctime32_s
API __ctime64
API __ctime64_s
API __ctype
API __cwait
API __cwprintf
API __cwprintf_l
API __cwprintf_p
API __cwprintf_p_l
API __cwprintf_s
API __cwprintf_s_l
API __cwscanf
API __cwscanf_l
API __cwscanf_s
API __cwscanf_s_l
API __daylight
API __difftime32
API __difftime64
API __dstbias
API __dup
API __dup2
API __ecvt
API __ecvt_s
API __endthread
API __endthreadex
API _environ
API __eof
API __errno
API __except_handler2
API __except_handler3
API __except_handler4_common
API __execl
API __execle
API __execlp
API __execlpe
API __execv
API __execve
API __execvp
API __execvpe
API __exit
API __expand
API __expand_dbg
API __fcloseall
API __fcvt
API __fcvt_s
API __fdopen
API __fgetchar
API _getwchar
API __filbuf
API __fileinfo
API __filelength
API __filelengthi64
API __fileno
API __findclose
API __findfirst
API __findfirst64
API __findfirsti64
API __findnext
API __findnext64
API __findnexti64
API __finite
API __flsbuf
API __flushall
API __fmode
API __fpclass
API __fpieee_flt
API __fpreset
API __fprintf_l
API __fprintf_p
API __fprintf_p_l
API __fprintf_s_l
API __fputchar
API __fputwchar
API __free_dbg
API __free_locale
API __freea
API __freea
API __fscanf_l
API __fscanf_s_l
API __fseeki64
API __fsopen
API __fstat
API __fstat64
API __fstati64
API __ftime
API __ftime
API __ftime32_s
API __ftime64
API __ftime64_s
API __ftol
API __ftol2
API __ftol2_sse
API __ftol2_sse_excpt
API __fullpath
API __fullpath_dbg
API __futime
API __futime32
API __futime64
API __fwprintf_l
API __fwprintf_p
API __fwprintf_p_l
API __fwprintf_s_l
API __fwscanf_l
API __fwscanf_s_l
API __gcvt
API __gcvt_s
API __get_current_locale
API __get_doserrno
API __get_environ
API __get_errno
API __get_fileinfo
API __get_fmode
API __get_heap_handle
API __get_osfhandle
API __get_osplatform
API __get_osver
API __get_output_format
API __get_pgmptr
API __get_sbh_threshold
API __get_terminate
API __get_unexpected
API __get_wenviron
API __get_winmajor
API __get_winminor
API __get_winver
API __get_wpgmptr
API __getch
API __getche
API __getcwd
API __getdcwd
API __getdiskfree
API __getdllprocaddr
API __getdrive
API __getdrives
API __getmaxstdio
API __getmbcp
API __getpid
API __getsystime
API __getw
API __getwch
API __getwche
API __getws
API __global_unwind2
API __gmtime32
API __gmtime32_s
API __gmtime64
API __gmtime64_s
API __heapadd
API __heapchk
API __heapmin
API __heapset
API __heapused
API __heapwalk
API __hypot
API __i64toa
API __i64toa_s
API __i64tow
API __i64tow_s
API __initterm
API __initterm_e
API __inp
API __inpd
API __inpw
API __invalid_parameter
API __iob
API __isalnum_l
API __isalpha_l
API __isatty
API __iscntrl_l
API __isctype
API __isctype_l
API __isdigit_l
API __isgraph_l
API __isleadbyte_l
API __islower_l
API __ismbbalnum
API __ismbbalnum_l
API __ismbbalpha
API __ismbbalpha_l
API __ismbbgraph
API __ismbbgraph_l
API __ismbbkalnum
API __ismbbkalnum_l
API __ismbbkana
API __ismbbkana_l
API __ismbbkprint
API __ismbbkprint_l
API __ismbbkpunct
API __ismbbkpunct_l
API __ismbblead
API __ismbblead_l
API __ismbbprint
API __ismbbprint_l
API __ismbbpunct
API __ismbbpunct_l
API __ismbbtrail
API __ismbbtrail_l
API __ismbcalnum
API __ismbcalnum_l
API __ismbcalpha
API __ismbcalpha_l
API __ismbcdigit
API __ismbcdigit_l
API __ismbcgraph
API __ismbcgraph_l
API __ismbchira
API __ismbchira_l
API __ismbckata
API __ismbckata_l
API __ismbcl0
API __ismbcl0_l
API __ismbcl1
API __ismbcl1_l
API __ismbcl2
API __ismbcl2_l
API __ismbclegal
API __ismbclegal_l
API __ismbclower
API __ismbclower_l
API __ismbcprint
API __ismbcprint_l
API __ismbcpunct
API __ismbcpunct_l
API __ismbcspace
API __ismbcspace_l
API __ismbcsymbol
API __ismbcsymbol_l
API __ismbcupper
API __ismbcupper_l
API __ismbslead
API __ismbslead_l
API __ismbstrail
API __ismbstrail_l
API __isnan
API __isprint_l
API __isspace_l
API __isupper_l
API __iswalnum_l
API __iswalpha_l
API __iswcntrl_l
API __iswctype_l
API __iswdigit_l
API __iswgraph_l
API __iswlower_l
API __iswprint_l
API __iswpunct_l
API __iswspace_l
API __iswupper_l
API __iswxdigit_l
API __isxdigit_l
API __ltoa
API __itoa_s
API __itow
API __ltow_s
API __j0
API __j1
API __jn
API __kbhit
API __lfind
API __lfind_s
API __libm_sse2_acos_precise
API __libm_sse2_asin_precise
API __libm_sse2_atan_precise
API __libm_sse2_cos_precise
API __libm_sse2_exp_precise
API __libm_sse2_log10_precise
API __libm_sse2_log_precise
API __libm_sse2_pow_precise
API __libm_sse2_sin_precise
API __libm_sse2_sqrt_precise
API __libm_sse2_tan_precise
API __loaddll
API __local_unwind2
API __local_unwind4
API __localtime32
API __localtime32_s
API __localtime64
API __localtime64_s
API __lock
API __locking
API __logb
API __longjmpex
API __lrotl
API __lrotr
API __lsearch
API __lsearch_s
API __lseek
API __lseeki64
API __ltoa
API __itoa_s
API __itow
API __ltow_s
API __makepath
API __makepath_s
API __malloc_dbg
API __mbbtombc
API __mbbtombc_l
API __mbbtype
API __mbcasemap
API __mbccpy
API __mbccpy_l
API __mbccpy_s
API __mbccpy_s_l
API __mbcjistojms
API __mbcjistojms_l
API __mbcjmstojis
API __mbcjmstojis_l
API __mbclen
API __mbclen_l
API __mbctohira
API __mbctohira_l
API __mbctokata
API __mbctokata_l
API __mbctolower
API __mbctolower_l
API __mbctombb
API __mbctombb_l
API __mbctoupper
API __mbctoupper_l
API __mbctype
API __mblen_l
API __mbsbtype
API __mbsbtype_l
API _strcat
API __mbscat_s
API __mbscat_s_l
API __mbschr
API __mbschr_l
API __mbscmp
API __mbscmp_l
API __mbscoll
API __mbscoll_l
API _strcpy
API __mbscpy_s
API __mbscpy_s_l
API __mbscspn
API __mbscspn_l
API __mbsdec
API __mbsdec_l
API __strdup
API __mbsicmp
API __mbsicmp_l
API __mbsicoll
API __mbsicoll_l
API __mbsinc
API __mbsinc_l
API __mbslen
API __mbslen_l
API __mbslwr
API __mbslwr_l
API __mbslwr_s
API __mbslwr_s_l
API __mbsnbcat
API __mbsnbcat_l
API __mbsnbcat_s
API __mbsnbcat_s_l
API __mbsnbcmp
API __mbsnbcmp_l
API __mbsnbcnt
API __mbsnbcnt_l
API __mbsnbcoll
API __mbsnbcoll_l
API __mbsnbcpy
API __mbsnbcpy_l
API __mbsnbcpy_s
API __mbsnbcpy_s_l
API __mbsnbicmp
API __mbsnbicmp_l
API __mbsnbicoll
API __mbsnbicoll_l
API __mbsnbset
API __mbsnbset_l
API __mbsnbset_s
API __mbsnbset_s_l
API __mbsncat
API __mbsncat_l
API __mbsncat_s
API __mbsncat_s_l
API __mbsnccnt
API __mbsnccnt_l
API __mbsncmp
API __mbsncmp_l
API __mbsncoll
API __mbsncoll_l
API __mbsncpy
API __mbsncpy_l
API __mbsncpy_s
API __mbsncpy_s_l
API __mbsnextc
API __mbsnextc_l
API __mbsnicmp
API __mbsnicmp_l
API __mbsnicoll
API __mbsnicoll_l
API __mbsninc
API __mbsninc_l
API __mbsnlen
API __mbsnlen_l
API __mbsnset
API __mbsnset_l
API __mbsnset_s
API __mbsnset_s_l
API __mbspbrk
API __mbspbrk_l
API __mbsrchr
API __mbsrchr_l
API __mbsrev
API __mbsrev_l
API __mbsset
API __mbsset_l
API __mbsset_s
API __mbsset_s_l
API __mbsspn
API __mbsspn_l
API __mbsspnp
API __mbsspnp_l
API __mbsstr
API __mbsstr_l
API __mbstok
API __mbstok_l
API __mbstok_s
API __mbstok_s_l
API __mbstowcs_l
API __mbstowcs_s_l
API __mbstrlen
API __mbstrlen_l
API __mbstrnlen
API __mbstrnlen_l
API __mbsupr
API __mbsupr_l
API __mbsupr_s
API __mbsupr_s_l
API __mbtowc_l
API __memccpy
API __memicmp
API __memicmp_l
API __mkdir
API __mkgmtime
API __mkgmtime32
API __mkgmtime64
API __mktemp
API __mktemp_s
API __mktime32
API __mktime64
API __msize
API __msize_dbg
API __nextafter
API __onexit
API __open
API __open_osfhandle
API _osplatform
API _osver
API __outp
API __outpd
API __outpw
API __pclose
API __pctype
API _pgmptr
API __pipe
API __popen
API __printf_l
API __printf_p
API __printf_p_l
API __printf_s_l
API __purecall
API __putch
API __putenv
API __putenv_s
API __putw
API __putwch
API __putws
API __pwctype
API __read
API __realloc_dbg
API __resetstkoflw
API __rmdir
API __rmtmp
API __lrotl
API __rotl64
API __lrotr
API __rotr64
API __safe_fdiv
API __safe_fdivr
API __safe_fprem
API __safe_fprem1
API __scalb
API __scanf_l
API __scanf_s_l
API __scprintf
API __scprintf_l
API __scprintf_p_l
API __scwprintf
API __scwprintf_l
API __scwprintf_p_l
API __searchenv
API __searchenv_s
API __seh_longjmp_unwind@4
API __seh_longjmp_unwind4@4
API __set_SSE2_enable
API __set_controlfp
API __set_doserrno
API __set_errno
API __set_error_mode
API __set_fileinfo
API __set_fmode
API __set_output_format
API __set_sbh_threshold
API __seterrormode
API __setjmp
API __setjmp3
API __setmaxstdio
API __setmbcp
API __setmode
API __setsystime
API __sleep
API __snprintf
API __snprintf_c
API __snprintf_c_l
API __snprintf_l
API __snprintf_s
API __snprintf_s_l
API __snscanf
API __snscanf_l
API __snscanf_s
API __snscanf_s_l
API __snwprintf
API __snwprintf_l
API __snwprintf_s
API __snwprintf_s_l
API __snwscanf
API __snwscanf_l
API __snwscanf_s
API __snwscanf_s_l
API __sopen
API __sopen_s
API __spawnl
API __spawnle
API __spawnlp
API __spawnlpe
API __spawnv
API __spawnve
API __spawnvp
API __spawnvpe
API __splitpath
API __splitpath_s
API __sprintf_l
API __sprintf_p_l
API __sprintf_s_l
API __sscanf_l
API __sscanf_s_l
API __stat
API __stat64
API __stati64
API __statusfp
API __stricmp
API __strcoll_l
API __strdate
API __strdate_s
API __strdup
API __strdup_dbg
API __strerror
API __strerror_s
API __stricmp
API __stricmp_l
API __stricoll
API __stricoll_l
API __strlwr
API __strlwr_l
API __strlwr_s
API __strlwr_s_l
API __strncoll
API __strncoll_l
API __strnicmp
API __strnicmp_l
API __strnicoll
API __strnicoll_l
API __strnset
API __strnset_s
API __strrev
API __strset
API __strset_s
API __strtime
API __strtime_s
API __strtod_l
API __strtoi64
API __strtoi64_l
API __strtol_l
API __strtoui64
API __strtoui64_l
API __strtoul_l
API __strupr
API __strupr_l
API __strupr_s
API __strupr_s_l
API __strxfrm_l
API __swab
API __swprintf
API __swprintf_c
API __swprintf_c_l
API __swprintf_p_l
API __swprintf_s_l
API __swscanf_l
API __swscanf_s_l
API __sys_errlist
API __sys_nerr
API __tell
API __telli64
API __tempnam
API __tempnam_dbg
API __time32
API __time64
API __timezone
API __tolower
API __tolower_l
API __toupper
API __toupper_l
API __towlower_l
API __towupper_l
API __tzname
API __tzset
API __ui64toa
API __ui64toa_s
API __ui64tow
API __ui64tow_s
API __ultoa
API __ultoa_s
API __ultow
API __ultow_s
API __umask
API __umask_s
API __ungetch
API __ungetwch
API __unlink
API __unloaddll
API __unlock
API _utime
API __utime32
API __utime64
API __vcprintf
API __vcprintf_l
API __vcprintf_p
API __vcprintf_p_l
API __vcprintf_s
API __vcprintf_s_l
API __vcwprintf
API __vcwprintf_l
API __vcwprintf_p
API __vcwprintf_p_l
API __vcwprintf_s
API __vcwprintf_s_l
API __vfprintf_l
API __vfprintf_p
API __vfprintf_p_l
API __vfprintf_s_l
API __vfwprintf_l
API __vfwprintf_p
API __vfwprintf_p_l
API __vfwprintf_s_l
API __vprintf_l
API __vprintf_p
API __vprintf_p_l
API __vprintf_s_l
API __vscprintf
API __vscprintf_l
API __vscprintf_p_l
API __vscwprintf
API __vscwprintf_l
API __vscwprintf_p_l
API __vsnprintf
API __vsnprintf_c
API __vsnprintf_c_l
API __vsnprintf_l
API __vsnprintf_s
API __vsnprintf_s_l
API __vsnwprintf
API __vsnwprintf_l
API __vsnwprintf_s
API __vsnwprintf_s_l
API __vsprintf_l
API __vsprintf_p
API __vsprintf_p_l
API __vsprintf_s_l
API _vswprintf
API __vswprintf_c
API __vswprintf_c_l
API __vswprintf_l
API __vswprintf_p_l
API __vswprintf_s_l
API __vwprintf_l
API __vwprintf_p
API __vwprintf_p_l
API __vwprintf_s_l
API __waccess
API __waccess_s
API __wasctime
API __wasctime_s
API __wassert
API __wchdir
API __wchmod
API __wcmdln
API __wcreat
API __wcscoll_l
API __wcsdup
API __wcsdup_dbg
API __wcserror
API __wcserror_s
API __wcsftime_l
API __wcsicmp
API __wcsicmp_l
API __wcsicoll
API __wcsicoll_l
API __wcslwr
API __wcslwr_l
API __wcslwr_s
API __wcslwr_s_l
API __wcsncoll
API __wcsncoll_l
API __wcsnicmp
API __wcsnicmp_l
API __wcsnicoll
API __wcsnicoll_l
API __wcsnset
API __wcsnset_s
API __wcsrev
API __wcsset
API __wcsset_s
API __wcstod_l
API __wcstoi64
API __wcstoi64_l
API __wcstol_l
API __wcstombs_l
API __wcstombs_s_l
API __wcstoui64
API __wcstoui64_l
API __wcstoul_l
API __wcsupr
API __wcsupr_l
API __wcsupr_s
API __wcsupr_s_l
API __wcsxfrm_l
API __wctime
API __wctime32
API __wctime32_s
API __wctime64
API __wctime64_s
API __wctomb_l
API __wctomb_s_l
API __wctype
API _wenviron
API __wexecl
API __wexecle
API __wexeclp
API __wexeclpe
API __wexecv
API __wexecve
API __wexecvp
API __wexecvpe
API __wfdopen
API __wfindfirst
API __wfindfirst64
API __wfindfirsti64
API __wfindnext
API __wfindnext64
API __wfindnexti64
API __wfopen
API __wfopen_s
API __wfreopen
API __wfreopen_s
API __wfsopen
API __wfullpath
API __wfullpath_dbg
API __wgetcwd
API __wgetdcwd
API __wgetenv
API __wgetenv_s
API _winmajor
API _winminor
API __winput_s
API _winver
API __wmakepath
API __wmakepath_s
API __wmkdir
API __wmktemp
API __wmktemp_s
API __wopen
API __woutput_s
API __wperror
API _wpgmptr
API __wpopen
API __wprintf_l
API __wprintf_p
API __wprintf_p_l
API __wprintf_s_l
API __wputenv
API __wputenv_s
API __wremove
API __wrename
API __write
API __wrmdir
API __wscanf_l
API __wscanf_s_l
API __wsearchenv
API __wsearchenv_s
API __wsetlocale
API __wsopen
API __wsopen_s
API __wspawnl
API __wspawnle
API __wspawnlp
API __wspawnlpe
API __wspawnv
API __wspawnve
API __wspawnvp
API __wspawnvpe
API __wsplitpath
API __wsplitpath_s
API __wstat
API __wstat64
API __wstati64
API __wstrdate
API __wstrdate_s
API __wstrtime
API __wstrtime_s
API __wsystem
API __wtempnam
API __wtempnam_dbg
API __wtmpnam
API __wtmpnam_s
API __wtof
API __wtof_l
API __wtoi
API __wtoi64
API __wtoi64_l
API __wtoi_l
API __wtol
API __wtol_l
API __wunlink
API __wutime
API __wutime32
API __wutime64
API __y0
API __y1
API __yn
API _abort
API _abs
API _acos
API _asctime
API _asctime_s
API _asin
API _atan
API _atan2
API _atexit
API _atof
API _atoi
API _atol
API _bsearch
API _bsearch_s
API _btowc
API _calloc
API _ceil
API _clearerr
API _clearerr_s
API _clock
API _cos
API _cosh
API _ctime
API _difftime
API _div
API _exit
API _exp
API _fabs
API _fclose
API _feof
API _ferror
API _fflush
API _getc
API _fgetpos
API _fgets
API _fgetwc
API _fgetws
API _floor
API _fmod
API _fopen
API _fopen_s
API _fprintf
API _fprintf_s
API _fputc
API _fputs
API _fputwc
API _fputws
API _fread
API _free
API _freopen
API _freopen_s
API _frexp
API _fscanf
API _fscanf_s
API _fseek
API _fsetpos
API _ftell
API _fwprintf
API _fwprintf_s
API _fwrite
API _fwscanf
API _fwscanf_s
API _getc
API __fgetchar
API _getenv
API _getenv_s
API _gets
API _getwc
API _getwchar
API _gmtime
API _is_wctype
API _isalnum
API _isalpha
API _iscntrl
API _isdigit
API _isgraph
API _isleadbyte
API _islower
API _isprint
API _ispunct
API _isspace
API _isupper
API _iswalnum
API _iswalpha
API _iswascii
API _iswcntrl
API _iswctype
API _iswdigit
API _iswgraph
API _iswlower
API _iswprint
API _iswpunct
API _iswspace
API _iswupper
API _iswxdigit
API _isxdigit
API _abs
API _ldexp
API _div
API _localeconv
API _localtime
API _log
API _log10
API _longjmp
API _malloc
API _mblen
API _mbrlen
API _mbrtowc
API __strdup_dbg
API _mbsrtowcs
API _mbsrtowcs_s
API _mbstowcs
API _mbstowcs_s
API _mbtowc
API _memchr
API _memcmp
API _memcpy
API _memcpy_s
API _memmove
API _memmove_s
API _memset
API _mktime
API _modf
API _perror
API _pow
API _printf
API _printf_s
API _fputc
API _putchar
API _puts
API _putwc
API _putwchar
API _qsort
API _qsort_s
API _raise
API _rand
API _rand_s
API _realloc
API _remove
API _rename
API _rewind
API _scanf
API _scanf_s
API _setbuf
API _setlocale
API _setvbuf
API _signal
API _sin
API _sinh
API _sprintf
API _sprintf_s
API _sqrt
API _srand
API _sscanf
API _sscanf_s
API _strcat
API _strcat_s
API _strchr
API _strcmp
API _strcoll
API _strcpy
API _strcpy_s
API _strcspn
API _strerror
API _strerror_s
API _strftime
API _strlen
API _strncat
API _strncat_s
API _strncmp
API _strncpy
API _strncpy_s
API _strnlen
API _strpbrk
API _strrchr
API _strspn
API _strstr
API _strtod
API _strtok
API _strtok_s
API _strtol
API _strtoul
API _strxfrm
API __swprintf
API _swprintf_s
API _swscanf
API _swscanf_s
API _system
API _tan
API _tanh
API _time
API _tmpfile
API _tmpfile_s
API _tmpnam
API _tmpnam_s
API _tolower
API _toupper
API _towlower
API _towupper
API _ungetc
API _ungetwc
API _utime
API _vfprintf
API _vfprintf_s
API _vfwprintf
API _vfwprintf_s
API _vprintf
API _vprintf_s
API __vsnprintf
API _vsprintf
API _vsprintf_s
API _vswprintf
API _vswprintf_s
API _vwprintf
API _vwprintf_s
API _wcrtomb
API _wcrtomb_s
API _wcscat
API _wcscat_s
API _wcschr
API _wcscmp
API _wcscoll
API _wcscpy
API _wcscpy_s
API _wcscspn
API _wcsftime
API _wcslen
API _wcsncat
API _wcsncat_s
API _wcsncmp
API _wcsncpy
API _wcsncpy_s
API _wcsnlen
API _wcspbrk
API _wcsrchr
API _wcsrtombs
API _wcsrtombs_s
API _wcsspn
API _wcsstr
API _wcstod
API _wcstok
API _wcstok_s
API _wcstol
API _wcstombs
API _wcstombs_s
API _wcstoul
API _wcsxfrm
API _wctob
API _wctomb
API _wctomb_s
API _wprintf
API _wprintf_s
API _wscanf
API _wscanf_s

end
