.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _AbortDoc@4
API _AbortPath@4
API _AddFontMemResourceEx@16
API _AddFontResourceAStub@4
API _AddFontResourceExA@12
API _AddFontResourceExW@12
API _AddFontResourceTracking@8
API _AddFontResourceW@4
API _AngleArc@24
API _AnimatePaletteStub@16
API _AnyLinkedFonts@0
API _ArcStub@36
API _ArcTo@36
API _NtGdiBRUSHOBJ_hGetColorTransform@4
API _NtGdiBRUSHOBJ_pvAllocRbrush@8
API _NtGdiBRUSHOBJ_pvGetRbrush@4
API _NtGdiBRUSHOBJ_ulGetBrushColor@4
API _NtGdiBeginGdiRendering@12
API _BeginPath@4
API _BitBltStub@36
API _NtGdiCLIPOBJ_bEnum@12
API _NtGdiCLIPOBJ_cEnumStart@20
API _NtGdiCLIPOBJ_ppoGetPath@4
API _CancelDC@4
API _CheckColorsInGamut@16
API _ChoosePixelFormat@8
API _Chord@36
API _ClearBitmapAttributes@8
API _ClearBrushAttributes@8
API _CloseEnhMetaFileStub@4
API _CloseFigure@4
API _CloseMetaFileStub@4
API _ColorCorrectPalette@16
API _ColorMatchToTarget@12
API _CombineRgn@16
API _CombineTransform@12
API _NtGdiConfigureOPMProtectedOutput@16
API _CopyEnhMetaFileA@8
API _CopyEnhMetaFileW@8
API _CopyMetaFileA@8
API _CopyMetaFileW@8
API _CreateBitmapStub@20
API _NtGdiCreateBitmapFromDxSurface@20
API _NtGdiCreateBitmapFromDxSurface2@28
API _CreateBitmapIndirectStub@4
API _CreateBrushIndirectStub@4
API _CreateColorSpaceA@4
API _CreateColorSpaceW@4
API _CreateCompatibleBitmapStub@12
API _CreateCompatibleDCStub@4
API _CreateDCA@16
API _CreateDCExW@20
API _CreateDCW@16
API _CreateDIBPatternBrush@8
API _CreateDIBPatternBrushPt@8
API _CreateDIBSectionStub@24
API _CreateDIBitmapStub@24
API _CreateDPIScaledDIBSection@28
API _CreateDiscardableBitmap@12
API _CreateEllipticRgn@16
API _CreateEllipticRgnIndirectStub@4
API _CreateEnhMetaFileAStub@16
API _CreateEnhMetaFileW@16
API _CreateFontAStub@56
API _CreateFontIndirectAStub@4
API _CreateFontIndirectExA@4
API _CreateFontIndirectExW@4
API _CreateFontIndirectW@4
API _CreateFontWStub@56
API _CreateHalftonePalette@4
API _CreateHatchBrush@8
API _CreateICA@16
API _CreateICW@16
API _CreateMetaFileAStub@4
API _CreateMetaFileW@4
API _NtGdiCreateOPMProtectedOutput@8
API _NtGdiCreateOPMProtectedOutputs@20
API _CreatePaletteStub@4
API _CreatePatternBrushStub@4
API _CreatePenStub@12
API _CreatePenIndirectStub@4
API _CreatePolyPolygonRgnStub@16
API _CreatePolygonRgn@12
API _CreateRectRgn@16
API _CreateRectRgnIndirect@4
API _CreateRoundRectRgnStub@24
API _CreateScalableFontResourceA@16
API _CreateScalableFontResourceW@16
API _CreateScaledCompatibleBitmap@16
API _CreateSessionMappedDIBSection@20
API _CreateSolidBrushStub@4
API D3DKMTAbandonSwapChain
API D3DKMTAcquireKeyedMutex
API D3DKMTAcquireKeyedMutex2
API D3DKMTAcquireSwapChain
API D3DKMTAddSurfaceToSwapChain
API D3DKMTAdjustFullscreenGamma
API D3DKMTCacheHybridQueryValue
API D3DKMTCancelPresents
API D3DKMTChangeVideoMemoryReservation
API D3DKMTCheckExclusiveOwnership
API D3DKMTCheckMonitorPowerState
API D3DKMTCheckMultiPlaneOverlaySupport
API D3DKMTCheckMultiPlaneOverlaySupport2
API D3DKMTCheckMultiPlaneOverlaySupport3
API D3DKMTCheckOcclusion
API D3DKMTCheckSharedResourceAccess
API D3DKMTCheckSinglePlaneForMultiPlaneOverlaySupport
API D3DKMTCheckVidPnExclusiveOwnership
API D3DKMTCloseAdapter
API D3DKMTConfigureSharedResource
API D3DKMTConnectDoorbell
API D3DKMTCreateAllocation
API D3DKMTCreateAllocation2
API D3DKMTCreateBundleObject
API D3DKMTCreateContext
API D3DKMTCreateContextVirtual
API _NtGdiDdDDICreateDCFromMemory@4
API D3DKMTCreateDevice
API D3DKMTCreateDoorbell
API D3DKMTCreateHwContext
API D3DKMTCreateHwQueue
API D3DKMTCreateKeyedMutex
API D3DKMTCreateKeyedMutex2
API D3DKMTCreateNativeFence
API D3DKMTCreateOutputDupl
API D3DKMTCreateOverlay
API D3DKMTCreatePagingQueue
API D3DKMTCreateProtectedSession
API D3DKMTCreateSwapChain
API D3DKMTCreateSynchronizationObject
API D3DKMTCreateSynchronizationObject2
API D3DKMTCreateTrackedWorkload
API D3DKMTDDisplayEnum
API D3DKMTDestroyAllocation
API D3DKMTDestroyAllocation2
API D3DKMTDestroyContext
API _NtGdiDdDDIDestroyDCFromMemory@4
API D3DKMTDestroyDevice
API D3DKMTDestroyDoorbell
API D3DKMTDestroyHwContext
API D3DKMTDestroyHwQueue
API D3DKMTDestroyKeyedMutex
API D3DKMTDestroyOutputDupl
API D3DKMTDestroyOverlay
API D3DKMTDestroyPagingQueue
API D3DKMTDestroyProtectedSession
API D3DKMTDestroySynchronizationObject
API D3DKMTDestroyTrackedWorkload
API D3DKMTDispMgrCreate
API D3DKMTDispMgrOperation
API D3DKMTDispMgrSourceOperation
API D3DKMTDispMgrTargetOperation
API D3DKMTDisplayMuxSwitchExecute
API D3DKMTDisplayMuxSwitchFinish
API D3DKMTDisplayMuxSwitchPrepare
API D3DKMTDisplayPortOperation
API D3DKMTDuplicateHandle
API D3DKMTEnumAdapters
API D3DKMTEnumAdapters2
API D3DKMTEnumAdapters3
API D3DKMTEnumProcesses
API D3DKMTEscape
API D3DKMTEvict
API D3DKMTExtractBundleObject
API D3DKMTFlipOverlay
API D3DKMTFlushHeapTransitions
API D3DKMTFreeGpuVirtualAddress
API D3DKMTGetAllocationPriority
API D3DKMTGetAvailableTrackedWorkloadIndex
API D3DKMTGetCachedHybridQueryValue
API D3DKMTGetContextInProcessSchedulingPriority
API D3DKMTGetContextSchedulingPriority
API D3DKMTGetDWMVerticalBlankEvent
API D3DKMTGetDeviceState
API D3DKMTGetDisplayModeList
API D3DKMTGetMemoryBudgetTarget
API D3DKMTGetMultiPlaneOverlayCaps
API D3DKMTGetMultisampleMethodList
API D3DKMTGetNativeFenceLogDetail
API D3DKMTGetOverlayState
API D3DKMTGetPostCompositionCaps
API D3DKMTGetPresentHistory
API D3DKMTGetPresentQueueEvent
API D3DKMTGetProcessDeviceRemovalSupport
API D3DKMTGetProcessList
API D3DKMTGetProcessSchedulingPriorityBand
API D3DKMTGetProcessSchedulingPriorityClass
API D3DKMTGetProperties
API D3DKMTGetResourcePresentPrivateDriverData
API D3DKMTGetRuntimeData
API D3DKMTGetScanLine
API D3DKMTGetSetSwapChainMetadata
API D3DKMTGetSharedPrimaryHandle
API D3DKMTGetSharedResourceAdapterLuid
API D3DKMTGetSwapChainSurfacePhysicalAddress
API D3DKMTGetTrackedWorkloadStatistics
API D3DKMTGetYieldPercentage
API D3DKMTInvalidateActiveVidPn
API D3DKMTInvalidateCache
API D3DKMTIsFeatureEnabled
API D3DKMTLock
API D3DKMTLock2
API D3DKMTMakeResident
API D3DKMTMapGpuVirtualAddress
API D3DKMTMarkDeviceAsError
API D3DKMTNetDispGetNextChunkInfo
API D3DKMTNetDispQueryMiracastDisplayDeviceStatus
API D3DKMTNetDispQueryMiracastDisplayDeviceSupport
API D3DKMTNetDispStartMiracastDisplayDevice
API D3DKMTNetDispStartMiracastDisplayDevice2
API D3DKMTNetDispStartMiracastDisplayDeviceEx
API D3DKMTNetDispStopMiracastDisplayDevice
API D3DKMTNotifyWorkSubmission
API D3DKMTOfferAllocations
API D3DKMTOpenAdapterFromDeviceName
API _D3DKMTOpenAdapterFromGdiDisplayName@4
API _D3DKMTOpenAdapterFromHdc@4
API D3DKMTOpenAdapterFromLuid
API D3DKMTOpenBundleObjectNtHandleFromName
API D3DKMTOpenKeyedMutex
API D3DKMTOpenKeyedMutex2
API D3DKMTOpenKeyedMutexFromNtHandle
API D3DKMTOpenNativeFenceFromNtHandle
API D3DKMTOpenNtHandleFromName
API D3DKMTOpenProtectedSessionFromNtHandle
API D3DKMTOpenResource
API D3DKMTOpenResource2
API D3DKMTOpenResourceFromNtHandle
API D3DKMTOpenSwapChain
API D3DKMTOpenSyncObjectFromNtHandle
API D3DKMTOpenSyncObjectFromNtHandle2
API D3DKMTOpenSyncObjectNtHandleFromName
API D3DKMTOpenSynchronizationObject
API D3DKMTOutputDuplGetFrameInfo
API D3DKMTOutputDuplGetMetaData
API D3DKMTOutputDuplGetPointerShapeData
API D3DKMTOutputDuplPresent
API D3DKMTOutputDuplPresentToHwQueue
API D3DKMTOutputDuplReleaseFrame
API D3DKMTPinDirectFlipResources
API D3DKMTPinResources
API D3DKMTPollDisplayChildren
API D3DKMTPresent
API D3DKMTPresentMultiPlaneOverlay
API D3DKMTPresentMultiPlaneOverlay2
API D3DKMTPresentMultiPlaneOverlay3
API D3DKMTPresentRedirected
API D3DKMTQueryAdapterInfo
API D3DKMTQueryAllocationResidency
API D3DKMTQueryClockCalibration
API D3DKMTQueryFSEBlock
API D3DKMTQueryProcessOfferInfo
API D3DKMTQueryProtectedSessionInfoFromNtHandle
API D3DKMTQueryProtectedSessionStatus
API _NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName@4
API D3DKMTQueryResourceInfo
API D3DKMTQueryResourceInfoFromNtHandle
API D3DKMTQueryStatistics
API D3DKMTQueryVidPnExclusiveOwnership
API D3DKMTQueryVideoMemoryInfo
API D3DKMTReclaimAllocations
API D3DKMTReclaimAllocations2
API D3DKMTRegisterTrimNotification
API D3DKMTRegisterVailProcess
API D3DKMTReleaseKeyedMutex
API D3DKMTReleaseKeyedMutex2
API D3DKMTReleaseProcessVidPnSourceOwners
API D3DKMTReleaseSwapChain
API D3DKMTRemoveSurfaceFromSwapChain
API D3DKMTRender
API D3DKMTReserveGpuVirtualAddress
API D3DKMTResetTrackedWorkloadStatistics
API D3DKMTSetAllocationPriority
API D3DKMTSetContextInProcessSchedulingPriority
API D3DKMTSetContextSchedulingPriority
API D3DKMTSetDisplayMode
API D3DKMTSetDisplayPrivateDriverFormat
API D3DKMTSetDodIndirectSwapchain
API D3DKMTSetFSEBlock
API D3DKMTSetGammaRamp
API D3DKMTSetHwProtectionTeardownRecovery
API D3DKMTSetMemoryBudgetTarget
API D3DKMTSetMonitorColorSpaceTransform
API D3DKMTSetProcessDeviceRemovalSupport
API D3DKMTSetProcessSchedulingPriorityBand
API D3DKMTSetProcessSchedulingPriorityClass
API D3DKMTSetProperties
API D3DKMTSetQueuedLimit
API D3DKMTSetStablePowerState
API D3DKMTSetStereoEnabled
API D3DKMTSetSyncRefreshCountWaitTarget
API D3DKMTSetVidPnSourceHwProtection
API D3DKMTSetVidPnSourceOwner
API D3DKMTSetVidPnSourceOwner1
API D3DKMTSetVidPnSourceOwner2
API D3DKMTSetYieldPercentage
API D3DKMTShareObjects
API D3DKMTSharedPrimaryLockNotification
API D3DKMTSharedPrimaryUnLockNotification
API D3DKMTSignalSynchronizationObject
API D3DKMTSignalSynchronizationObject2
API D3DKMTSignalSynchronizationObjectFromCpu
API D3DKMTSignalSynchronizationObjectFromGpu
API D3DKMTSignalSynchronizationObjectFromGpu2
API D3DKMTSubmitCommand
API D3DKMTSubmitCommandToHwQueue
API D3DKMTSubmitPresentBltToHwQueue
API D3DKMTSubmitPresentToHwQueue
API D3DKMTSubmitSignalSyncObjectsToHwQueue
API D3DKMTSubmitWaitForSyncObjectsToHwQueue
API D3DKMTTrimProcessCommitment
API D3DKMTUnOrderedPresentSwapChain
API D3DKMTUnlock
API D3DKMTUnlock2
API D3DKMTUnpinDirectFlipResources
API D3DKMTUnpinResources
API D3DKMTUnregisterTrimNotification
API D3DKMTUpdateAllocationProperty
API D3DKMTUpdateGpuVirtualAddress
API D3DKMTUpdateOverlay
API D3DKMTUpdateTrackedWorkload
API D3DKMTVailConnect
API D3DKMTVailDisconnect
API D3DKMTVailPromoteCompositionSurface
API D3DKMTWaitForIdle
API D3DKMTWaitForSynchronizationObject
API D3DKMTWaitForSynchronizationObject2
API D3DKMTWaitForSynchronizationObjectFromCpu
API D3DKMTWaitForSynchronizationObjectFromGpu
API D3DKMTWaitForVerticalBlankEvent
API D3DKMTWaitForVerticalBlankEvent2
API _NtGdiDDCCIGetCapabilitiesString@12
API _NtGdiDDCCIGetCapabilitiesStringLength@8
API _NtGdiDDCCIGetTimingReport@8
API _NtGdiDDCCIGetVCPFeature@20
API _NtGdiDDCCISaveCurrentSettings@4
API _NtGdiDDCCISetVCPFeature@12
API _DPtoLPStub@12
API _NtGdiDdCreateFullscreenSprite@16
API _NtGdiDdDestroyFullscreenSprite@8
API _NtGdiDxgGenericThunk@24
API _NtGdiD3dContextCreate@16
API _NtGdiDdBeginMoCompFrame@8
API _NtGdiDdBlt@12
API _NtGdiDdCanCreateSurface@8
API _NtGdiDdCanCreateD3DBuffer@8
API _NtGdiDdColorControl@8
API _NtGdiDdCreateDirectDrawObject@4
API _NtGdiDdCreateSurface@32
API _NtGdiDdCreateD3DBuffer@32
API _NtGdiDdCreateMoComp@8
API _NtGdiDdCreateSurfaceObject@24
API _NtGdiD3dContextDestroy@4
API _NtGdiDdDeleteDirectDrawObject@4
API _NtGdiDdDeleteSurfaceObject@4
API _NtGdiDdDestroyMoComp@8
API _NtGdiDdDestroySurface@8
API _NtGdiDdDestroyD3DBuffer@4
API _NtGdiDdEndMoCompFrame@8
API _NtGdiDdFlip@20
API _NtGdiDdFlipToGDISurface@8
API _NtGdiDdGetAvailDriverMemory@8
API _NtGdiDdGetBltStatus@8
API _NtGdiD3dContextDestroyAll@4
API _NtGdiDdGetDC@8
API _NtGdiDdGetDriverInfo@8
API _NtGdiDdGetDxHandle@12
API _NtGdiDdGetFlipStatus@8
API _NtGdiDdGetInternalMoCompInfo@8
API _NtGdiDdGetMoCompBuffInfo@8
API _NtGdiDdGetMoCompGuids@8
API _NtGdiDdGetMoCompFormats@8
API _NtGdiDdGetScanLine@8
API _NtGdiDdLock@12
API _NtGdiD3dValidateTextureStageState@4
API _NtGdiDdLockD3D@8
API _NtGdiDdQueryDirectDrawObject@44
API _NtGdiDdQueryMoCompStatus@8
API _NtGdiDdReenableDirectDrawObject@8
API _NtGdiDdReleaseDC@4
API _NtGdiDdRenderMoComp@8
API _NtGdiDdResetVisrgn@8
API _NtGdiDdSetColorKey@8
API _NtGdiDdSetExclusiveMode@8
API _NtGdiDdSetGammaRamp@12
API _NtGdiD3dDrawPrimitives2@28
API _NtGdiDdCreateSurfaceEx@12
API _NtGdiDdSetOverlayPosition@12
API _NtGdiDdUnattachSurface@8
API _NtGdiDdUnlock@8
API _NtGdiDdUnlockD3D@8
API _NtGdiDdUpdateOverlay@12
API _NtGdiDdWaitForVerticalBlank@8
API _NtGdiDdGetDriverState@4
API _NtGdiDdAddAttachedSurface@12
API _NtGdiDdAlphaBlt@12
API _NtGdiDdAttachSurface@8
API _NtGdiDdNotifyFullscreenSpriteUpdate@8
API _NtGdiDdQueryVisRgnUniqueness@0
API _DeleteColorSpace@4
API _DeleteDC@4
API _DeleteEnhMetaFileStub@4
API _DeleteMetaFileStub@4
API _DeleteObject@4
API _DescribePixelFormat@16
API _NtGdiDestroyOPMProtectedOutput@4
API _NtGdiDestroyPhysicalMonitor@4
API _DeviceCapabilitiesExA@24
API DeviceCapabilitiesExW
API _DrawEscape@16
API _DwmCreatedBitmapRemotingOutput@0
API _EllipseStub@20
API _NtGdiEnableEudc@4
API _EndDoc@4
API _EndFormPage@4
API _NtGdiEndGdiRendering@16
API _EndPage@4
API _EndPath@4
API _EngAcquireSemaphore@4
API _NtGdiEngAlphaBlend@28
API _NtGdiEngAssociateSurface@12
API _NtGdiEngBitBlt@44
API _NtGdiEngCheckAbort@4
API _EngComputeGlyphSet@12
API _NtGdiEngCopyBits@24
API _EngCreateBitmap@24
API _NtGdiEngCreateClip@0
API _EngCreateDeviceBitmap@16
API _EngCreateDeviceSurface@16
API _EngCreatePalette@24
API _EngCreateSemaphore@0
API _NtGdiEngDeleteClip@4
API _EngDeletePalette@4
API _NtGdiEngDeletePath@4
API _EngDeleteSemaphore@4
API _EngDeleteSurface@4
API _NtGdiEngEraseSurface@12
API _NtGdiEngFillPath@28
API _EngFindResource@16
API _EngFreeModule@4
API _EngGetCurrentCodePage@8
API _EngGetDriverName@4
API _EngGetPrinterDataFileName@4
API _NtGdiEngGradientFill@40
API _NtGdiEngLineTo@36
API _EngLoadModule@4
API _NtGdiEngLockSurface@4
API _NtGdiEngMarkBandingSurface@4
API _EngMultiByteToUnicodeN@20
API _EngMultiByteToWideChar@20
API _NtGdiEngPaint@20
API _NtGdiEngPlgBlt@44
API _EngQueryEMFInfo@8
API _EngQueryLocalTime@4
API _EngReleaseSemaphore@4
API _NtGdiEngStretchBlt@44
API _NtGdiEngStretchBltROP@52
API _NtGdiEngStrokeAndFillPath@40
API _NtGdiEngStrokePath@32
API _NtGdiEngTextOut@40
API _NtGdiEngTransparentBlt@32
API _EngUnicodeToMultiByteN@20
API _NtGdiEngUnlockSurface@4
API _EngWideCharToMultiByte@20
API _EnumEnhMetaFileStub@20
API _EnumFontFamiliesAStub@16
API _EnumFontFamiliesExAStub@20
API _EnumFontFamiliesExW@20
API _EnumFontFamiliesW@16
API _EnumFontsA@16
API _EnumFontsW@16
API _EnumICMProfilesA@12
API _EnumICMProfilesW@12
API _EnumMetaFileStub@16
API _EnumObjects@16
API _EqualRgn@8
API _Escape@20
API _EudcLoadLinkW@16
API _EudcUnloadLinkW@8
API _ExcludeClipRect@20
API _ExtCreatePen@20
API _ExtCreateRegion@12
API _ExtEscape@24
API _ExtFloodFill@20
API _ExtSelectClipRgn@12
API _ExtTextOutA@32
API _ExtTextOutW@32
API _NtGdiFONTOBJ_cGetAllGlyphHandles@8
API _NtGdiFONTOBJ_cGetGlyphs@20
API _NtGdiFONTOBJ_pQueryGlyphAttrs@8
API _NtGdiFONTOBJ_pfdg@4
API _NtGdiFONTOBJ_pifi@4
API _NtGdiFONTOBJ_pvTrueTypeFontFile@8
API _NtGdiFONTOBJ_pxoGetXform@4
API _NtGdiFONTOBJ_vGetInfo@12
API _FillPath@4
API _FillRgnStub@12
API _FixBrushOrgEx@16
API _FlattenPath@4
API _FloodFill@16
API _FontIsLinked@4
API _FrameRgnStub@20
API _Gdi32DllInitialize@12
API _GdiAddFontResourceW@12
API _GdiAddGlsBounds@8
API _GdiAddGlsRecord@16
API _GdiAddInitialFonts@0
API _GdiAlphaBlend@44
API _GdiArtificialDecrementDriver@8
API GdiBatchLimit
API _GdiCleanCacheDC@4
API _GdiCommentStub@12
API _GdiConsoleTextOut@16
API _GdiConvertAndCheckDC@4
API _GdiConvertBitmap@4
API _GdiConvertBitmapV5@16
API _GdiConvertBrush@4
API _GdiConvertDC@4
API _GdiConvertEnhMetaFile@4
API _GdiConvertFont@4
API _GdiConvertMetaFilePict@4
API _GdiConvertPalette@4
API _GdiConvertRegion@4
API _GdiConvertToDevmodeW@4
API _GdiCreateLocalEnhMetaFile@4
API _GdiCreateLocalMetaFilePict@4
API _GdiCurrentProcessSplWow64@0
API _GdiDeleteLocalDC@4
API _GdiDeleteSpoolFileHandle@4
API _GdiDescribePixelFormat@16
API _GdiDisableUMPDSandboxing@0
API _GdiDllInitialize@8
API _GdiDrawStream@12
API _GdiEndDocEMF@4
API _GdiEndPageEMF@8
API _GdiEntry1@8
API _GdiEntry10@8
API _GdiEntry11@8
API _GdiEntry12@8
API _DdQueryDisplaySettingsUniqueness@0
API _GdiEntry14@12
API _GdiEntry15@12
API _GdiEntry16@12
API _GdiEntry2@44
API _GdiEntry3@4
API _GdiEntry4@8
API _GdiEntry5@4
API _GdiEntry6@8
API _GdiEntry7@8
API _GdiEntry8@4
API _GdiEntry9@24
API _GdiFixUpHandle@4
API _GdiFlush@0
API _NtGdiFullscreenControl@20
API _GdiGetBatchLimit@0
API _GdiGetBitmapBitsSize@4
API _GdiGetCharDimensions@12
API _GetCodePage@4
API _GdiGetDC@4
API _GdiGetDevmodeForPage@16
API _GdiGetEntry@8
API _GdiGetLocalBrush@4
API _GdiGetLocalDC@4
API _GdiGetLocalFont@4
API _GdiGetPageCount@4
API _GdiGetPageHandle@12
API _GdiGetSpoolFileHandle@12
API _NtGdiGetSpoolMessage@16
API _GdiGetVariationStoreDelta@24
API _GdiGradientFill@24
API _GdiHandleBeingTracked@4
API _NtGdiInitSpool@0
API _GdiInitializeLanguagePack@4
API _GdiIsMetaFileDC@4
API _GdiIsMetaPrintDC@4
API _GdiIsPlayMetafileDC@4
API _GdiIsScreenDC@4
API _GdiIsUMPDSandboxingEnabled@0
API _GdiLoadType1Fonts@0
API _GdiPlayDCScript@24
API _GdiPlayEMF@20
API _GdiPlayJournal@20
API _GdiPlayPageEMF@20
API _GdiPlayPrivatePageEMF@12
API _GdiPlayScript@28
API _GdiPrinterThunk@16
API _GdiProcessSetup@0
API _NtGdiQueryFonts@12
API _GdiQueryTable@0
API _GdiRealizationInfo@8
API _GdiReleaseDC@4
API _GdiReleaseLocalDC@4
API _GdiResetDCEMF@8
API _GdiSetAttrs@4
API _GdiSetBatchLimit@4
API _GdiSetLastError@4
API _GdiSetPixelFormat@8
API _GdiSetServerAttr@8
API _GdiStartDocEMF@8
API _GdiStartPageEMF@4
API _GdiSupportsFontChangeEvent@0
API _GdiSwapBuffers@4
API _GdiTrackHCreate@4
API _GdiTrackHDelete@4
API _GdiTransparentBlt@44
API _GdiValidateHandle@4
API _GdiWaitForTextReady@0
API _GdipIsAssertEnabled@4
API _GditGetCallerTLStorage@0
API _GditPopCallerInfo@0
API _GditPushCallerInfo@4
API _GetArcDirection@4
API _GetAspectRatioFilterEx@8
API _GetBitmapAttributes@4
API _GetBitmapBitsStub@12
API _GetBitmapDimensionEx@8
API _NtGdiGetBitmapDpiScaleValue@4
API _GetBkColorStub@4
API _GetBkMode@4
API _GetBoundsRect@12
API _GetBrushAttributes@4
API _GetBrushOrgEx@8
API _NtGdiGetCOPPCompatibleOPMInformation@12
API _NtGdiGetCertificate@16
API _NtGdiGetCertificateByHandle@16
API _NtGdiGetCertificateSize@12
API _NtGdiGetCertificateSizeByHandle@12
API _GetCharABCWidthsA@16
API _GetCharABCWidthsFloatA@16
API _GetCharABCWidthsFloatI@20
API _GetCharABCWidthsFloatW@16
API _GetCharABCWidthsI@20
API _GetCharABCWidthsW@16
API _GetCharWidth32A@16
API _GetCharWidth32W@16
API _GetCharWidthAStub@16
API _GetCharWidthFloatA@16
API _GetCharWidthFloatW@16
API _GetCharWidthI@20
API _NtGdiGetCharWidthInfo@8
API _GetCharWidthW@16
API _GetCharacterPlacementA@24
API _GetCharacterPlacementW@24
API _GetClipBox@8
API _GetClipRgnStub@8
API _GetColorAdjustment@8
API _GetColorSpace@4
API _GetCurrentDpiInfo@8
API _GetCurrentObjectStub@8
API _GetCurrentPositionExStub@8
API _GetDCBrushColor@4
API _GetDCDpiScaleValue@4
API _GetDCOrgEx@8
API _GetDCPenColor@4
API _GetDIBColorTable@16
API _GetDIBitsStub@28
API _GetDeviceCaps@8
API _GetDeviceGammaRamp@8
API _GetETM@8
API _GetEUDCTimeStamp@0
API _GetEUDCTimeStampExW@4
API _GetEnhMetaFileAStub@4
API _GetEnhMetaFileBitsStub@12
API _GetEnhMetaFileDescriptionAStub@12
API _GetEnhMetaFileDescriptionW@12
API _GetEnhMetaFileHeader@12
API _GetEnhMetaFilePaletteEntries@12
API _GetEnhMetaFilePixelFormat@12
API _GetEnhMetaFileW@4
API _GetFontAssocStatus@4
API _GetFontData@20
API _GetFontFileData@24
API _GetFontFileInfo@20
API _GetFontLanguageInfo@4
API _GetFontRealizationInfo@8
API _GetFontResourceInfoW@16
API _NtGdiGetFontUnicodeRanges@8
API _GetGlyphIndicesA@20
API _GetGlyphIndicesW@20
API _GetGlyphOutline@28
API _GetGlyphOutlineAStub@28
API _GetGlyphOutlineWStub@28
API _GetGlyphOutlineWow@28
API _GetGraphicsMode@4
API _GetHFONT@4
API _GetICMProfileA@12
API _GetICMProfileW@12
API _GetKerningPairsAStub@12
API _GetKerningPairsAStub@12
API _GetKerningPairsW@12
API _GetLayout@4
API _GetLogColorSpaceA@12
API _GetLogColorSpaceW@12
API _GetMapMode@4
API _GetMetaFileA@4
API _GetMetaFileBitsExStub@12
API _GetMetaFileW@4
API _GetMetaRgn@8
API _GetMiterLimit@8
API _GetNearestColor@8
API _GetNearestPaletteIndexStub@8
API _NtGdiGetNumberOfPhysicalMonitors@8
API _NtGdiGetOPMInformation@12
API _NtGdiGetOPMRandomNumber@8
API _GetObjectAStub@12
API _GetObjectTypeStub@4
API _GetObjectWStub@12
API _GetOutlineTextMetricsAStub@12
API _GetOutlineTextMetricsW@12
API _GetPaletteEntriesStub@16
API _GetPath@16
API _NtGdiGetPhysicalMonitorDescription@12
API _NtGdiGetPhysicalMonitorFromTarget@16
API _NtGdiGetPhysicalMonitors@16
API _GetPixelStub@12
API _GetPixelFormat@4
API _GetPolyFillMode@4
API _GetProcessSessionFonts@20
API _GetROP2Stub@4
API _GetRandomRgn@12
API _GetRasterizerCapsStub@8
API _GetRegionData@12
API _GetRelAbs@8
API _GetRgnBox@8
API _GetStockObjectStub@4
API _GetStretchBltMode@4
API _GetStringBitmapA@20
API _NtGdiGetStringBitmapW@20
API _NtGdiGetSuggestedOPMProtectedOutputArraySize@8
API _GetSystemPaletteEntriesStub@16
API _GetSystemPaletteUse@4
API _GetTextAlignStub@4
API _GetTextCharacterExtraStub@4
API _GetTextCharset@4
API _NtGdiGetTextCharsetInfo@12
API _GetTextColorStub@4
API _GetTextExtentExPointAStub@28
API _GetTextExtentExPointIStub@28
API _GetTextExtentExPointWStub@28
API _GetTextExtentExPointWPri@28
API _GetTextExtentPoint32AStub@16
API _GetTextExtentPoint32WStub@16
API _GetTextExtentPointAStub@16
API _GetTextExtentPointIStub@16
API _GetTextExtentPointWStub@16
API _GetTextFaceAStub@12
API _GetTextFaceAliasW@12
API _GetTextFaceW@12
API _GetTextMetricsA@8
API _GetTextMetricsWStub@8
API _GetTransform@12
API _GetViewportExtEx@8
API _GetViewportOrgExStub@8
API _GetWinMetaFileBits@20
API _GetWindowExtEx@8
API _GetWindowOrgEx@8
API _GetWorldTransform@8
API _NtGdiHT_Get8BPPFormatPalette@16
API _NtGdiHT_Get8BPPMaskPalette@24
API _InternalDeleteDC@4
API _InternalDeleteObject@4
API _IntersectClipRect@20
API _InvertRgnStub@8
API _IsValidEnhMetaRecord@8
API _IsValidEnhMetaRecordOffExt@16
API _LPtoDPStub@12
API _LineDDA@24
API _LineTo@12
API _LpkDrawTextEx@40
API LpkEditControl
API _LpkExtTextOut@36
API _LpkGetCharacterPlacement@28
API _LpkGetEditControl@0
API _LpkGetTextExtentExPoint@36
API _LpkInitialize@4
API _LpkPSMTextOut@24
API _LpkPresent@0
API _LpkTabbedTextOut@48
API _LpkUseGDIWidthCache@20
API _LpkpEditControlSize
API _LpkpInitializeEditControl@8
API _MaskBlt@48
API _MirrorRgn@8
API _ModerncoreCreateICW@16
API _ModerncoreDeleteDC@4
API _ModerncoreGdiInit@0
API _ModifyWorldTransform@12
API _MoveToEx@16
API _NamedEscape@28
API _OffsetClipRgn@12
API _OffsetRgn@12
API _OffsetViewportOrgEx@16
API _OffsetWindowOrgEx@16
API _NtGdiPATHOBJ_bEnum@8
API _NtGdiPATHOBJ_bEnumClipLines@12
API _NtGdiPATHOBJ_vEnumStart@4
API _NtGdiPATHOBJ_vEnumStartClipLines@16
API _NtGdiPATHOBJ_vGetBounds@8
API _PaintRgn@8
API _PatBltStub@24
API _PathToRegion@4
API _PieStub@36
API _PlayEnhMetaFileStub@12
API _PlayEnhMetaFileRecord@16
API _PlayMetaFileStub@8
API _PlayMetaFileRecord@16
API _PlgBlt@40
API _PolyBezierStub@12
API _PolyBezierTo@12
API _PolyDraw@16
API _PolyPatBlt@20
API _PolyPolygonStub@16
API _PolyPolyline@16
API _PolyTextOutA@12
API _PolyTextOutW@12
API _PolygonStub@12
API _PolylineStub@12
API _PolylineTo@12
API _PtInRegion@12
API _PtVisible@12
API _QueryFontAssocStatus@0
API _RealizePaletteStub@4
API _RectInRegion@8
API _RectVisibleStub@8
API _Rectangle@20
API _RemoveFontMemResourceEx@4
API _RemoveFontResourceAStub@4
API _RemoveFontResourceExA@12
API _RemoveFontResourceExW@12
API _RemoveFontResourceTracking@8
API _RemoveFontResourceW@4
API _ResetDCA@8
API _ResetDCW@8
API _ResizePaletteStub@8
API _RestoreDC@8
API _RoundRectStub@28
API _NtGdiSTROBJ_bEnum@12
API _NtGdiSTROBJ_bEnumPositionsOnly@12
API _NtGdiSTROBJ_bGetAdvanceWidths@16
API _NtGdiSTROBJ_dwGetCodePage@4
API _NtGdiSTROBJ_vEnumStart@4
API _SaveDC@4
API _NtGdiScaleRgn@8
API _NtGdiScaleValues@12
API _ScaleViewportExtEx@24
API _ScaleWindowExtEx@24
API _ScriptApplyDigitSubstitution@12
API _ScriptApplyLogicalWidth@36
API _ScriptBreak@16
API _ScriptCPtoX@36
API _ScriptCacheGetHeight@12
API _ScriptFreeCache@4
API _ScriptGetCMap@24
API _ScriptGetFontAlternateGlyphs@40
API _ScriptGetFontFeatureTags@32
API _ScriptGetFontLanguageTags@28
API _ScriptGetFontProperties@12
API _ScriptGetFontScriptTags@24
API _ScriptGetGlyphABCWidth@16
API _ScriptGetLogicalWidths@28
API _ScriptGetProperties@8
API _ScriptIsComplex@12
API _ScriptItemize@28
API _ScriptItemizeOpenType@32
API _ScriptJustify@24
API _ScriptLayout@16
API _ScriptPlace@36
API _ScriptPlaceOpenType@72
API _ScriptPositionSingleGlyph@52
API _ScriptRecordDigitSubstitution@8
API _ScriptShape@40
API _ScriptShapeOpenType@64
API _ScriptStringAnalyse@52
API _ScriptStringCPtoX@16
API _ScriptStringFree@4
API _ScriptStringGetLogicalWidths@8
API _ScriptStringGetOrder@8
API _ScriptStringOut@32
API _ScriptStringValidate@4
API _ScriptStringXtoCP@16
API _ScriptString_pLogAttr@4
API _ScriptString_pSize@4
API _ScriptString_pcOutChars@4
API _ScriptSubstituteSingleGlyph@36
API _ScriptTextOut@56
API _ScriptXtoCP@36
API _SelectBrushLocal@8
API _SelectClipPath@8
API _SelectClipRgn@8
API _SelectFontLocal@8
API _SelectObject@8
API _SelectPaletteStub@12
API _SetAbortProc@8
API _SetArcDirection@8
API _SetBitmapAttributes@8
API _SetBitmapBitsStub@12
API _SetBitmapDimensionEx@16
API _SetBkColorStub@8
API _SetBkMode@8
API _SetBoundsRect@12
API _SetBrushAttributes@8
API _SetBrushOrgEx@16
API _SetColorAdjustment@8
API _SetColorSpace@8
API _SetDCBrushColor@8
API _SetDCPenColor@8
API _SetDIBColorTable@16
API _SetDIBitsStub@28
API _SetDIBitsToDeviceStub@48
API _SetDeviceGammaRamp@8
API _SetEnhMetaFileBits@8
API _SetFontEnumeration@4
API _SetGraphicsMode@8
API _SetICMMode@8
API _SetICMProfileA@8
API _SetICMProfileW@8
API _SetLayout@8
API _SetLayoutWidth@12
API _NtGdiSetMagicColors@12
API _SetMapModeStub@8
API _SetMapperFlags@8
API _SetMetaFileBitsExStub@8
API _SetMetaRgn@4
API _SetMiterLimit@12
API _NtGdiSetOPMSigningKeyAndSequenceNumbers@8
API _SetPaletteEntriesStub@16
API _SetPixelStub@16
API _SetPixelFormat@12
API _SetPixelV@16
API _SetPolyFillMode@8
API _SetROP2Stub@8
API _SetRectRgn@20
API _SetRelAbs@8
API _SetStretchBltMode@8
API _SetSystemPaletteUse@8
API _SetTextAlign@8
API _SetTextCharacterExtra@8
API _SetTextColor@8
API _SetTextJustification@12
API _SetViewportExtExStub@16
API _SetViewportOrgExStub@16
API _SetVirtualResolution@20
API _SetWinMetaFileBits@16
API _SetWindowExtExStub@16
API _SetWindowOrgExStub@16
API _SetWorldTransform@8
API _StartDocAStub@8
API _StartDocW@8
API _StartFormPage@4
API _StartPage@4
API _StretchBltStub@44
API _StretchDIBits@52
API _StrokeAndFillPath@4
API _StrokePath@4
API _SwapBuffers@4
API _TextOutAStub@20
API _TextOutW@20
API _TranslateCharsetInfoStub@12
API _UnloadNetworkFonts@4
API _UnrealizeObjectStub@4
API _UpdateColorsStub@4
API _UpdateICMRegKeyA@16
API _UpdateICMRegKeyW@16
API _UspAllocCache@8
API _UspAllocTemp@8
API _UspFreeMem@4
API _WidenPath@4
API _NtGdiXFORMOBJ_bApplyXform@20
API _NtGdiXFORMOBJ_iGetXform@8
API _NtGdiXLATEOBJ_cGetPalette@16
API _NtGdiXLATEOBJ_hGetColorTransform@4
API _NtGdiXLATEOBJ_iXlate@8
API _XLATEOBJ_piVector@4
API _bCreateDCW@24
API _bDeleteLDC@4
API _bInitSystemAndFontsDirectoriesW@8
API _bMakePathNameW@16
API _cGetTTFFromFOT@28
API fpClosePrinter
API _ftsWordBreak@20
API gCookie
API gMaxGdiHandleCount
API gW32PID
API g_systemCallFilterId
API _gdiPlaySpoolStream@24
API ghICM
API _hGetPEBHandle@8
API pGdiDevCaps
API pGdiSharedHandleTable
API pGdiSharedMemory
API @pldcGet@4
API _vSetPldc@8
API _DrvQueryMonitorUniqueness@0
API _DrvQueryPrivateDisplayChangeUniqueness@0
API _DwmGenerateMoveData@4
API _DwmHLSurfCloseCompositorRef@4
API _DwmHLSurfOpenCompositorRef@4
API _DwmGetDirtyRgn@20
API _DwmHLSurfGetDirtyRgn@40
API _DwmGetRedirectionStyle@8
API _DwmQueryCompositionId@0
API _DrvQueryAdapterPopulationUniqueness@0
API _DwmGetSurfaceData@8
API _DwmHLsurfSetUpdatedId@8
API _DwmHLsurfSetPresentFlags@8
API _DwmHLSurfSetSignalOnDirty@20

end
