API MACRO name
name proc
name endp
ENDM

.code

API _Cbuild
API _Cmulcc
API _Cmulcr
API _CreateFrameInfo
API _CxxThrowException
API _exit
API _FCbuild
API _FCmulcc
API _FCmulcr
API _FindAndUnlinkFrame
API _GetImageBase
API _GetThrowImageBase
API _Getdays
API _Getmonths
API _Gettnames
API _IsExceptionObjectToBeDestroyed
API _LCbuild
API _LCmulcc
API _LCmulcr
API _SetImageBase
API _SetThrowImageBase
API _SetWinRTOutOfMemoryExceptionCallback
API _Strftime
API _W_Getdays
API _W_Getmonths
API _W_Gettnames
API _Wcsftime
API __AdjustPointer
API __BuildCatchObject
API __BuildCatchObjectHelper
API __C_specific_handler
API __C_specific_handler_noexcept
API __CxxDetectRethrow
API __CxxExceptionFilter
API __CxxFrameHandler2
API __CxxFrameHandler2
API __CxxFrameHandler3
API __CxxFrameHandler4
API __CxxQueryExceptionSize
API __CxxRegisterExceptionObject
API __CxxUnregisterExceptionObject
API __DestructExceptionObject
API __FrameUnwindFilter
API __GetPlatformExceptionInfo
API __NLG_Dispatch2
API __NLG_Return2
API __RTCastToVoid
API __RTDynamicCast
API __RTtypeid
API __TypeMatch
API ___lc_codepage_func
API ___lc_collate_cp_func
API ___lc_locale_name_func
API ___mb_cur_max_func
API ___mb_cur_max_l_func
API __acrt_iob_func
API __conio_common_vcprintf
API __conio_common_vcprintf_p
API __conio_common_vcprintf_s
API __conio_common_vcscanf
API __conio_common_vcwprintf
API __conio_common_vcwprintf_p
API __conio_common_vcwprintf_s
API __conio_common_vcwscanf
API __current_exception
API __current_exception_context
API __daylight
API __dcrt_get_wide_environment_from_os
API __dcrt_initial_narrow_environment
API __doserrno
API __dstbias
API __fpe_flt_rounds
API __fpecode
API __initialize_lconv_for_unsigned_char
API __intrinsic_setjmp
API __intrinsic_setjmpex
API __isascii
API __iscsym
API __iscsymf
API __iswcsym
API __iswcsymf
API __p___argc
API __p___argv
API __p___wargv
API __p__acmdln
API __p__commode
API __p__environ
API __p__fmode
API __p__mbcasemap
API __p__mbctype
API __p__pgmptr
API __p__wcmdln
API __p__wenviron
API __p__wpgmptr
API __pctype_func
API __processing_throw
API __pwctype_func
API __pxcptinfoptrs
API __report_gsfailure
API __setusermatherr
API __std_exception_copy
API __std_exception_destroy
API __std_terminate
API __std_type_info_compare
API __std_type_info_destroy_list
API __std_type_info_hash
API __std_type_info_name
API __stdio_common_vfprintf
API __stdio_common_vfprintf_p
API __stdio_common_vfprintf_s
API __stdio_common_vfscanf
API __stdio_common_vfwprintf
API __stdio_common_vfwprintf_p
API __stdio_common_vfwprintf_s
API __stdio_common_vfwscanf
API __stdio_common_vsnprintf_s
API __stdio_common_vsnwprintf_s
API __stdio_common_vsprintf
API __stdio_common_vsprintf_p
API __stdio_common_vsprintf_s
API __stdio_common_vsscanf
API __stdio_common_vswprintf
API __stdio_common_vswprintf_p
API __stdio_common_vswprintf_s
API __stdio_common_vswscanf
API __strncnt
API __sys_errlist
API __sys_nerr
API __threadhandle
API __threadid
API __timezone
API __toascii
API __tzname
API __unDName
API __unDNameEx
API __uncaught_exception
API __uncaught_exceptions
API __wcserror
API __wcserror_s
API __wcsncnt
API _abs64
API _access
API _access_s
API _aligned_free
API _aligned_malloc
API _aligned_msize
API _aligned_offset_malloc
API _aligned_offset_realloc
API _aligned_offset_recalloc
API _aligned_realloc
API _aligned_recalloc
API _assert
API _atodbl
API _atodbl_l
API _atof_l
API _atoflt
API _atoflt_l
API _atoi64
API _atoi64_l
API _atoi_l
API _atol_l
API _atoldbl
API _atoldbl_l
API _atoi64_l
API _beep
API _beginthread
API _beginthreadex
API _byteswap_uint64
API _byteswap_ulong
API _byteswap_ushort
API _c_exit
API _cabs
API _callnewh
API _calloc_base
API _cexit
API _cgets
API _cgets_s
API _cgetws
API _cgetws_s
API _chdir
API _chdrive
API _chgsign
API _chgsignf
API _chmod
API _chsize
API _chsize_s
API _clearfp
API _close
API _commit
API _configthreadlocale
API _configure_narrow_argv
API _configure_wide_argv
API _control87
API _controlfp
API _controlfp_s
API _copysign
API _copysignf
API _cputs
API _cputws
API _creat
API _create_locale
API _crt_at_quick_exit
API _crt_atexit
API _ctime32
API _ctime32_s
API _ctime64
API _ctime64_s
API _cwait
API _d_int
API _ldclass
API _dexp
API _difftime32
API _difftime64
API _dlog
API _dnorm
API _dpcomp
API _ldpoly
API _dscale
API _ldsign
API _dsin
API _dtest
API _dunscale
API _dup
API _dup2
API _dupenv_s
API _ecvt
API _ecvt_s
API _endthread
API _endthreadex
API _eof
API _errno
API _except1
API _execl
API _execle
API _execlp
API _execlpe
API _execute_onexit_table
API _execv
API _execve
API _execvp
API _execvpe
API _exit
API _expand
API _fclose_nolock
API _fcloseall
API _fcvt
API _fcvt_s
API _fd_int
API _fdclass
API _fdexp
API _fdlog
API _fdnorm
API _fdopen
API _fdpcomp
API _fdpoly
API _fdscale
API _fdsign
API _fdsin
API _fdtest
API _fdunscale
API _fflush_nolock
API _fgetc_nolock
API _fgetchar
API _fgetwc_nolock
API _fgetwchar
API _filelength
API _filelengthi64
API _fileno
API _findclose
API _findfirst32
API _findfirst32i64
API _findfirst64
API _findfirst64i32
API _findnext32
API _findnext32i64
API _findnext64
API _findnext64i32
API _finite
API _finitef
API _flushall
API _fpclass
API _fpclassf
API _fpieee_flt
API _fpreset
API _fputc_nolock
API _fputchar
API _fputwc_nolock
API _fputwchar
API _fread_nolock
API _fread_nolock_s
API _free_base
API _free_locale
API _fseek_nolock
API _fseeki64
API _fseeki64_nolock
API _fsopen
API _fstat32
API _fstat32i64
API _fstat64
API _fstat64i32
API _ftell_nolock
API _ftelli64
API _ftelli64_nolock
API _ftime32
API _ftime32_s
API _ftime64
API _ftime64_s
API _fullpath
API _futime32
API _futime64
API _fwrite_nolock
API _gcvt
API _gcvt_s
API _get_FMA3_enable
API _get_current_locale
API _get_daylight
API _get_doserrno
API _get_dstbias
API _get_errno
API _get_fmode
API _get_heap_handle
API _get_initial_narrow_environment
API _get_initial_wide_environment
API _get_invalid_parameter_handler
API _get_narrow_winmain_command_line
API _get_osfhandle
API _get_pgmptr
API _get_printf_count_output
API _get_purecall_handler
API _get_stream_buffer_pointers
API _get_terminate
API _get_thread_local_invalid_parameter_handler
API _get_timezone
API _get_tzname
API _get_unexpected
API _get_wide_winmain_command_line
API _get_wpgmptr
API _getc_nolock
API _getch
API _getch_nolock
API _getche
API _getche_nolock
API _getcwd
API _getdcwd
API _getdiskfree
API _getdllprocaddr
API _getdrive
API _getdrives
API _getmaxstdio
API _getmbcp
API _getpid
API _getsystime
API _getw
API _getwc_nolock
API _getwch
API _getwch_nolock
API _getwche
API _getwche_nolock
API _getws
API _getws_s
API _gmtime32
API _gmtime32_s
API _gmtime64
API _gmtime64_s
API _heapchk
API _heapmin
API _heapwalk
API _hypot
API _hypotf
API _i64toa
API _i64toa_s
API _i64tow
API _i64tow_s
API _initialize_narrow_environment
API _initialize_onexit_table
API _initialize_wide_environment
API _initterm
API _initterm_e
API _invalid_parameter_noinfo
API _invalid_parameter_noinfo_noreturn
API _invoke_watson
API _is_exception_typeof
API _isalnum_l
API _isalpha_l
API _isatty
API _isblank_l
API _iscntrl_l
API _isctype
API _isctype_l
API _isdigit_l
API _isgraph_l
API _isleadbyte_l
API _islower_l
API _ismbbalnum
API _ismbbalnum_l
API _ismbbalpha
API _ismbbalpha_l
API _ismbbblank
API _ismbbblank_l
API _ismbbgraph
API _ismbbgraph_l
API _ismbbkalnum
API _ismbbkalnum_l
API _ismbbkana
API _ismbbkana_l
API _ismbbkprint
API _ismbbkprint_l
API _ismbbkpunct
API _ismbbkpunct_l
API _ismbblead
API _ismbblead_l
API _ismbbprint
API _ismbbprint_l
API _ismbbpunct
API _ismbbpunct_l
API _ismbbtrail
API _ismbbtrail_l
API _ismbcalnum
API _ismbcalnum_l
API _ismbcalpha
API _ismbcalpha_l
API _ismbcblank
API _ismbcblank_l
API _ismbcdigit
API _ismbcdigit_l
API _ismbcgraph
API _ismbcgraph_l
API _ismbchira
API _ismbchira_l
API _ismbckata
API _ismbckata_l
API _ismbcl0
API _ismbcl0_l
API _ismbcl1
API _ismbcl1_l
API _ismbcl2
API _ismbcl2_l
API _ismbclegal
API _ismbclegal_l
API _ismbclower
API _ismbclower_l
API _ismbcprint
API _ismbcprint_l
API _ismbcpunct
API _ismbcpunct_l
API _ismbcspace
API _ismbcspace_l
API _ismbcsymbol
API _ismbcsymbol_l
API _ismbcupper
API _ismbcupper_l
API _ismbslead
API _ismbslead_l
API _ismbstrail
API _ismbstrail_l
API _isnan
API _isnanf
API _isprint_l
API _ispunct_l
API _isspace_l
API _isupper_l
API _iswalnum_l
API _iswalpha_l
API _iswblank_l
API _iswcntrl_l
API _iswcsym_l
API _iswcsymf_l
API _iswctype_l
API _iswdigit_l
API _iswgraph_l
API _iswlower_l
API _iswprint_l
API _iswpunct_l
API _iswspace_l
API _iswupper_l
API _iswxdigit_l
API _isxdigit_l
API _itoa
API _itoa_s
API _itow
API _itow_s
API _j0
API _j1
API _jn
API _kbhit
API _ld_int
API _ldclass
API _ldexp
API _ldlog
API _dpcomp
API _ldpoly
API _ldscale
API _ldsign
API _ldsin
API _ldtest
API _ldunscale
API _lfind
API _lfind_s
API _loaddll
API _local_unwind
API _localtime32
API _localtime32_s
API _localtime64
API _localtime64_s
API _lock_file
API _lock_locales
API _locking
API _logb
API _logbf
API _lrotl
API _lrotr
API _lsearch
API _lsearch_s
API _lseek
API _lseeki64
API _ltoa
API _ltoa_s
API _ltow
API _ltow_s
API _makepath
API _makepath_s
API _malloc_base
API _mbbtombc
API _mbbtombc_l
API _mbbtype
API _mbbtype_l
API _mbcasemap
API _mbccpy
API _mbccpy_l
API _mbccpy_s
API _mbccpy_s_l
API _mbcjistojms
API _mbcjistojms_l
API _mbcjmstojis
API _mbcjmstojis_l
API _mbclen
API _mbclen_l
API _mbctohira
API _mbctohira_l
API _mbctokata
API _mbctokata_l
API _mbctolower
API _mbctolower_l
API _mbctombb
API _mbctombb_l
API _mbctoupper
API _mbctoupper_l
API _mblen_l
API _mbsbtype
API _mbsbtype_l
API _mbscat_s
API _mbscat_s_l
API _mbschr
API _mbschr_l
API _mbscmp
API _mbscmp_l
API _mbscoll
API _mbscoll_l
API _mbscpy_s
API _mbscpy_s_l
API _mbscspn
API _mbscspn_l
API _mbsdec
API _mbsdec_l
API _mbsdup
API _mbsicmp
API _mbsicmp_l
API _mbsicoll
API _mbsicoll_l
API _mbsinc
API _mbsinc_l
API _mbslen
API _mbslen_l
API _mbslwr
API _mbslwr_l
API _mbslwr_s
API _mbslwr_s_l
API _mbsnbcat
API _mbsnbcat_l
API _mbsnbcat_s
API _mbsnbcat_s_l
API _mbsnbcmp
API _mbsnbcmp_l
API _mbsnbcnt
API _mbsnbcnt_l
API _mbsnbcoll
API _mbsnbcoll_l
API _mbsnbcpy
API _mbsnbcpy_l
API _mbsnbcpy_s
API _mbsnbcpy_s_l
API _mbsnbicmp
API _mbsnbicmp_l
API _mbsnbicoll
API _mbsnbicoll_l
API _mbsnbset
API _mbsnbset_l
API _mbsnbset_s
API _mbsnbset_s_l
API _mbsncat
API _mbsncat_l
API _mbsncat_s
API _mbsncat_s_l
API _mbsnccnt
API _mbsnccnt_l
API _mbsncmp
API _mbsncmp_l
API _mbsncoll
API _mbsncoll_l
API _mbsncpy
API _mbsncpy_l
API _mbsncpy_s
API _mbsncpy_s_l
API _mbsnextc
API _mbsnextc_l
API _mbsnicmp
API _mbsnicmp_l
API _mbsnicoll
API _mbsnicoll_l
API _mbsninc
API _mbsninc_l
API _mbsnlen
API _mbsnlen_l
API _mbsnset
API _mbsnset_l
API _mbsnset_s
API _mbsnset_s_l
API _mbspbrk
API _mbspbrk_l
API _mbsrchr
API _mbsrchr_l
API _mbsrev
API _mbsrev_l
API _mbsset
API _mbsset_l
API _mbsset_s
API _mbsset_s_l
API _mbsspn
API _mbsspn_l
API _mbsspnp
API _mbsspnp_l
API _mbsstr
API _mbsstr_l
API _mbstok
API _mbstok_l
API _mbstok_s
API _mbstok_s_l
API _mbstowcs_l
API _mbstowcs_s_l
API _mbstrlen
API _mbstrlen_l
API _mbstrnlen
API _mbstrnlen_l
API _mbsupr
API _mbsupr_l
API _mbsupr_s
API _mbsupr_s_l
API _mbtowc_l
API _memccpy
API _memicmp
API _memicmp_l
API _mkdir
API _mkgmtime32
API _mkgmtime64
API _mktemp
API _mktemp_s
API _mktime32
API _mktime64
API _msize
API _nextafter
API _nextafterf
API _o__Getdays
API _o__Getmonths
API _o__Gettnames
API _o__Strftime
API _o__W_Getdays
API _o__W_Getmonths
API _o__W_Gettnames
API _o__Wcsftime
API _o____lc_codepage_func
API _o____lc_collate_cp_func
API _o____lc_locale_name_func
API _o____mb_cur_max_func
API _o___acrt_iob_func
API _o___conio_common_vcprintf
API _o___conio_common_vcprintf_p
API _o___conio_common_vcprintf_s
API _o___conio_common_vcscanf
API _o___conio_common_vcwprintf
API _o___conio_common_vcwprintf_p
API _o___conio_common_vcwprintf_s
API _o___conio_common_vcwscanf
API _o___daylight
API _o___dstbias
API _o___fpe_flt_rounds
API _o___p___argc
API _o___p___argv
API _o___p___wargv
API _o___p__acmdln
API _o___p__commode
API _o___p__environ
API _o___p__fmode
API _o___p__mbcasemap
API _o___p__mbctype
API _o___p__pgmptr
API _o___p__wcmdln
API _o___p__wenviron
API _o___p__wpgmptr
API _o___pctype_func
API _o___pwctype_func
API _o___std_exception_copy
API _o___std_exception_destroy
API _o___std_type_info_destroy_list
API _o___std_type_info_name
API _o___stdio_common_vfprintf
API _o___stdio_common_vfprintf_p
API _o___stdio_common_vfprintf_s
API _o___stdio_common_vfscanf
API _o___stdio_common_vfwprintf
API _o___stdio_common_vfwprintf_p
API _o___stdio_common_vfwprintf_s
API _o___stdio_common_vfwscanf
API _o___stdio_common_vsnprintf_s
API _o___stdio_common_vsnwprintf_s
API _o___stdio_common_vsprintf
API _o___stdio_common_vsprintf_p
API _o___stdio_common_vsprintf_s
API _o___stdio_common_vsscanf
API _o___stdio_common_vswprintf
API _o___stdio_common_vswprintf_p
API _o___stdio_common_vswprintf_s
API _o___stdio_common_vswscanf
API _o___timezone
API _o___tzname
API _o___wcserror
API _o__access
API _o__access_s
API _o__aligned_free
API _o__aligned_malloc
API _o__aligned_msize
API _o__aligned_offset_malloc
API _o__aligned_offset_realloc
API _o__aligned_offset_recalloc
API _o__aligned_realloc
API _o__aligned_recalloc
API _o__atodbl
API _o__atodbl_l
API _o__atof_l
API _o__atoflt
API _o__atoflt_l
API _o_atoll
API _o__atoi64_l
API _o__atoi_l
API _o__atol_l
API _o__atoldbl
API _o__atoldbl_l
API _o__atoi64_l
API _o__beep
API _o__beginthread
API _o__beginthreadex
API _o__cabs
API _o__callnewh
API _o__calloc_base
API _o__cexit
API _o__cgets
API _o__cgets_s
API _o__cgetws
API _o__cgetws_s
API _o__chdir
API _o__chdrive
API _o__chmod
API _o__chsize
API _o__chsize_s
API _o__close
API _o__commit
API _o__configthreadlocale
API _o__configure_narrow_argv
API _o__configure_wide_argv
API _o__controlfp_s
API _o__cputs
API _o__cputws
API _o__creat
API _o__create_locale
API _o__crt_atexit
API _o__ctime32_s
API _o__ctime64_s
API _o__cwait
API _o__d_int
API _o__dclass
API _o__difftime32
API _o__difftime64
API _o__dlog
API _o__dnorm
API _o__dpcomp
API _o__dpoly
API _o__dscale
API _o__dsign
API _o__dsin
API _o__dtest
API _o__dunscale
API _o__dup
API _o__dup2
API _o__dupenv_s
API _o__ecvt
API _o__ecvt_s
API _o__endthread
API _o__endthreadex
API _o__eof
API _o__errno
API _o__except1
API _o__execute_onexit_table
API _o__execv
API _o__execve
API _o__execvp
API _o__execvpe
API _o__exit
API _o__expand
API _o__fclose_nolock
API _o__fcloseall
API _o__fcvt
API _o__fcvt_s
API _o__fd_int
API _o__fdclass
API _o__fdexp
API _o__fdlog
API _o__fdopen
API _o__fdpcomp
API _o__fdpoly
API _o__fdscale
API _o__fdsign
API _o__fdsin
API _o__fflush_nolock
API _o__fgetc_nolock
API _o_getchar
API _o__fgetwc_nolock
API _o_getwchar
API _o__filelength
API _o__filelengthi64
API _o__fileno
API _o__findclose
API _o__findfirst32
API _o__findfirst32i64
API _o__findfirst64
API _o__findfirst64i32
API _o__findnext32
API _o__findnext32i64
API _o__findnext64
API _o__findnext64i32
API _o__flushall
API _o__fpclass
API _o__fpclassf
API _o__fputc_nolock
API _o__fputchar
API _o__fputwc_nolock
API _o__fputwchar
API _o__fread_nolock
API _o__fread_nolock_s
API _o__free_base
API _o__free_locale
API _o__fseek_nolock
API _o__fseeki64
API _o__fseeki64_nolock
API _o__fsopen
API _o__fstat32
API _o__fstat32i64
API _o__fstat64
API _o__fstat64i32
API _o__ftell_nolock
API _o__ftelli64
API _o__ftelli64_nolock
API _o__ftime32
API _o__ftime32_s
API _o__ftime64
API _o__ftime64_s
API _o__fullpath
API _o__futime32
API _o__futime64
API _o__fwrite_nolock
API _o__gcvt
API _o__gcvt_s
API _o__get_daylight
API _o__get_doserrno
API _o__get_dstbias
API _o__get_errno
API _o__get_fmode
API _o__get_heap_handle
API _o__get_initial_narrow_environment
API _o__get_initial_wide_environment
API _o__get_invalid_parameter_handler
API _o__get_narrow_winmain_command_line
API _o__get_osfhandle
API _o__get_pgmptr
API _o__get_stream_buffer_pointers
API _o__get_terminate
API _o__get_thread_local_invalid_parameter_handler
API _o__get_timezone
API _o__get_tzname
API _o__get_wide_winmain_command_line
API _o__get_wpgmptr
API _o__getc_nolock
API _o__getch
API _o__getch_nolock
API _o__getche
API _o__getche_nolock
API _o__getcwd
API _o__getdcwd
API _o__getdiskfree
API _o__getdllprocaddr
API _o__getdrive
API _o__getdrives
API _o__getmbcp
API _o__getsystime
API _o__getw
API _o__getwc_nolock
API _o__getwch
API _o__getwch_nolock
API _o__getwche
API _o__getwche_nolock
API _o__getws
API _o__getws_s
API _o__gmtime32
API _o__gmtime32_s
API _o__gmtime64
API _o__gmtime64_s
API _o__heapchk
API _o__heapmin
API _o__hypot
API _o__hypotf
API _o__i64toa
API _o__i64toa_s
API _o__i64tow
API _o__i64tow_s
API _o__initialize_narrow_environment
API _o__initialize_onexit_table
API _o__initialize_wide_environment
API _o__invalid_parameter_noinfo
API _o__invalid_parameter_noinfo_noreturn
API _o__isatty
API _o__isctype
API _o__isctype_l
API _o__isleadbyte_l
API _o__ismbbalnum
API _o__ismbbalnum_l
API _o__ismbbalpha
API _o__ismbbalpha_l
API _o__ismbbblank
API _o__ismbbblank_l
API _o__ismbbgraph
API _o__ismbbgraph_l
API _o__ismbbkalnum
API _o__ismbbkalnum_l
API _o__ismbbkana
API _o__ismbbkana_l
API _o__ismbbkprint
API _o__ismbbkprint_l
API _o__ismbbkpunct
API _o__ismbbkpunct_l
API _o__ismbblead
API _o__ismbblead_l
API _o__ismbbprint
API _o__ismbbprint_l
API _o__ismbbpunct
API _o__ismbbpunct_l
API _o__ismbbtrail
API _o__ismbbtrail_l
API _o__ismbcalnum
API _o__ismbcalnum_l
API _o__ismbcalpha
API _o__ismbcalpha_l
API _o__ismbcblank
API _o__ismbcblank_l
API _o__ismbcdigit
API _o__ismbcdigit_l
API _o__ismbcgraph
API _o__ismbcgraph_l
API _o__ismbchira
API _o__ismbchira_l
API _o__ismbckata
API _o__ismbckata_l
API _o__ismbcl0
API _o__ismbcl0_l
API _o__ismbcl1
API _o__ismbcl1_l
API _o__ismbcl2
API _o__ismbcl2_l
API _o__ismbclegal
API _o__ismbclegal_l
API _o__ismbclower
API _o__ismbclower_l
API _o__ismbcprint
API _o__ismbcprint_l
API _o__ismbcpunct
API _o__ismbcpunct_l
API _o__ismbcspace
API _o__ismbcspace_l
API _o__ismbcsymbol
API _o__ismbcsymbol_l
API _o__ismbcupper
API _o__ismbcupper_l
API _o__ismbslead
API _o__ismbslead_l
API _o__ismbstrail
API _o__ismbstrail_l
API _o__iswctype_l
API _o__itoa
API _o__itoa_s
API _o__itow
API _o__itow_s
API _o__j0
API _o__j1
API _o__jn
API _o__kbhit
API _o__ld_int
API _o__ldclass
API _o__ldexp
API _o__ldlog
API _o__dpcomp
API _o__dpoly
API _o__ldscale
API _o__ldsign
API _o__ldsin
API _o__ldtest
API _o__ldunscale
API _o__lfind
API _o__lfind_s
API _o__loaddll
API _o__localtime32
API _o__localtime32_s
API _o__localtime64
API _o__localtime64_s
API _o__lock_file
API _o__locking
API _o__logb
API _o__logbf
API _o__lsearch
API _o__lsearch_s
API _o__lseek
API _o__lseeki64
API _o__ltoa
API _o__ltoa_s
API _o__ltow
API _o__ltow_s
API _o__makepath
API _o__makepath_s
API _o__malloc_base
API _o__mbbtombc
API _o__mbbtombc_l
API _o__mbbtype
API _o__mbbtype_l
API _o__mbccpy
API _o__mbccpy_l
API _o__mbccpy_s
API _o__mbccpy_s_l
API _o__mbcjistojms
API _o__mbcjistojms_l
API _o__mbcjmstojis
API _o__mbcjmstojis_l
API _o__mbclen
API _o__mbclen_l
API _o__mbctohira
API _o__mbctohira_l
API _o__mbctokata
API _o__mbctokata_l
API _o__mbctolower
API _o__mbctolower_l
API _o__mbctombb
API _o__mbctombb_l
API _o__mbctoupper
API _o__mbctoupper_l
API _o__mblen_l
API _o__mbsbtype
API _o__mbsbtype_l
API _o__mbscat_s
API _o__mbscat_s_l
API _o__mbschr
API _o__mbschr_l
API _o__mbscmp
API _o__mbscmp_l
API _o__mbscoll
API _o__mbscoll_l
API _o__mbscpy_s
API _o__mbscpy_s_l
API _o__mbscspn
API _o__mbscspn_l
API _o__mbsdec
API _o__mbsdec_l
API _o__mbsicmp
API _o__mbsicmp_l
API _o__mbsicoll
API _o__mbsicoll_l
API _o__mbsinc
API _o__mbsinc_l
API _o__mbslen
API _o__mbslen_l
API _o__mbslwr
API _o__mbslwr_l
API _o__mbslwr_s
API _o__mbslwr_s_l
API _o__mbsnbcat
API _o__mbsnbcat_l
API _o__mbsnbcat_s
API _o__mbsnbcat_s_l
API _o__mbsnbcmp
API _o__mbsnbcmp_l
API _o__mbsnbcnt
API _o__mbsnbcnt_l
API _o__mbsnbcoll
API _o__mbsnbcoll_l
API _o__mbsnbcpy
API _o__mbsnbcpy_l
API _o__mbsnbcpy_s
API _o__mbsnbcpy_s_l
API _o__mbsnbicmp
API _o__mbsnbicmp_l
API _o__mbsnbicoll
API _o__mbsnbicoll_l
API _o__mbsnbset
API _o__mbsnbset_l
API _o__mbsnbset_s
API _o__mbsnbset_s_l
API _o__mbsncat
API _o__mbsncat_l
API _o__mbsncat_s
API _o__mbsncat_s_l
API _o__mbsnccnt
API _o__mbsnccnt_l
API _o__mbsncmp
API _o__mbsncmp_l
API _o__mbsncoll
API _o__mbsncoll_l
API _o__mbsncpy
API _o__mbsncpy_l
API _o__mbsncpy_s
API _o__mbsncpy_s_l
API _o__mbsnextc
API _o__mbsnextc_l
API _o__mbsnicmp
API _o__mbsnicmp_l
API _o__mbsnicoll
API _o__mbsnicoll_l
API _o__mbsninc
API _o__mbsninc_l
API _o__mbsnlen
API _o__mbsnlen_l
API _o__mbsnset
API _o__mbsnset_l
API _o__mbsnset_s
API _o__mbsnset_s_l
API _o__mbspbrk
API _o__mbspbrk_l
API _o__mbsrchr
API _o__mbsrchr_l
API _o__mbsrev
API _o__mbsrev_l
API _o__mbsset
API _o__mbsset_l
API _o__mbsset_s
API _o__mbsset_s_l
API _o__mbsspn
API _o__mbsspn_l
API _o__mbsspnp
API _o__mbsspnp_l
API _o__mbsstr
API _o__mbsstr_l
API _o__mbstok
API _o__mbstok_l
API _o__mbstok_s
API _o__mbstok_s_l
API _o__mbstowcs_l
API _o__mbstowcs_s_l
API _o__mbstrlen
API _o__mbstrlen_l
API _o__mbstrnlen
API _o__mbstrnlen_l
API _o__mbsupr
API _o__mbsupr_l
API _o__mbsupr_s
API _o__mbsupr_s_l
API _o__mbtowc_l
API _o__memicmp
API _o__memicmp_l
API _o__mkdir
API _o__mkgmtime32
API _o__mkgmtime64
API _o__mktemp
API _o__mktemp_s
API _o__mktime32
API _o__mktime64
API _o__msize
API _o__nextafter
API _o__nextafterf
API _o__open_osfhandle
API _o__pclose
API _o__pipe
API _o__popen
API _o__purecall
API _o__putc_nolock
API _o__putch
API _o__putch_nolock
API _o__putenv
API _o__putenv_s
API _o__putw
API _o__putwc_nolock
API _o__putwch
API _o__putwch_nolock
API _o__putws
API _o__read
API _o__realloc_base
API _o__recalloc
API _o__register_onexit_function
API _o__resetstkoflw
API _o__rmdir
API _o__rmtmp
API _o__scalb
API _o__scalbf
API _o__searchenv
API _o__searchenv_s
API _o__seh_filter_dll
API _o__seh_filter_exe
API _o__set_abort_behavior
API _o__set_app_type
API _o__set_doserrno
API _o__set_errno
API _o__set_fmode
API _o__set_invalid_parameter_handler
API _o__set_new_handler
API _o__set_new_mode
API _o__set_thread_local_invalid_parameter_handler
API _o__seterrormode
API _o__setmbcp
API _o__setmode
API _o__setsystime
API _o__sleep
API _o__sopen
API _o__sopen_dispatch
API _o__sopen_s
API _o__spawnv
API _o__spawnve
API _o__spawnvp
API _o__spawnvpe
API _o__splitpath
API _o__splitpath_s
API _o__stat32
API _o__stat32i64
API _o__stat64
API _o__stat64i32
API _o__strcoll_l
API _o__strdate
API _o__strdate_s
API _o__strdup
API _o__strerror
API _o__strerror_s
API _o__strftime_l
API _o__stricmp
API _o__stricmp_l
API _o__stricoll
API _o__stricoll_l
API _o__strlwr
API _o__strlwr_l
API _o__strlwr_s
API _o__strlwr_s_l
API _o__strncoll
API _o__strncoll_l
API _o__strnicmp
API _o__strnicmp_l
API _o__strnicoll
API _o__strnicoll_l
API _o__strnset_s
API _o__strset_s
API _o__strtime
API _o__strtime_s
API _o__strtold_l
API _o__strtof_l
API _o__strtoi64
API _o__strtoi64_l
API _o__strtol_l
API _o__strtold_l
API _o__strtoi64_l
API _o__strtoui64
API _o__strtoui64_l
API _o__strtoul_l
API _o__strtoui64_l
API _o__strupr
API _o__strupr_l
API _o__strupr_s
API _o__strupr_s_l
API _o__strxfrm_l
API _o__swab
API _o__tell
API _o__telli64
API _o__timespec32_get
API _o__timespec64_get
API _o__tolower
API _o__tolower_l
API _o__toupper
API _o__toupper_l
API _o__towlower_l
API _o__towupper_l
API _o__tzset
API _o__ui64toa
API _o__ui64toa_s
API _o__ui64tow
API _o__ui64tow_s
API _o__ultoa
API _o__ultoa_s
API _o__ultow
API _o__ultow_s
API _o__umask
API _o__umask_s
API _o__ungetc_nolock
API _o__ungetch
API _o__ungetch_nolock
API _o__ungetwc_nolock
API _o__ungetwch
API _o__ungetwch_nolock
API _o__unlink
API _o__unloaddll
API _o__unlock_file
API _o__utime32
API _o__utime64
API _o__waccess
API _o__waccess_s
API _o__wasctime
API _o__wasctime_s
API _o__wchdir
API _o__wchmod
API _o__wcreat
API _o__wcreate_locale
API _o__wcscoll_l
API _o__wcsdup
API _o__wcserror
API _o__wcserror_s
API _o__wcsftime_l
API _o__wcsicmp
API _o__wcsicmp_l
API _o__wcsicoll
API _o__wcsicoll_l
API _o__wcslwr
API _o__wcslwr_l
API _o__wcslwr_s
API _o__wcslwr_s_l
API _o__wcsncoll
API _o__wcsncoll_l
API _o__wcsnicmp
API _o__wcsnicmp_l
API _o__wcsnicoll
API _o__wcsnicoll_l
API _o__wcsnset
API _o__wcsnset_s
API _o__wcsset
API _o__wcsset_s
API _o__wcstod_l
API _o__wcstof_l
API _o_wcstoll
API _o__wcstoll_l
API _o__wcstol_l
API _o__wcstod_l
API _o__wcstoll_l
API _o__wcstombs_l
API _o__wcstombs_s_l
API _o_wcstoull
API _o__wcstoui64_l
API _o__wcstoul_l
API _o__wcstoui64_l
API _o__wcsupr
API _o__wcsupr_l
API _o__wcsupr_s
API _o__wcsupr_s_l
API _o__wcsxfrm_l
API _o__wctime32
API _o__wctime32_s
API _o__wctime64
API _o__wctime64_s
API _o__wctomb_l
API _o__wctomb_s_l
API _o__wdupenv_s
API _o__wexecv
API _o__wexecve
API _o__wexecvp
API _o__wexecvpe
API _o__wfdopen
API _o__wfindfirst32
API _o__wfindfirst32i64
API _o__wfindfirst64
API _o__wfindfirst64i32
API _o__wfindnext32
API _o__wfindnext32i64
API _o__wfindnext64
API _o__wfindnext64i32
API _o__wfopen
API _o__wfopen_s
API _o__wfreopen
API _o__wfreopen_s
API _o__wfsopen
API _o__wfullpath
API _o__wgetcwd
API _o__wgetdcwd
API _o__wgetenv
API _o__wgetenv_s
API _o__wmakepath
API _o__wmakepath_s
API _o__wmkdir
API _o__wmktemp
API _o__wmktemp_s
API _o__wperror
API _o__wpopen
API _o__wputenv
API _o__wputenv_s
API _o__wremove
API _o__wrename
API _o__write
API _o__wrmdir
API _o__wsearchenv
API _o__wsearchenv_s
API _o__wsetlocale
API _o__wsopen_dispatch
API _o__wsopen_s
API _o__wspawnv
API _o__wspawnve
API _o__wspawnvp
API _o__wspawnvpe
API _o__wsplitpath
API _o__wsplitpath_s
API _o__wstat32
API _o__wstat32i64
API _o__wstat64
API _o__wstat64i32
API _o__wstrdate
API _o__wstrdate_s
API _o__wstrtime
API _o__wstrtime_s
API _o__wsystem
API _o__wtmpnam_s
API _o__wtof
API _o__wtof_l
API _o__wtoi
API _o__wtoll
API _o__wtoll_l
API _o__wtoi_l
API _o__wtol
API _o__wtol_l
API _o__wtoll
API _o__wtoll_l
API _o__wunlink
API _o__wutime32
API _o__wutime64
API _o__y0
API _o__y1
API _o__yn
API _o_abort
API _o_acos
API _o_acosf
API _o_acosh
API _o_acoshf
API _o_acoshl
API _o_asctime
API _o_asctime_s
API _o_asin
API _o_asinf
API _o_asinh
API _o_asinhf
API _o_asinhl
API _o_atan
API _o_atan2
API _o_atan2f
API _o_atanf
API _o_atanh
API _o_atanhf
API _o_atanhl
API _o_atof
API _o_atoi
API _o_atol
API _o_atoll
API _o_bsearch
API _o_bsearch_s
API _o_btowc
API _o_calloc
API _o_cbrt
API _o_cbrtf
API _o_ceil
API _o_ceilf
API _o_clearerr
API _o_clearerr_s
API _o_cos
API _o_cosf
API _o_cosh
API _o_coshf
API _o_erf
API _o_erfc
API _o_erfcf
API _o_erfcl
API _o_erff
API _o_erfl
API _o_exit
API _o_exp
API _o_exp2
API _o_exp2f
API _o_exp2l
API _o_expf
API _o_fabs
API _o_fclose
API _o_feof
API _o_ferror
API _o_fflush
API _o_fgetc
API _o_fgetpos
API _o_fgets
API _o_fgetwc
API _o_fgetws
API _o_floor
API _o_floorf
API _o_fma
API _o_fmaf
API _o_fmal
API _o_fmod
API _o_fmodf
API _o_fopen
API _o_fopen_s
API _o_fputc
API _o_fputs
API _o_fputwc
API _o_fputws
API _o_fread
API _o_fread_s
API _o_free
API _o_freopen
API _o_freopen_s
API _o_frexp
API _o_fseek
API _o_fsetpos
API _o_ftell
API _o_fwrite
API _o_getc
API _o_getchar
API _o_getenv
API _o_getenv_s
API _o_gets
API _o_gets_s
API _o_getwc
API _o_getwchar
API _o_hypot
API _o_is_wctype
API _o_isalnum
API _o_isalpha
API _o_isblank
API _o_iscntrl
API _o_isdigit
API _o_isgraph
API _o_isleadbyte
API _o_islower
API _o_isprint
API _o_ispunct
API _o_isspace
API _o_isupper
API _o_iswalnum
API _o_iswalpha
API _o_iswascii
API _o_iswblank
API _o_iswcntrl
API _o_iswctype
API _o_iswdigit
API _o_iswgraph
API _o_iswlower
API _o_iswprint
API _o_iswpunct
API _o_iswspace
API _o_iswupper
API _o_iswxdigit
API _o_isxdigit
API _o_ldexp
API _o_lgamma
API _o_lgammaf
API _o_lgammal
API _o_llrint
API _o_llrintf
API _o_llrintl
API _o_llround
API _o_llroundf
API _o_llroundl
API _o_localeconv
API _o_log
API _o_log10
API _o_log10f
API _o_log1p
API _o_log1pf
API _o_log1pl
API _o_log2
API _o_log2f
API _o_log2l
API _o_logb
API _o_logbf
API _o_logbl
API _o_logf
API _o_lrint
API _o_lrintf
API _o_lrintl
API _o_lround
API _o_lroundf
API _o_lroundl
API _o_malloc
API _o_mblen
API _o_mbrlen
API _o_mbrtoc16
API _o_mbrtoc32
API _o_mbrtowc
API _o_mbsrtowcs
API _o_mbsrtowcs_s
API _o_mbstowcs
API _o_mbstowcs_s
API _o_mbtowc
API _o_memcpy_s
API memset
API _o_modf
API _o_modff
API _o_nan
API _o_nanf
API _o_nanl
API _o_nearbyintl
API _o_nearbyintf
API _o_nearbyintl
API _o_nextafter
API _o_nextafterf
API _o_nextafterl
API _o_nexttoward
API _o_nexttowardf
API _o_nexttowardl
API _o_pow
API _o_powf
API _o_putc
API _o_putchar
API _o_puts
API _o_putwc
API _o_putwchar
API _o_qsort
API _o_qsort_s
API _o_raise
API _o_rand
API _o_rand_s
API _o_realloc
API _o_remainder
API _o_remainderf
API _o_remainderl
API _o_remove
API _o_remquo
API _o_remquof
API _o_remquol
API _o_rename
API _o_rewind
API _o_rintl
API _o_rintf
API _o_rintl
API _o_round
API _o_roundf
API _o_round
API _o_scalbln
API _o_scalblnf
API _o_scalblnl
API _o_scalbnl
API _o_scalbnf
API _o_scalbnl
API _o_set_terminate
API _o_setbuf
API _o_setlocale
API _o_setvbuf
API _o_sin
API _o_sinf
API _o_sinh
API _o_sinhf
API _o_sqrt
API _o_sqrtf
API _o_srand
API _o_strcat_s
API _o_strcoll
API _o_strcpy_s
API _o_strerror
API _o_strerror_s
API _o_strftime
API _o_strncat_s
API _o_strncpy_s
API _o_strtod
API _o_strtof
API _o_strtok
API _o_strtok_s
API _o_strtol
API _o_strtold
API _o__strtoi64
API _o_strtoul
API _o__strtoui64
API _o_system
API _o_tan
API _o_tanf
API _o_tanh
API _o_tanhf
API _o_terminate
API _o_tgamma
API _o_tgammaf
API _o_tgammal
API _o_tmpfile_s
API _o_tmpnam_s
API _o_tolower
API _o_toupper
API _o_towlower
API _o_towupper
API _o_ungetc
API _o_ungetwc
API _o_wcrtomb
API _o_wcrtomb_s
API _o_wcscat_s
API _o_wcscoll
API _o_wcscpy
API _o_wcscpy_s
API _o_wcsftime
API _o_wcsncat_s
API _o_wcsncpy_s
API _o_wcsrtombs
API _o_wcsrtombs_s
API _o_wcstod
API _o_wcstof
API _o_wcstok
API _o_wcstok_s
API _o_wcstol
API _o_wcstold
API _o_wcstoll
API _o_wcstombs
API _o_wcstombs_s
API _o_wcstoul
API _o_wcstoull
API _o_wctob
API _o_wctomb
API _o_wctomb_s
API _o_wmemcpy_s
API _o_wmemmove_s
API _open
API _open_osfhandle
API _pclose
API _pipe
API _popen
API _purecall
API _putc_nolock
API _putch
API _putch_nolock
API _putenv
API _putenv_s
API _putw
API _putwc_nolock
API _putwch
API _putwch_nolock
API _putws
API _query_app_type
API _query_new_handler
API _query_new_mode
API _read
API _realloc_base
API _recalloc
API _register_onexit_function
API _register_thread_local_exe_atexit_callback
API _resetstkoflw
API _rmdir
API _rmtmp
API _rotl
API _rotl64
API _rotr
API _rotr64
API _scalb
API _scalbf
API _searchenv
API _searchenv_s
API _seh_filter_dll
API _seh_filter_exe
API _set_FMA3_enable
API _set_abort_behavior
API _set_app_type
API _set_controlfp
API _set_doserrno
API _set_errno
API _set_error_mode
API _set_fmode
API _set_invalid_parameter_handler
API _set_new_handler
API _set_new_mode
API _set_printf_count_output
API _set_purecall_handler
API _set_se_translator
API _set_thread_local_invalid_parameter_handler
API _seterrormode
API _setmaxstdio
API _setmbcp
API _setmode
API _setsystime
API _sleep
API _sopen
API _sopen_dispatch
API _sopen_s
API _spawnl
API _spawnle
API _spawnlp
API _spawnlpe
API _spawnv
API _spawnve
API _spawnvp
API _spawnvpe
API _splitpath
API _splitpath_s
API _stat32
API _stat32i64
API _stat64
API _stat64i32
API _statusfp
API _strcoll_l
API _strdate
API _strdate_s
API _mbsdup
API _strerror
API _strerror_s
API _strftime_l
API _stricmp
API _stricmp_l
API _stricoll
API _stricoll_l
API _strlwr
API _strlwr_l
API _strlwr_s
API _strlwr_s_l
API _strncoll
API _strncoll_l
API _strnicmp
API _strnicmp_l
API _strnicoll
API _strnicoll_l
API _strnset
API _strnset_s
API _strrev
API _strset
API _strset_s
API _strtime
API _strtime_s
API _strtold_l
API _strtof_l
API strtoll
API _strtoi64_l
API _strtoi64_l
API _strtol_l
API _strtold_l
API _strtoi64_l
API _strtoui64
API _strtoui64_l
API _strtoul_l
API _strtoui64_l
API _strtoui64_l
API _strupr
API _strupr_l
API _strupr_s
API _strupr_s_l
API _strxfrm_l
API _swab
API _tell
API _telli64
API _tempnam
API _time32
API _time64
API _timespec32_get
API _timespec64_get
API _tolower
API _tolower_l
API _toupper
API _toupper_l
API _towlower_l
API _towupper_l
API _tzset
API _ui64toa
API _ui64toa_s
API _ui64tow
API _ui64tow_s
API _ultoa
API _ultoa_s
API _ultow
API _ultow_s
API _umask
API _umask_s
API _ungetc_nolock
API _ungetch
API _ungetch_nolock
API _ungetwc_nolock
API _ungetwch
API _ungetwch_nolock
API _unlink
API _unloaddll
API _unlock_file
API _unlock_locales
API _utime32
API _utime64
API _waccess
API _waccess_s
API _wasctime
API _wasctime_s
API _wassert
API _wchdir
API _wchmod
API _wcreat
API _wcreate_locale
API _wcscoll_l
API _wcsdup
API _wcserror
API _wcserror_s
API _wcsftime_l
API _wcsicmp
API _wcsicmp_l
API _wcsicoll
API _wcsicoll_l
API _wcslwr
API _wcslwr_l
API _wcslwr_s
API _wcslwr_s_l
API _wcsncoll
API _wcsncoll_l
API _wcsnicmp
API _wcsnicmp_l
API _wcsnicoll
API _wcsnicoll_l
API _wcsnset
API _wcsnset_s
API _wcsrev
API _wcsset
API _wcsset_s
API _wcstold_l
API _wcstof_l
API wcstoll
API _wcstoi64_l
API _wcstoi64_l
API _wcstol_l
API _wcstold_l
API _wcstoi64_l
API _wcstombs_l
API _wcstombs_s_l
API _wcstoui64
API _wcstoull_l
API _wcstoul_l
API _wcstoull_l
API _wcstoull_l
API _wcsupr
API _wcsupr_l
API _wcsupr_s
API _wcsupr_s_l
API _wcsxfrm_l
API _wctime32
API _wctime32_s
API _wctime64
API _wctime64_s
API _wctomb_l
API _wctomb_s_l
API _wctype
API _wdupenv_s
API _wexecl
API _wexecle
API _wexeclp
API _wexeclpe
API _wexecv
API _wexecve
API _wexecvp
API _wexecvpe
API _wfdopen
API _wfindfirst32
API _wfindfirst32i64
API _wfindfirst64
API _wfindfirst64i32
API _wfindnext32
API _wfindnext32i64
API _wfindnext64
API _wfindnext64i32
API _wfopen
API _wfopen_s
API _wfreopen
API _wfreopen_s
API _wfsopen
API _wfullpath
API _wgetcwd
API _wgetdcwd
API _wgetenv
API _wgetenv_s
API _wmakepath
API _wmakepath_s
API _wmkdir
API _wmktemp
API _wmktemp_s
API _wopen
API _wperror
API _wpopen
API _wputenv
API _wputenv_s
API _wremove
API _wrename
API _write
API _wrmdir
API _wsearchenv
API _wsearchenv_s
API _wsetlocale
API _wsopen
API _wsopen_dispatch
API _wsopen_s
API _wspawnl
API _wspawnle
API _wspawnlp
API _wspawnlpe
API _wspawnv
API _wspawnve
API _wspawnvp
API _wspawnvpe
API _wsplitpath
API _wsplitpath_s
API _wstat32
API _wstat32i64
API _wstat64
API _wstat64i32
API _wstrdate
API _wstrdate_s
API _wstrtime
API _wstrtime_s
API _wsystem
API _wtempnam
API _wtmpnam
API _wtmpnam_s
API _wtof
API _wtof_l
API _wtoi
API _wtoll
API _wtoll_l
API _wtoi_l
API _wtol
API _wtol_l
API _wtoll
API _wtoll_l
API _wunlink
API _wutime32
API _wutime64
API _y0
API _y1
API _yn
API abort
API abs
API acos
API acosf
API acosh
API acoshf
API acoshl
API asctime
API asctime_s
API asin
API asinf
API asinh
API asinhf
API asinhl
API atan
API atan2
API atan2f
API atanf
API atanh
API atanhf
API atanhl
API atof
API atoi
API atol
API _atoi64
API bsearch
API bsearch_s
API btowc
API c16rtomb
API c32rtomb
API cabs
API cabsf
API cabsl
API cacos
API cacosf
API cacosh
API cacoshf
API cacoshl
API cacosl
API calloc
API carg
API cargf
API cargl
API casin
API casinf
API casinh
API casinhf
API casinhl
API casinl
API catan
API catanf
API catanh
API catanhf
API catanhl
API catanl
API cbrt
API cbrtf
API cbrt
API ccos
API ccosf
API ccosh
API ccoshf
API ccoshl
API ccosl
API ceil
API ceilf
API cexp
API cexpf
API cexpl
API cimag
API cimagf
API cimagl
API clearerr
API clearerr_s
API clock
API clog
API clog10
API clog10f
API clog10l
API clogf
API clogl
API conj
API conjf
API conjl
API copysignl
API copysignf
API copysignl
API cos
API cosf
API cosh
API coshf
API cpow
API cpowf
API cpowl
API cproj
API cprojf
API cprojl
API creal
API crealf
API creall
API csin
API csinf
API csinh
API csinhf
API csinhl
API csinl
API csqrt
API csqrtf
API csqrtl
API ctan
API ctanf
API ctanh
API ctanhf
API ctanhl
API ctanl
API $div
API erf
API erfc
API erfcf
API erfcl
API erff
API erfl
API exit
API exp
API exp2
API exp2f
API exp2l
API expf
API expm1
API expm1f
API expm1
API $fabs
API fclose
API fdiml
API fdimf
API fdiml
API feclearexcept
API fegetenv
API fegetexceptflag
API fegetround
API feholdexcept
API feof
API ferror
API fesetenv
API fesetexceptflag
API fesetround
API fetestexcept
API fflush
API fgetc
API fgetpos
API fgets
API fgetwc
API fgetws
API floor
API floorf
API fma
API fmaf
API fmal
API fmax
API fmaxf
API fmax
API fmin
API fminf
API fmin
API fmod
API fmodf
API fopen
API fopen_s
API fputc
API fputs
API fputwc
API fputws
API fread
API fread_s
API free
API freopen
API freopen_s
API frexp
API fseek
API fsetpos
API ftell
API fwrite
API getc
API _fgetchar
API getenv
API getenv_s
API gets
API gets_s
API getwc
API _fgetwchar
API hypot
API ilogbl
API ilogbf
API ilogbl
API _abs64
API imaxdiv
API is_wctype
API isalnum
API isalpha
API isblank
API iscntrl
API isdigit
API isgraph
API isleadbyte
API islower
API isprint
API ispunct
API isspace
API isupper
API iswalnum
API iswalpha
API iswascii
API iswblank
API iswcntrl
API iswctype
API iswdigit
API iswgraph
API iswlower
API iswprint
API iswpunct
API iswspace
API iswupper
API iswxdigit
API isxdigit
API labs
API ldexp
API ldiv
API lgamma
API lgammaf
API lgammal
API _abs64
API lldiv
API llrintl
API llrintf
API llrintl
API llround
API llroundf
API llround
API localeconv
API log
API log10
API log10f
API log1p
API log1pf
API log1pl
API log2
API log2f
API log2l
API logb
API logbf
API logbl
API logf
API longjmp
API lrint
API lrintf
API lrint
API lroundl
API lroundf
API lroundl
API malloc
API mblen
API mbrlen
API mbrtoc16
API mbrtoc32
API mbrtowc
API mbsrtowcs
API mbsrtowcs_s
API mbstowcs
API mbstowcs_s
API mbtowc
API memchr
API memcmp
API memmove
API memcpy_s
API memmove
API memmove_s
API memset
API modf
API modff
API nan
API nanf
API nanl
API nearbyint
API nearbyintf
API nearbyint
API nextafterl
API nextafterf
API nextafterl
API nexttowardl
API nexttowardf
API nexttowardl
API norm
API normf
API norml
API perror
API pow
API powf
API putc
API putchar
API puts
API putwc
API putwchar
API qsort
API qsort_s
API quick_exit
API raise
API rand
API rand_s
API realloc
API remainder
API remainderf
API remainderl
API remove
API remquo
API remquof
API remquol
API rename
API rewind
API rintl
API rintf
API rintl
API roundl
API roundf
API roundl
API scalblnl
API scalblnf
API scalblnl
API scalbnl
API scalbnf
API scalbnl
API set_terminate
API set_unexpected
API setbuf
API setjmp
API setlocale
API setvbuf
API signal
API sin
API sinf
API sinh
API sinhf
API sqrt
API sqrtf
API srand
API strcat
API strcat_s
API strchr
API strcmp
API strcoll
API strcpy
API strcpy_s
API strcspn
API strerror
API strerror_s
API strftime
API strlen
API strncat
API strncat_s
API strncmp
API strncpy
API strncpy_s
API strnlen
API strpbrk
API strrchr
API strspn
API strstr
API strtod
API strtof
API strtoll
API strtok
API strtok_s
API strtol
API strtold
API strtoll
API strtoul
API _strtoui64
API _strtoui64
API strxfrm
API system
API tan
API tanf
API tanh
API tanhf
API terminate
API tgamma
API tgammaf
API tgammal
API tmpfile
API tmpfile_s
API tmpnam
API tmpnam_s
API tolower
API toupper
API towctrans
API towlower
API towupper
API trunc
API truncf
API trunc
API unexpected
API ungetc
API ungetwc
API wcrtomb
API wcrtomb_s
API wcscat
API wcscat_s
API wcschr
API wcscmp
API wcscoll
API wcscpy
API wcscpy_s
API wcscspn
API wcsftime
API wcslen
API wcsncat
API wcsncat_s
API wcsncmp
API wcsncpy
API wcsncpy_s
API wcsnlen
API wcspbrk
API wcsrchr
API wcsrtombs
API wcsrtombs_s
API wcsspn
API wcsstr
API wcstold
API wcstof
API wcstoll
API wcstok
API wcstok_s
API wcstol
API wcstold
API wcstoll
API wcstombs
API wcstombs_s
API wcstoul
API _wcstoui64
API _wcstoui64
API wcsxfrm
API wctob
API wctomb
API wctomb_s
API wctrans
API wctype
API wmemcpy_s
API wmemmove_s

end
