.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API __CIacos
API __CIasin
API __CIatan
API __CIatan2
API __CIcos
API __CIcosh
API __CIexp
API __CIfmod
API __CIlog
API __CIlog10
API __CIpow
API __CIsin
API __CIsinh
API __CIsqrt
API __CItan
API __CItanh
API __LCbuild
API __Cmulcc
API __LCmulcr
API __CreateFrameInfo
API __CxxThrowException@8
API __EH_prolog
API __exit
API __FCbuild
API __FCmulcc
API __FCmulcr
API __FindAndUnlinkFrame
API __Getdays
API __Getmonths
API __Gettnames
API __IsExceptionObjectToBeDestroyed
API __LCbuild
API __Cmulcc
API __LCmulcr
API __NLG_Dispatch
API __NLG_Return
API __NLG_Return2
API __SetWinRTOutOfMemoryExceptionCallback
API __Strftime
API __W_Getdays
API __W_Getmonths
API __W_Gettnames
API __Wcsftime
API ___AdjustPointer
API ___BuildCatchObject
API ___BuildCatchObjectHelper
API ___CxxDetectRethrow
API ___CxxExceptionFilter
API ___CxxFrameHandler2
API ___CxxFrameHandler2
API ___CxxFrameHandler2
API ___CxxLongjmpUnwind@4
API ___CxxQueryExceptionSize
API ___CxxRegisterExceptionObject
API ___CxxUnregisterExceptionObject
API ___DestructExceptionObject
API ___FrameUnwindFilter
API ___GetPlatformExceptionInfo
API ___RTCastToVoid
API ___RTDynamicCast
API ___RTtypeid
API ___TypeMatch
API ____lc_codepage_func
API ____lc_collate_cp_func
API ____lc_locale_name_func
API ____mb_cur_max_func
API ____mb_cur_max_l_func
API ___acrt_iob_func
API ___conio_common_vcprintf
API ___conio_common_vcprintf_p
API ___conio_common_vcprintf_s
API ___conio_common_vcscanf
API ___conio_common_vcwprintf
API ___conio_common_vcwprintf_p
API ___conio_common_vcwprintf_s
API ___conio_common_vcwscanf
API ___control87_2
API ___current_exception
API ___current_exception_context
API ___daylight
API ___dcrt_get_wide_environment_from_os
API __dcrt_initial_narrow_environment
API ___doserrno
API ___dstbias
API ___fpe_flt_rounds
API ___fpecode
API ___initialize_lconv_for_unsigned_char
API ___intrinsic_abnormal_termination
API ___intrinsic_setjmp
API ___isascii
API ___iscsym
API ___iscsymf
API ___iswcsym
API __iswcsymf_l
API ___libm_sse2_acos
API ___libm_sse2_acosf
API ___libm_sse2_asin
API ___libm_sse2_asinf
API ___libm_sse2_atan
API ___libm_sse2_atan2
API ___libm_sse2_atanf
API ___libm_sse2_cos
API ___libm_sse2_cosf
API ___libm_sse2_exp
API ___libm_sse2_expf
API ___libm_sse2_log
API ___libm_sse2_log10
API ___libm_sse2_log10f
API ___libm_sse2_logf
API ___libm_sse2_pow
API ___libm_sse2_powf
API ___libm_sse2_sin
API ___libm_sse2_sinf
API ___libm_sse2_tan
API ___libm_sse2_tanf
API ___p___argc
API ___p___argv
API ___p___wargv
API ___p__acmdln
API ___p__commode
API ___p__environ
API ___p__fmode
API ___p__mbcasemap
API ___p__mbctype
API ___p__pgmptr
API ___p__wcmdln
API ___p__wenviron
API ___p__wpgmptr
API ___pctype_func
API ___processing_throw
API ___pwctype_func
API ___pxcptinfoptrs
API ___report_gsfailure
API ___setusermatherr
API ___std_exception_copy
API ___std_exception_destroy
API ___std_terminate
API ___std_type_info_compare
API ___std_type_info_destroy_list
API ___std_type_info_hash
API ___std_type_info_name
API ___stdio_common_vfprintf
API ___stdio_common_vfprintf_p
API ___stdio_common_vfprintf_s
API ___stdio_common_vfscanf
API ___stdio_common_vfwprintf
API ___stdio_common_vfwprintf_p
API ___stdio_common_vfwprintf_s
API ___stdio_common_vfwscanf
API ___stdio_common_vsnprintf_s
API ___stdio_common_vsnwprintf_s
API ___stdio_common_vsprintf
API ___stdio_common_vsprintf_p
API ___stdio_common_vsprintf_s
API ___stdio_common_vsscanf
API ___stdio_common_vswprintf
API ___stdio_common_vswprintf_p
API ___stdio_common_vswprintf_s
API ___stdio_common_vswscanf
API ___strncnt
API ___sys_errlist
API ___sys_nerr
API ___threadhandle
API ___threadid
API ___timezone
API ___toascii
API ___tzname
API ___unDName
API ___unDNameEx
API ___uncaught_exception
API ___uncaught_exceptions
API ___wcserror
API ___wcserror_s
API ___wcsncnt
API __abs64
API __access
API __access_s
API __aligned_free
API __aligned_malloc
API __aligned_msize
API __aligned_offset_malloc
API __aligned_offset_realloc
API __aligned_offset_recalloc
API __aligned_realloc
API __aligned_recalloc
API __assert
API __atodbl
API __atodbl_l
API __atof_l
API __atoflt
API __atoflt_l
API _atoll
API __atoi64_l
API __atol_l
API __atol_l
API __atoldbl
API __atoldbl_l
API __atoi64_l
API __beep
API __beginthread
API __beginthreadex
API __byteswap_uint64
API __byteswap_ulong
API __byteswap_ushort
API __c_exit
API __cabs
API __callnewh
API __calloc_base
API __cexit
API __cgets
API __cgets_s
API __cgetws
API __cgetws_s
API __chdir
API __chdrive
API __chgsign
API __chgsignf
API __chkesp
API __chmod
API __chsize
API __chsize_s
API __clearfp
API __close
API __commit
API __configthreadlocale
API __configure_narrow_argv
API __configure_wide_argv
API __control87
API __controlfp
API __controlfp_s
API __copysign
API __copysignf
API __cputs
API __cputws
API __creat
API __create_locale
API __crt_at_quick_exit
API __crt_atexit
API __crt_debugger_hook
API __ctime32
API __ctime32_s
API __ctime64
API __ctime64_s
API __cwait
API __d_int
API __ldclass
API __dexp
API __difftime32
API __difftime64
API __dlog
API __dnorm
API __dpcomp
API __ldpoly
API __dscale
API __dsign
API __dsin
API __ldtest
API __dunscale
API __dup
API __dup2
API __dupenv_s
API __ecvt
API __ecvt_s
API __endthread
API __endthreadex
API __eof
API __errno
API __except1
API __except_handler2
API __except_handler3
API __except_handler4_common
API __execl
API __execle
API __execlp
API __execlpe
API __execute_onexit_table
API __execv
API __execve
API __execvp
API __execvpe
API __exit
API __expand
API __fclose_nolock
API __fcloseall
API __fcvt
API __fcvt_s
API __fd_int
API __fdclass
API __fdexp
API __fdlog
API __fdnorm
API __fdopen
API __fdpcomp
API __fdpoly
API __fdscale
API __fdsign
API __fdsin
API __fdtest
API __fdunscale
API __fflush_nolock
API __fgetc_nolock
API __fgetchar
API __fgetwc_nolock
API _getwchar
API __filelength
API __filelengthi64
API __fileno
API __findclose
API __findfirst32
API __findfirst32i64
API __findfirst64
API __findfirst64i32
API __findnext32
API __findnext32i64
API __findnext64
API __findnext64i32
API __finite
API __flushall
API __fpclass
API __fpieee_flt
API __fpreset
API __fputc_nolock
API __fputchar
API __fputwc_nolock
API __fputwchar
API __fread_nolock
API __fread_nolock_s
API __free_base
API __free_locale
API __fseek_nolock
API __fseeki64
API __fseeki64_nolock
API __fsopen
API __fstat32
API __fstat32i64
API __fstat64
API __fstat64i32
API __ftell_nolock
API __ftelli64
API __ftelli64_nolock
API __ftime32_s
API __ftime32_s
API __ftime64
API __ftime64
API __ftol
API __fullpath
API __futime32
API __futime64
API __fwrite_nolock
API __gcvt
API __gcvt_s
API __get_current_locale
API __get_daylight
API __get_doserrno
API __get_dstbias
API __get_errno
API __get_fmode
API __get_heap_handle
API __get_initial_narrow_environment
API __get_initial_wide_environment
API __get_invalid_parameter_handler
API __get_narrow_winmain_command_line
API __get_osfhandle
API __get_pgmptr
API __get_printf_count_output
API __get_purecall_handler
API __get_stream_buffer_pointers
API __get_terminate
API __get_thread_local_invalid_parameter_handler
API __get_timezone
API __get_tzname
API __get_unexpected
API __get_wide_winmain_command_line
API __get_wpgmptr
API __getc_nolock
API __getch
API __getch_nolock
API __getche
API __getche_nolock
API __getcwd
API __getdcwd
API __getdiskfree
API __getdllprocaddr
API __getdrive
API __getdrives
API __getmaxstdio
API __getmbcp
API __getpid
API __getsystime
API __getw
API __getwc_nolock
API __getwch
API __getwch_nolock
API __getwche
API __getwche_nolock
API __getws
API __getws_s
API __global_unwind2
API __gmtime32
API __gmtime32_s
API __gmtime64
API __gmtime64_s
API __heapchk
API __heapmin
API __heapwalk
API __hypot
API __hypotf
API __i64toa
API __i64toa_s
API __i64tow
API __i64tow_s
API __initialize_narrow_environment
API __initialize_onexit_table
API __initialize_wide_environment
API __initterm
API __initterm_e
API __invalid_parameter_noinfo
API __invalid_parameter_noinfo_noreturn
API __invoke_watson
API __is_exception_typeof
API __isalnum_l
API __isalpha_l
API __isatty
API __isblank_l
API __iscntrl_l
API __isctype
API __isctype_l
API __isdigit_l
API __isgraph_l
API __isleadbyte_l
API __islower_l
API __ismbbalnum
API __ismbbalnum_l
API __ismbbalpha
API __ismbbalpha_l
API __ismbbblank
API __ismbbblank_l
API __ismbbgraph
API __ismbbgraph_l
API __ismbbkalnum
API __ismbbkalnum_l
API __ismbbkana
API __ismbbkana_l
API __ismbbkprint
API __ismbbkprint_l
API __ismbbkpunct
API __ismbbkpunct_l
API __ismbblead
API __ismbblead_l
API __ismbbprint
API __ismbbprint_l
API __ismbbpunct
API __ismbbpunct_l
API __ismbbtrail
API __ismbbtrail_l
API __ismbcalnum
API __ismbcalnum_l
API __ismbcalpha
API __ismbcalpha_l
API __ismbcblank
API __ismbcblank_l
API __ismbcdigit
API __ismbcdigit_l
API __ismbcgraph
API __ismbcgraph_l
API __ismbchira
API __ismbchira_l
API __ismbckata
API __ismbckata_l
API __ismbcl0
API __ismbcl0_l
API __ismbcl1
API __ismbcl1_l
API __ismbcl2
API __ismbcl2_l
API __ismbclegal
API __ismbclegal_l
API __ismbclower
API __ismbclower_l
API __ismbcprint
API __ismbcprint_l
API __ismbcpunct
API __ismbcpunct_l
API __ismbcspace
API __ismbcspace_l
API __ismbcsymbol
API __ismbcsymbol_l
API __ismbcupper
API __ismbcupper_l
API __ismbslead
API __ismbslead_l
API __ismbstrail
API __ismbstrail_l
API __isnan
API __isprint_l
API __ispunct_l
API __isspace_l
API __isupper_l
API _iswalnum
API __iswalpha_l
API _iswblank
API __iswcntrl_l
API ___iswcsym
API __iswcsymf_l
API __iswctype_l
API __iswdigit_l
API __iswgraph_l
API _iswlower
API _iswprint
API __iswpunct_l
API __iswspace_l
API _iswupper
API _iswxdigit
API __isxdigit_l
API __itoa
API __itoa_s
API __itow
API __itow_s
API __j0
API __j1
API __jn
API __kbhit
API __ld_int
API __ldclass
API __ldexp
API __ldlog
API __dpcomp
API __ldpoly
API __ldscale
API __dsign
API __ldsin
API __ldtest
API __ldunscale
API __lfind
API __lfind_s
API __libm_sse2_acos_precise
API __libm_sse2_asin_precise
API __libm_sse2_atan_precise
API __libm_sse2_cos_precise
API __libm_sse2_exp_precise
API __libm_sse2_log10_precise
API __libm_sse2_log_precise
API __libm_sse2_pow_precise
API __libm_sse2_sin_precise
API __libm_sse2_sqrt_precise
API __libm_sse2_tan_precise
API __loaddll
API __local_unwind2
API __local_unwind4
API __localtime32
API __localtime32_s
API __localtime64
API __localtime64_s
API __lock_file
API __lock_locales
API __locking
API __logb
API __longjmpex
API __rotl
API __rotr
API __lsearch
API __lsearch_s
API __lseek
API __lseeki64
API __ltoa
API __ltoa_s
API __ltow
API __ltow_s
API __makepath
API __makepath_s
API __malloc_base
API __mbbtombc
API __mbbtombc_l
API __mbbtype
API __mbbtype_l
API _mbcasemap
API __mbccpy
API __mbccpy_l
API __mbccpy_s
API __mbccpy_s_l
API __mbcjistojms
API __mbcjistojms_l
API __mbcjmstojis
API __mbcjmstojis_l
API __mbclen
API __mbclen_l
API __mbctohira
API __mbctohira_l
API __mbctokata
API __mbctokata_l
API __mbctolower
API __mbctolower_l
API __mbctombb
API __mbctombb_l
API __mbctoupper
API __mbctoupper_l
API __mblen_l
API __mbsbtype
API __mbsbtype_l
API __mbscat_s
API __mbscat_s_l
API __mbschr
API __mbschr_l
API __mbscmp
API __mbscmp_l
API __mbscoll
API __mbscoll_l
API __mbscpy_s
API __mbscpy_s_l
API __mbscspn
API __mbscspn_l
API __mbsdec
API __mbsdec_l
API __mbsdup
API __mbsicmp
API __mbsicmp_l
API __mbsicoll
API __mbsicoll_l
API __mbsinc
API __mbsinc_l
API __mbslen
API __mbslen_l
API __mbslwr
API __mbslwr_l
API __mbslwr_s
API __mbslwr_s_l
API __mbsnbcat
API __mbsnbcat_l
API __mbsnbcat_s
API __mbsnbcat_s_l
API __mbsnbcmp
API __mbsnbcmp_l
API __mbsnbcnt
API __mbsnbcnt_l
API __mbsnbcoll
API __mbsnbcoll_l
API __mbsnbcpy
API __mbsnbcpy_l
API __mbsnbcpy_s
API __mbsnbcpy_s_l
API __mbsnbicmp
API __mbsnbicmp_l
API __mbsnbicoll
API __mbsnbicoll_l
API __mbsnbset
API __mbsnbset_l
API __mbsnbset_s
API __mbsnbset_s_l
API __mbsncat
API __mbsncat_l
API __mbsncat_s
API __mbsncat_s_l
API __mbsnccnt
API __mbsnccnt_l
API __mbsncmp
API __mbsncmp_l
API __mbsncoll
API __mbsncoll_l
API __mbsncpy
API __mbsncpy_l
API __mbsncpy_s
API __mbsncpy_s_l
API __mbsnextc
API __mbsnextc_l
API __mbsnicmp
API __mbsnicmp_l
API __mbsnicoll
API __mbsnicoll_l
API __mbsninc
API __mbsninc_l
API __mbsnlen
API __mbsnlen_l
API __mbsnset
API __mbsnset_l
API __mbsnset_s
API __mbsnset_s_l
API __mbspbrk
API __mbspbrk_l
API __mbsrchr
API __mbsrchr_l
API __mbsrev
API __mbsrev_l
API __mbsset
API __mbsset_l
API __mbsset_s
API __mbsset_s_l
API __mbsspn
API __mbsspn_l
API __mbsspnp
API __mbsspnp_l
API __mbsstr
API __mbsstr_l
API __mbstok
API __mbstok_l
API __mbstok_s
API __mbstok_s_l
API __mbstowcs_l
API __mbstowcs_s_l
API __mbstrlen
API __mbstrlen_l
API __mbstrnlen
API __mbstrnlen_l
API __mbsupr
API __mbsupr_l
API __mbsupr_s
API __mbsupr_s_l
API __mbtowc_l
API __memccpy
API __memicmp
API __memicmp_l
API __mkdir
API __mkgmtime32
API __mkgmtime64
API __mktemp
API __mktemp_s
API __mktime32
API __mktime64
API __msize
API __nextafter
API __o__CIacos
API __o__CIasin
API __o__CIatan
API __o__CIatan2
API __o__CIcos
API __o__CIcosh
API __o__CIexp
API __o__CIfmod
API __o__CIlog
API __o__CIlog10
API __o__CIpow
API __o__CIsin
API __o__CIsinh
API __o__CIsqrt
API __o__CItan
API __o__CItanh
API __o__Getdays
API __o__Getmonths
API __o__Gettnames
API __o__Strftime
API __o__W_Getdays
API __o__W_Getmonths
API __o__W_Gettnames
API __o__Wcsftime
API __o____lc_codepage_func
API __o____lc_collate_cp_func
API __o____lc_locale_name_func
API __o____mb_cur_max_func
API __o___acrt_iob_func
API __o___conio_common_vcprintf
API __o___conio_common_vcprintf_p
API __o___conio_common_vcprintf_s
API __o___conio_common_vcscanf
API __o___conio_common_vcwprintf
API __o___conio_common_vcwprintf_p
API __o___conio_common_vcwprintf_s
API __o___conio_common_vcwscanf
API __o___daylight
API __o___dstbias
API __o___fpe_flt_rounds
API __o___libm_sse2_acos
API __o___libm_sse2_acosf
API __o___libm_sse2_asin
API __o___libm_sse2_asinf
API __o___libm_sse2_atan
API __o___libm_sse2_atan2
API __o___libm_sse2_atanf
API __o___libm_sse2_cos
API __o___libm_sse2_cosf
API __o___libm_sse2_exp
API __o___libm_sse2_expf
API __o___libm_sse2_log
API __o___libm_sse2_log10
API __o___libm_sse2_log10f
API __o___libm_sse2_logf
API __o___libm_sse2_pow
API __o___libm_sse2_powf
API __o___libm_sse2_sin
API __o___libm_sse2_sinf
API __o___libm_sse2_tan
API __o___libm_sse2_tanf
API __o___p___argc
API __o___p___argv
API __o___p___wargv
API __o___p__acmdln
API __o___p__commode
API __o___p__environ
API __o___p__fmode
API __o___p__mbcasemap
API __o___p__mbctype
API __o___p__pgmptr
API __o___p__wcmdln
API __o___p__wenviron
API __o___p__wpgmptr
API __o___pctype_func
API __o___pwctype_func
API __o___std_exception_copy
API __o___std_exception_destroy
API __o___std_type_info_destroy_list
API __o___std_type_info_name
API __o___stdio_common_vfprintf
API __o___stdio_common_vfprintf_p
API __o___stdio_common_vfprintf_s
API __o___stdio_common_vfscanf
API __o___stdio_common_vfwprintf
API __o___stdio_common_vfwprintf_p
API __o___stdio_common_vfwprintf_s
API __o___stdio_common_vfwscanf
API __o___stdio_common_vsnprintf_s
API __o___stdio_common_vsnwprintf_s
API __o___stdio_common_vsprintf
API __o___stdio_common_vsprintf_p
API __o___stdio_common_vsprintf_s
API __o___stdio_common_vsscanf
API __o___stdio_common_vswprintf
API __o___stdio_common_vswprintf_p
API __o___stdio_common_vswprintf_s
API __o___stdio_common_vswscanf
API __o___timezone
API __o___tzname
API __o___wcserror
API __o__access
API __o__access_s
API __o__aligned_free
API __o__aligned_malloc
API __o__aligned_msize
API __o__aligned_offset_malloc
API __o__aligned_offset_realloc
API __o__aligned_offset_recalloc
API __o__aligned_realloc
API __o__aligned_recalloc
API __o__atodbl
API __o__atodbl_l
API __o__atof_l
API __o__atoflt
API __o__atoflt_l
API __o_atoll
API __o__atoll_l
API __o__atoi_l
API __o__atoi_l
API __o__atoldbl
API __o__atoldbl_l
API __o__atoll_l
API __o__beep
API __o__beginthread
API __o__beginthreadex
API __o__cabs
API __o__callnewh
API __o__calloc_base
API __o__cexit
API __o__cgets
API __o__cgets_s
API __o__cgetws
API __o__cgetws_s
API __o__chdir
API __o__chdrive
API __o__chmod
API __o__chsize
API __o__chsize_s
API __o__close
API __o__commit
API __o__configthreadlocale
API __o__configure_narrow_argv
API __o__configure_wide_argv
API __o__controlfp_s
API __o__cputs
API __o__cputws
API __o__creat
API __o__create_locale
API __o__crt_atexit
API __o__ctime32_s
API __o__ctime64_s
API __o__cwait
API __o__d_int
API __o__dclass
API __o__difftime32
API __o__difftime64
API __o__dlog
API __o__dnorm
API __o__ldpcomp
API __o__ldpoly
API __o__dscale
API __o__dsign
API __o__dsin
API __o__dtest
API __o__dunscale
API __o__dup
API __o__dup2
API __o__dupenv_s
API __o__ecvt
API __o__ecvt_s
API __o__endthread
API __o__endthreadex
API __o__eof
API __o__errno
API __o__except1
API __o__execute_onexit_table
API __o__execv
API __o__execve
API __o__execvp
API __o__execvpe
API __o__exit
API __o__expand
API __o__fclose_nolock
API __o__fcloseall
API __o__fcvt
API __o__fcvt_s
API __o__fd_int
API __o__fdclass
API __o__fdexp
API __o__fdlog
API __o__fdopen
API __o__fdpcomp
API __o__fdpoly
API __o__fdscale
API __o__fdsign
API __o__fdsin
API __o__fflush_nolock
API __o__fgetc_nolock
API __o_getchar
API __o__fgetwc_nolock
API __o_getwchar
API __o__filelength
API __o__filelengthi64
API __o__fileno
API __o__findclose
API __o__findfirst32
API __o__findfirst32i64
API __o__findfirst64
API __o__findfirst64i32
API __o__findnext32
API __o__findnext32i64
API __o__findnext64
API __o__findnext64i32
API __o__flushall
API __o__fpclass
API __o__fputc_nolock
API __o__fputchar
API __o__fputwc_nolock
API __o__fputwchar
API __o__fread_nolock
API __o__fread_nolock_s
API __o__free_base
API __o__free_locale
API __o__fseek_nolock
API __o__fseeki64
API __o__fseeki64_nolock
API __o__fsopen
API __o__fstat32
API __o__fstat32i64
API __o__fstat64
API __o__fstat64i32
API __o__ftell_nolock
API __o__ftelli64
API __o__ftelli64_nolock
API __o__ftime32
API __o__ftime32_s
API __o__ftime64
API __o__ftime64_s
API __o__fullpath
API __o__futime32
API __o__futime64
API __o__fwrite_nolock
API __o__gcvt
API __o__gcvt_s
API __o__get_daylight
API __o__get_doserrno
API __o__get_dstbias
API __o__get_errno
API __o__get_fmode
API __o__get_heap_handle
API __o__get_initial_narrow_environment
API __o__get_initial_wide_environment
API __o__get_invalid_parameter_handler
API __o__get_narrow_winmain_command_line
API __o__get_osfhandle
API __o__get_pgmptr
API __o__get_stream_buffer_pointers
API __o__get_terminate
API __o__get_thread_local_invalid_parameter_handler
API __o__get_timezone
API __o__get_tzname
API __o__get_wide_winmain_command_line
API __o__get_wpgmptr
API __o__getc_nolock
API __o__getch
API __o__getch_nolock
API __o__getche
API __o__getche_nolock
API __o__getcwd
API __o__getdcwd
API __o__getdiskfree
API __o__getdllprocaddr
API __o__getdrive
API __o__getdrives
API __o__getmbcp
API __o__getsystime
API __o__getw
API __o__getwc_nolock
API __o__getwch
API __o__getwch_nolock
API __o__getwche
API __o__getwche_nolock
API __o__getws
API __o__getws_s
API __o__gmtime32
API __o__gmtime32_s
API __o__gmtime64
API __o__gmtime64_s
API __o__heapchk
API __o__heapmin
API __o__hypot
API __o__hypotf
API __o__i64toa
API __o__i64toa_s
API __o__i64tow
API __o__i64tow_s
API __o__initialize_narrow_environment
API __o__initialize_onexit_table
API __o__initialize_wide_environment
API __o__invalid_parameter_noinfo
API __o__invalid_parameter_noinfo_noreturn
API __o__isatty
API __o__isctype
API __o__isctype_l
API __o__isleadbyte_l
API __o__ismbbalnum
API __o__ismbbalnum_l
API __o__ismbbalpha
API __o__ismbbalpha_l
API __o__ismbbblank
API __o__ismbbblank_l
API __o__ismbbgraph
API __o__ismbbgraph_l
API __o__ismbbkalnum
API __o__ismbbkalnum_l
API __o__ismbbkana
API __o__ismbbkana_l
API __o__ismbbkprint
API __o__ismbbkprint_l
API __o__ismbbkpunct
API __o__ismbbkpunct_l
API __o__ismbblead
API __o__ismbblead_l
API __o__ismbbprint
API __o__ismbbprint_l
API __o__ismbbpunct
API __o__ismbbpunct_l
API __o__ismbbtrail
API __o__ismbbtrail_l
API __o__ismbcalnum
API __o__ismbcalnum_l
API __o__ismbcalpha
API __o__ismbcalpha_l
API __o__ismbcblank
API __o__ismbcblank_l
API __o__ismbcdigit
API __o__ismbcdigit_l
API __o__ismbcgraph
API __o__ismbcgraph_l
API __o__ismbchira
API __o__ismbchira_l
API __o__ismbckata
API __o__ismbckata_l
API __o__ismbcl0
API __o__ismbcl0_l
API __o__ismbcl1
API __o__ismbcl1_l
API __o__ismbcl2
API __o__ismbcl2_l
API __o__ismbclegal
API __o__ismbclegal_l
API __o__ismbclower
API __o__ismbclower_l
API __o__ismbcprint
API __o__ismbcprint_l
API __o__ismbcpunct
API __o__ismbcpunct_l
API __o__ismbcspace
API __o__ismbcspace_l
API __o__ismbcsymbol
API __o__ismbcsymbol_l
API __o__ismbcupper
API __o__ismbcupper_l
API __o__ismbslead
API __o__ismbslead_l
API __o__ismbstrail
API __o__ismbstrail_l
API __o__iswctype_l
API __o__itoa
API __o__itoa_s
API __o__itow
API __o__itow_s
API __o__j0
API __o__j1
API __o__jn
API __o__kbhit
API __o__ld_int
API __o__dclass
API __o__ldexp
API __o__ldlog
API __o__ldpcomp
API __o__ldpoly
API __o__ldscale
API __o__ldsign
API __o__ldsin
API __o__dtest
API __o__ldunscale
API __o__lfind
API __o__lfind_s
API __o__libm_sse2_acos_precise
API __o__libm_sse2_asin_precise
API __o__libm_sse2_atan_precise
API __o__libm_sse2_cos_precise
API __o__libm_sse2_exp_precise
API __o__libm_sse2_log10_precise
API __o__libm_sse2_log_precise
API __o__libm_sse2_pow_precise
API __o__libm_sse2_sin_precise
API __o__libm_sse2_sqrt_precise
API __o__libm_sse2_tan_precise
API __o__loaddll
API __o__localtime32
API __o__localtime32_s
API __o__localtime64
API __o__localtime64_s
API __o__lock_file
API __o__locking
API __o__logb
API __o__lsearch
API __o__lsearch_s
API __o__lseek
API __o__lseeki64
API __o__ltoa
API __o__ltoa_s
API __o__ltow
API __o__ltow_s
API __o__makepath
API __o__makepath_s
API __o__malloc_base
API __o__mbbtombc
API __o__mbbtombc_l
API __o__mbbtype
API __o__mbbtype_l
API __o__mbccpy
API __o__mbccpy_l
API __o__mbccpy_s
API __o__mbccpy_s_l
API __o__mbcjistojms
API __o__mbcjistojms_l
API __o__mbcjmstojis
API __o__mbcjmstojis_l
API __o__mbclen
API __o__mbclen_l
API __o__mbctohira
API __o__mbctohira_l
API __o__mbctokata
API __o__mbctokata_l
API __o__mbctolower
API __o__mbctolower_l
API __o__mbctombb
API __o__mbctombb_l
API __o__mbctoupper
API __o__mbctoupper_l
API __o__mblen_l
API __o__mbsbtype
API __o__mbsbtype_l
API __o__mbscat_s
API __o__mbscat_s_l
API __o__mbschr
API __o__mbschr_l
API __o__mbscmp
API __o__mbscmp_l
API __o__mbscoll
API __o__mbscoll_l
API __o__mbscpy_s
API __o__mbscpy_s_l
API __o__mbscspn
API __o__mbscspn_l
API __o__mbsdec
API __o__mbsdec_l
API __o__mbsicmp
API __o__mbsicmp_l
API __o__mbsicoll
API __o__mbsicoll_l
API __o__mbsinc
API __o__mbsinc_l
API __o__mbslen
API __o__mbslen_l
API __o__mbslwr
API __o__mbslwr_l
API __o__mbslwr_s
API __o__mbslwr_s_l
API __o__mbsnbcat
API __o__mbsnbcat_l
API __o__mbsnbcat_s
API __o__mbsnbcat_s_l
API __o__mbsnbcmp
API __o__mbsnbcmp_l
API __o__mbsnbcnt
API __o__mbsnbcnt_l
API __o__mbsnbcoll
API __o__mbsnbcoll_l
API __o__mbsnbcpy
API __o__mbsnbcpy_l
API __o__mbsnbcpy_s
API __o__mbsnbcpy_s_l
API __o__mbsnbicmp
API __o__mbsnbicmp_l
API __o__mbsnbicoll
API __o__mbsnbicoll_l
API __o__mbsnbset
API __o__mbsnbset_l
API __o__mbsnbset_s
API __o__mbsnbset_s_l
API __o__mbsncat
API __o__mbsncat_l
API __o__mbsncat_s
API __o__mbsncat_s_l
API __o__mbsnccnt
API __o__mbsnccnt_l
API __o__mbsncmp
API __o__mbsncmp_l
API __o__mbsncoll
API __o__mbsncoll_l
API __o__mbsncpy
API __o__mbsncpy_l
API __o__mbsncpy_s
API __o__mbsncpy_s_l
API __o__mbsnextc
API __o__mbsnextc_l
API __o__mbsnicmp
API __o__mbsnicmp_l
API __o__mbsnicoll
API __o__mbsnicoll_l
API __o__mbsninc
API __o__mbsninc_l
API __o__mbsnlen
API __o__mbsnlen_l
API __o__mbsnset
API __o__mbsnset_l
API __o__mbsnset_s
API __o__mbsnset_s_l
API __o__mbspbrk
API __o__mbspbrk_l
API __o__mbsrchr
API __o__mbsrchr_l
API __o__mbsrev
API __o__mbsrev_l
API __o__mbsset
API __o__mbsset_l
API __o__mbsset_s
API __o__mbsset_s_l
API __o__mbsspn
API __o__mbsspn_l
API __o__mbsspnp
API __o__mbsspnp_l
API __o__mbsstr
API __o__mbsstr_l
API __o__mbstok
API __o__mbstok_l
API __o__mbstok_s
API __o__mbstok_s_l
API __o__mbstowcs_l
API __o__mbstowcs_s_l
API __o__mbstrlen
API __o__mbstrlen_l
API __o__mbstrnlen
API __o__mbstrnlen_l
API __o__mbsupr
API __o__mbsupr_l
API __o__mbsupr_s
API __o__mbsupr_s_l
API __o__mbtowc_l
API __o__memicmp
API __o__memicmp_l
API __o__mkdir
API __o__mkgmtime32
API __o__mkgmtime64
API __o__mktemp
API __o__mktemp_s
API __o__mktime32
API __o__mktime64
API __o__msize
API __o__nextafter
API __o__open_osfhandle
API __o__pclose
API __o__pipe
API __o__popen
API __o__purecall
API __o__putc_nolock
API __o__putch
API __o__putch_nolock
API __o__putenv
API __o__putenv_s
API __o__putw
API __o__putwc_nolock
API __o__putwch
API __o__putwch_nolock
API __o__putws
API __o__read
API __o__realloc_base
API __o__recalloc
API __o__register_onexit_function
API __o__resetstkoflw
API __o__rmdir
API __o__rmtmp
API __o__scalb
API __o__searchenv
API __o__searchenv_s
API __o__seh_filter_dll
API __o__seh_filter_exe
API __o__set_abort_behavior
API __o__set_app_type
API __o__set_doserrno
API __o__set_errno
API __o__set_fmode
API __o__set_invalid_parameter_handler
API __o__set_new_handler
API __o__set_new_mode
API __o__set_thread_local_invalid_parameter_handler
API __o__seterrormode
API __o__setmbcp
API __o__setmode
API __o__setsystime
API __o__sleep
API __o__sopen
API __o__sopen_dispatch
API __o__sopen_s
API __o__spawnv
API __o__spawnve
API __o__spawnvp
API __o__spawnvpe
API __o__splitpath
API __o__splitpath_s
API __o__stat32
API __o__stat32i64
API __o__stat64
API __o__stat64i32
API __o__strcoll_l
API __o__strdate
API __o__strdate_s
API __o__strdup
API __o__strerror
API __o__strerror_s
API __o__strftime_l
API __o__stricmp
API __o__stricmp_l
API __o__stricoll
API __o__stricoll_l
API __o__strlwr
API __o__strlwr_l
API __o__strlwr_s
API __o__strlwr_s_l
API __o__strncoll
API __o__strncoll_l
API __o__strnicmp
API __o__strnicmp_l
API __o__strnicoll
API __o__strnicoll_l
API __o__strnset_s
API __o__strset_s
API __o__strtime
API __o__strtime_s
API __o__strtod_l
API __o__strtof_l
API __o_strtoll
API __o__strtoll_l
API __o__strtol_l
API __o__strtod_l
API __o__strtoll_l
API __o__strtoui64
API __o__strtoull_l
API __o__strtoul_l
API __o__strtoull_l
API __o__strupr
API __o__strupr_l
API __o__strupr_s
API __o__strupr_s_l
API __o__strxfrm_l
API __o__swab
API __o__tell
API __o__telli64
API __o__timespec32_get
API __o__timespec64_get
API __o__tolower
API __o__tolower_l
API __o__toupper
API __o__toupper_l
API __o__towlower_l
API __o__towupper_l
API __o__tzset
API __o__ui64toa
API __o__ui64toa_s
API __o__ui64tow
API __o__ui64tow_s
API __o__ultoa
API __o__ultoa_s
API __o__ultow
API __o__ultow_s
API __o__umask
API __o__umask_s
API __o__ungetc_nolock
API __o__ungetch
API __o__ungetch_nolock
API __o__ungetwc_nolock
API __o__ungetwch
API __o__ungetwch_nolock
API __o__unlink
API __o__unloaddll
API __o__unlock_file
API __o__utime32
API __o__utime64
API __o__waccess
API __o__waccess_s
API __o__wasctime
API __o__wasctime_s
API __o__wchdir
API __o__wchmod
API __o__wcreat
API __o__wcreate_locale
API __o__wcscoll_l
API __o__wcsdup
API __o__wcserror
API __o__wcserror_s
API __o__wcsftime_l
API __o__wcsicmp
API __o__wcsicmp_l
API __o__wcsicoll
API __o__wcsicoll_l
API __o__wcslwr
API __o__wcslwr_l
API __o__wcslwr_s
API __o__wcslwr_s_l
API __o__wcsncoll
API __o__wcsncoll_l
API __o__wcsnicmp
API __o__wcsnicmp_l
API __o__wcsnicoll
API __o__wcsnicoll_l
API __o__wcsnset
API __o__wcsnset_s
API __o__wcsset
API __o__wcsset_s
API __o__wcstod_l
API __o__wcstof_l
API __o_wcstoll
API __o__wcstoll_l
API __o__wcstol_l
API __o__wcstod_l
API __o__wcstoll_l
API __o__wcstombs_l
API __o__wcstombs_s_l
API __o__wcstoui64
API __o__wcstoull_l
API __o__wcstoul_l
API __o__wcstoull_l
API __o__wcsupr
API __o__wcsupr_l
API __o__wcsupr_s
API __o__wcsupr_s_l
API __o__wcsxfrm_l
API __o__wctime32
API __o__wctime32_s
API __o__wctime64
API __o__wctime64_s
API __o__wctomb_l
API __o__wctomb_s_l
API __o__wdupenv_s
API __o__wexecv
API __o__wexecve
API __o__wexecvp
API __o__wexecvpe
API __o__wfdopen
API __o__wfindfirst32
API __o__wfindfirst32i64
API __o__wfindfirst64
API __o__wfindfirst64i32
API __o__wfindnext32
API __o__wfindnext32i64
API __o__wfindnext64
API __o__wfindnext64i32
API __o__wfopen
API __o__wfopen_s
API __o__wfreopen
API __o__wfreopen_s
API __o__wfsopen
API __o__wfullpath
API __o__wgetcwd
API __o__wgetdcwd
API __o__wgetenv
API __o__wgetenv_s
API __o__wmakepath
API __o__wmakepath_s
API __o__wmkdir
API __o__wmktemp
API __o__wmktemp_s
API __o__wperror
API __o__wpopen
API __o__wputenv
API __o__wputenv_s
API __o__wremove
API __o__wrename
API __o__write
API __o__wrmdir
API __o__wsearchenv
API __o__wsearchenv_s
API __o__wsetlocale
API __o__wsopen_dispatch
API __o__wsopen_s
API __o__wspawnv
API __o__wspawnve
API __o__wspawnvp
API __o__wspawnvpe
API __o__wsplitpath
API __o__wsplitpath_s
API __o__wstat32
API __o__wstat32i64
API __o__wstat64
API __o__wstat64i32
API __o__wstrdate
API __o__wstrdate_s
API __o__wstrtime
API __o__wstrtime_s
API __o__wsystem
API __o__wtmpnam_s
API __o__wtof
API __o__wtof_l
API __o__wtoi
API __o__wtoi64
API __o__wtoi64_l
API __o__wtoi_l
API __o__wtol
API __o__wtoi_l
API __o__wtoi64
API __o__wtoi64_l
API __o__wunlink
API __o__wutime32
API __o__wutime64
API __o__y0
API __o__y1
API __o__yn
API __o_abort
API __o_acos
API __o_acosh
API __o_acoshf
API __o_acosh
API __o_asctime
API __o_asctime_s
API __o_asin
API __o_asinh
API __o_asinhf
API __o_asinh
API __o_atan
API __o_atan2
API __o_atanhl
API __o_atanhf
API __o_atanhl
API __o_atof
API __o_atoi
API __o_atol
API __o_atoll
API __o_bsearch
API __o_bsearch_s
API __o_btowc
API __o_calloc
API __o_cbrt
API __o_cbrtf
API __o_ceil
API __o_clearerr
API __o_clearerr_s
API __o_cos
API __o_cosh
API __o_erf
API __o_erfc
API __o_erfcf
API __o_erfcl
API __o_erff
API __o_erfl
API __o_exit
API __o_exp
API __o_exp2
API __o_exp2f
API __o_exp2l
API __o_fabs
API __o_fclose
API __o_feof
API __o_ferror
API __o_fflush
API __o_fgetc
API __o_fgetpos
API __o_fgets
API __o_fgetwc
API __o_fgetws
API __o_floor
API __o_fma
API __o_fmaf
API __o_fmal
API __o_fmod
API __o_fopen
API __o_fopen_s
API __o_fputc
API __o_fputs
API __o_fputwc
API __o_fputws
API __o_fread
API __o_fread_s
API __o_free
API __o_freopen
API __o_freopen_s
API __o_frexp
API __o_fseek
API __o_fsetpos
API __o_ftell
API __o_fwrite
API __o_getc
API __o_getchar
API __o_getenv
API __o_getenv_s
API __o_gets
API __o_gets_s
API __o_getwc
API __o_getwchar
API __o__hypot
API __o_is_wctype
API __o_isalnum
API __o_isalpha
API __o_isblank
API __o_iscntrl
API __o_isdigit
API __o_isgraph
API __o_isleadbyte
API __o_islower
API __o_isprint
API __o_ispunct
API __o_isspace
API __o_isupper
API __o_iswalnum
API __o_iswalpha
API __o_iswascii
API __o_iswblank
API __o_iswcntrl
API __o_iswctype
API __o_iswdigit
API __o_iswgraph
API __o_iswlower
API __o_iswprint
API __o_iswpunct
API __o_iswspace
API __o_iswupper
API __o_iswxdigit
API __o_isxdigit
API __o_ldexp
API __o_lgamma
API __o_lgammaf
API __o_lgammal
API __o_llrint
API __o_llrintf
API __o_llrintl
API __o_llround
API __o_llroundf
API __o_llround
API __o_localeconv
API __o_log
API __o_log10
API __o_log1pl
API __o_log1pf
API __o_log1pl
API __o_log2
API __o_log2f
API __o_log2l
API __o_logbl
API __o_logbf
API __o_logbl
API __o_lrint
API __o_lrintf
API __o_lrintl
API __o_lround
API __o_lroundf
API __o_lroundl
API __o_malloc
API __o_mblen
API __o_mbrlen
API __o_mbrtoc16
API __o_mbrtoc32
API __o_mbrtowc
API __o_mbsrtowcs
API __o_mbsrtowcs_s
API __o_mbstowcs
API __o_mbstowcs_s
API __o_mbtowc
API __o_memcpy_s
API _memset
API __o_modf
API __o_nan
API __o_nanf
API __o_nanl
API __o_nearbyint
API __o_nearbyintf
API __o_nearbyintl
API __o__nextafter
API __o_nextafterf
API __o__nextafter
API __o_nexttoward
API __o_nexttowardf
API __o__nextafter
API __o_pow
API __o_powf
API __o_putc
API __o_putchar
API __o_puts
API __o_putwc
API __o_putwchar
API __o_qsort
API __o_qsort_s
API __o_raise
API __o_rand
API __o_rand_s
API __o_realloc
API __o_remainder
API __o_remainderf
API __o_remainder
API __o_remove
API __o_remquo
API __o_remquof
API __o_remquo
API __o_rename
API __o_rewind
API __o_rint
API __o_rintf
API __o_rintl
API __o_round
API __o_roundf
API __o_roundl
API __o_scalbnl
API __o_scalblnf
API __o_scalblnl
API __o_scalbnl
API __o_scalbnf
API __o_scalbnl
API __o_set_terminate
API __o_setbuf
API __o_setlocale
API __o_setvbuf
API __o_sin
API __o_sinh
API __o_sqrt
API __o_srand
API __o_strcat_s
API __o_strcoll
API __o_strcpy_s
API __o_strerror
API __o_strerror_s
API __o_strftime
API __o_strncat_s
API __o_strncpy_s
API __o_strtod
API __o_strtof
API __o_strtok
API __o_strtok_s
API __o_strtol
API __o_strtod
API __o_strtoll
API __o_strtoul
API __o_strtoull
API __o_system
API __o_tan
API __o_tanh
API __o_terminate
API __o_tgamma
API __o_tgammaf
API __o_tgammal
API __o_tmpfile_s
API __o_tmpnam_s
API __o_tolower
API __o_toupper
API __o_towlower
API __o_towupper
API __o_ungetc
API __o_ungetwc
API __o_wcrtomb
API __o_wcrtomb_s
API __o_wcscat_s
API __o_wcscoll
API __o_wcscpy
API __o_wcscpy_s
API __o_wcsftime
API __o_wcsncat_s
API __o_wcsncpy_s
API __o_wcsrtombs
API __o_wcsrtombs_s
API __o_wcstod
API __o_wcstof
API __o_wcstok
API __o_wcstok_s
API __o_wcstol
API __o_wcstod
API __o_wcstoll
API __o_wcstombs
API __o_wcstombs_s
API __o_wcstoul
API __o_wcstoull
API __o_wctob
API __o_wctomb
API __o_wctomb_s
API __o_wmemcpy_s
API __o_wmemmove_s
API __open
API __open_osfhandle
API __pclose
API __pipe
API __popen
API __purecall
API __putc_nolock
API __putch
API __putch_nolock
API __putenv
API __putenv_s
API __putw
API __putwc_nolock
API __putwch
API __putwch_nolock
API __putws
API __query_app_type
API __query_new_handler
API __query_new_mode
API __read
API __realloc_base
API __recalloc
API __register_onexit_function
API __register_thread_local_exe_atexit_callback
API __resetstkoflw
API __rmdir
API __rmtmp
API __rotl
API __rotl64
API __rotr
API __rotr64
API __scalb
API __searchenv
API __searchenv_s
API __seh_filter_dll
API __seh_filter_exe
API __seh_longjmp_unwind@4
API __seh_longjmp_unwind4@4
API __set_SSE2_enable
API __set_abort_behavior
API __set_app_type
API __set_controlfp
API __set_doserrno
API __set_errno
API __set_error_mode
API __set_fmode
API __set_invalid_parameter_handler
API __set_new_handler
API __set_new_mode
API __set_printf_count_output
API __set_purecall_handler
API __set_se_translator
API __set_thread_local_invalid_parameter_handler
API __seterrormode
API __setjmp3
API __setmaxstdio
API __setmbcp
API __setmode
API __setsystime
API __sleep
API __sopen
API __sopen_dispatch
API __sopen_s
API __spawnl
API __spawnle
API __spawnlp
API __spawnlpe
API __spawnv
API __spawnve
API __spawnvp
API __spawnvpe
API __splitpath
API __splitpath_s
API __stat32
API __stat32i64
API __stat64
API __stat64i32
API __statusfp
API __statusfp2
API __strcoll_l
API __strdate
API __strdate_s
API __mbsdup
API __strerror
API __strerror_s
API __strftime_l
API __stricmp
API __stricmp_l
API __stricoll
API __stricoll_l
API __strlwr
API __strlwr_l
API __strlwr_s
API __strlwr_s_l
API __strncoll
API __strncoll_l
API __strnicmp
API __strnicmp_l
API __strnicoll
API __strnicoll_l
API __strnset
API __strnset_s
API __strrev
API __strset
API __strset_s
API __strtime
API __strtime_s
API __strtod_l
API __strtof_l
API __strtoi64
API __strtoimax_l
API __strtoimax_l
API __strtol_l
API __strtod_l
API __strtoimax_l
API _strtoumax
API __strtoumax_l
API __strtoul_l
API __strtoumax_l
API __strtoumax_l
API __strupr
API __strupr_l
API __strupr_s
API __strupr_s_l
API __strxfrm_l
API __swab
API __tell
API __telli64
API __tempnam
API __time32
API __time64
API __timespec32_get
API __timespec64_get
API __tolower
API __tolower_l
API __toupper
API __toupper_l
API __towlower_l
API __towupper_l
API __tzset
API __ui64toa
API __ui64toa_s
API __ui64tow
API __ui64tow_s
API __ultoa
API __ultoa_s
API __ultow
API __ultow_s
API __umask
API __umask_s
API __ungetc_nolock
API __ungetch
API __ungetch_nolock
API __ungetwc_nolock
API __ungetwch
API __ungetwch_nolock
API __unlink
API __unloaddll
API __unlock_file
API __unlock_locales
API __utime32
API __utime64
API __waccess
API __waccess_s
API __wasctime
API __wasctime_s
API __wassert
API __wchdir
API __wchmod
API __wcreat
API __wcreate_locale
API __wcscoll_l
API __wcsdup
API __wcserror
API __wcserror_s
API __wcsftime_l
API __wcsicmp
API __wcsicmp_l
API __wcsicoll
API __wcsicoll_l
API __wcslwr
API __wcslwr_l
API __wcslwr_s
API __wcslwr_s_l
API __wcsncoll
API __wcsncoll_l
API __wcsnicmp
API __wcsnicmp_l
API __wcsnicoll
API __wcsnicoll_l
API __wcsnset
API __wcsnset_s
API __wcsrev
API __wcsset
API __wcsset_s
API __wcstold_l
API __wcstof_l
API __wcstoi64
API __wcstoll_l
API __wcstoll_l
API __wcstol_l
API __wcstold_l
API __wcstoll_l
API __wcstombs_l
API __wcstombs_s_l
API _wcstoumax
API __wcstoumax_l
API __wcstoul_l
API __wcstoumax_l
API __wcstoumax_l
API __wcsupr
API __wcsupr_l
API __wcsupr_s
API __wcsupr_s_l
API __wcsxfrm_l
API __wctime32
API __wctime32_s
API __wctime64
API __wctime64_s
API __wctomb_l
API __wctomb_s_l
API __wctype
API __wdupenv_s
API __wexecl
API __wexecle
API __wexeclp
API __wexeclpe
API __wexecv
API __wexecve
API __wexecvp
API __wexecvpe
API __wfdopen
API __wfindfirst32
API __wfindfirst32i64
API __wfindfirst64
API __wfindfirst64i32
API __wfindnext32
API __wfindnext32i64
API __wfindnext64
API __wfindnext64i32
API __wfopen
API __wfopen_s
API __wfreopen
API __wfreopen_s
API __wfsopen
API __wfullpath
API __wgetcwd
API __wgetdcwd
API __wgetenv
API __wgetenv_s
API __wmakepath
API __wmakepath_s
API __wmkdir
API __wmktemp
API __wmktemp_s
API __wopen
API __wperror
API __wpopen
API __wputenv
API __wputenv_s
API __wremove
API __wrename
API __write
API __wrmdir
API __wsearchenv
API __wsearchenv_s
API __wsetlocale
API __wsopen
API __wsopen_dispatch
API __wsopen_s
API __wspawnl
API __wspawnle
API __wspawnlp
API __wspawnlpe
API __wspawnv
API __wspawnve
API __wspawnvp
API __wspawnvpe
API __wsplitpath
API __wsplitpath_s
API __wstat32
API __wstat32i64
API __wstat64
API __wstat64i32
API __wstrdate
API __wstrdate_s
API __wstrtime
API __wstrtime_s
API __wsystem
API __wtempnam
API __wtmpnam
API __wtmpnam_s
API __wtof
API __wtof_l
API __wtoi
API __wtoll
API __wtoll_l
API __wtol_l
API __wtol
API __wtol_l
API __wtoll
API __wtoll_l
API __wunlink
API __wutime32
API __wutime64
API __y0
API __y1
API __yn
API _abort
API _abs
API _acos
API _acosh
API _acoshf
API _acosh
API _asctime
API _asctime_s
API _asin
API _asinhl
API _asinhf
API _asinhl
API _atan
API _atan2
API _atanh
API _atanhf
API _atanh
API _atof
API _atoi
API _atol
API _atoll
API _bsearch
API _bsearch_s
API _btowc
API _c16rtomb
API _c32rtomb
API __hypot
API _cabsf
API _cabsl
API _cacos
API _cacosf
API _cacosh
API _cacoshf
API _cacoshl
API _cacosl
API _calloc
API _carg
API _cargf
API _cargl
API _casin
API _casinf
API _casinh
API _casinhf
API _casinhl
API _casinl
API _catanl
API _catanf
API _catanhl
API _catanhf
API _catanhl
API _catanl
API _cbrt
API _cbrtf
API _cbrtl
API _ccos
API _ccosf
API _ccoshl
API _ccoshf
API _ccoshl
API _ccos
API _ceil
API _cexpl
API _cexpf
API _cexpl
API _cimag
API _cimagf
API _cimag
API _clearerr
API _clearerr_s
API _clock
API _clogl
API _clog10
API _clog10f
API _clog10
API _clogf
API _clogl
API _conj
API _conjf
API _conj
API _copysign
API _copysignf
API _copysign
API _cos
API _cosh
API _cpow
API _cpowf
API _cpow
API _cproj
API _cprojf
API _cproj
API _creal
API _crealf
API _creal
API _csin
API _csinf
API _csinhl
API _csinhf
API _csinhl
API _csin
API _csqrt
API _csqrtf
API _csqrtl
API _ctanl
API _ctanf
API _ctanhl
API _ctanhf
API _ctanhl
API _ctanl
API _ldiv
API _erf
API _erfc
API _erfcf
API _erfcl
API _erff
API _erfl
API _exit
API _exp
API _exp2
API _exp2f
API _exp2l
API _expm1
API _expm1f
API _expm1
API _fabs
API _fclose
API _fdim
API _fdimf
API _fdim
API _feclearexcept
API _fegetenv
API _fegetexceptflag
API _fegetround
API _feholdexcept
API _feof
API _ferror
API _fesetenv
API _fesetexceptflag
API _fesetround
API _fetestexcept
API _fflush
API _fgetc
API _fgetpos
API _fgets
API _fgetwc
API _fgetws
API _floor
API _fma
API _fmaf
API _fmal
API _fmax
API _fmaxf
API _fmaxl
API _fmin
API _fminf
API _fmin
API _fmod
API _fopen
API _fopen_s
API _fputc
API _fputs
API _fputwc
API _fputws
API _fread
API _fread_s
API _free
API _freopen
API _freopen_s
API _frexp
API _fseek
API _fsetpos
API _ftell
API _fwrite
API _getc
API __fgetchar
API _getenv
API _getenv_s
API _gets
API _gets_s
API _getwc
API _getwchar
API __hypot
API _ilogb
API _ilogbf
API _ilogb
API __abs64
API _imaxdiv
API _is_wctype
API _isalnum
API _isalpha
API _isblank
API _iscntrl
API _isdigit
API _isgraph
API _isleadbyte
API _islower
API _isprint
API _ispunct
API _isspace
API _isupper
API _iswalnum
API __iswalpha_l
API _iswascii
API _iswblank
API __iswcntrl_l
API _iswctype
API __iswdigit_l
API __iswgraph_l
API _iswlower
API _iswprint
API __iswpunct_l
API _iswspace
API _iswupper
API _iswxdigit
API _isxdigit
API _abs
API _ldexp
API _ldiv
API _lgamma
API _lgammaf
API _lgammal
API __abs64
API _lldiv
API _llrint
API _llrintf
API _llrintl
API _llroundl
API _llroundf
API _llroundl
API _localeconv
API _log
API _log10
API _log1p
API _log1pf
API _log1p
API _log2
API _log2f
API _log2l
API _logbl
API _logbf
API _logbl
API _longjmp
API _lrint
API _lrintf
API _lrintl
API _lround
API _lroundf
API _lroundl
API _malloc
API _mblen
API _mbrlen
API _mbrtoc16
API _mbrtoc32
API _mbrtowc
API _mbsrtowcs
API _mbsrtowcs_s
API _mbstowcs
API _mbstowcs_s
API _mbtowc
API _memchr
API _memcmp
API _memcpy
API _memcpy_s
API _memmove
API _memmove_s
API _memset
API _modf
API _nanl
API _nanf
API _nanl
API _nearbyint
API _nearbyintf
API _nearbyintl
API __nextafter
API _nextafterf
API __nextafter
API _nexttoward
API _nexttowardf
API __nextafter
API _norm
API _normf
API _norm
API _perror
API _pow
API _powf
API _putc
API _putchar
API _puts
API _putwc
API _putwchar
API _qsort
API _qsort_s
API _quick_exit
API _raise
API _rand
API _rand_s
API _realloc
API _remainderl
API _remainderf
API _remainderl
API _remove
API _remquo
API _remquof
API _remquo
API _rename
API _rewind
API _rint
API _rintf
API _rintl
API _round
API _roundf
API _roundl
API _scalbln
API _scalblnf
API _scalbln
API _scalbln
API _scalblnf
API _scalbln
API _set_terminate
API _set_unexpected
API _setbuf
API _setlocale
API _setvbuf
API _signal
API _sin
API _sinh
API _sqrt
API _srand
API _strcat
API _strcat_s
API _strchr
API _strcmp
API _strcoll
API _strcpy
API _strcpy_s
API _strcspn
API _strerror
API _strerror_s
API _strftime
API _strlen
API _strncat
API _strncat_s
API _strncmp
API _strncpy
API _strncpy_s
API _strnlen
API _strpbrk
API _strrchr
API _strspn
API _strstr
API _strtold
API _strtof
API __strtoi64
API _strtok
API _strtok_s
API _strtol
API _strtold
API __strtoi64
API _strtoul
API _strtoull
API _strtoumax
API _strxfrm
API _system
API _tan
API _tanh
API _terminate
API _tgamma
API _tgammaf
API _tgammal
API _tmpfile
API _tmpfile_s
API _tmpnam
API _tmpnam_s
API _tolower
API _toupper
API _towctrans
API _towlower
API _towupper
API _trunc
API _truncf
API _truncl
API _unexpected
API _ungetc
API _ungetwc
API _wcrtomb
API _wcrtomb_s
API _wcscat
API _wcscat_s
API _wcschr
API _wcscmp
API _wcscoll
API _wcscpy
API _wcscpy_s
API _wcscspn
API _wcsftime
API _wcslen
API _wcsncat
API _wcsncat_s
API _wcsncmp
API _wcsncpy
API _wcsncpy_s
API _wcsnlen
API _wcspbrk
API _wcsrchr
API _wcsrtombs
API _wcsrtombs_s
API _wcsspn
API _wcsstr
API _wcstod
API _wcstof
API __wcstoi64
API _wcstok
API _wcstok_s
API _wcstol
API _wcstod
API __wcstoi64
API _wcstombs
API _wcstombs_s
API _wcstoul
API _wcstoull
API _wcstoumax
API _wcsxfrm
API _wctob
API _wctomb
API _wctomb_s
API _wctrans
API _wctype
API _wmemcpy_s
API _wmemmove_s

end
