API MACRO name
name proc
name endp
ENDM

.code

API ?AddOrRemoveOCSPISAPIExtension@@YAJHPEAH@Z
API CAAccessCheck
API CAAccessCheckEx
API CAAddCACertificateType
API CAAddCACertificateTypeEx
API CACertTypeAccessCheck
API CACertTypeAccessCheckEx
API CACertTypeAuthzAccessCheck
API CACertTypeGetSecurity
API CACertTypeQuery
API CACertTypeRegisterQuery
API CACertTypeSetSecurity
API CACertTypeUnregisterQuery
API CACloneCertType
API CACloseCA
API CACloseCertType
API CACountCAs
API CACountCertTypes
API CACreateAutoEnrollmentObjectEx
API CACreateCertType
API CACreateLocalAutoEnrollmentObject
API CACreateNewCA
API CADCSetCertTypePropertyEx
API CADeleteCA
API CADeleteCAEx
API CADeleteCertType
API CADeleteCertTypeEx
API CADeleteLocalAutoEnrollmentObject
API CAEnumCertTypes
API CAEnumCertTypesEx
API CAEnumCertTypesForCA
API CAEnumCertTypesForCAEx
API CAEnumFirstCA
API CAEnumNextCA
API CAEnumNextCertType
API CAFindByCertType
API CAFindByIssuerDN
API CAFindByName
API CAFindCertTypeByName
API CAFreeCAProperty
API CAFreeCertTypeExtensions
API CAFreeCertTypeProperty
API CAGetAccessRights
API CAGetCACertificate
API CAGetCAExpiration
API CAGetCAFlags
API CAGetCAProperty
API CAGetCASecurity
API CAGetCertTypeAccessRights
API CAGetCertTypeExpiration
API CAGetCertTypeExtensions
API CAGetCertTypeExtensionsEx
API CAGetCertTypeFlags
API CAGetCertTypeFlagsEx
API CAGetCertTypeKeySpec
API CAGetCertTypeProperty
API CAGetCertTypePropertyEx
API ?CAGetConfigStringFromUIPicker@@YAJPEAUHWND__@@PEAPEAG@Z
API CAGetDN
API CAInstallDefaultCertType
API CAInstallDefaultCertTypeEx
API CAIsCertTypeCurrent
API CAIsCertTypeCurrentEx
API CAIsCertTypeValid
API CAIsValid
API CAOIDAdd
API CAOIDAddEx
API CAOIDCreateNew
API CAOIDCreateNewEx
API CAOIDDelete
API CAOIDDeleteEx
API CAOIDFreeLdapURL
API CAOIDFreeProperty
API CAOIDGetLdapURL
API CAOIDGetProperty
API CAOIDGetPropertyEx
API CAOIDSetProperty
API CAOIDSetPropertyEx
API CARemoveCACertificateType
API CARemoveCACertificateTypeEx
API CASetCACertificate
API CASetCAExpiration
API CASetCAFlags
API CASetCAProperty
API CASetCASecurity
API CASetCertTypeExpiration
API CASetCertTypeExtension
API CASetCertTypeFlags
API CASetCertTypeFlagsEx
API CASetCertTypeKeySpec
API CASetCertTypeProperty
API CASetCertTypePropertyEx
API CAUpdateCA
API CAUpdateCAEx
API CAUpdateCertType
API CAUpdateCertTypeEx
API ?CSPrintAssert@@YAXPEBD0K0@Z
API ?CSPrintError@@YAXPEBDPEBG0KJJ@Z
API ?CSPrintErrorLineFile@@YAXKJ@Z
API ?CSPrintErrorLineFile2@@YAXKJJ@Z
API ?CSPrintErrorLineFileData@@YAXPEBGKJ@Z
API ?CSPrintErrorLineFileData2@@YAXPEBGKJJ@Z
API ?CertcliGetDetailedCertcliVersionString@@YAJPEAPEBG@Z
API ?DbgIsSSActive@@YAHK@Z
API ?DbgLogStringInit@@YAXP6AXPEBD@Z@Z
API ?DbgLogStringInit2@@YA?AW4LogPriority@@P6AXPEBD@ZW41@@Z
API ?DbgPrintf@@YAHKPEBDZZ
API ?DbgPrintfInit@@YAXPEBD@Z
API ?DbgPrintfW@@YAHKPEBGZZ
API ?DecodeFileW@@YAJPEBGPEAPEAEPEAKK@Z
API DllCanUnloadNow
API DllGetClassObject
API DllMain
API DllRegisterServer
API DllRegisterServer
API ?EnableASPInIIS@@YAJPEAH@Z
API ?RemoveVDir@@YAJPEBGPEAH@Z
API ?EncodeToFileW@@YAJPEBGPEBEKK@Z
API ?IsASPEnabledInIIS@@YAJAEA_N@Z
API ?IsASPEnabledInIIS@@YAJAEA_N@Z
API ?IsISAPIExtensionEnabled@@YAJPEBGAEA_N@Z
API ?RemoveISAPIExtension@@YAJPEBG@Z
API ?RemoveVDir@@YAJPEBGPEAH@Z
API ?SplitConfigString@@YAJPEBGPEAPEAG1@Z
API ?WszToMultiByteInteger@@YAJKPEBGPEAKPEAPEAE@Z
API ?WszToMultiByteIntegerBuf@@YAJKPEBGPEAKPEAE@Z
API caTranslateFileTimePeriodToPeriodUnits
API ?myAddShare@@YAJPEBG00HPEAH@Z
API ?myCAPropGetDisplayName@@YAJJPEAPEBG@Z
API ?myCAPropInfoLookup@@YAJPEBU_CAPROP@@JJPEAPEBU1@@Z
API ?myCAPropInfoUnmarshal@@YAJPEBU_CATRANSPROP@@JKPEAPEAU_CAPROP@@@Z
API ?myCryptBinaryToString@@YAJPEBEKKPEAPEAG@Z
API ?myCryptBinaryToStringA@@YAJPEBEKKPEAPEAD@Z
API ?myCryptStringToBinary@@YAJPEBGKKPEAPEAEPEAK22@Z
API ?myCryptStringToBinaryA@@YAJPEBDKKPEAPEAEPEAK22@Z
API ?myDoesDSExist@@YAJH@Z
API ?myEnablePrivilege@@YAJJH@Z
API ?myFreeColumnDisplayNames@@YAXXZ
API ?myGenerateGuidSerialNumber@@YAXPEAU_GUID@@@Z
API ?myGenerateGuidString@@YAJPEAPEAG@Z
API ?myGetErrorMessageText@@YAPEAGJK@Z
API ?myGetErrorMessageText1@@YAPEAGJKPEBG@Z
API ?myGetErrorMessageTextEx@@YAPEAGJKPEAPEBGK@Z
API ?myGetHashAlgorithmOIDInfoFromSignatureAlgorithm@@YAJPEBU_CRYPT_ALGORITHM_IDENTIFIER@@PEAPEBU_CRYPT_OID_INFO@@@Z
API ?myGetSidFromDomain@@YAKPEAGPEAPEAX@Z
API ?myGetTargetMachineDomainDnsName@@YAJPEBGPEAPEAG11@Z
API ?myHExceptionCode@@YAJPEBU_EXCEPTION_POINTERS@@@Z
API ?myHExceptionCodePrint@@YAJPEBU_EXCEPTION_POINTERS@@PEBDKK@Z
API ?myHGetLastError@@YAJXZ
API ?myHResultToStringRaw_old@@YAPEBGPEAGJ@Z
API ?myHResultToString_old@@YAPEBGPEAGJ@Z
API ?myIsDelayLoadHResult@@YAHJ@Z
API ?myJetHResult@@YAJJ@Z
API ?myLogExceptionInit@@YAXP6AXJPEBU_EXCEPTION_POINTERS@@PEBDKK@Z@Z
API ?myModifyVirtualRootsAndFileShares@@YAJKW4ENUM_CATYPES@@KPEAK1@Z
API myNetLogonUser
API ?myOIDHashOIDToString@@YAJPEBGPEAPEAG@Z
API ?myRevertSanitizeName@@YAJPEBGPEAPEAG@Z
API myRobustLdapBind
API myRobustLdapBindEx
API ?mySanitizeName@@YAJPEBGPEAPEAG@Z
API ?mySanitizedNameToDSName@@YAJPEBGPEAPEAG@Z
API ?mySanitizedNameToShortName@@YAJPEBGHPEAPEAG@Z
API ?mylstrcmpiL@@YAHPEBG0@Z
API IsRequestConnectionLocal
API ?myGetCertificateFromPicker@@YAJPEAUHINSTANCE__@@PEAUHWND__@@HHKPEBGKPEAPEAXPEAPEBGKPEBQEBDPEAPEBU_CERT_CONTEXT@@@Z
API ?PingCertServer@@YAJPEBG0PEAPEAG1PEAPEAU_CAINFO@@PEAK1@Z
API CertificateInterfaceInit
API CertServerFreeMemory
API CertServerRetrievePending
API CertServerSubmitRequest
API ?myGetConfigFromPicker@@YAJPEAUHWND__@@PEBG11KHPEAKPEAPEBU_CRYPTUI_CA_CONTEXT@@@Z

end
