.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API ?IsISAPIExtensionEnabled@@YGJPBGAA_N@Z
API _CAAccessCheck@8
API _CAAccessCheckEx@12
API _CAAddCACertificateType@8
API _CAAddCACertificateTypeEx@12
API _CACertTypeAccessCheck@8
API _CACertTypeAccessCheckEx@12
API _CACertTypeAuthzAccessCheck@12
API _CACertTypeGetSecurity@8
API _CACertTypeQuery@8
API _CACertTypeRegisterQuery@12
API _CACertTypeSetSecurity@8
API _CACertTypeUnregisterQuery@4
API _CACloneCertType@24
API _CACloseCA@4
API _CACloseCertType@4
API _CACountCAs@4
API _CACountCertTypes@4
API _CACreateAutoEnrollmentObjectEx@28
API _CACreateCertType@16
API _CACreateLocalAutoEnrollmentObject@16
API _CACreateNewCA@16
API _CADCSetCertTypePropertyEx@16
API _CADeleteCA@4
API _CADeleteCAEx@12
API _CADeleteCertType@4
API _CADeleteCertTypeEx@12
API _CADeleteLocalAutoEnrollmentObject@16
API _CAEnumCertTypes@8
API _CAEnumCertTypesEx@12
API _CAEnumCertTypesForCA@12
API _CAEnumCertTypesForCAEx@16
API _CAEnumFirstCA@12
API _CAEnumNextCA@8
API _CAEnumNextCertType@8
API _CAFindByCertType@16
API _CAFindByIssuerDN@16
API _CAFindByName@16
API _CAFindCertTypeByName@16
API _CAFreeCAProperty@8
API _CAFreeCertTypeExtensions@8
API _CAFreeCertTypeProperty@8
API _CAGetAccessRights@12
API _CAGetCACertificate@8
API _CAGetCAExpiration@12
API _CAGetCAFlags@8
API _CAGetCAProperty@12
API _CAGetCASecurity@8
API _CAGetCertTypeAccessRights@12
API _CAGetCertTypeExpiration@12
API _CAGetCertTypeExtensions@8
API _CAGetCertTypeExtensionsEx@16
API _CAGetCertTypeFlags@8
API _CAGetCertTypeFlagsEx@12
API _CAGetCertTypeKeySpec@8
API _CAGetCertTypeProperty@12
API _CAGetCertTypePropertyEx@12
API ?CAGetConfigStringFromUIPicker@@YGJPAUHWND__@@PAPAG@Z
API _CAGetDN@4
API _CAInstallDefaultCertType@4
API _CAInstallDefaultCertTypeEx@8
API _CAIsCertTypeCurrent@8
API _CAIsCertTypeCurrentEx@12
API _CAIsCertTypeValid@8
API _CAIsValid@8
API _CAOIDAdd@12
API _CAOIDAddEx@16
API _CAOIDCreateNew@12
API _CAOIDCreateNewEx@16
API _CAOIDDelete@4
API _CAOIDDeleteEx@12
API _CAOIDFreeLdapURL@4
API _CAOIDFreeProperty@4
API _CAOIDGetLdapURL@12
API _CAOIDGetProperty@12
API _CAOIDGetPropertyEx@20
API _CAOIDSetProperty@12
API _CAOIDSetPropertyEx@20
API _CARemoveCACertificateType@8
API _CARemoveCACertificateTypeEx@12
API _CASetCACertificate@8
API _CASetCAExpiration@12
API _CASetCAFlags@8
API _CASetCAProperty@12
API _CASetCASecurity@8
API _CASetCertTypeExpiration@12
API _CASetCertTypeExtension@16
API _CASetCertTypeFlags@8
API _CASetCertTypeFlagsEx@12
API _CASetCertTypeKeySpec@8
API _CASetCertTypeProperty@12
API _CASetCertTypePropertyEx@12
API _CAUpdateCA@4
API _CAUpdateCAEx@12
API _CAUpdateCertType@4
API _CAUpdateCertTypeEx@12
API ?CSPrintAssert@@YGXPBD0K0@Z
API ?CSPrintError@@YGXPBDPBG0KJJ@Z
API ?CSPrintErrorLineFile@@YGXKJ@Z
API ?CSPrintErrorLineFile2@@YGXKJJ@Z
API ?CSPrintErrorLineFileData@@YGXPBGKJ@Z
API ?CSPrintErrorLineFileData2@@YGXPBGKJJ@Z
API ?CertcliGetDetailedCertcliVersionString@@YGJPAPBG@Z
API ?DbgIsSSActive@@YGHK@Z
API ?DbgLogStringInit@@YGXP6GXPBD@Z@Z
API ?DbgLogStringInit2@@YG?AW4LogPriority@@P6GXPBD@ZW41@@Z
API ?DbgPrintf@@YAHKPBDZZ
API ?DbgPrintfInit@@YGXPBD@Z
API ?DbgPrintfW@@YAHKPBGZZ
API ?DecodeFileW@@YGJPBGPAPAEPAKK@Z
API _DllCanUnloadNow@0
API _DllGetClassObject@12
API _DllMain@12
API _DllRegisterServer@0
API _DllRegisterServer@0
API ?EnableASPInIIS@@YGJPAH@Z
API ?IsISAPIExtensionEnabled@@YGJPBGAA_N@Z
API ?EncodeToFileW@@YGJPBGPBEKK@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?IsISAPIExtensionEnabled@@YGJPBGAA_N@Z
API ?EnableASPInIIS@@YGJPAH@Z
API ?IsISAPIExtensionEnabled@@YGJPBGAA_N@Z
API ?SplitConfigString@@YGJPBGPAPAG1@Z
API ?WszToMultiByteInteger@@YGJKPBGPAKPAPAE@Z
API ?WszToMultiByteIntegerBuf@@YGJKPBGPAKPAE@Z
API _caTranslateFileTimePeriodToPeriodUnits@16
API ?myModifyVirtualRootsAndFileShares@@YGJKW4ENUM_CATYPES@@KPAK1@Z
API ?myCAPropGetDisplayName@@YGJJPAPBG@Z
API ?myCAPropInfoLookup@@YGJPBU_CAPROP@@JJPAPBU1@@Z
API ?myCAPropInfoUnmarshal@@YGJPBU_CATRANSPROP@@JKPAPAU_CAPROP@@@Z
API ?myCryptBinaryToString@@YGJPBEKKPAPAG@Z
API ?myCryptBinaryToStringA@@YGJPBEKKPAPAD@Z
API ?myCryptStringToBinary@@YGJPBGKKPAPAEPAK22@Z
API ?myCryptStringToBinaryA@@YGJPBDKKPAPAEPAK22@Z
API ?myDoesDSExist@@YGJH@Z
API ?myEnablePrivilege@@YGJJH@Z
API ?myFreeColumnDisplayNames@@YGXXZ
API ?myGenerateGuidSerialNumber@@YGXPAU_GUID@@@Z
API ?myGenerateGuidString@@YGJPAPAG@Z
API ?myGetErrorMessageText@@YGPAGJK@Z
API ?myGetErrorMessageText1@@YGPAGJKPBG@Z
API ?myGetErrorMessageTextEx@@YGPAGJKPAPBGK@Z
API ?myGetHashAlgorithmOIDInfoFromSignatureAlgorithm@@YGJPBU_CRYPT_ALGORITHM_IDENTIFIER@@PAPBU_CRYPT_OID_INFO@@@Z
API ?myGetSidFromDomain@@YGKPAGPAPAX@Z
API ?myGetTargetMachineDomainDnsName@@YGJPBGPAPAG11@Z
API ?myHExceptionCode@@YGJPBU_EXCEPTION_POINTERS@@@Z
API ?myHExceptionCodePrint@@YGJPBU_EXCEPTION_POINTERS@@PBDKK@Z
API ?myHGetLastError@@YGJXZ
API ?myHResultToStringRaw_old@@YGPBGPAGJ@Z
API ?myHResultToString_old@@YGPBGPAGJ@Z
API ?myIsDelayLoadHResult@@YGHJ@Z
API ?myJetHResult@@YGJJ@Z
API ?myLogExceptionInit@@YGXP6GXJPBU_EXCEPTION_POINTERS@@PBDKK@Z@Z
API ?myModifyVirtualRootsAndFileShares@@YGJKW4ENUM_CATYPES@@KPAK1@Z
API _myNetLogonUser@16
API ?myOIDHashOIDToString@@YGJPBGPAPAG@Z
API ?myRevertSanitizeName@@YGJPBGPAPAG@Z
API _myRobustLdapBind@8
API _myRobustLdapBindEx@24
API ?mySanitizeName@@YGJPBGPAPAG@Z
API ?mySanitizedNameToDSName@@YGJPBGPAPAG@Z
API ?mySanitizedNameToShortName@@YGJPBGHPAPAG@Z
API ?mylstrcmpiL@@YGHPBG0@Z
API _IsRequestConnectionLocal@8
API ?myGetCertificateFromPicker@@YGJPAUHINSTANCE__@@PAUHWND__@@HHKPBGKPAPAXPAPBGKPBQBDPAPBU_CERT_CONTEXT@@@Z
API ?PingCertServer@@YGJPBG0PAPAG1PAPAU_CAINFO@@PAK1@Z
API _CertificateInterfaceInit@8
API _CertServerFreeMemory@4
API _CertServerRetrievePending@20
API _CertServerSubmitRequest@28
API ?myGetConfigFromPicker@@YGJPAUHWND__@@PBG11KHPAKPAPBU_CRYPTUI_CA_CONTEXT@@@Z

end
