API MACRO name
name proc
name endp
ENDM

.code

API ?CloudAPPluginInitialize@@YAJKPEAU_GUID@@PEAU_CLOUDAP_SECPKG_FUNCTION_TABLE@@PEAKQEAGQEAEPEAPEAX5PEAU_APPLUGIN_SECPKG_FUNCTION_TABLE@@@Z
API DllRegisterServer
API DllRegisterServer

end
