.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _BindMoniker@16
API _CLIPFORMAT_UserFree@8
API ?CLIPFORMAT_UserFreeExt@@YGXPAKPAG@Z
API _CLIPFORMAT_UserMarshal@12
API ?CLIPFORMAT_UserMarshalExt@@YGPAEPAKPAEPAG@Z
API _CLIPFORMAT_UserSize@12
API ?CLIPFORMAT_UserSizeExt@@YGKPAKKPAG@Z
API _CLIPFORMAT_UserUnmarshal@12
API ?CLIPFORMAT_UserUnmarshalExt@@YGPAEPAKPAEPAG@Z
API _CLSIDFromOle1Class@12
API _CLSIDFromProgID@8
API _CLSIDFromProgIDEx@8
API _CLSIDFromString@8
API _CStdAsyncStubBuffer2_Connect@8
API _CStdStubBuffer2_Disconnect@4
API _CStdAsyncStubBuffer2_Release@4
API ?AddRef@?$AddComReferenceCounting_StandardReferenceCountingLayer@VCPolicySet@@V?$AddComReferenceCounting_ReferenceCountLayer@VCPolicySet@@V?$Allocation_SealedClassDeleteSelfLayer@VCPolicySet@@V?$MixinBase@VCPolicySet@@V?$Mixins_BaseForwarderLayer@U?$ForwardedBases@UIPolicySet@@$$V@ObjectLibrary@@@Details@ObjectLibrary@@@Details@ObjectLibrary@@@Details@ObjectLibrary@@@Details@ObjectLibrary@@@Details@ObjectLibrary@@UAGKXZ
API _CStdAsyncStubBuffer_Connect@8
API _CStdStubBuffer_Disconnect@4
API _CStdAsyncStubBuffer_Invoke@12
API _CStdAsyncStubBuffer_QueryInterface@12
API _CStdAsyncStubBuffer_Release@4
API _CStdStubBuffer2_Connect@8
API _CStdStubBuffer2_CountRefs@4
API _CStdStubBuffer2_Disconnect@4
API _CStdStubBuffer2_QueryInterface@12
API _CheckInitDde@4
API _CleanROTForApartment@0
API _ClearQITableEntry@4
API ?ClipboardProcessUninitialize@@YGXXZ
API _CoAddRefServerProcess@0
API _CoAicGetTokenForCOM@48
API _CoAllowSetForegroundWindow@8
API _CoAllowUnmarshalerCLSID@4
API _CoBuildVersion@0
API _CoCancelCall@8
API _CoCheckElevationEnabled@4
API _CoCopyProxy@8
API _CoCreateFreeThreadedMarshaler@8
API _CoCreateGuid@4
API _CoCreateInstance@20
API _CoCreateInstanceEx@24
API _CoCreateInstanceFromApp@24
API _CoCreateObjectInContext@16
API _CoDeactivateObject@8
API _CoDecodeProxy@16
API _CoDecrementMTAUsage@4
API _CoDisableCallCancellation@4
API _CoDisconnectContext@4
API _CoDisconnectObject@8
API _CoDosDateTimeToFileTime@12
API _CoEnableCallCancellation@4
API _CoFileTimeNow@4
API _CoFileTimeToDosDateTime@12
API _CoFreeAllLibraries@0
API _CoFreeLibrary@4
API _CoFreeUnusedLibraries@0
API _CoFreeUnusedLibrariesEx@8
API _CoGetActivationState@24
API _CoGetApartmentID@8
API _CoGetApartmentType@8
API _CoGetCallContext@8
API _CoGetCallState@8
API _CoGetCallerTID@4
API _CoGetCancelObject@12
API _CoGetClassObject@20
API _CoGetClassVersion@12
API _GetCatalogHelper@8
API _CoGetContextToken@4
API _CoGetCurrentLogicalThreadId@4
API _CoGetCurrentProcess@0
API _CoGetDefaultContext@12
API _CoGetInstanceFromFile@32
API _CoGetInstanceFromIStorage@28
API _CoGetInterceptor@16
API _CoGetInterceptorForOle32@16
API _CoGetInterceptorFromTypeInfo@20
API _CoGetInterfaceAndReleaseStream@12
API _CoGetMalloc@8
API _CoGetMarshalSizeMax@24
API _CoGetModuleType@8
API _CoGetObject@16
API _CoGetObjectContext@8
API _CoGetPSClsid@8
API _CoGetProcessIdentifier@4
API _CoGetStandardMarshal@24
API _CoGetStdMarshalEx@12
API _CoGetSystemSecurityPermissions@8
API _CoGetSystemWow64DirectoryW@8
API _CoGetTreatAsClass@8
API _CoHandlePriorityEventsFromMessagePump@0
API _CoImpersonateClient@0
API _CoIncrementMTAUsage@4
API _CoInitialize@4
API _CoInitializeEx@8
API _CoInitializeSecurity@36
API _CoInitializeWOW@8
API _CoInstall@20
API _CoInvalidateRemoteMachineBindings@4
API _CoIsHandlerConnected@4
API _CoIsOle1Class@4
API _CoLoadLibrary@8
API _CoLockObjectExternal@12
API _CoMarshalHresult@8
API _CoMarshalInterThreadInterfaceInStream@12
API _CoMarshalInterface@24
API _CoPopServiceDomain@4
API _CoPushServiceDomain@4
API _CoQueryAuthenticationServices@8
API _CoQueryClientBlanket@28
API _CoQueryProxyBlanket@32
API _CoQueryReleaseObject@4
API _CoReactivateObject@8
API _CoRegisterActivationFilter@4
API _CoRegisterChannelHook@8
API _CoRegisterClassObject@20
API _CoRegisterInitializeSpy@8
API _CoRegisterMallocSpy@4
API _CoRegisterMessageFilter@8
API _CoRegisterPSClsid@8
API _CoRegisterSurrogate@4
API _CoRegisterSurrogateEx@8
API _CoReleaseMarshalData@4
API _CoReleaseServerProcess@0
API _CoResumeClassObjects@0
API _CoRetireServer@4
API _CoRevertToSelf@0
API _CoRevokeClassObject@4
API _CoRevokeInitializeSpy@8
API _CoRevokeMallocSpy@0
API _CoSetCancelObject@4
API _CoSetMessageDispatcher@4
API _CoSetProxyBlanket@32
API ?GetServerObjectContext@CProxyManagerImpl@CDdeObject@@UAGPAUIObjContext@@XZ
API _CoSuspendClassObjects@0
API _CoSwitchCallContext@8
API _CoTaskMemAlloc@4
API _CoTaskMemFree@4
API _CoTaskMemRealloc@8
API _CoTestCancel@0
API _CoTreatAsClass@8
API _CoTryGetInterceptorForAppModelVirtualization@16
API _CoUninitialize@0
API _CoUnloadingWOW@4
API _CoUnmarshalHresult@8
API _CoUnmarshalInterface@12
API _CoVrfCheckThreadState@4
API _CoVrfGetThreadState@4
API _CoVrfReleaseThreadState@4
API _CoWaitForMultipleHandles@20
API _CoWaitForMultipleObjects@20
API ?IsDirty@CClassMoniker@@UAGJXZ
API _ComPs_NdrDllGetClassObject@24
API _ComPs_NdrDllRegisterProxy@20
API _ComPs_NdrDllUnregisterProxy@20
API _CreateAntiMoniker@4
API _CreateBindCtx@8
API _CreateClassMoniker@8
API _CreateDataAdviseHolder@4
API _CreateDataCache@16
API _CoCreateErrorInfo@4
API _CreateFileMoniker@8
API _CreateGenericComposite@12
API _CreateILockBytesOnHGlobalStub@12
API _CreateItemMoniker@12
API _CreateObjrefMoniker@8
API _CreateOleAdviseHolder@4
API _CreatePointerMoniker@8
API _CreateStdProgressIndicator@16
API _CreateStreamOnHGlobal@12
API _DcomChannelSetHResult@12
API _DdeBindToObject@20
API _DeletePatternAndExtensionTables@0
API _DestroyRunningObjectTable@0
API _DllDebugObjectRPCHook@8
API _DllGetClassObject@12
API _DllGetClassObject@12
API ?RaiseEvent@?$HashMapOptions@PAUHSTRING__@@PAUIInspectable@@U?$DefaultLifetimeTraits@PAUHSTRING__@@@Internal@Collections@Foundation@Windows@@$0A@$0A@$0A@@Internal@Collections@Foundation@Windows@@SAJZZ
API _DoDragDrop@16
API _DragDropSetFDT@4
API _EnableHookObject@8
API _FindExt@4
API _FmtIdToPropStgNameStub@8
API _FreePropVariantArray@8
API _GetActiveObjectExt@12
API _GetClassFile@8
API _GetConvertStgStub@4
API _GetDocumentBitStgStub@4
API _CoGetErrorInfo@8
API _GetHGlobalFromILockBytesStub@8
API _GetHGlobalFromStream@8
API _GetHookInterface@4
API _GetObjectFromRotByPath@8
API _GetRunningObjectTable@8
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API _HBITMAP_UserFree@8
API _HBITMAP_UserMarshal@12
API _HBITMAP_UserSize@12
API _HBITMAP_UserUnmarshal@12
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API _HDC_UserFree@8
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API _HENHMETAFILE_UserFree@8
API _HENHMETAFILE_UserMarshal@12
API _HENHMETAFILE_UserSize@12
API _HENHMETAFILE_UserUnmarshal@12
API _HGLOBAL_UserFree@8
API _HGLOBAL_UserMarshal@12
API _HGLOBAL_UserSize@12
API _HGLOBAL_UserUnmarshal@12
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API _HMETAFILEPICT_UserFree@8
API _HMETAFILEPICT_UserMarshal@12
API _HMETAFILEPICT_UserSize@12
API _HMETAFILEPICT_UserUnmarshal@12
API _HMETAFILE_UserFree@8
API _HMETAFILE_UserMarshal@12
API _HMETAFILE_UserSize@12
API _HMETAFILE_UserUnmarshal@12
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API _HPALETTE_UserFree@8
API ?HPALETTE_UserFreeExt@@YGXPAKPAPAUHPALETTE__@@@Z
API _HPALETTE_UserMarshal@12
API ?HPALETTE_UserMarshalExt@@YGPAEPAKPAEPAPAUHPALETTE__@@@Z
API _HPALETTE_UserSize@12
API ?HPALETTE_UserSizeExt@@YGKPAKKPAPAUHPALETTE__@@@Z
API _HPALETTE_UserUnmarshal@12
API ?HPALETTE_UserUnmarshalExt@@YGPAEPAKPAEPAPAUHPALETTE__@@@Z
API _HDC_UserFree@8
API _HDC_UserMarshal@12
API _HWND_UserSize@12
API _HMENU_UserUnmarshal@12
API ?ReportStubInvokeFailure@ServerCall@@UAGXJ@Z
API ?HWND_UserFreeExt@@YGXPAKPAPAUHWND__@@@Z
API _HDC_UserMarshal@12
API ?HWND_UserMarshalExt@@YGPAEPAKPAEPAPAUHWND__@@@Z
API _HWND_UserSize@12
API ?HWND_UserSizeExt@@YGKPAKKPAPAUHWND__@@@Z
API _HMENU_UserUnmarshal@12
API ?HWND_UserUnmarshalExt@@YGPAEPAKPAEPAPAUHWND__@@@Z
API _HkOleRegisterObject@16
API _IIDFromString@8
API _IsAccelerator@16
API _IsEqualGUID@8
API _IsRoInitializeASTAAllowedInDesktop@4
API ?IsDirty@CClassMoniker@@UAGJXZ
API _IsValidInterface@4
API _ExportedIsValidPtrIn@8
API _ExportedIsValidPtrIn@8
API _MkParseDisplayName@16
API _MonikerCommonPrefixWith@12
API ?MonikerLoadTypeLib@@YGJPBGPAPAUITypeLib@@@Z
API _MonikerRelativePathTo@16
API ?NdrOleInitializeExtension@@YGJPAPBU_NDROLE_EXTENSION_ROUTINES_TABLE@@PAPBU_NDR_FWD_ROUTINES@@@Z
API _NdrProxyForwardingFunction10@0
API _NdrProxyForwardingFunction11@0
API _NdrProxyForwardingFunction12@0
API _NdrProxyForwardingFunction13@0
API _NdrProxyForwardingFunction14@0
API _NdrProxyForwardingFunction15@0
API _NdrProxyForwardingFunction16@0
API _NdrProxyForwardingFunction17@0
API _NdrProxyForwardingFunction18@0
API _NdrProxyForwardingFunction19@0
API _NdrProxyForwardingFunction20@0
API _NdrProxyForwardingFunction21@0
API _NdrProxyForwardingFunction22@0
API _NdrProxyForwardingFunction23@0
API _NdrProxyForwardingFunction24@0
API _NdrProxyForwardingFunction25@0
API _NdrProxyForwardingFunction26@0
API _NdrProxyForwardingFunction27@0
API _NdrProxyForwardingFunction28@0
API _NdrProxyForwardingFunction29@0
API _NdrProxyForwardingFunction3@0
API _NdrProxyForwardingFunction30@0
API _NdrProxyForwardingFunction31@0
API _NdrProxyForwardingFunction32@0
API _NdrProxyForwardingFunction4@0
API _NdrProxyForwardingFunction5@0
API _NdrProxyForwardingFunction6@0
API _NdrProxyForwardingFunction7@0
API _NdrProxyForwardingFunction8@0
API _NdrProxyForwardingFunction9@0
API _ObjectStublessClient10@0
API _ObjectStublessClient11@0
API _ObjectStublessClient12@0
API _ObjectStublessClient13@0
API _ObjectStublessClient14@0
API _ObjectStublessClient15@0
API _ObjectStublessClient16@0
API _ObjectStublessClient17@0
API _ObjectStublessClient18@0
API _ObjectStublessClient19@0
API _ObjectStublessClient20@0
API _ObjectStublessClient21@0
API _ObjectStublessClient22@0
API _ObjectStublessClient23@0
API _ObjectStublessClient24@0
API _ObjectStublessClient25@0
API _ObjectStublessClient26@0
API _ObjectStublessClient27@0
API _ObjectStublessClient28@0
API _ObjectStublessClient29@0
API _ObjectStublessClient3@0
API _ObjectStublessClient30@0
API _ObjectStublessClient31@0
API _ObjectStublessClient32@0
API _ObjectStublessClient4@0
API _ObjectStublessClient5@0
API _ObjectStublessClient6@0
API _ObjectStublessClient7@0
API _ObjectStublessClient8@0
API _ObjectStublessClient9@0
API _Ole32DllGetClassObject@12
API _CoBuildVersion@0
API _OleConvertIStorageToOLESTREAM@8
API _OleConvertIStorageToOLESTREAMEx@28
API _OleConvertOLESTREAMToIStorage@12
API _OleConvertOLESTREAMToIStorage2@24
API _OleConvertOLESTREAMToIStorageEx@28
API _OleConvertOLESTREAMToIStorageEx2@40
API _OleCreate@28
API _OleCreateDefaultHandler@16
API _OleCreateEmbeddingHelper@24
API _OleCreateEx@48
API _OleCreateFontIndirectExt@12
API _OleCreateFromData@28
API _OleCreateFromDataEx@48
API _OleCreateFromFile@32
API _OleCreateFromFileEx@52
API _OleCreateLink@28
API _OleCreateLinkEx@48
API _OleCreateLinkFromData@28
API _OleCreateLinkFromDataEx@48
API _OleCreateLinkToFile@28
API _OleCreateLinkToFileEx@48
API _OleCreateMenuDescriptor@8
API _OleCreatePictureIndirectExt@16
API _OleCreatePropertyFrameIndirectExt@4
API _OleCreateStaticFromData@28
API _OleDestroyMenuDescriptor@4
API _OleDoAutoConvert@8
API _OleDraw@16
API _OleDuplicateData@12
API _OleFlushClipboard@0
API _OleGetAutoConvert@8
API _OleGetClipboard@4
API _OleGetClipboardWithEnterpriseInfo@20
API _OleGetIconOfClass@12
API _OleGetIconOfFile@8
API _OleGetPackageClipboardOwner@4
API _OleIconToCursorExt@8
API _OleInitialize@4
API _OleInitializeWOW@8
API _OleIsCurrentClipboard@4
API _OleIsRunning@4
API _OleLoad@16
API _OleLoadFromStream@12
API _OleLoadPictureExt@32
API _OleLoadPictureFileExt@32
API _OleLoadPicturePathExt@24
API _OleLockRunning@12
API _OleMetafilePictFromIconAndLabel@16
API _OleNoteObjectVisible@8
API _OleQueryCreateFromData@4
API _OleQueryLinkFromData@4
API _OleRegEnumFormatEtc@12
API _OleRegEnumVerbs@8
API _OleRegGetMiscStatus@12
API _OleRegGetUserType@12
API _OleReleaseEnumVerbCache@0
API _OleRun@4
API _OleSave@12
API _OleSavePictureFileExt@8
API _OleSaveToStream@8
API _OleSetAutoConvert@8
API _OleSetClipboard@4
API _OleSetContainedObject@8
API _OleSetMenuDescriptor@20
API _OleTranslateAccelerator@12
API _OleTranslateColorExt@12
API _OleUninitialize@0
API _OpenOrCreateStream@12
API _ProgIDFromCLSID@8
API _PropStgNameToFmtIdStub@8
API _PropSysAllocStringStub@4
API _PropSysFreeStringStub@4
API _PropVariantChangeTypeStub@20
API _PropVariantClear@4
API _PropVariantCopy@8
API ?ReadStorageProperties@@YGJPAUIStorage@@PAU_GUID@@@Z
API _ReadClassStmStub@8
API _ReadFmtUserTypeStg@12
API _ReadOleStg@24
API ?ReadStorageProperties@@YGJPAUIStorage@@PAU_GUID@@@Z
API _ReadStringStream@8
API _RegisterActiveObjectExt@16
API _RegisterDragDrop@8
API _ReleaseStgMedium@4
API _RevokeActiveObjectExt@8
API _RevokeDragDrop@4
API _RoGetAgileReference@16
API _SNB_UserFree@8
API _SNB_UserMarshal@12
API _SNB_UserSize@12
API _SNB_UserUnmarshal@12
API _STGMEDIUM_UserFree@8
API ?STGMEDIUM_UserFreeExt@@YGXPAKPAUtagSTGMEDIUM@@@Z
API _STGMEDIUM_UserMarshal@12
API ?STGMEDIUM_UserMarshalExt@@YGPAEPAKPAEPAUtagSTGMEDIUM@@@Z
API _STGMEDIUM_UserSize@12
API ?STGMEDIUM_UserSizeExt@@YGKPAKKPAUtagSTGMEDIUM@@@Z
API _STGMEDIUM_UserUnmarshal@12
API ?STGMEDIUM_UserUnmarshalExt@@YGPAEPAKPAEPAUtagSTGMEDIUM@@@Z
API _SetConvertStg@8
API _SetDocumentBitStg@8
API _CoSetErrorInfo@8
API ?SetOleautModule@@YGXPAUHINSTANCE__@@@Z
API _SetWOWThunkGlobalPtr@4
API ?StdTypesGetClassObject@@YGJABU_GUID@@0PAPAX@Z
API ?StdTypesRegisterServer@@YGJXZ
API _StgConvertPropertyToVariantStub@16
API _StgConvertVariantToPropertyStub@28
API _StgCreateDocfileStub@16
API _StgCreateDocfileOnILockBytesStub@16
API _StgCreatePropSetStgStub@12
API _StgCreatePropStgStub@24
API _StgCreateStorageExStub@32
API _StgGetIFillLockBytesOnFileStub@8
API _StgGetIFillLockBytesOnILockBytesStub@8
API _StgIsStorageFileStub@4
API _StgIsStorageILockBytesStub@4
API _StgOpenAsyncDocfileOnIFillLockBytesStub@16
API _StgOpenPropStgStub@20
API _StgOpenStorageStub@24
API _StgOpenStorageExStub@32
API _StgOpenStorageOnHandleStub@24
API _StgOpenStorageOnILockBytesStub@24
API _StgPropertyLengthAsVariantStub@16
API _StgSetTimesStub@16
API _StoreQITableEntry@8
API _StringFromCLSID@8
API _StringFromGUID2@12
API _StringFromIID@8
API _UpdateDCOMSettings@0
API ?UpdateProcessTracing@@YGJKH@Z
API _UtConvertDvtd16toDvtd32@12
API _UtConvertDvtd32toDvtd16@12
API _UtGetDvtd16Info@8
API _UtGetDvtd32Info@8
API _WdtpInterfacePointer_UserFree@4
API _WdtpInterfacePointer_UserMarshal@20
API _WdtpInterfacePointer_UserSize@20
API _WdtpInterfacePointer_UserUnmarshal@16
API _WriteClassStgStub@8
API _WriteClassStmStub@8
API _WriteFmtUserTypeStg@12
API _WriteOleStg@16
API ?WriteStorageProperties@@YGJPAUIStorage@@ABU_GUID@@GPAG@Z
API _WriteStringStream@8
API _OleStartDragOperationInternal@20
API _OleCreateDragOperationInternal@12
API _OleRevokeDropTargetInternal@4
API _OleRegisterDropTargetInternal@8
API _OleGetSessionClipboardBroker@4
API _OleInitClipboardBroker@0
API _OleRundownClipboardBroker@0
API _OleGetClipboardBroker@4

end
