.686

.MODEL FLAT

API MACRO name
name proc
name endp
ENDM

.code

API _RtlAcquireSRWLockExclusive@4
API _RtlAcquireSRWLockShared@4
API _ActivateActCtxStub@8
API _ActivateActCtxWorker@8
API _ActivatePackageVirtualizationContext@8
API _AddAtomA@4
API _AddAtomW@4
API _AddConsoleAliasA@12
API _AddConsoleAliasW@12
API _AddDllDirectory@4
API _AddIntegrityLabelToBoundaryDescriptor@8
API _AddLocalAlternateComputerNameA@8
API _AddLocalAlternateComputerNameW@8
API _AddRefActCtxStub@4
API _AddRefActCtxWorker@4
API _AddResourceAttributeAceStub@28
API _AddSIDToBoundaryDescriptorStub@8
API _AddScopedPolicyIDAceStub@20
API _AddSecureMemoryCacheCallback@4
API _RtlAddVectoredContinueHandler@8
API _RtlAddVectoredExceptionHandler@8
API _AdjustCalendarDate@12
API _AllocConsole@0
API _AllocConsoleWithOptions@8
API _AllocateUserPhysicalPagesStub@12
API _AllocateUserPhysicalPagesNumaStub@16
API _AppPolicyGetClrCompat@8
API _AppPolicyGetCreateFileAccess@8
API _AppPolicyGetLifecycleManagement@8
API _AppPolicyGetMediaFoundationCodecLoading@8
API _AppPolicyGetProcessTerminationMethod@8
API _AppPolicyGetShowDeveloperDiagnostic@8
API _AppPolicyGetThreadInitializationType@8
API _AppPolicyGetWindowingModel@8
API _AppXGetOSMaxVersionTested@8
API _ApplicationRecoveryFinished@4
API _ApplicationRecoveryInProgress@4
API _AreFileApisANSIStub@0
API _AreShortNamesEnabled@8
API _AssignProcessToJobObject@8
API _AttachConsole@4
API _BackupRead@28
API _BackupReadEx@24
API _BackupSeek@24
API _BackupWrite@28
API _BackupWriteEx@24
API _BaseCheckAppcompatCacheStub@16
API _BaseCheckAppcompatCacheExStub@36
API _BaseCheckAppcompatCacheExWorker@36
API _BaseCheckAppcompatCacheWorker@16
API _BaseCheckElevation@48
API _BaseCleanupAppcompatCacheSupportStub@4
API _BaseCleanupAppcompatCacheSupportWorker@4
API _BaseDestroyVDMEnvironment@8
API _BaseDllReadWriteIniFile@32
API _BaseDumpAppcompatCacheStub@0
API @_guard_check_icall_nop@4
API _BaseElevationPostProcessing@12
API _BaseFlushAppcompatCacheStub@0
API _BaseFlushAppcompatCacheWorker@0
API _BaseFormatObjectAttributes@16
API _BaseFormatTimeOut@8
API _SortCloseHandle@4
API _BaseGenerateAppCompatData@24
API _BaseGetNamedObjectDirectoryStub@4
API _BaseInitAppcompatCacheSupportStub@0
API ?get_FirstMonthInThisYear@YearMonthCalendar@Calendars@Globalization@Windows@@UBEHXZ
API _BaseIsAppcompatInfrastructureDisabledWorker@0
API _BaseIsAppcompatInfrastructureDisabledWorker@0
API _BaseIsDosApplication@8
API _BaseQueryModuleData@28
API _BaseReadAppCompatDataForProcessWorker@12
API _BaseSetLastNTError@4
API @BaseThreadInitThunk@12
API _BaseUpdateAppcompatCacheStub@12
API _BaseUpdateAppcompatCacheWorker@12
API _BaseUpdateVDMEntry@16
API _BaseWriteErrorElevationRequiredEvent@0
API _Basep8BitStringToDynamicUnicodeString@8
API _BasepAllocateActivationContextActivationBlock@16
API _BasepAnsiStringToDynamicUnicodeString@8
API _BasepAppContainerEnvironmentExtension@12
API _BasepAppXExtension@24
API _BasepCheckAppCompat@16
API _BasepCheckPplSupport@8
API _BasepCheckWebBladeHashes@4
API _BasepCheckWinSaferRestrictions@16
API _BasepConstructSxsCreateProcessMessage@80
API _BasepCopyEncryption@12
API _BasepFinishPackageActivation@28
API _BasepFinishPackageActivationForSxS@24
API _BasepFreeActivationContextActivationBlock@4
API _BasepFreeActivationTokenInfo@4
API _BasepFreeAppCompatData@12
API _BasepGetAppCompatData@60
API _BasepGetComputerNameFromNtPath@16
API _BasepGetExeArchType@12
API _BasepGetPackageActivationTokenForSxS@12
API _BasepGetPackageActivationTokenForFilePath2@12
API _BasepGetPackageActivationTokenForSxS@12
API _BasepGetPackageActivationTokenForSxS2@12
API _BasepGetPackagedAppInfoForFile@16
API _BasepInitAppCompatData@12
API _BasepIsProcessAllowed@4
API _BasepMapModuleHandle@8
API _WerpNotifyLoadStringResourceWorker@16
API _BasepPostSuccessAppXExtension@8
API _BasepProcessInvalidImage@84
API _BasepQueryAppCompat@72
API _BasepQueryModuleChpeSettings@44
API _BasepReleaseAppXContext@4
API _BasepReleasePackagedAppInfo@4
API _BasepReleaseSxsCreateProcessUtilityStruct@4
API _BasepReportFault@8
API _BasepSetFileEncryptionCompression@32
API _BeepImplementation@8
API _BeginUpdateResourceA@8
API _BeginUpdateResourceW@8
API _BindIoCompletionCallback@12
API _BuildCommDCBA@8
API _BuildCommDCBAndTimeoutsA@12
API _BuildCommDCBAndTimeoutsW@12
API _BuildCommDCBW@8
API _BuildIoRingCancelRequest@20
API _BuildIoRingFlushFile@24
API _BuildIoRingReadFile@44
API _BuildIoRingReadFileScatter@40
API _BuildIoRingRegisterBuffers@16
API _BuildIoRingRegisterFileHandles@16
API _BuildIoRingWriteFile@48
API _BuildIoRingWriteFileGather@44
API _CallNamedPipeA@28
API _CallNamedPipeW@28
API _CallbackMayRunLongStub@4
API _CancelDeviceWakeupRequest@4
API _CancelIoStub@4
API _CancelIoExStub@8
API _CancelSynchronousIoStub@4
API _TpCancelAsyncIoOperation@4
API _CancelTimerQueueTimer@8
API _CancelWaitableTimer@4
API _CeipIsOptedIn@0
API _ChangeTimerQueueTimerStub@16
API _CheckAllowDecryptedRemoteDestinationPolicyStub@0
API _CheckElevation@20
API _CheckElevationEnabled@4
API _CheckForReadOnlyResource@8
API _CheckForReadOnlyResourceFilter@4
API _CheckNameLegalDOS8Dot3A@20
API _CheckNameLegalDOS8Dot3W@20
API _CheckRemoteDebuggerPresentStub@8
API _CheckTokenCapabilityStub@12
API _CheckTokenMembershipExStub@16
API _ClearCommBreak@4
API _ClearCommError@12
API _CloseConsoleHandle@4
API _CloseHandle@4
API _CloseIoRing@4
API _ClosePackageInfo@4
API _ClosePrivateNamespaceStub@8
API ?get_FirstMonthInThisYear@YearMonthCalendar@Calendars@Globalization@Windows@@UBEHXZ
API _ClosePseudoConsole@4
API _CloseState@4
API _TpReleasePool@4
API _TpReleaseCleanupGroup@4
API _TpReleaseCleanupGroupMembers@12
API _TpReleaseIoCompletion@4
API _TpReleaseTimer@4
API _TpReleaseWait@4
API _TpReleaseWork@4
API _UTUnRegister@4
API _CommConfigDialogA@12
API _CommConfigDialogW@12
API _CompareCalendarDates@12
API _CompareFileTime@8
API _CompareStringAStub@24
API _CompareStringExStub@36
API _CompareStringOrdinalStub@20
API _CompareStringWStub@24
API _ConnectNamedPipeStub@8
API _ConsoleMenuControl@12
API _ContinueDebugEventStub@12
API _ConvertCalDateTimeToSystemTime@8
API _ConvertDefaultLocaleStub@4
API _ConvertFiberToThread@0
API _ConvertNLSDayOfWeekToWin32DayOfWeek@4
API _ConvertSystemTimeToCalDateTime@12
API _ConvertThreadToFiber@4
API _ConvertThreadToFiberEx@8
API _CopyContextStub@12
API _CopyFile2Stub@12
API _CopyFileA@12
API _CopyFileExA@24
API _CopyFileExWStub@24
API _CopyFileTransactedA@28
API _CopyFileTransactedW@28
API _CopyFileW@12
API _CopyLZFile@8
API _CreateActCtxA@4
API _CreateActCtxWStub@4
API _CreateActCtxWWorker@4
API _CreateBoundaryDescriptorA@8
API _CreateBoundaryDescriptorWStub@8
API _CreateConsoleScreenBuffer@20
API _CreateDirectoryA@8
API _CreateDirectoryExA@12
API _CreateDirectoryExWStub@12
API _CreateDirectoryTransactedA@16
API _CreateDirectoryTransactedW@16
API _CreateDirectoryW@8
API _CreateEnclave@32
API _CreateEventA@16
API _CreateEventExA@16
API _CreateEventExW@16
API _CreateEventW@16
API _CreateFiber@12
API _CreateFiberEx@20
API _CreateFile2@20
API _CreateFileA@28
API _CreateFileMappingA@24
API _CreateFileMappingFromApp@24
API _CreateFileMappingNumaA@28
API _CreateFileMappingNumaWStub@28
API _CreateFileMappingWStub@24
API _CreateFileTransactedA@40
API _CreateFileTransactedW@40
API _CreateFileW@28
API _CreateHardLinkAStub@12
API _CreateHardLinkTransactedA@16
API _CreateHardLinkTransactedW@16
API _CreateHardLinkWStub@12
API _CreateIoCompletionPortStub@16
API _CreateIoRing@24
API _CreateJobObjectA@8
API _CreateJobObjectW@8
API _CreateJobSet@12
API _CreateMailslotA@16
API _CreateMailslotW@16
API _CreateMemoryResourceNotificationStub@4
API _CreateMutexA@12
API _CreateMutexExA@16
API _CreateMutexExW@16
API _CreateMutexW@12
API _CreateNamedPipeA@32
API _CreateNamedPipeWStub@32
API _CreatePackageVirtualizationContext@8
API _CreatePipeStub@16
API _CreatePrivateNamespaceA@12
API _CreatePrivateNamespaceWStub@12
API _CreateProcessAStub@40
API _CreateProcessAsUserAStub@44
API _CreateProcessAsUserWStub@44
API _CreateProcessInternalAStub@48
API _CreateProcessInternalWStub@48
API _CreateProcessWStub@40
API _CreatePseudoConsole@20
API _CreateRemoteThreadStub@28
API _CreateRemoteThreadEx@32
API _CreateSemaphoreA@16
API _CreateSemaphoreExA@24
API _CreateSemaphoreExW@24
API _CreateSemaphoreW@16
API _CreateSocketHandle@0
API _CreateSymbolicLinkA@12
API _CreateSymbolicLinkTransactedA@16
API _CreateSymbolicLinkTransactedW@16
API _CreateSymbolicLinkWStub@12
API _CreateTapePartition@16
API _CreateThreadStub@24
API _CreateThreadpoolStub@4
API _CreateThreadpoolCleanupGroupStub@0
API _CreateThreadpoolIoStub@16
API _CreateThreadpoolTimerStub@12
API _CreateThreadpoolWaitStub@12
API _CreateThreadpoolWorkStub@12
API _CreateTimerQueueStub@0
API _CreateTimerQueueTimerStub@28
API _CreateToolhelp32Snapshot@8
API _CreateWaitableTimerA@12
API _CreateWaitableTimerExA@16
API _CreateWaitableTimerExW@16
API _CreateWaitableTimerW@12
API _CtrlRoutine@4
API _DeactivateActCtxStub@8
API _DeactivateActCtxWorker@8
API _DeactivatePackageVirtualizationContext@4
API _DebugActiveProcessStub@4
API _DebugActiveProcessStopStub@4
API _DebugBreakStub@0
API _DebugBreakProcess@4
API _DebugSetProcessKillOnExit@4
API _RtlDecodePointer@4
API _RtlDecodeSystemPointer@4
API _DefineDosDeviceA@12
API _DefineDosDeviceW@12
API _DelayLoadFailureHookStub@8
API _DeleteAtom@4
API _DeleteBoundaryDescriptorStub@4
API _RtlDeleteCriticalSection@4
API _DeleteFiber@4
API _DeleteFileA@4
API _DeleteFileTransactedA@8
API _DeleteFileTransactedW@8
API _DeleteFileW@4
API _sqlite3_mutex_enter@4
API _DeleteSynchronizationBarrierStub@4
API _DeleteTimerQueue@4
API _DeleteTimerQueueExStub@8
API _DeleteTimerQueueTimerStub@12
API _DeleteVolumeMountPointA@4
API _DeleteVolumeMountPointW@4
API _DeviceIoControlImplementation@32
API _DisableThreadLibraryCallsStub@4
API _DisableThreadProfiling@4
API _TpDisassociateCallback@4
API _DiscardVirtualMemory@8
API _DisconnectNamedPipeStub@4
API _DnsHostnameToComputerNameA@12
API _DnsHostnameToComputerNameExWStub@12
API _DnsHostnameToComputerNameW@12
API _DosDateTimeToFileTime@12
API _DosPathToSessionPathA@12
API _DosPathToSessionPathW@12
API _DuplicateConsoleHandle@16
API _DuplicateEncryptionInfoFileExt@20
API _DuplicateHandle@28
API _DuplicatePackageVirtualizationContext@8
API _EnableProcessOptionalXStateFeaturesStub@8
API _EnableThreadProfiling@20
API _RtlEncodePointer@4
API _RtlEncodeSystemPointer@4
API _EndUpdateResourceA@8
API _EndUpdateResourceW@8
API _RtlEnterCriticalSection@4
API _EnterSynchronizationBarrierStub@8
API _EnumCalendarInfoA@16
API _EnumCalendarInfoExA@16
API _EnumCalendarInfoExExStub@24
API _EnumCalendarInfoExWStub@16
API _EnumCalendarInfoWStub@16
API _EnumDateFormatsA@12
API _EnumDateFormatsExA@12
API _EnumDateFormatsExExStub@16
API _EnumDateFormatsExWStub@12
API _EnumDateFormatsWStub@12
API _EnumLanguageGroupLocalesA@16
API _EnumLanguageGroupLocalesWStub@16
API _EnumResourceLanguagesA@20
API _EnumResourceLanguagesExAStub@28
API _EnumResourceLanguagesExWStub@28
API _EnumResourceLanguagesW@20
API _EnumResourceNamesA@16
API _EnumResourceNamesExAStub@24
API _EnumResourceNamesExWStub@24
API _EnumResourceNamesW@16
API _EnumResourceTypesA@12
API _EnumResourceTypesExAStub@20
API _EnumResourceTypesExWStub@20
API _EnumResourceTypesW@12
API _EnumSystemCodePagesA@8
API _EnumSystemCodePagesWStub@8
API _EnumSystemFirmwareTablesStub@12
API _EnumSystemGeoID@12
API _EnumSystemGeoNames@12
API _EnumSystemLanguageGroupsA@12
API _EnumSystemLanguageGroupsWStub@12
API _EnumSystemLocalesAStub@8
API _EnumSystemLocalesExStub@16
API _EnumSystemLocalesWStub@8
API _EnumTimeFormatsA@12
API _EnumTimeFormatsExStub@16
API _EnumTimeFormatsWStub@12
API _EnumUILanguagesA@12
API _EnumUILanguagesWStub@12
API _EnumerateLocalComputerNamesA@16
API _EnumerateLocalComputerNamesW@16
API _EraseTape@12
API _EscapeCommFunction@8
API _ExitProcessImplementation@4
API _RtlExitUserThread@4
API _ExitVDM@8
API _ExpandEnvironmentStringsAStub@12
API _ExpandEnvironmentStringsWStub@12
API _ExpungeConsoleCommandHistoryA@4
API _ExpungeConsoleCommandHistoryW@4
API _FatalAppExitAStub@8
API _FatalAppExitWStub@8
API _FatalExit@4
API _FileTimeToDosDateTime@12
API _FileTimeToLocalFileTime@8
API _FileTimeToSystemTime@8
API _FillConsoleOutputAttribute@20
API _FillConsoleOutputCharacterA@20
API _FillConsoleOutputCharacterW@20
API _FindActCtxSectionGuidStub@20
API _FindActCtxSectionGuidWorker@20
API _FindActCtxSectionStringA@20
API _FindActCtxSectionStringWStub@20
API _FindActCtxSectionStringWWorker@20
API _FindAtomA@4
API _FindAtomW@4
API _FindClose@4
API _FindCloseChangeNotification@4
API _FindFirstChangeNotificationA@12
API _FindFirstChangeNotificationW@12
API _FindFirstFileA@8
API _FindFirstFileExA@24
API _FindFirstFileExW@24
API _FindFirstFileNameTransactedW@20
API _FindFirstFileNameW@16
API _FindFirstFileTransactedA@28
API _FindFirstFileTransactedW@28
API _FindFirstFileW@8
API _FindFirstStreamTransactedW@20
API _FindFirstStreamW@16
API _FindFirstVolumeA@8
API _FindFirstVolumeMountPointA@12
API _FindFirstVolumeMountPointW@12
API _FindFirstVolumeW@8
API _FindNLSStringStub@28
API _FindNLSStringExStub@40
API _FindNextChangeNotification@4
API _FindNextFileA@8
API _FindNextFileNameW@12
API _FindNextFileW@8
API _FindNextStreamW@8
API _FindNextVolumeA@12
API _FindNextVolumeMountPointA@12
API _FindNextVolumeMountPointW@12
API _FindNextVolumeW@12
API _FindPackagesByPackageFamily@28
API _FindResourceA@12
API _FindResourceExA@16
API _FindResourceExWStub@16
API _FindResourceWStub@12
API _FindStringOrdinalStub@24
API _FindVolumeClose@4
API _FindVolumeMountPointClose@4
API _FlsAllocStub@4
API _FlsFreeStub@4
API _FlsGetValue@4
API _RtlFlsGetValue2@4
API _FlsSetValueStub@8
API _FlushConsoleInputBuffer@4
API _FlushFileBuffers@4
API _FlushInstructionCacheStub@12
API _ZwFlushProcessWriteBuffers@0
API _FlushViewOfFileStub@8
API _FoldStringA@20
API _FoldStringWStub@20
API _FormatApplicationUserModelId@16
API _FormatMessageAStub@28
API _FormatMessageWStub@28
API _FreeConsole@0
API _FreeEnvironmentStringsAStub@4
API _FreeEnvironmentStringsWStub@4
API _FreeLibraryStub@4
API _FreeLibraryAndExitThreadStub@8
API _TpCallbackUnloadDllOnCompletion@8
API _FreeMemoryJobObject@4
API _FreeResourceStub@4
API _FreeUserPhysicalPagesStub@12
API _GenerateConsoleCtrlEvent@8
API _GetACPStub@0
API _GetActiveProcessorCount@4
API _GetActiveProcessorGroupCount@0
API _GetAppContainerAceStub@16
API _GetAppContainerNamedObjectPathStub@20
API _GetApplicationRecoveryCallbackStub@20
API _GetApplicationRecoveryCallbackWorker@20
API _GetApplicationRestartSettingsStub@16
API _GetApplicationRestartSettingsWorker@16
API _GetApplicationUserModelId@12
API _GetAtomNameA@12
API _GetAtomNameW@12
API _GetBinaryTypeA@8
API _GetBinaryTypeA@8
API _GetBinaryTypeW@8
API _GetCPInfoStub@8
API _GetCPInfoExA@12
API _GetCPInfoExWStub@12
API _GetCachedSigningLevelStub@24
API _GetCalendarDateFormat@24
API _GetCalendarDateFormatEx@24
API _GetCalendarDaysInMonth@16
API _GetCalendarDifferenceInDays@12
API _GetCalendarInfoA@24
API _GetCalendarInfoEx@28
API _GetCalendarInfoW@24
API _GetCalendarMonthsInYear@12
API _GetCalendarSupportedDateRange@12
API _GetCalendarWeekNumber@16
API _GetComPlusPackageInstallStatus@0
API _GetCommConfig@12
API _GetCommMask@8
API _GetCommModemStatus@8
API _GetCommProperties@8
API _GetCommState@8
API _GetCommTimeouts@8
API _GetCommandLineAStub@0
API _GetCommandLineWStub@0
API _GetCompressedFileSizeAStub@8
API _GetCompressedFileSizeTransactedA@12
API _GetCompressedFileSizeTransactedW@12
API _GetCompressedFileSizeWStub@8
API _GetComputerNameA@8
API _GetComputerNameExAStub@12
API _GetComputerNameExWStub@12
API _GetComputerNameW@8
API _GetConsoleAliasA@16
API _GetConsoleAliasExesA@8
API _GetConsoleAliasExesLengthA@0
API _GetConsoleAliasExesLengthW@0
API _GetConsoleAliasExesW@8
API _GetConsoleAliasW@16
API _GetConsoleAliasesA@12
API _GetConsoleAliasesLengthA@4
API _GetConsoleAliasesLengthW@4
API _GetConsoleAliasesW@12
API _GetConsoleCP@0
API _GetConsoleCharType@12
API _GetConsoleCommandHistoryA@12
API _GetConsoleCommandHistoryLengthA@4
API _GetConsoleCommandHistoryLengthW@4
API _GetConsoleCommandHistoryW@12
API _GetConsoleCursorInfo@8
API _GetConsoleCursorMode@12
API _GetConsoleDisplayMode@4
API _GetConsoleFontInfo@16
API _GetConsoleFontSize@8
API _GetConsoleHardwareState@12
API _GetConsoleHistoryInfo@4
API _GetConsoleInputExeNameA@8
API _GetConsoleInputExeNameW@8
API _GetConsoleInputWaitHandle@0
API _GetConsoleKeyboardLayoutNameA@4
API _GetConsoleKeyboardLayoutNameW@4
API _GetConsoleMode@8
API _GetConsoleNlsMode@8
API _GetConsoleOriginalTitleA@8
API _GetConsoleOriginalTitleW@8
API _GetConsoleOutputCP@0
API _GetConsoleProcessList@8
API _GetConsoleScreenBufferInfo@8
API _GetConsoleScreenBufferInfoEx@8
API _GetConsoleSelectionInfo@4
API _GetConsoleTitleA@8
API _GetConsoleTitleW@8
API _GetConsoleWindow@0
API _GetCurrencyFormatA@24
API _GetCurrencyFormatExStub@24
API _GetCurrencyFormatWStub@24
API _GetCurrentActCtxStub@4
API _GetCurrentActCtxWorker@4
API _GetCurrentApplicationUserModelId@8
API _GetCurrentConsoleFont@12
API _GetCurrentConsoleFontEx@12
API _GetCurrentDirectoryAStub@8
API _GetCurrentDirectoryWStub@8
API _GetCurrentPackageFamilyName@8
API _GetCurrentPackageFullName@8
API _GetCurrentPackageId@8
API _GetCurrentPackageInfo@16
API _GetCurrentPackagePath@8
API _GetCurrentPackageVirtualizationContext@0
API _GetCurrentProcess@0
API _GetCurrentProcessId@0
API _RtlGetCurrentProcessorNumber@0
API _RtlGetCurrentProcessorNumberEx@4
API _GetCurrentThread@0
API _GetCurrentThreadId@0
API _GetCurrentThreadStackLimits@8
API _GetDateFormatAStub@24
API _GetDateFormatAWorker@28
API _GetDateFormatExStub@28
API _GetDateFormatWStub@24
API _GetDateFormatWWorker@28
API _GetDefaultCommConfigA@12
API _GetDefaultCommConfigW@12
API _GetDevicePowerState@8
API _GetDiskFreeSpaceA@20
API _GetDiskFreeSpaceExA@16
API _GetDiskFreeSpaceExW@16
API _GetDiskFreeSpaceW@20
API _GetDiskSpaceInformationA@8
API _GetDiskSpaceInformationW@8
API _GetDllDirectoryA@8
API _GetDllDirectoryW@8
API _GetDriveTypeA@4
API _GetDriveTypeW@4
API _GetDurationFormat@32
API _GetDurationFormatExStub@32
API _GetDynamicTimeZoneInformationStub@4
API _GetEnabledXStateFeaturesStub@0
API _GetEncryptedFileVersionExt@8
API _GetEnvironmentStringsStub@0
API _GetEnvironmentStrings@0
API _GetEnvironmentStringsWStub@0
API _GetEnvironmentVariableAStub@12
API _GetEnvironmentVariableWStub@12
API _GetEraNameCountedStringStub@16
API _GetErrorModeStub@0
API _GetExitCodeProcessImplementation@8
API _GetExitCodeThreadStub@8
API _GetExpandedNameA@8
API _GetExpandedNameW@8
API _GetFileAttributesA@4
API _GetFileAttributesExA@12
API _GetFileAttributesExW@12
API _GetFileAttributesTransactedA@16
API _GetFileAttributesTransactedW@16
API _GetFileAttributesW@4
API _GetFileBandwidthReservation@24
API _GetFileInformationByHandle@8
API _GetFileInformationByHandleExStub@16
API _GetFileInformationByNameStub@16
API _GetFileMUIInfoStub@16
API _GetFileMUIPathStub@28
API _GetFileSize@8
API _GetFileSizeEx@8
API _GetFileTime@16
API _GetFileType@4
API _GetFinalPathNameByHandleA@16
API _GetFinalPathNameByHandleW@16
API _GetFirmwareEnvironmentVariableA@16
API _GetFirmwareEnvironmentVariableExA@20
API _GetFirmwareEnvironmentVariableExW@20
API _GetFirmwareEnvironmentVariableW@16
API _GetFirmwareType@4
API _GetFullPathNameA@16
API _GetFullPathNameTransactedA@20
API _GetFullPathNameTransactedW@20
API _GetFullPathNameW@16
API _GetGeoInfoA@20
API _GetGeoInfoEx@16
API _GetGeoInfoW@20
API _GetHandleContext@4
API _GetHandleInformation@8
API _GetIoRingInfo@8
API _GetLargePageMinimumStub@0
API _GetLargestConsoleWindowSize@4
API _GetLastError@0
API _GetLocalTimeStub@4
API _GetLocaleInfoAStub@16
API _GetLocaleInfoExStub@16
API _GetLocaleInfoWStub@16
API _GetLogicalDriveStringsA@8
API _GetLogicalDriveStringsW@8
API _GetLogicalDrives@0
API _GetLogicalProcessorInformationStub@8
API _GetLogicalProcessorInformationEx@12
API _GetLongPathNameA@12
API _GetLongPathNameTransactedA@16
API _GetLongPathNameTransactedW@16
API _GetLongPathNameW@12
API _GetMachineTypeAttributes@8
API _GetMailslotInfo@20
API _GetMaximumProcessorCount@4
API _GetMaximumProcessorGroupCount@0
API _GetMemoryErrorHandlingCapabilitiesStub@4
API _GetModuleFileNameAStub@12
API _GetModuleFileNameWStub@12
API _GetModuleHandleAStub@4
API _GetModuleHandleExAStub@12
API _GetModuleHandleExWStub@12
API _GetModuleHandleWStub@4
API _GetNLSVersionStub@12
API _GetNLSVersionExStub@12
API _GetNamedPipeAttributeStub@20
API _GetNamedPipeClientComputerNameA@12
API _GetNamedPipeClientComputerNameWStub@12
API _GetNamedPipeClientProcessId@8
API _GetNamedPipeClientSessionId@8
API _GetNamedPipeHandleStateA@28
API _GetNamedPipeHandleStateWStub@28
API _GetNamedPipeInfo@20
API _GetNamedPipeServerProcessId@8
API _GetNamedPipeServerSessionId@8
API _GetNativeSystemInfoStub@4
API _GetNextVDMCommand@4
API _GetNumaAvailableMemoryNode@8
API _GetNumaAvailableMemoryNodeEx@8
API _GetNumaHighestNodeNumberStub@4
API _GetNumaNodeNumberFromHandle@8
API _GetNumaNodeProcessorMask@8
API _GetNumaNodeProcessorMask2@16
API _GetNumaNodeProcessorMaskExStub@8
API _GetNumaProcessorNode@8
API _GetNumaProcessorNodeEx@8
API _GetNumaProximityNode@8
API _GetNumaProximityNodeExStub@8
API _GetNumberFormatA@24
API _GetNumberFormatExStub@24
API _GetNumberFormatWStub@24
API _GetNumberOfConsoleFonts@0
API _GetNumberOfConsoleInputEvents@8
API _GetNumberOfConsoleMouseButtons@4
API _GetOEMCPStub@0
API _GetOverlappedResultStub@16
API _GetOverlappedResultEx@20
API _GetPackageApplicationIds@16
API _GetPackageFamilyName@12
API _GetPackageFullName@12
API _GetPackageId@12
API _GetPackageInfo@20
API _GetPackagePath@16
API _GetPackagePathByFullName@12
API _GetPackagesByPackageFamily@20
API _GetPhysicallyInstalledSystemMemoryStub@4
API _GetPriorityClassStub@4
API _GetPrivateProfileIntA@16
API _GetPrivateProfileIntW@16
API _GetPrivateProfileSectionA@16
API _GetPrivateProfileSectionNamesA@12
API _GetPrivateProfileSectionNamesW@12
API _GetPrivateProfileSectionW@16
API _GetPrivateProfileStringA@24
API _GetPrivateProfileStringW@24
API _GetPrivateProfileStructA@20
API _GetPrivateProfileStructW@20
API _GetProcAddressStub@8
API _GetProcessAffinityMask@12
API _GetProcessDEPPolicy@12
API _GetProcessDefaultCpuSetMasks@16
API _GetProcessDefaultCpuSets@16
API _GetProcessGroupAffinityStub@12
API _GetProcessHandleCountStub@8
API _GetProcessHeap@0
API _GetProcessHeapsStub@8
API _GetProcessIdStub@4
API _GetProcessIdOfThreadStub@4
API _GetProcessInformation@16
API _GetProcessIoCounters@8
API _GetProcessMitigationPolicy@16
API _GetProcessPreferredUILanguagesStub@16
API _GetProcessPriorityBoostStub@8
API _GetProcessShutdownParametersStub@8
API _GetProcessTimesStub@20
API _GetProcessVersionStub@4
API _GetProcessWorkingSetSize@12
API _GetProcessWorkingSetSizeExStub@16
API _GetProcessesInVirtualizationContext@12
API _GetProcessorSystemCycleTime@12
API _GetProductInfoStub@20
API _GetProfileIntA@12
API _GetProfileIntW@12
API _GetProfileSectionA@12
API _GetProfileSectionW@12
API _GetProfileStringA@20
API _GetProfileStringW@20
API _GetQueuedCompletionStatusStub@20
API _GetQueuedCompletionStatusExStub@24
API _GetShortPathNameA@12
API _GetShortPathNameW@12
API _GetStagedPackagePathByFullName@12
API _GetStartupInfoA@4
API _GetStartupInfoWStub@4
API _GetStateFolder@16
API _GetStdHandleStub@4
API _GetStringScriptsStub@20
API _GetStringTypeExA@20
API _GetStringTypeExA@20
API _GetStringTypeExWStub@20
API _GetStringTypeWStub@16
API _GetSystemAppDataKey@16
API _GetSystemCpuSetInformation@20
API _GetSystemDEPPolicy@0
API _GetSystemDefaultLCIDStub@0
API _GetSystemDefaultLangIDStub@0
API _GetSystemDefaultLocaleNameStub@8
API _GetSystemDefaultUILanguageStub@0
API _GetSystemDirectoryAStub@8
API _GetSystemDirectoryWStub@8
API _GetSystemFileCacheSizeStub@12
API _GetSystemFirmwareTableStub@16
API _GetSystemInfoStub@4
API _GetSystemPowerStatus@4
API _GetSystemPreferredUILanguagesStub@16
API _GetSystemRegistryQuota@8
API _GetSystemTimeStub@4
API _GetSystemTimeAdjustmentStub@12
API _GetSystemTimeAsFileTimeStub@4
API _GetSystemTimePreciseAsFileTime@4
API _GetSystemTimesStub@12
API _GetSystemWindowsDirectoryAStub@8
API _GetSystemWindowsDirectoryWStub@8
API _GetSystemWow64DirectoryA@8
API _GetSystemWow64DirectoryW@8
API _GetTapeParameters@16
API _GetTapePosition@20
API _GetTapeStatus@4
API _GetTempFileNameA@16
API _GetTempFileNameW@16
API _GetTempPath2A@8
API _GetTempPath2W@8
API _GetTempPathA@8
API _GetTempPathW@8
API _GetThreadContextStub@8
API _GetThreadDescription@8
API _GetThreadEnabledXStateFeaturesStub@0
API _GetThreadErrorModeStub@0
API _GetThreadGroupAffinityStub@8
API _GetThreadIOPendingFlagStub@8
API _GetThreadIdStub@4
API _GetThreadIdealProcessorExStub@8
API _GetThreadInformation@16
API _GetThreadLocaleStub@0
API _GetThreadPreferredUILanguagesStub@16
API _GetThreadPriorityStub@4
API _GetThreadPriorityBoostStub@8
API _GetThreadSelectedCpuSetMasks@16
API _GetThreadSelectedCpuSets@16
API _GetThreadSelectorEntry@12
API _GetThreadTimesStub@20
API _GetThreadUILanguageStub@0
API _GetTickCountStub@0
API _GetTickCount64@0
API _GetTimeFormatAStub@24
API _GetTimeFormatAWorker@28
API _GetTimeFormatExStub@24
API _GetTimeFormatWStub@24
API _GetTimeFormatWWorker@24
API _GetTimeZoneInformationStub@4
API _GetTimeZoneInformationForYearStub@12
API _GetUILanguageInfoStub@20
API _GetUserDefaultGeoName@8
API _GetUserDefaultLCIDStub@0
API _GetUserDefaultLangIDStub@0
API _GetUserDefaultLocaleNameStub@8
API _GetUserDefaultUILanguageStub@0
API _GetUserGeoID@4
API _GetUserPreferredUILanguagesStub@16
API _GetVDMCurrentDirectories@8
API _GetVersionStub@0
API _GetVersionExAStub@4
API _GetVersionExWStub@4
API _GetVolumeInformationA@32
API _GetVolumeInformationByHandleW@32
API _GetVolumeInformationW@32
API _GetVolumeNameForVolumeMountPointA@12
API _GetVolumeNameForVolumeMountPointW@12
API _GetVolumePathNameA@12
API _GetVolumePathNameW@12
API _GetVolumePathNamesForVolumeNameA@16
API _GetVolumePathNamesForVolumeNameW@16
API _GetWindowsDirectoryAStub@8
API _GetWindowsDirectoryWStub@8
API _GetWriteWatchStub@24
API _GetXStateFeaturesMaskStub@8
API _GlobalAddAtomA@4
API _GlobalAddAtomExA@8
API _GlobalAddAtomExW@8
API _GlobalAddAtomW@4
API _GlobalAllocStub@8
API _LocalCompact@4
API _GlobalDeleteAtom@4
API _GlobalFindAtomA@4
API _GlobalFindAtomW@4
API _GlobalFix@4
API _GlobalFlagsStub@4
API _GlobalFreeStub@4
API _GlobalGetAtomNameA@12
API _GlobalGetAtomNameW@12
API _GlobalHandleStub@4
API _GlobalLockStub@4
API _GlobalMemoryStatus@4
API _GlobalMemoryStatusExStub@4
API _GlobalReAllocStub@12
API _GlobalSizeStub@4
API _GlobalUnlockStub@4
API _GlobalUnfix@4
API _GlobalUnlockStub@4
API _GlobalLockStub@4
API _Heap32First@12
API _Heap32ListFirst@8
API _Heap32ListNext@8
API _Heap32Next@4
API _RtlAllocateHeap@12
API _HeapCompactStub@8
API _HeapCreateStub@12
API _HeapDestroyStub@4
API _HeapFreeStub@12
API _HeapLockStub@4
API _HeapQueryInformationStub@20
API _RtlReAllocateHeap@16
API _HeapSetInformationStub@16
API _RtlSizeHeap@12
API _HeapSummaryStub@12
API _HeapUnlockStub@4
API _HeapValidateStub@12
API _HeapWalkStub@8
API _IdnToAsciiStub@20
API _IdnToNameprepUnicodeStub@20
API _IdnToUnicodeStub@20
API _InitAtomTable@4
API _InitOnceBeginInitialize@16
API _InitOnceComplete@12
API _InitOnceExecuteOnce@16
API _RtlRunOnceInitialize@4
API _RtlRunOnceInitialize@4
API _InitializeContextStub@16
API _InitializeContext2Stub@24
API _RtlInitializeCriticalSection@4
API _InitializeCriticalSectionAndSpinCount@8
API _InitializeCriticalSectionEx@12
API _InitializeEnclave@20
API _InitializeProcThreadAttributeList@16
API _RtlInitializeSListHead@4
API _RtlRunOnceInitialize@4
API _InitializeSynchronizationBarrierStub@12
API _InstallELAMCertificateInfo@4
API _InterlockedCompareExchangeStub@12
API _InterlockedCompareExchange64@20
API _InterlockedDecrementStub@4
API _InterlockedExchangeStub@8
API _InterlockedExchangeAddStub@8
API _RtlInterlockedFlushSList@4
API _InterlockedIncrementStub@4
API _RtlInterlockedPopEntrySList@4
API _RtlInterlockedPushEntrySList@8
API @InterlockedPushListSList@16
API _RtlInterlockedPushListSListEx@16
API _InvalidateConsoleDIBits@8
API _IsBadCodePtr@4
API _IsBadHugeReadPtr@8
API _IsBadHugeWritePtr@8
API _IsBadReadPtr@8
API _IsBadStringPtrA@8
API _IsBadStringPtrW@8
API _IsBadWritePtr@8
API _IsCalendarLeapDay@20
API _IsCalendarLeapMonth@16
API _IsCalendarLeapYear@12
API _IsDBCSLeadByteStub@4
API _IsDBCSLeadByteExStub@8
API _IsDebuggerPresentStub@0
API _IsEnclaveTypeSupported@4
API _IsIoRingOpSupported@8
API _IsNLSDefinedStringStub@20
API _IsNativeVhdBoot@4
API _IsNormalizedStringStub@12
API _IsProcessCritical@8
API _IsProcessInJobStub@12
API _IsProcessorFeaturePresentStub@4
API _IsSystemResumeAutomatic@0
API _IsThreadAFiber@0
API _TpIsTimerSet@4
API _sqlite3_value_bytes@4
API _IsValidCalDateTime@8
API _IsValidCodePageStub@4
API _IsValidLanguageGroupStub@8
API _IsValidLocaleStub@8
API _IsValidLocaleNameStub@4
API _IsValidNLSVersionStub@12
API _IsWow64GuestMachineSupported@8
API _IsWow64ProcessStub@8
API _IsWow64Process2@12
API _K32EmptyWorkingSetStub@4
API _K32EnumDeviceDriversStub@12
API _K32EnumPageFilesAStub@8
API _K32EnumPageFilesWStub@8
API _K32EnumProcessModulesStub@16
API _K32EnumProcessModulesExStub@20
API _K32EnumProcessesStub@12
API _K32GetDeviceDriverBaseNameAStub@12
API _K32GetDeviceDriverBaseNameWStub@12
API _K32GetDeviceDriverFileNameAStub@12
API _K32GetDeviceDriverFileNameWStub@12
API _K32GetMappedFileNameAStub@16
API _K32GetMappedFileNameWStub@16
API _K32GetModuleBaseNameAStub@16
API _K32GetModuleBaseNameWStub@16
API _K32GetModuleFileNameExAStub@16
API _K32GetModuleFileNameExWStub@16
API _K32GetModuleInformationStub@16
API _K32GetPerformanceInfoStub@8
API _K32GetProcessImageFileNameAStub@12
API _K32GetProcessImageFileNameWStub@12
API _K32GetProcessMemoryInfoStub@12
API _K32GetWsChangesStub@12
API _K32GetWsChangesExStub@12
API _K32InitializeProcessForWsWatchStub@4
API _K32QueryWorkingSetStub@12
API _K32QueryWorkingSetExStub@12
API _LCIDToLocaleNameStub@16
API _LCMapStringAStub@24
API _LCMapStringExStub@36
API _LCMapStringWStub@24
API _LZCloseFile@4
API _LZCloseFile@4
API _LZCopy@8
API _LZCreateFileW@20
API @_guard_check_icall_nop@4
API _LZInit@4
API _LZOpenFileA@12
API _LZOpenFileW@12
API _LZRead@12
API _LZSeek@12
API ?get_FirstMonthInThisYear@YearMonthCalendar@Calendars@Globalization@Windows@@UBEHXZ
API _RtlLeaveCriticalSection@4
API _TpCallbackLeaveCriticalSectionOnCompletion@8
API _LoadAppInitDllsImplementation@0
API _LoadEnclaveData@36
API _LoadLibraryAStub@4
API _LoadLibraryExAStub@12
API _LoadLibraryExWStub@12
API _LoadLibraryWStub@4
API _LoadModule@8
API _LoadPackagedLibrary@8
API _LoadResourceStub@8
API _LoadStringBaseExWStub@20
API _LoadStringBaseW@16
API _LocalAllocStub@8
API _LocalCompact@4
API _LocalFileTimeToFileTime@8
API _LocalFileTimeToLocalSystemTime@12
API _LocalFlagsStub@4
API _LocalFreeStub@4
API _LocalHandle@4
API _LocalLockStub@4
API _LocalReAllocStub@12
API _LocalShrink@8
API _LocalSizeStub@4
API _LocalSystemTimeToLocalFileTime@12
API _LocalUnlockStub@4
API _LocaleNameToLCIDStub@8
API _LocateXStateFeatureStub@12
API _LockFile@20
API _LockFileEx@24
API _LockResourceStub@4
API _RtlLogUnexpectedCodepath@4
API _MapUserPhysicalPagesStub@12
API _MapUserPhysicalPagesScatter@12
API _MapViewOfFileStub@20
API _MapViewOfFileExStub@24
API _MapViewOfFileExNumaStub@28
API _MapViewOfFileFromApp@20
API _Module32First@8
API _Module32FirstW@8
API _Module32Next@8
API _Module32NextW@8
API _MoveFileA@8
API _MoveFileExA@12
API _MoveFileExWStub@12
API _MoveFileTransactedA@24
API _MoveFileTransactedW@24
API _MoveFileW@8
API _MoveFileWithProgressA@20
API _MoveFileWithProgressWStub@20
API _MulDiv@12
API _MultiByteToWideCharStub@24
API _NeedCurrentDirectoryForExePathAStub@4
API _NeedCurrentDirectoryForExePathWStub@4
API _NlsCheckPolicy@8
API _NlsGetCacheUpdateCount@0
API _NlsUpdateLocale@8
API _NlsUpdateSystemLocale@8
API _NormalizeStringStub@20
API _NotifyMountMgrStub@12
API _NotifyUILanguageChange@20
API _NtVdm64CreateProcessInternalW@48
API _OOBEComplete@4
API _OfferVirtualMemory@12
API _OpenConsoleW@16
API _OpenConsoleWStub@16
API _OpenEventA@12
API _OpenEventW@12
API _OpenFile@12
API _OpenFileByIdStub@24
API _OpenFileMappingA@12
API _OpenFileMappingWStub@12
API _OpenJobObjectA@12
API _OpenJobObjectW@12
API _OpenMutexA@12
API _OpenMutexW@12
API _OpenPackageInfoByFullName@12
API _OpenPrivateNamespaceA@8
API _OpenPrivateNamespaceWStub@8
API _OpenProcessStub@12
API _OpenProcessToken@12
API ?get_FirstMonthInThisYear@YearMonthCalendar@Calendars@Globalization@Windows@@UBEHXZ
API _OpenSemaphoreA@12
API _OpenSemaphoreW@12
API _OpenState@0
API _OpenStateExplicit@8
API _OpenThreadStub@12
API _OpenThreadToken@16
API _OpenWaitableTimerA@12
API _OpenWaitableTimerW@12
API _OutputDebugStringAStub@4
API _OutputDebugStringWStub@4
API _PackageFamilyNameFromFullName@12
API _PackageFamilyNameFromId@12
API _PackageFullNameFromId@12
API _PackageIdFromFullName@16
API _PackageNameAndPublisherIdFromFamilyName@20
API _ParseApplicationUserModelId@20
API _PeekConsoleInputA@16
API _PeekConsoleInputW@16
API _PeekNamedPipeStub@24
API _PopIoRingCompletion@8
API _PostQueuedCompletionStatusStub@16
API _PowerClearRequest@8
API _PowerCreateRequest@4
API _PowerSetRequest@8
API _PrefetchVirtualMemory@16
API _PrepareTape@12
API _PrivCopyFileExWStub@24
API _PrivMoveFileIdentityW@12
API _Process32First@8
API _Process32FirstW@8
API _Process32Next@8
API _Process32NextW@8
API _ProcessIdToSessionIdStub@8
API _PssCaptureSnapshotStub@16
API _PssDuplicateSnapshotStub@20
API _PssFreeSnapshotStub@8
API _PssQuerySnapshotStub@16
API _PssWalkMarkerCreateStub@8
API _PssWalkMarkerFreeStub@4
API _PssWalkMarkerGetPositionStub@8
API _PssWalkMarkerSeekToBeginningStub@4
API _PssWalkMarkerSetPositionStub@8
API _PssWalkMarkerSeekToBeginningStub@4
API _PssWalkMarkerSetPositionStub@8
API _PssWalkMarkerGetPositionStub@8
API _PssWalkSnapshotStub@20
API _PulseEventStub@4
API _PurgeComm@8
API _QueryActCtxSettingsWStub@28
API _QueryActCtxSettingsWWorker@28
API _QueryActCtxWStub@28
API _QueryActCtxWWorker@28
API _RtlQueryDepthSList@4
API _QueryDosDeviceA@12
API _QueryDosDeviceW@12
API _QueryFullProcessImageNameAStub@16
API _QueryFullProcessImageNameWStub@16
API _QueryIdleProcessorCycleTimeStub@8
API _QueryIdleProcessorCycleTimeExStub@12
API _QueryInformationJobObject@20
API _QueryIoRateControlInformationJobObject@16
API _QueryIoRingCapabilities@4
API _QueryMemoryResourceNotificationStub@8
API _QueryPerformanceCounterStub@4
API _QueryPerformanceFrequencyStub@4
API _QueryProcessAffinityUpdateModeStub@8
API _QueryProcessCycleTimeStub@8
API _QueryProtectedPolicy@8
API _QueryThreadCycleTimeStub@8
API _QueryThreadProfiling@8
API _QueryThreadpoolStackInformationStub@8
API _QueryUnbiasedInterruptTimeStub@4
API _QueueUserAPCStub@12
API _QueueUserAPC2@16
API _QueueUserWorkItemStub@12
API _QuirkGetData2Worker@8
API _QuirkGetDataWorker@8
API _QuirkIsEnabled2Worker@12
API _QuirkIsEnabled3Worker@8
API _QuirkIsEnabledForPackage2Worker@24
API _QuirkIsEnabledForPackage3Worker@20
API _QuirkIsEnabledForPackage4Worker@20
API _QuirkIsEnabledForPackageWorker@16
API _QuirkIsEnabledForProcessWorker@12
API _QuirkIsEnabledWorker@4
API _RaiseExceptionStub@16
API _RaiseFailFastException@12
API _RaiseInvalid16BitExeError@4
API _ReOpenFileStub@16
API _ReadConsoleA@20
API _ReadConsoleInputA@16
API _ReadConsoleInputExA@20
API _ReadConsoleInputExW@20
API _ReadConsoleInputW@16
API _ReadConsoleOutputA@20
API _ReadConsoleOutputAttribute@20
API _ReadConsoleOutputCharacterA@20
API _ReadConsoleOutputCharacterW@20
API _ReadConsoleOutputW@20
API _ReadConsoleW@20
API _ReadDirectoryChangesExWStub@36
API _ReadDirectoryChangesWStub@32
API _ReadFile@20
API _ReadFileEx@20
API _ReadFileScatter@20
API _ReadProcessMemoryStub@20
API _ReadThreadProfilingData@12
API _ReclaimVirtualMemory@8
API _RegCloseKeyStub@4
API _RegCopyTreeWStub@12
API _RegCreateKeyExAStub@36
API _RegCreateKeyExWStub@36
API _RegDeleteKeyExAStub@16
API _RegDeleteKeyExWStub@16
API _RegDeleteTreeAStub@8
API _RegDeleteTreeWStub@8
API _RegDeleteValueAStub@8
API _RegDeleteValueWStub@8
API _RegDisablePredefinedCacheExStub@0
API _RegEnumKeyExAStub@32
API _RegEnumKeyExWStub@32
API _RegEnumValueAStub@32
API _RegEnumValueWStub@32
API _RegFlushKeyStub@4
API _RegGetKeySecurityStub@16
API _RegGetValueAStub@28
API _RegGetValueWStub@28
API _RegLoadKeyAStub@12
API _RegLoadKeyWStub@12
API _RegLoadMUIStringAStub@28
API _RegLoadMUIStringWStub@28
API _RegNotifyChangeKeyValueStub@20
API _RegOpenCurrentUserStub@8
API _RegOpenKeyExAStub@20
API _RegOpenKeyExWStub@20
API _RegOpenUserClassesRootStub@16
API _RegQueryInfoKeyAStub@48
API _RegQueryInfoKeyWStub@48
API _RegQueryValueExAStub@24
API _RegQueryValueExWStub@24
API _RegRestoreKeyAStub@12
API _RegRestoreKeyWStub@12
API _RegSaveKeyExAStub@16
API _RegSaveKeyExWStub@16
API _RegSetKeySecurityStub@12
API _RegSetValueExAStub@24
API _RegSetValueExWStub@24
API _RegUnLoadKeyAStub@8
API _RegUnLoadKeyWStub@8
API _RegisterApplicationRecoveryCallback@16
API _RegisterApplicationRestartStub@8
API _RegisterBadMemoryNotificationStub@4
API _SetHandleContext@8
API _RegisterConsoleOS2@4
API _RegisterConsoleVDM@36
API _RegisterWaitForInputIdle@4
API _RegisterWaitForSingleObject@24
API _RegisterWaitForSingleObjectExStub@20
API _RegisterWaitUntilOOBECompleted@12
API _RegisterWowBaseHandlers@4
API _RegisterWowExec@4
API _ReleaseActCtxStub@4
API _ReleaseActCtxWorker@4
API _ReleaseMutex@4
API _TpCallbackReleaseMutexOnCompletion@8
API _ReleasePackageVirtualizationContext@4
API _ReleasePseudoConsole@4
API _RtlReleaseSRWLockExclusive@4
API _RtlReleaseSRWLockShared@4
API _ReleaseSemaphore@12
API _TpCallbackReleaseSemaphoreOnCompletion@12
API _RemoveDirectoryA@4
API _RemoveDirectoryTransactedA@8
API _RemoveDirectoryTransactedW@8
API _RemoveDirectoryW@4
API _RemoveDllDirectory@4
API _RemoveLocalAlternateComputerNameA@8
API _RemoveLocalAlternateComputerNameW@8
API _RemoveSecureMemoryCacheCallback@4
API _RtlRemoveVectoredContinueHandler@4
API _RtlRemoveVectoredExceptionHandler@4
API _ReplaceFileWStub@24
API _ReplaceFileA@24
API _ReplaceFileWStub@24
API _ReplacePartitionUnit@12
API _CancelDeviceWakeupRequest@4
API _CancelDeviceWakeupRequest@4
API _ResetEvent@4
API _ResetWriteWatchStub@8
API _ResizePseudoConsole@8
API _LdrResolveDelayLoadedAPI@24
API _LdrResolveDelayLoadsFromDll@12
API _ResolveLocaleNameStub@12
API _RtlSetLastWin32Error@4
API _ResumeThreadStub@4
API _RtlCaptureContext@4
API _RtlCaptureStackBackTrace@16
API _RtlFillMemoryStub@12
API _RtlMoveMemory@12
API _RtlPcToFileHeaderStub@8
API _RtlUnwindStub@16
API _RtlZeroMemory@8
API _ScrollConsoleScreenBufferA@20
API _ScrollConsoleScreenBufferW@20
API _SearchPathAStub@24
API _SearchPathWStub@24
API _SetCachedSigningLevelStub@16
API _SetCalendarInfoA@16
API _SetCalendarInfoWStub@16
API _SetComPlusPackageInstallStatus@4
API _SetCommBreak@4
API _SetCommConfig@12
API _SetCommMask@8
API _SetCommState@8
API _SetCommTimeouts@8
API _SetComputerNameAStub@4
API _SetComputerNameEx2WStub@12
API _SetComputerNameExAStub@8
API _SetComputerNameExWStub@8
API _SetComputerNameWStub@4
API _SetConsoleActiveScreenBuffer@4
API _SetConsoleCP@4
API _SetConsoleCtrlHandler@8
API _SetConsoleCursor@8
API _SetConsoleCursorInfo@8
API _SetConsoleCursorMode@12
API _SetConsoleCursorPosition@8
API _SetConsoleDisplayMode@12
API _SetConsoleFont@8
API _SetConsoleHardwareState@12
API _SetConsoleHistoryInfo@4
API _SetConsoleIcon@4
API _SetConsoleInputExeNameA@4
API _SetConsoleInputExeNameW@4
API _SetConsoleKeyShortcuts@16
API _SetConsoleLocalEUDC@16
API _SetConsoleMaximumWindowSize@8
API _SetConsoleMenuClose@4
API _SetConsoleMode@8
API _SetConsoleNlsMode@8
API _SetConsoleNumberOfCommandsA@8
API _SetConsoleNumberOfCommandsW@8
API _SetConsoleOS2OemFormat@4
API _SetConsoleOutputCP@4
API _SetConsolePalette@12
API _SetConsoleScreenBufferInfoEx@8
API _SetConsoleScreenBufferSize@8
API _SetConsoleTextAttribute@8
API _SetConsoleTitleA@4
API _SetConsoleTitleW@4
API _SetConsoleWindowInfo@12
API _RtlSetCriticalSectionSpinCount@8
API _SetCurrentConsoleFontEx@12
API _SetCurrentDirectoryAStub@4
API _SetCurrentDirectoryWStub@4
API _SetDefaultCommConfigA@12
API _SetDefaultCommConfigW@12
API _SetDefaultDllDirectories@4
API _SetDllDirectoryA@4
API _SetDllDirectoryW@4
API _SetDynamicTimeZoneInformationStub@4
API _SetEndOfFile@4
API _SetEnvironmentStringsA@4
API _SetEnvironmentStringsWStub@4
API _SetEnvironmentVariableAStub@8
API _SetEnvironmentVariableWStub@8
API _SetErrorModeStub@4
API _SetEvent@4
API _TpCallbackSetEventOnCompletion@8
API _SetFileApisToANSIStub@0
API _SetFileApisToOEMStub@0
API _SetFileAttributesA@8
API _SetFileAttributesTransactedA@12
API _SetFileAttributesTransactedW@12
API _SetFileAttributesW@8
API _SetFileBandwidthReservation@24
API _SetFileCompletionNotificationModes@8
API _SetFileInformationByHandle@16
API _SetFileIoOverlappedRangeStub@12
API _SetFilePointer@16
API _SetFilePointerEx@20
API _SetFileShortNameA@8
API _SetFileShortNameW@8
API _SetFileTime@16
API _SetFileValidData@12
API _SetFirmwareEnvironmentVariableA@16
API _SetFirmwareEnvironmentVariableExA@20
API _SetFirmwareEnvironmentVariableExW@20
API _SetFirmwareEnvironmentVariableW@16
API _SetHandleContext@8
API _SetHandleCount@4
API _SetHandleInformation@12
API _SetInformationJobObject@16
API _SetIoRateControlInformationJobObject@8
API _SetIoRingCompletionEvent@8
API _SetLastConsoleEventActive@0
API _SetLastErrorStub@4
API _SetLocalPrimaryComputerNameA@8
API _SetLocalPrimaryComputerNameW@8
API _SetLocalTimeStub@4
API _SetLocaleInfoA@12
API _SetLocaleInfoWStub@12
API _SetMailslotInfo@8
API _SetMessageWaitingIndicator@8
API _SetNamedPipeAttribute@20
API _SetNamedPipeHandleStateStub@16
API _SetPriorityClassStub@8
API _SetProcessAffinityMask@8
API _SetProcessAffinityUpdateModeStub@8
API _SetProcessDEPPolicy@4
API _SetProcessDefaultCpuSetMasks@12
API _SetProcessDefaultCpuSets@12
API _SetProcessDynamicEHContinuationTargets@12
API _SetProcessDynamicEnforcedCetCompatibleRanges@12
API _SetProcessInformation@16
API _SetProcessMitigationPolicy@12
API _SetProcessPreferredUILanguagesStub@12
API _SetProcessPriorityBoostStub@8
API _SetProcessShutdownParametersStub@8
API _SetProcessWorkingSetSize@12
API _SetProcessWorkingSetSizeExStub@16
API _SetProtectedPolicy@12
API _SetSearchPathMode@4
API _SetStdHandleStub@8
API _SetStdHandleExStub@12
API _SetSystemFileCacheSizeStub@12
API _SetSystemPowerState@8
API _SetSystemTimeStub@4
API _SetSystemTimeAdjustment@8
API _SetTapeParameters@12
API _SetTapePosition@24
API _SetTermsrvAppInstallMode@4
API _SetThreadAffinityMask@8
API _SetThreadContextStub@8
API _SetThreadDescription@8
API _SetThreadErrorModeStub@8
API _SetThreadExecutionState@4
API _SetThreadGroupAffinityStub@12
API _SetThreadIdealProcessorStub@8
API _SetThreadIdealProcessorExStub@12
API _SetThreadInformation@16
API _SetThreadLocaleStub@4
API _SetThreadPreferredUILanguagesStub@12
API _SetThreadPriorityStub@8
API _SetThreadPriorityBoostStub@8
API _SetThreadSelectedCpuSetMasks@12
API _SetThreadSelectedCpuSets@12
API _SetThreadStackGuaranteeStub@4
API _SetThreadToken@8
API _SetThreadUILanguageStub@4
API _SetThreadpoolStackInformationStub@8
API _TpSetPoolMaxThreads@8
API _SetThreadpoolThreadMinimumStub@8
API _TpSetTimer@16
API _TpSetTimerEx@16
API _TpSetWait@12
API _TpSetWaitEx@16
API _SetTimeZoneInformationStub@4
API _SetTimerQueueTimer@24
API _SetUnhandledExceptionFilterStub@4
API _SetUserGeoID@4
API _SetUserGeoName@4
API _SetVDMCurrentDirectories@8
API _SetVolumeLabelA@8
API _SetVolumeLabelW@8
API _SetVolumeMountPointA@8
API _SetVolumeMountPointW@8
API _SetVolumeMountPointWStub@8
API _SetWaitableTimer@24
API _SetWaitableTimerEx@28
API _SetXStateFeaturesMaskStub@12
API _SetupComm@12
API _ShowConsoleCursor@8
API _SignalObjectAndWaitStub@16
API _SizeofResourceStub@8
API _SleepStub@4
API _SleepConditionVariableCS@12
API _SleepConditionVariableSRW@16
API _SleepEx@8
API _SortCloseHandle@4
API _SortGetHandle@12
API _TpStartAsyncIoOperation@4
API _SubmitIoRing@16
API _TpPostWork@4
API _SuspendThreadStub@4
API _SwitchToFiber@4
API _SwitchToThreadStub@0
API _SystemTimeToFileTimeStub@8
API _SystemTimeToTzSpecificLocalTimeStub@12
API _SystemTimeToTzSpecificLocalTimeEx@12
API _TerminateJobObject@8
API _TerminateProcessStub@8
API _TerminateThreadStub@8
API _TermsrvAppInstallMode@0
API _TermsrvConvertSysRootToUserDir@8
API _TermsrvCreateRegEntry@20
API _TermsrvDeleteKey@4
API _TermsrvDeleteValue@8
API _TermsrvGetPreSetValue@16
API _TermsrvGetWindowsDirectoryA@8
API _TermsrvGetWindowsDirectoryW@8
API _TermsrvOpenRegEntry@12
API _TermsrvOpenUserClasses@8
API _TermsrvRestoreKey@12
API _TermsrvSetKeySecurity@12
API _TermsrvSetValueKey@24
API _TermsrvSyncUserIniFileExt@4
API _Thread32First@8
API _Thread32Next@8
API _TlsAllocStub@0
API _TlsFreeStub@4
API _TlsGetValue@4
API _TlsGetValue2@4
API _TlsSetValueStub@8
API _Toolhelp32ReadProcessMemory@20
API _TransactNamedPipeStub@28
API _TransmitCommChar@8
API _RtlTryAcquireSRWLockExclusive@4
API _RtlTryAcquireSRWLockShared@4
API _RtlTryEnterCriticalSection@4
API _TrySubmitThreadpoolCallbackStub@12
API _TzSpecificLocalTimeToSystemTimeStub@12
API _TzSpecificLocalTimeToSystemTimeEx@12
API _UTRegister@28
API _UTUnRegister@4
API _UnhandledExceptionFilterStub@4
API _UnlockFile@20
API _UnlockFileEx@20
API _UnmapViewOfFileStub@4
API _UnmapViewOfFileEx@8
API _UnregisterApplicationRecoveryCallback@0
API _UnregisterApplicationRestartStub@0
API _UnregisterBadMemoryNotificationStub@4
API _CreateSocketHandle@0
API _UnregisterWait@4
API _UnregisterWaitExStub@8
API _UnregisterWaitUntilOOBECompleted@4
API _UpdateCalendarDayOfWeek@4
API _UpdateProcThreadAttribute@28
API _UpdateResourceA@24
API _UpdateResourceW@24
API _VDMConsoleOperation@8
API _VDMOperationStarted@4
API _VerLanguageNameAStub@12
API _VerLanguageNameWStub@12
API _VerSetConditionMask@16
API _VerifyConsoleIoHandle@4
API _VerifyScriptsStub@20
API _VerifyVersionInfoA@16
API _VerifyVersionInfoW@16
API _VirtualAllocStub@16
API _VirtualAllocExStub@20
API _VirtualAllocExNumaStub@24
API _VirtualFreeStub@12
API _VirtualFreeExStub@16
API _VirtualLockStub@8
API _VirtualProtectStub@16
API _VirtualProtectExStub@20
API _VirtualQueryStub@12
API _VirtualQueryExStub@16
API _VirtualUnlockStub@8
API _WTSGetActiveConsoleSessionId@0
API _WaitCommEvent@12
API _WaitForDebugEventStub@8
API _WaitForDebugEventEx@8
API _WaitForMultipleObjects@16
API _WaitForMultipleObjectsEx@20
API _WaitForSingleObject@8
API _WaitForSingleObjectEx@12
API _TpWaitForIoCompletion@8
API _TpWaitForTimer@8
API _TpWaitForWait@8
API _TpWaitForWork@8
API _WaitNamedPipeA@8
API _WaitNamedPipeWStub@8
API _RtlWakeAllConditionVariable@4
API _RtlWakeConditionVariable@4
API _WerGetFlags@8
API _WerGetFlags@8
API _WerRegisterAdditionalProcessStub@8
API _WerRegisterAppLocalDumpStub@4
API _WerRegisterCustomMetadataStub@8
API _WerRegisterExcludedMemoryBlockStub@8
API _WerRegisterFileStub@12
API _WerRegisterFileWorker@12
API _WerRegisterMemoryBlockStub@8
API _WerRegisterMemoryBlockWorker@8
API _WerRegisterRuntimeExceptionModuleStub@8
API _WerRegisterRuntimeExceptionModuleWorker@8
API _WerSetFlags@4
API _WerSetFlags@4
API _WerUnregisterAdditionalProcessStub@4
API _WerUnregisterAppLocalDumpStub@0
API _WerUnregisterCustomMetadataStub@4
API _WerUnregisterExcludedMemoryBlockStub@4
API _WerUnregisterFileStub@4
API _WerUnregisterFileWorker@4
API _WerUnregisterMemoryBlockStub@4
API _WerUnregisterMemoryBlockWorker@4
API _WerUnregisterRuntimeExceptionModuleStub@8
API _WerUnregisterRuntimeExceptionModuleWorker@8
API _WerpGetDebugger@8
API _WerpInitiateRemoteRecovery@4
API _WerpLaunchAeDebug@20
API _WerpNotifyLoadStringResourceWorker@16
API _WerpNotifyUseStringResourceWorker@4
API _WideCharToMultiByteStub@32
API _WinExec@8
API _Wow64DisableWow64FsRedirectionStub@4
API _Wow64EnableWow64FsRedirection@4
API _Wow64GetThreadContextStub@8
API _Wow64GetThreadSelectorEntry@12
API _Wow64RevertWow64FsRedirectionStub@4
API _Wow64SetThreadContextStub@8
API _Wow64SuspendThreadStub@4
API _Wow64Transition
API _WriteConsoleA@20
API _WriteConsoleInputA@16
API _WriteConsoleInputVDMA@16
API _WriteConsoleInputVDMW@16
API _WriteConsoleInputW@16
API _WriteConsoleOutputA@20
API _WriteConsoleOutputAttribute@20
API _WriteConsoleOutputCharacterA@20
API _WriteConsoleOutputCharacterW@20
API _WriteConsoleOutputW@20
API _WriteConsoleW@20
API _WriteFile@20
API _WriteFileEx@20
API _WriteFileGather@20
API _WritePrivateProfileSectionA@12
API _WritePrivateProfileSectionW@12
API _WritePrivateProfileStringA@16
API _WritePrivateProfileStringW@16
API _WritePrivateProfileStructA@20
API _WritePrivateProfileStructW@20
API _WriteProcessMemoryStub@20
API _WriteProfileSectionA@8
API _WriteProfileSectionW@8
API _WriteProfileStringA@12
API _WriteProfileStringW@12
API _WriteTapemark@16
API _ZombifyActCtxStub@4
API _ZombifyActCtxWorker@4
API __lread@12
API __lwrite@12
API __lclose@4
API __lcreat@8
API __llseek@12
API __lopen@8
API __lread@12
API __lwrite@12
API _lstrcatA@8
API _lstrcatA@8
API _lstrcatW@8
API _lstrcmpStub@8
API _lstrcmpStub@8
API _lstrcmpWStub@8
API _lstrcmpiStub@8
API _lstrcmpiStub@8
API _lstrcmpiWStub@8
API _lstrcpyA@8
API _lstrcpyA@8
API _lstrcpyW@8
API _lstrcpynAStub@12
API _lstrcpynAStub@12
API _lstrcpynWStub@12
API _lstrlenAStub@4
API _lstrlenAStub@4
API _lstrlenWStub@4
API _timeBeginPeriod@4
API _timeEndPeriod@4
API _timeGetDevCaps@8
API _timeGetSystemTime@8
API _timeGetTime@0

end
